### ISSUE TITLE
[FEATURE] City ESP

### ISSUE THREAD

**Issue by ignelias** [John200410/rusherhack-issues#10]
city esp which shows where you can city someone

**Comment by John200410** [comment]
This has been added to v1.1.1 as a setting under ESP

https://rusherhack.org/i/is6mvbzal2.mp4

**Comment by TheRedBlocker** [comment]
Can u make city esp a separate module or like u said add it to hole esp

**Comment by John200410** [comment]
Yes It will moved it to a setting under HoleESP
