### ISSUE TITLE
[BUG] MapReset doesn't switch to a new stack of maps when one stack is empty.

### ISSUE THREAD

**Issue by TheRedBlocker** [John200410/rusherhack-issues#100]
**Describe the bug**
When you turn on MapReset, it will reset one stack of maps and then stop.

**To Reproduce**
Hold multiple stacks of maps in survival mode and turn on MapReset.

**Expected behavior**
I expected that after one stack of maps was reset, it would switch to a new stack so it would be more afkable.

**Comment by John200410** [comment]
Thank you for reporting this

**Comment by John200410** [comment]
MapReset has been rewritten in v1.1.2 and this will no longer happen.
