### ISSUE TITLE
[FEATURE] autotool improvement

### ISSUE THREAD

**Issue by Vaimok** [John200410/rusherhack-issues#1008]
**What feature would you like to be added.**
add option to disable autotool moving tools from your inventory to your hotbar

**Is your feature request related to a problem? Please describe.**
feature request

**Additional context**
-

**Comment by SoggyBacco** [comment]
please add this, i always lose my gap slot when i get someone elses sword or pick off the ground

**Comment by John200410** [comment]
This has been done in the next update.
