### ISSUE TITLE
[FEATURE] in game notifications improvements (duplicate of issue 805 (kinda))

### ISSUE THREAD

**Issue by ghost** [John200410/rusherhack-issues#1009]
**What feature would you like to be added.**
option to change colors in chat notifs, option to stack settings in hud notifs (for example same person popping for 2nd time would replace the first popup but say 2 pops instead of 1), option to disable popup animations, option to priorize popups, option to change the time popups stay in your screen and option to possibly customize popups (different colors and maybe different icons).

**Is your feature request related to a problem? Please describe.**
no

**Additional context**
-

**Comment by John200410** [comment]
Closing in favor of #1161
