### ISSUE TITLE
Option to disable notifications (right now you can only do either chat or HUD) [FEATURE]

### ISSUE THREAD

**Issue by ManOnTheMoon28** [John200410/rusherhack-issues#101]
**Option to disable notifications**
Allows you to disable the notifications that come with rusherhack (I dont mean the notifications MODULE, i  mean the notifications that appear whenever you disable a module, find chests with basefiner, etc.)

**Comment by John200410** [comment]
Thank you for the suggestion. Currently you can toggle the module enable/disable notifications by disabling ModuleNotify under HUD. I will still add an option to disable notifications entirely however.

**Comment by John200410** [comment]
This has been added in v1.1.2
