### ISSUE TITLE
ig a bug?

### ISSUE THREAD

**Issue by Gaamr** [John200410/rusherhack-issues#1021]
it would be nice to be able to use step and strafe together, since in 1.2.2 atleast they dont work together, and neither(?) or only strafe work(?), i cant remember which one it is but if it isn't already in 1.2.3 it would be nice to not have to use another client for step because rh strafe is too sexy

**Comment by John200410** [comment]
Are you referring to ground strafe?

**Comment by Gaamr** [comment]
Yeah, sorry for not mentioning that

**Comment by John200410** [comment]
Fixed in the next update.

**Comment by Gaamr** [comment]
Incredible. Thank you.
