### ISSUE TITLE
[FEATURE] Prevent crashing when using search for an entitiy/blocks that might exceed reasonalble quantities

### ISSUE THREAD

**Issue by epifeny** [John200410/rusherhack-issues#1026]
**What feature would you like to be added.**
In `*search` I use blocks of type `netherack` in the overworld. I sometimes forget that I have them and when I go into the nether, my client will freeze due to the sheer quantity of tracers. Perhaps a soft default limit should be set and a notification should be given to the player to change it if needed when that limit is reached and more results might freeze the client.

**Is your feature request related to a problem? Please describe.**
NA

**Additional context**
NA

**Comment by LowTPS** [comment]
It can look like this:
Search
*some other settings*
NoNetherBlocks
and NoNetherBlocks would authomatically remove netherrack, magma etc. from search list while you are in the nether and authomatically add these blocks back once you exit

**Comment by jumboman32** [comment]
#977
