### ISSUE TITLE
Game crashing

### ISSUE THREAD

**Issue by duduzingameprei** [John200410/rusherhack-issues#1030]
**Describe the bug**
when i try to join any server or single player world  except 2b2t's queue my game crashes and this error apear:

The game crashed whilst tesselating block model
Error: java.lang.ArrayIndexOutOfBoundsException: 5
Exit code: -1

**To Reproduce**
Literraly just join any world or server except 2b2t's queue

**Other mods**
by first i was using highway tools kami blue snowclient cracked and optfine, but now just optfine

**Expected behavior**
join normaly and play

**Screenshots**
ill put videos if possible

https://user-images.githubusercontent.com/86319806/131592755-fa96e3b6-2f03-4833-8541-c3649c6f4c49.mp4

**Additional context**
when i was using the other mods i entered the world or server but it dont loads then if i try to do anything even alt tab the game screen keeps there and i cant do anything to the game the only thing i can do is make the game to not respond with clicks and close it

**Comment by LiquidSmokeBalls** [comment]
maybe ask on the support cause john is more active there?

**Comment by John200410** [comment]
Dm me the crash log on Discord.
