### ISSUE TITLE
[FEATURE] Selfblock wait

### ISSUE THREAD

**Issue by HarryPotter42MC** [John200410/rusherhack-issues#1033]
**What feature would you like to be added.**
So: burrow doesn't do anything when a hitbox/crystal is in the way, and that's ok but an option would be cool wich waits until it can place it so when you're getting crystalled it tries to burrow in the tick where there's no crystal. S it would stay on until it burrowed
sorry, I mean selfblock not burrow
**Is your feature request related to a problem? Please describe.**
I hate when burrow doesn't work due to crystals

**Comment by jumboman32** [comment]
Just add an active mode to SelfBlock like Surround has.

**Comment by jumboman32** [comment]
closing in favor of #1020
