### ISSUE TITLE
[BUG] Tunnelesp false positives

### ISSUE THREAD

**Issue by HarryPotter42MC** [John200410/rusherhack-issues#1034]
**What feature would you like to be added.**
A blacklist and whitelist for tunnelesp so this: 
![image](https://user-images.githubusercontent.com/82435253/132093052-009fd8fc-44f3-4c88-a809-fcacfaef4106.png)
doesn't happen :)

**Is your feature request related to a problem? Please describe.**
^picture above

**Comment by John200410** [comment]
I will just make it only show tunnels that have at least two holes

**Comment by John200410** [comment]
Fixed in the next update.
