### ISSUE TITLE
[FEATURE] narrator disabler module

### ISSUE THREAD

**Issue by HarryPotter42MC** [John200410/rusherhack-issues#1035]
**What feature would you like to be added.**
A utility module wich disables all narrator stuff so that shitty voice doesn't annoy me when I sprint and press b

**Is your feature request related to a problem? Please describe.**
I hate that shitty narrator

**Comment by LiquidSmokeBalls** [comment]
press control and b lmao it disables narrator lmao

**Comment by LiquidSmokeBalls** [comment]
and i think its not possible to add a module that disables something from the actual minecraft settings

**Comment by RickyTheRacc** [comment]
Just turn it off in minecraft settings lol

**Comment by John200410** [comment]
https://www.curseforge.com/minecraft/mc-mods/rebind-narrator

**Comment by HarryPotter42MC** [comment]
> Just turn it off in minecraft settings lol

you cant

**Comment by HarryPotter42MC** [comment]
> press control and b lmao it disables narrator lmao

it enables it all the time so I don't wanna need to do that

**Comment by HarryPotter42MC** [comment]
> and i think its not possible to add a module that disables something from the actual minecraft settings

why does norender work then? huh wheres your logic
