### ISSUE TITLE
[FEATURE] Rekit on Deaeth

### ISSUE THREAD

**Issue by RickyTheRacc** [John200410/rusherhack-issues#1038]
**What feature would you like to be added.**
An option in AutoRespawn that will automatically select a kit for you when you respawn. You can enter the name of the kit in a text field

**Is your feature request related to a problem?**
Not necessarily a problem, but having it automatically done would be preferable to typing the command out every time.

**Comment by jumboman32** [comment]
This is lazy. Use the up arrow.
