### ISSUE TITLE
[FEATURE] Semitransparent Xray

### ISSUE THREAD

**Issue by tycrek** [John200410/rusherhack-issues#104]
**What feature would you like to be added.**

Semitransparent Xray similar to Future. Option for opacity if possible.

**Comment by John200410** [comment]
Thank you for the suggestion

**Comment by John200410** [comment]
This has been added in the next update:
![image](https://user-images.githubusercontent.com/43681932/123191176-d762ce80-d46e-11eb-9bdd-1bfc1e1d75c5.png)
