### ISSUE TITLE
[FEATURE] MiddleClick Shulker 

### ISSUE THREAD

**Issue by tescomealdeal** [John200410/rusherhack-issues#1040]
**What feature would you like to be added.**
A setting added to ExtraTooltips Shulkers where if you middleclick a shulker in your inventory, it performs *peek on it

**Is your feature request related to a problem? Please describe.**
I believe this would be a nice addition to the client

**Comment by John200410** [comment]
Make a macro to MOUSE3 to use the peek command

**Comment by John200410** [comment]
Nevermind I misread. You can use the Locking setting to "lock" the preview in place so you can hover over the items in the shulker.
