### ISSUE TITLE
[FEATURE] Setting command

### ISSUE THREAD

**Issue by tescomealdeal** [John200410/rusherhack-issues#1042]
**What feature would you like to be added.**
a command to turn settings on/off or change values of  settings, would work well combined with the *macro command
could work something like *setting [modulename] [settingname] [on/off/value]

**Comment by John200410** [comment]
You can already do this.

"<module name> <setting name> <value>

**Comment by tescomealdeal** [comment]
are you able to toggle settings off and on though by putting something like *[modulename] [settingname] toggle ?

**Comment by FluorideHistorian** [comment]
*toggle <module name>

**Comment by FluorideHistorian** [comment]
*module_name setting_name
for toggle or
*module_name setting_name true/false
