### ISSUE TITLE
[FEATURE] rebreak option if the fast break fails or if u want to switch blocks

### ISSUE THREAD

**Issue by LiquidSmokeBalls** [John200410/rusherhack-issues#1043]
sometimes in strict.2b2tpvp.net rushehacks fast break will fail and not break. Since Rusherhack's fastbreak doesnt have a "insta-rebreak" optition i would have to go out of the distance that allows it to cancel the break and i most likely will get crystaled and will die. this is very annoying because rusherhacks fastbreak option is more reliable then any other client ive tested (konas paid future and catalyst). So if this can be added this will be really great since we already have the render feature that allows us to see the certain time that it will break so we can either burrow and trap them to crystal them or just let them take a bit of damage or make them run out of their hole thus crystaling them. 

pls 
-TwoOneTwo 

PS: this was a cringe paragraph lmao bully me for it :smile:

**Comment by jennifer-uwu** [comment]
there is an instant rebreak option

**Comment by LiquidSmokeBalls** [comment]
it doesnt allow u to switch to a different block in render distance

**Comment by system69-e** [comment]
> there is an instant rebreak option

except ive never seen it work
