### ISSUE TITLE
[BUG] autototem alternatewhen doesnt work

### ISSUE THREAD

**Issue by SoggyBacco** [John200410/rusherhack-issues#1048]
alternatewhen, requiresautocrystal, and alternatebind dont function with the current ca when autototem is set to health mode

**Comment by TwoThreeTwo** [comment]
duplicate issue #1250

john should take a look at this ngl

**Comment by John200410** [comment]
This should be fixed in the next update.

**Comment by John200410** [comment]
Why would you want it to alternate when health mode already makes it alternate? I don't understand
