### ISSUE TITLE
[FEATURE] Allow for shulker peek when the shulker is within a chest

### ISSUE THREAD

**Issue by TheGreatRambler** [John200410/rusherhack-issues#1049]
**What feature would you like to be added.**
Allowing for shulker peek, which is currently only available for items within your inventory, to be performed on a shulker within a chest or other storage.

**Is your feature request related to a problem? Please describe.**
I would like to be able to view the NBT data and drag fake illegals into my inventory, as when a shulker is peeked within the inventory you can drag fake items from the window. It is purely an aesthetic change, as extratooltips locked shulker view also allows you to view nbt data.

**Comment by jennifer-uwu** [comment]
you can use fake creative for fake illegals

**Comment by TheGreatRambler** [comment]
It doesn't allow me to put existing illegals into my hand from shulkers within chests so I wouldn't say it is a replacement

**Comment by jennifer-uwu** [comment]
you can use creative toolbars to save the items you want

**Comment by TheGreatRambler** [comment]
I can *create* illegals with fake creative, I can't take them out of shulkers from dispensers. It isn't an exact replacement. If the feature is not worth implementing just say that
