### ISSUE TITLE
[BUG] Schematics move with freecam.

### ISSUE THREAD

**Issue by Chiwarn** [John200410/rusherhack-issues#1057]
**Describe the bug**
When im trying to move around and look at a schematic the entire thing moves around with freecam.
**To Reproduce**
Load a schematic, turn on freecam, and move around.

**Other mods**
Future client, Schematica, Lunartis core, Journey map, Rusherhack (obv), And baritone.

**Expected behavior**
To move around and observe the schematic freely.

**Additional context**
Im not sure if this is a problem with schematica, or rusher hack, or future, but if it is correlating with rusherhack it would be nice to have it fixed

**Comment by John200410** [comment]
This is a bug from schematica's side, not rusherhack.

You can either use Freecam mode Old or use this patched version of schematica: https://cdn.discordapp.com/attachments/813750678060269648/868982870855802891/Schematica-1.12.2-1.8.0.169-universal_patc-875C2.jar
