### ISSUE TITLE
[BUG] Alt Maganer & Replay Mod

### ISSUE THREAD

**Issue by rockeZZergon** [John200410/rusherhack-issues#106]
Issue on screenshot 
![image](https://user-images.githubusercontent.com/64991049/98211695-162d2e00-1f4b-11eb-9f51-59ed6892ac4d.png)

**Comment by John200410** [comment]
ReplayMod shifts the y value for the buttons. I have added compatibility for my button. Fix will be in the next update.
![image](https://user-images.githubusercontent.com/43681932/98280966-27396780-1f6a-11eb-925a-fa50382e372a.png)
