### ISSUE TITLE
[FEATURE] anvil burrow

### ISSUE THREAD

**Issue by droideka101** [John200410/rusherhack-issues#1068]
**What feature would you like to be added.**
auto burrow for anvils

**Is your feature request related to a problem? Please describe.**
for servers that have fakejump patched so u can still burrow

**Additional context**
n/a

**Comment by jennifer-uwu** [comment]
what servers have fake jump patched? lmao

**Comment by droideka101** [comment]
> what servers have fake jump patched? lmao

the ones that have patched phase and burrow

**Comment by jennifer-uwu** [comment]
I think most server burrow patches just move you out of the block, but you could always use non instant burrow if it's just the fake jump that is patched
