### ISSUE TITLE
[FEATURE] Faster Strafe

### ISSUE THREAD

**Issue by HausemasterIssue** [John200410/rusherhack-issues#1069]
**What feature would you like to be added.**
future strafe goes over 26 km/h on strict and 28 km/h on normal. rusherhack needs to be faster, it only goes around 24 km/h on strict. you need to improve it to go faster john.

**Is your feature request related to a problem? Please describe.**
i hate it when shitty future users can run away all the day from a rusherhack user faster than they can catch them and ez them.

**Additional context**
john is cool

**Comment by SoggyBacco** [comment]
future strafe is the same speed as rh, only difference is velocityboost. future is also 24km on strict and 27 on nonstrict

**Comment by HausemasterIssue** [comment]
hmmm i don't think so. multiple sources have confirmed that future does go 26 km/h on strict. it's new with 2.11.1 i think, but you'd have to load up future and see for urself.

**Comment by SoggyBacco** [comment]
i use future and rh every time i log on, strictstrafe is 24km on both clients.
