### ISSUE TITLE
[FEATURE] setting for scaling ALL hud elements

### ISSUE THREAD

**Issue by Badinek** [John200410/rusherhack-issues#1072]
**What feature would you like to be added.**
A detailed explanation of what this feature should be.
Add "Scale" setting to every hud element to make it bigger/smaller, the minecraft gui scale setting doesnt really help in this scenario. If it would be too much of bother then atleast make it for the Inventory hud element.

**Is your feature request related to a problem? Please describe.**
An user wanted this feature for Inventory, so you could do it for all while at it.

**Additional context**
boe jiden

**Comment by Vaimok** [comment]
i support this suggestion!

**Comment by GentlemanMC** [comment]
Do it

**Comment by John200410** [comment]
Duplicate of #576
