### ISSUE TITLE
[BUG] 2b2tlist doesnt do anything

### ISSUE THREAD

**Issue by Badinek** [John200410/rusherhack-issues#1073]
**Describe the bug**
the *2b2tlist command doesnt work- it only says "could not connect". An user reported this and wanted me to make issue.

**To Reproduce**
type *2b2tlist  in chat and see

**Other mods**
List other forge mods you are using (if any):
doesnt affect

**Expected behavior**
i expect it to print out list of online players as it should

**Screenshots**
https://i.imgur.com/WsmIWdu.png

**Additional context**
balls

**Comment by John200410** [comment]
This is because RusherB0T is offline. Not a bug in rusherhack
