### ISSUE TITLE
[BUG] Nametags disappearing.

### ISSUE THREAD

**Issue by 7x47** [John200410/rusherhack-issues#1074]
**Describe the bug**
When a Nametag approaches the edge of your screen, it disappears.

**To Reproduce**
Set up a Fakeplayer or just get an alt, distance doesn't matter. Look up slowly. When the Nametag gets close to the edge of your screen, it should disappear.

**Other mods**
Future Client, Baritone & Optifine

**Expected behavior**
The Nametag should NOT disappear when it approaches the edge of your screen.

**Screenshots**
 - Still there https://user-images.githubusercontent.com/91796156/135725316-c403872e-e011-41b9-ba3e-21ed583c64b2.png
 -  Near Edge https://user-images.githubusercontent.com/91796156/135725318-fd847419-920f-4647-aec8-ef5706c43674.png
 - Gone https://user-images.githubusercontent.com/91796156/135725319-ff355be1-2eb8-4a37-b9cf-2406487a4a3d.png

**Additional context**
No Added Context.

**Comment by John200410** [comment]
This has been fixed in the next update.
