### ISSUE TITLE
[FEATURE] Look Backwards

### ISSUE THREAD

**Issue by SynnKFPS** [John200410/rusherhack-issues#1077]
**What feature would you like to be added.**
A Module that when you press the key you set, your camera turns to the back of the player, and when you release it, the camera returns to normal. Can't be rotated above 180°

**Is your feature request related to a problem? Please describe.**
There is no way to know who is behind you without pressing F5 3 times or using tracers

**Additional context**
Option "i dont know a name": If enabled, when you release the key, your real camera will be not changed

**Comment by LiquidSmokeBalls** [comment]
freelook.

**Comment by SynnKFPS** [comment]
what

**Comment by LiquidSmokeBalls** [comment]
freelook makes it so if u hold a certain bind u can look in any direction and ur still able to go in the same direction

**Comment by SynnKFPS** [comment]
yes but you will need to move your mouse to back everytime you start freelooking

**Comment by WQDIJ1w** [comment]
hi

**Comment by WQDIJ1w** [comment]
@everyone

**Comment by jennifer-uwu** [comment]
freelook

**Comment by SynnKFPS** [comment]
its not

**Comment by WQDIJ1w** [comment]
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D
D

**Comment by SynnKFPS** [comment]
shut tup

**Comment by jumboman32** [comment]
F5
