### ISSUE TITLE
[FEATURE] Change antiAFK chat message

### ISSUE THREAD

**Issue by RalphORama** [John200410/rusherhack-issues#1078]
## What feature would you like to be added.

It would be nice to have the option to change the default antiAFK message or pick randomly from a .txt file like the spammer module.

## Is your feature request related to a problem? Please describe.

The default antiafk message "hey guys, I am new, does anyone have coordinates for a farm?" is effective but kinda lame lol. I would just like to add more variety.

## Additional context

N/A

**Comment by John200410** [comment]
This setting has been removed. Use Spammer instead.
