### ISSUE TITLE
[FEATURE] hud options

### ISSUE THREAD

**Issue by RoastedCheese** [John200410/rusherhack-issues#1080]
Add an option under hud elements to show only the value and the measurement (e.g. only showing 0.0 b/s instead of Speed: 0.0 b/s or only showing Default instead of Profile: Default). Also, an option to show the nether coords in the position hud element on a separate line would be very useful
This would remove a lot of clutter from the hud and practically remove the issue of coordinates colliding with the hotbar (I know that there is already the x-y option but I think it would look much better this way).

**Comment by John200410** [comment]
This has been added in the next update
