### ISSUE TITLE
[BUG] no cluster doesnt work when enemy is on fire

### ISSUE THREAD

**Issue by GentlemanMC** [John200410/rusherhack-issues#1082]
**Describe the bug**
A clear and concise description of what the bug 
when an enemy is burning no cluster stops working

**To Reproduce**
1-find a player
2-cluster
3-make him burn
**Other mods**
List other forge mods you are using (if any):

**Expected behavior**
alpha shouldnt be at maximum when enemy is on fire
**Screenshots**
im on mobile :trollface: 
**Additional context**
no cluster doesnt turn down armor alpha btw

idk if its an issue

**Comment by John200410** [comment]
This has been fixed in the next update.
