### ISSUE TITLE
[BUG] nametags shows -0 for totem pop counter

### ISSUE THREAD

**Issue by Doogie13** [John200410/rusherhack-issues#1087]
**Describe the bug**
The NameTags Module shows -0 or -1 instead of 0 or 1 for totem pops

**To Reproduce**
use nametags with totem pops enabled, 
look at player
see issue

**Other mods**
![image](https://user-images.githubusercontent.com/62295632/136704569-be2d03ab-9170-4836-b744-85f3a3603d22.png)
+ future client

**Expected behavior**
shows 0 or 1 rather than -0 or -1

**Screenshots**
![image](https://user-images.githubusercontent.com/62295632/136704590-f837a203-c6e5-4cf8-a634-248545bcdba7.png)

**Comment by John200410** [comment]
This is intended.
