### ISSUE TITLE
[FEATURE] AutoEat compatibility with Boatfly

### ISSUE THREAD

**Issue by tycrek** [John200410/rusherhack-issues#109]
**What feature would you like to be added.**

Vanilla MC doesn't let you eat while *moving* in boats and it looks like autoeat is affected by this too. You can get around it by stopping flying, then start eating, and continue flying. You only need to stop for a split second for it to work. Maybe there could be a setting in AutoEat called "Boat" that will automatically stop flight to start eating then continue immediately after. The key thing is that you *can* eat while flying, it just has to stop moving to start eating.

**Comment by tycrek** [comment]
Oh also show hunger bar while in a Boat

**Comment by John200410** [comment]
Thank you for the suggestions

**Comment by John200410** [comment]
The ability to use your hand while rowing a boat in boatfly has been added.
