### ISSUE TITLE
[FEATURE] Update extrasign.json autosign message via chat command

### ISSUE THREAD

**Issue by RalphORama** [John200410/rusherhack-issues#1096]
## What feature would you like to be added.

Like the `spammer` command, the message automatically added to signs by ExtraSign > AutoSign should have a chat/console command to update the message. 

## Is your feature request related to a problem? Please describe.

As far as I'm aware, the only way to update the AutoSign message is to edit `.minecraft/rusherhack/extrasign.json` and restart the client. It would be nice to simplify the process of updating this message.

**Comment by John200410** [comment]
In the next update I have made it so the sign text saves when you modify it in the edit sign screen.

I believe this to be the simplest way of doing it
