### ISSUE TITLE
[FEATURE] Autodupe

### ISSUE THREAD

**Issue by Overheadcams** [John200410/rusherhack-issues#1104]
**What feature would you like to be added.**
AN autodupe that when activated, drops the item in your main hand, and without opening inventory activates the recipe to craft a button.

**Is your feature request related to a problem? Please describe.**
No

**Additional context**
This is an item dupe that works in servers like 5b5t and is called the inventory crafting dupe.

**Comment by jennifer-uwu** [comment]
bloat
