### ISSUE TITLE
[FEATURE] 2b2t 6/8hr limit timer

### ISSUE THREAD

**Issue by Sand-Turtle** [John200410/rusherhack-issues#1115]
**What feature would you like to be added.**
A module (with a customizable time) which will count down how long you have been in the main 2b2t server. 
Ideally it will automatically start when u switch to the main 2b2t server from queue and not activate in proxies. 
It could change the name of the window from "minecraft 1.12.2" or override the name of a client changing the name (or just concatenate it) into a timer.
It should notify you when it reaches close to the end of the timer as well

**Is your feature request related to a problem? Please describe.**
Not knowing how long you have left in the server is a pain for when u need to be online for an event or something that you need to do in one go.

**Comment by John200410** [comment]
Use the OnlineTime hud element
