### ISSUE TITLE
(BUG) i cant download rusherhack jar pls give

### ISSUE THREAD

**Issue by sdfffsscxxx** [John200410/rusherhack-issues#1117]
**Describe the bug**

**To Reproduce**

**Other mods**
List other forge mods you are using (if any):

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by LiquidSmokeBalls** [comment]
Get the role in the rusherhack discord and then you can download it by logging into the installer.

-John

**Comment by sdfffsscxxx** [comment]
whers the disocrd link

**Comment by FluorideHistorian** [comment]
in the installer

**Comment by sdfffsscxxx** [comment]
wheres the installer

**Comment by FluorideHistorian** [comment]
rusherhack.org/users

**Comment by sdfffsscxxx** [comment]
i have my login and everything

**Comment by LiquidSmokeBalls** [comment]
so login 😐

**Comment by sdfffsscxxx** [comment]
I have a email and password
It says hey cant do cpaitals and shit

**Comment by John200410** [comment]
This is the issue tracker. Not a place to ask for support
