### ISSUE TITLE
[FEATURE] Add Highwaytools

### ISSUE THREAD

**Issue by McUtter11** [John200410/rusherhack-issues#1121]
I know we already have auto tunnel but it is inconsistent and it does not place obsidian. Baritone works too but it is slow as fuck and stops randomly.  I'm suggesting we add a highway tools like kami blue where it will search shulkers and mine E-Chests for obsidian. However even with kami blue's highway tools it is slow as well on some servers. Just fork auto tunnel into highway tools and automate it so it can search shulkers automatically.

**Comment by jumboman32** [comment]
That would be selling HWT.
