### ISSUE TITLE
[FEATURE] Gradient Animation in the ArryList

### ISSUE THREAD

**Issue by Infisrael** [John200410/rusherhack-issues#1122]
**What feature would you like to be added.**
A Gradient Animation in the ArryList
(eg. https://i.imgur.com/A6u17wo.png)

**Is your feature request related to a problem? Please describe.**
none.

**Additional context**

**Comment by Ozynt** [comment]
duplicate, you made the issue first but the other issue has a better video showing the animation so I will close this. #1160
