### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by Chiwarn** [John200410/rusherhack-issues#1125]
**What feature would you like to be added.**
An option to make it so nuker doesn't mine under you.

**Is your feature request related to a problem? Please describe.**
When I'm standing on top of something and turn on nuker to clear something, or for other reasons. It mines under me making it hard to remove anything.

**Additional context**
I would like if nuker had an option to not mine the block you are standing on.

**Comment by John200410** [comment]
Enable the Flatten setting.
