### ISSUE TITLE
[FEATURE] make spammer use /msg instead of /w

### ISSUE THREAD

**Issue by mmvanheusden** [John200410/rusherhack-issues#1127]
**What feature would you like to be added.**
spammer with whisper enabled uses /w [message] by default, and i want it to use /msg instead

**Is your feature request related to a problem? Please describe.**
i play on a server where /w is disabled.

**Comment by jumboman32** [comment]
Might as well just make it customizable

**Comment by mmvanheusden** [comment]
yes

**Comment by John200410** [comment]
This has been done in the next update.
