### ISSUE TITLE
[FEATURE] Make ESP Outline not Outline Fire

### ISSUE THREAD

**Issue by HausemasterIssue** [John200410/rusherhack-issues#1128]
**What feature would you like to be added.**
With ESP Outline mode, when someone catches on fire the outline ESP outlines the fire and the player. It looks ugly and is annoying.

**Is your feature request related to a problem? Please describe.**
It may be a bug, it may be intentional, either way there should be an option for it.

**Additional context**

**Comment by Infisrael** [comment]
cry about it

**Comment by Phantom568** [comment]
Use mode Shader instead

**Comment by HausemasterIssue** [comment]
Shader mode takes a huge hit on my performance, plus the lines get kind of blurry. Outline mode uses up way less resources and looks better, it's just the fire outline bug that needs a quick fix.

**Comment by TwoThreeTwo** [comment]
This has been fixed for a bit.
