### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by spazzzzz** [John200410/rusherhack-issues#1131]
prediction mode to autototem so when off handing it can switch to a totem if there is  a crystal or another entity that could do damage

**Comment by HausemasterIssue** [comment]
The AutoTotem in RusherHack is pretty hard to config and isn't really that good. It could use with a rewrite. It does work quite good on 2b, but more understandable settings and things like Smart mode, Right Click Gap etc. could be really good, especially if it is designed for strict.

**Comment by Vaimok** [comment]
rh autototem works fine on 2b2t.

**Comment by HausemasterIssue** [comment]
It does. Just it could use a lot more features such as right click gap.

**Comment by John200410** [comment]
Duplicate of #806
