### ISSUE TITLE
[FEATURE] RainbowEnchant Durability

### ISSUE THREAD

**Issue by Lavacasted** [John200410/rusherhack-issues#1133]
**What feature would you like to be added.**
RainbowEnchant but when armor is 75-100% dura the enchant glint is green, 50-70% is orange, 20-40% is yellow, 1-19% is red

**Is your feature request related to a problem? 
No

**Additional context**

Will be useful when I am doing stash sorting and i can see what durability level my armors have without opening the shulker. (while using peek tooltip ofc)

**Comment by John200410** [comment]
This has been added in the next update:

https://rusherhack.org/i/r1gorhnzwd.mp4
