### ISSUE TITLE
[BUG] Criticals will attempt to perform critical hits on end crystals

### ISSUE THREAD

**Issue by Doogie13** [John200410/rusherhack-issues#1138]
**Describe the bug**
Criticals will attempt to crit crystals which is useless 

**To Reproduce**
Use Criticals on .cc
Use CA with fast config
Get kicked over and over (its not the CA causing this)

**Other mods**
List other forge mods you are using (if any):
![image](https://user-images.githubusercontent.com/62295632/142928914-2d7bd368-b7ea-4888-be15-baaa502bb3e4.png)

**Expected behavior**
Don't try to crit if the attacked entity is a crystal

**Screenshots**
N/A

**Additional context**
![image](https://user-images.githubusercontent.com/62295632/142929037-ad98babd-b4aa-4417-9c86-d8440b2c38ab.png)

**Comment by jennifer-uwu** [comment]
wtf is that shitcode lmfao

**Comment by John200410** [comment]
Criticals already only works on living entities.
