### ISSUE TITLE
[FEATURE] Rotation Lock

### ISSUE THREAD

**Issue by CaptainTheBeam** [John200410/rusherhack-issues#114]
**What feature would you like to be added.**
Locks your view to a certain angle so you cant change it useful for afk flying on the highways with autowalk

**Is your feature request related to a problem? Please describe.**
Boats going off the side of the highways when flying hands-free, not really a problem but is very annoying.

**Additional context**
Make it so it would snap onto the horizontal and diagonal highways

**Comment by John200410** [comment]
RotationLock is already in the client. Player -> RotationLock. However it currently does not work in vehicles (fixed in v1.1.2)
