### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by icpvpbadly** [John200410/rusherhack-issues#1143]
**What feature would you like to be added.**
add a working bowbomb and make it seperate from bowspam and shader chams

**Is your feature request related to a problem? Please describe.**
for the shader chams no its not a problem, but the bowbomb inside bowspam doesnt work at all

**Additional context**
i love you john

**Comment by John200410** [comment]
BowBomb is patched on 2b2t.

Rest is duplicate of #1140
