### ISSUE TITLE
[BUG] Search Range Is Not Working Properly

### ISSUE THREAD

**Issue by HausemasterIssue** [John200410/rusherhack-issues#1145]
**Describe the bug**
I use search a lot for base hunting. Usually, when something that search will pick up comes into render distance, it won't pick it up until I get closer to it. Also, some things can be right under me and search won't pick them up for a bit. All these issues occur when I'm at 500 range (the max). ESP usually picks them up the moment they come into render distance, but search does not until I get a bit closer to them.

**To Reproduce**
Set the range on search to Max, and put a chest right out of your render distance, then load the chunk and ESP should pick it up but search won't until you get closer.

**Other mods**
OptiFine

**Expected behavior**
Search should be able to pick up stuff the moment it comes into render distance.

**Screenshots**
Not applicable, try it yourself.

**Additional context**
You should either rework the search range, or increase the default max range to 1000 or something bigger so you can pick up stuff the moment it comes into render distance.

I'm on 12 render distance by the way.

Yes I know I can just increase the range via commands but that's a bit annoying.

P.S. Can you add an AutoSwitch option to AutoTrap, where you can choose between swapping silent, normal, or none please?

**Comment by John200410** [comment]
This has been fixed in the next update.
