### ISSUE TITLE
Piston Aura

### ISSUE THREAD

**Issue by Affenballe** [John200410/rusherhack-issues#1146]
**What feature would you like to be added.**
Piston Aura

**Is your feature request related to a problem? Please describe.**
It's not related to a problem, i just think it would make the client better overall.

**Additional context**
I'm not sure if the hack itself is called "Piston Aura" but it basically just allows you to automatically place a piston and place a redstone torch (or button or something that can activate it) and push an end crystal over your enemy's head so it will do full damage even in a hole.

**Comment by browsky300** [comment]
john closed the original piston aura issue and said he won't add it

**Comment by jennifer-uwu** [comment]
duplicate #271
