### ISSUE TITLE
Quality of life features that i'd like

### ISSUE THREAD

**Issue by 06d** [John200410/rusherhack-issues#1149]
.coords (if you type the command it copies your coordinates to your clipboard)
A bind in autoarmor for elytra switch
opacity setting for viewmodel
Seprate module for reverse step (I know it already exists in the step module but they are fused)
A width setting for scaffold 
Old render modes for packetmine
transparent mode for chams in normal mode
A beacon for pearls in pvp info (would be more helpful than just coordinates)

**Comment by Lavacasted** [comment]
*coords is already implemented in client.

**Comment by Ozynt** [comment]
- [ ] *coords
- [ ] elytrabind in autoarmor
- [ ] opacity setting for viewmodel
- [ ] Seprate module for reverse step
- [ ] A width setting for scaffold
- [ ] Old render modes for packetmine
- [ ] transparent mode for chams
- [ ] A beacon for pearls in pvp info

**Comment by John200410** [comment]
A separate module for reverse step is not happening.

Width setting for Scaffold #881 

What do you mean by "Old render modes for packetmine"?

"transparent mode for chams in normal mode" If you use Fill mode then set the color to white (while having Texture setting enabled), you can use the Opacity slider.

"A beacon for pearls in pvp info (would be more helpful than just coordinates)" What do you mean by this? If a trajectory then you can just use the Trajectories module.

**Comment by Ozynt** [comment]
All of these suggestions is already in other issues.
