### ISSUE TITLE
[BUG] AutoEat Gapples eats gapples infinitely 

### ISSUE THREAD

**Issue by tycrek** [John200410/rusherhack-issues#115]
**Describe the bug**

AutoEat gapples keeps eating them until you scroll away.

**To Reproduce**

![image](https://user-images.githubusercontent.com/29926144/98333149-588f5300-1fbd-11eb-907c-ec5513c528fa.png)

**Comment by John200410** [comment]
Unable to reproduce. What is the TPS of the server you are trying this on?

**Comment by tycrek** [comment]
> 
> 
> Unable to reproduce. What is the TPS of the server you are trying this on?

It's on 2b2t in any TPS. I have it set to gaps (rarely carry food anymore) and it just continuously eats them.

**Comment by John200410** [comment]
Can you try getting a recording of this happening?

**Comment by tycrek** [comment]
Sure

**Comment by tycrek** [comment]
OBS is crashing my laptop now, nice

**Comment by John200410** [comment]
Any update on that recording?

**Comment by tycrek** [comment]
It got fixed in an update somehow, I'm unable to reproduce it.
