### ISSUE TITLE
Unmerge Step and ReverseStep

### ISSUE THREAD

**Issue by SewerHatch** [John200410/rusherhack-issues#1153]
As for me and many pvpers it is needed to keep ReverseStep enabled at all times but be able to enable and disable Step on keybind when needed. Current macro system cant solve this issue so i ask you to make two separate modules that would work independantly

**Comment by Vaimok** [comment]
no.

**Comment by John200410** [comment]
The current macro system does solve this issue. Create a bind to toggle the Upwards setting.

**Comment by SewerHatch** [comment]
but you cant toggle settings, right? i could manage it only via *set but it would require you to use 2 bind buttons to toggle and untoggle it

**Comment by John200410** [comment]
*macro add <key> step upwards

this macro will toggle the upwards setting

**Comment by 06d** [comment]
> 

wouldn't it just be easier to unmerge them tho?
Would be simpler to understand/use than to make some macro

**Comment by John200410** [comment]
I'm not separating them.
