### ISSUE TITLE
I dont know if this is a Bug but every time i join it says The hwid check has failed. Please request a hwid reset using the support button on our site 

### ISSUE THREAD

**Issue by FutureNNV** [John200410/rusherhack-issues#1156]
**Describe the bug**

**To Reproduce**

**Other mods**
List other forge mods you are using (if any):

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by John200410** [comment]
Did you read what it said? Use the support button on the website and don't post a bug report on the issue tracker
