### ISSUE TITLE
[FEATURE] NoBob

### ISSUE THREAD

**Issue by HausemasterIssue** [John200410/rusherhack-issues#1157]
**What feature would you like to be added.**
NoBob, not just turn the bobbing setting off but like Future's where your arms go down a bit while walking? Example of it https://www.youtube.com/watch?v=0Xrixu3KTZg

**Is your feature request related to a problem? Please describe.**
Nah, just a nice visual feature I'd quite like in RusherHack.

**Additional context**
It is sexy

**Comment by NutrientAphid** [comment]
optifine exists
options> video settings> view bobbing> off

**Comment by HausemasterIssue** [comment]
@NutrientAphid No like, have you ever seen Future NoBob? like you don't walk and your arms are static, then if u walk they go down and stay down until you don't move again, not literally disabling bobbing.

**Comment by John200410** [comment]
Can you provide a video of what you are talking about?

**Comment by HausemasterIssue** [comment]
@John200410 Code example: https://github.com/momentumdevelopment/momentum/blob/main/src/main/java/me/linus/momentum/module/modules/render/NoBob.java

Video example: https://www.youtube.com/watch?v=0NR_Y8Ptq3A&t=49s

Look at how the players hands look when they walk and stop walking.

**Comment by John200410** [comment]
This has been added in the next update as a setting to NoRender
