### ISSUE TITLE
[FEATURE] ExtraChat/Notifications Mention "self" toggle

### ISSUE THREAD

**Issue by tycrek** [John200410/rusherhack-issues#116]
**What feature would you like to be added.**

(reminder from discord) have a `self` setting to not make the Ding sound effect or send a system notification if you sent the message

**Comment by John200410** [comment]
Thank you for the suggestion

**Comment by John200410** [comment]
MentionIgnoreSelf setting has been added to ExtraChat and will appear in the next update.
