### ISSUE TITLE
[FEATURE] Scrolling array list color 

### ISSUE THREAD

**Issue by 2147483647ms** [John200410/rusherhack-issues#1160]
Scrolling array list color.
Set a min and max color then it will scroll through the colors and all intermittent colors.

**Comment by Ozynt** [comment]
like this?
https://user-images.githubusercontent.com/58683893/159116488-399cf2f3-1500-44c7-a179-876d7ea57fa3.MOV

**Comment by 2147483647ms** [comment]
yes

**Comment by Ozynt** [comment]
Please add this color animation for all hud elements and make the animation sync.

**Comment by Ozynt** [comment]
This has been added in the next update.
