### ISSUE TITLE
[FEATURE] Edit Notifications

### ISSUE THREAD

**Issue by wce2005a** [John200410/rusherhack-issues#1161]
**What feature would you like to be added.**
Customize Icon, Instead of lightbulb, make background for it custom, rounded edges etc

**Is your feature request related to a problem? Please describe.**
GUI Notifications are a pain if they arent clean

**Additional context**
Just a nice to have..Please add it though

**Comment by John200410** [comment]
You can already change the icon via texturepack

**Comment by John200410** [comment]
Notification customization has been added in the next update.
