### ISSUE TITLE
[FEATURE] Proxy Support

### ISSUE THREAD

**Issue by wce2005a** [John200410/rusherhack-issues#1162]
**What feature would you like to be added.**
Proxy support so you can connect to 2b with more than 3 accounts and other servers the same.

**Is your feature request related to a problem? Please describe.**
This will also help for IP loggers, use presets and such.

**Additional context**
add to window manager ig

**Comment by HausemasterIssue** [comment]
Sounds kinda complicated to me, you probably have to spend money on a VPS or something.

**Comment by wce2005a** [comment]
> Sounds kinda complicated to me, you probably have to spend money on a VPS or something.

No, You just use a socks5 proxy lmao
IP:PORT and if its premium then auth

**Comment by John200410** [comment]
Can't you just use a VPN?

**Comment by wce2005a** [comment]
> Can't you just use a VPN?

Point is so I can have 2 accounts on a server that only allows 1 or 2b because they limit accounts to 3 per ip

**Comment by John200410** [comment]
> > Can't you just use a VPN?
> 
> Point is so I can have 2 accounts on a server that only allows 1 or 2b because they limit accounts to 3 per ip

So why can't you just use a VPN?

**Comment by wce2005a** [comment]
Because I can't have 2 different proxied accounts on the same PC?

**Comment by John200410** [comment]
You can join with a VPN then switch locations after you connect to the server

**Comment by wce2005a** [comment]
If you dc from a vpn it kicks you, if you join without one you can only have one but its fine ill just use a separate mod

**Comment by John200410** [comment]
Yea I don't really want to add this into rusherhack

**Comment by end41r** [comment]
Genius john lol
