### ISSUE TITLE
[FEATURE] Color Sync

### ISSUE THREAD

**Issue by Infisrael** [John200410/rusherhack-issues#1163]
**What feature would you like to be added.**
Color sync for hud elements, so you pick a color and it syncs with the other hud elements colors

**Is your feature request related to a problem? Please describe.**
1 color for every hud element looks clean to me and I can't be asked to do it manually for each one.

**Comment by wce2005a** [comment]
yes pls

**Comment by John200410** [comment]
Duplicate of #63
