### ISSUE TITLE
Custom View model[FEATURE]

### ISSUE THREAD

**Issue by Cooliokid** [John200410/rusherhack-issues#117]
**What feature would you like to be added.** 
Makes it so i can change scale and change item location 

**Is your feature request related to a problem? Please describe.**
I used pyro but I switched because its bad and view model is the only thing i miss from pyro

**Additional context**
Screenshots of pyro viewmodel
also this could replace small sheild 
![image](https://user-images.githubusercontent.com/69168012/98403391-bfdcef80-201d-11eb-94e8-c316d7760d46.png)

**Comment by John200410** [comment]
Thank you for the suggestion

**Comment by John200410** [comment]
TODO: Setting for hand

**Comment by John200410** [comment]
This has been made.
https://www.youtube.com/watch?v=HmbFb4LYfFI
