### ISSUE TITLE
[FEATURE]Add RenderScale for the BoatFly

### ISSUE THREAD

**Issue by 0popbob** [John200410/rusherhack-issues#118]
Add RenderScale for the BoatFly 
add a render for the boatfly because when using it it is difficult to see the road and it would be good to be able to see the road

**Comment by John200410** [comment]
Thank you for the suggestion

**Comment by John200410** [comment]
This has been finished and will be in the next update.
![image](https://user-images.githubusercontent.com/43681932/98458715-94631d80-2161-11eb-9f46-c4d8a42e7ff4.png)
