### ISSUE TITLE
[BUG] Walking sideways with Speed and NoSlow with your shield up sends you flying

### ISSUE THREAD

**Issue by Silkaaa** [John200410/rusherhack-issues#1182]
**Describe the bug**

Using Speed and NoSlow with your shield up sends you flying

**To Reproduce**

1) Turn on speed (on strafe mode)
2) Turn on NoSlowdown
3) Get a shield
4) Put your shield up and press "A" or "D"

**Other mods**
List other forge mods you are using (if any):

3arthqu4ke client

**Expected behavior**
I expect it to strafe/bhop normally.

**Screenshots**

**Additional context**

**Comment by NutrientAphid** [comment]
this also happens eating

**Comment by ZenovJB** [comment]
prolly on phoboses side

**Comment by HausemasterIssue** [comment]
Yeah phobos causes this i think, i tried it with phobos 1.3.1 and the same issue occured, and without it the issue went away so its a compativility issue probably

**Comment by John200410** [comment]
Are you using Rusher's NoSlow and Speed?

**Comment by teejwrld** [comment]
if your using noslow on rusher and other clients it can do that

**Comment by HausemasterIssue** [comment]
I tried this with Future and GameSense at once, without rusher, and the same issue occured. i turned on both noslow's, turned on strafe and went flying sideways. so i don't think it's necessarily a compatibility issue with rusherhack itself. noslow works by multiplying your move values to cancel out the noslow, and when two noslow's are active at once maybe they multiply your movement by 5, then another client's noslow multiplies it by 5 too causing you to go flying? anyways idk, it could just be that rusher's noslow is done in some different way or is chinese.

**Comment by teejwrld** [comment]
It's just the noslows are coded differently and can bug out if they are used together, to fix it all you need to do is use 1 clients noslow

**Comment by HausemasterIssue** [comment]
^ Exactly. close this issue john.
