### ISSUE TITLE
[FEATURE] plus cape

### ISSUE THREAD

**Issue by ghost** [John200410/rusherhack-issues#1184]
**What feature would you like to be added.**
A detailed explanation of what this feature should be.
being able to change plus cape accounts in the installer // being able to change the account once a month in the installer //  use uuid to store the cape account instead of username

**Comment by jumboman32** [comment]
john had said this won't happen

**Comment by John200410** [comment]
> john had said this won't happen

what when did i say that

**Comment by John200410** [comment]
i have been saying the opposite

**Comment by TwoThreeTwo** [comment]
Well, 
>use uuid to store the cape account instead of username

John added this on 8/10/2022 (August 10, 2022). Since they're based off UUID, then the only way you can change it is every 2 weeks due to Mojang implementing that. Can we close this issue?

**Comment by TwoThreeTwo** [comment]
Gonna close this since referring to my comment it is technically completed
