### ISSUE TITLE
AutoSurround Issue

### ISSUE THREAD

**Issue by 0rthrus** [John200410/rusherhack-issues#1186]
Issue with "Center" option within the module "AutoSurround" where if you are not perfectly in a certain spot, then the module causes your game to jitter and becomes unplayable until you disable the module. I think that a possible solution to this could be making an option within "Center" which allows you to adjust how quickly you are redirected to the center of the block so that you are able to use "AutoSurround" without any issues like this.
I have linked a video of the issue.
[https://streamable.com/nyzvmt](https://streamable.com/nyzvmt)

**Comment by John200410** [comment]
This has been fixed in the next update.
