### ISSUE TITLE
[BUG] Freecam and AutoWalk doesn't work with Boatfly

### ISSUE THREAD

**Issue by rockeZZergon** [John200410/rusherhack-issues#119]
1) If you turned on AutoWalk and Boatfly, u will not move
2) If you turned on freecam while boatflying, "antikick" will stop work, so you will get kicked after few seconds

**Comment by John200410** [comment]
Thank you for reporting these bugs

**Comment by John200410** [comment]
Both of these bugs have been fixed and will appear in the next update.
