### ISSUE TITLE
[FEATURE] glint speed setting to rainbowenchant

### ISSUE THREAD

**Issue by GentlemanMC** [John200410/rusherhack-issues#1192]
**What feature would you like to be added.**
A setting that changes the glint animation speed 

**Additional context**
maybe also rename rainbowenchant to enchantcolor

**Comment by HausemasterIssue** [comment]
Seems complicated to implement.

**Comment by John200410** [comment]
This has been added in the next update.

**Comment by TwoThreeTwo** [comment]
WHAT?

**Comment by GentlemanMC** [comment]
🕺
