### ISSUE TITLE
[BUG] NCP Step is unreliable (2b2tpvp)

### ISSUE THREAD

**Issue by Doogie13** [John200410/rusherhack-issues#1197]
**Describe the bug**
NCP step does not use correct timer speed. It should use `50 * (packets.length + 1)` with the `+1` for vanilla sending the move packet it ordinarily would. Instead, it just uses `50 * packets.length` (I assume, it is definitely too fast compared to Future, gs++)
It also might not use good offsets (I haven't checked)

**To Reproduce**
Use NCP step on 2b2tpvp.net with timer enabled and see that timer does not make the step bypass consistantly every step, using it multiple times in a short span.

**Other mods**
Future client, Optifine, Baritone

**Expected behavior**
Step will not rubberband at all and will use timer speed as calulated above

**Screenshots**
N/A

**Additional context**
Other NCP steps work perfectly fine consistantly, over and over.

**Comment by John200410** [comment]
It should be better in the next update.
