### ISSUE TITLE
Frame dupe

### ISSUE THREAD

**Issue by aledlb8** [John200410/rusherhack-issues#1201]
make a auto frame dupe :)

**Comment by HausemasterIssue** [comment]
It's like patched on virtually every server.

**Comment by aledlb8** [comment]
is not patched in 6b6t.org

**Comment by TwoThreeTwo** [comment]
but it is patched on every single server that is actually known. Not some russian cracked server with less than 30 players.

**Comment by NutrientAphid** [comment]
just use an autoclicker

**Comment by aledlb8** [comment]
6b6t.org has 100+ players

**Comment by TwoThreeTwo** [comment]
Yea but, Rusherhack is focused onto 2b2t, there's just things john wont add because he thinks it's bloat. I'd recomend that you find a client that has the "AutoFrameDupe" thing.

**Comment by HausemasterIssue** [comment]
Exactly, it's just not a practical to add something for a server that few people play, that is cracked, unpopular and will only be rarely used. Plus it's cracked I think so I doubt cracked users who can't afford the game can afford RusherHack.

**Comment by Justgamer101** [comment]
> Exactly, it's just not a practical to add something for a server that few people play, that is cracked, unpopular and will only be rarely used. Plus it's cracked I think so I doubt cracked users who can't afford the game can afford RusherHack.

actually, 6b is quite popular. You'd be surprised. This will never be implemented to rh because the only people who use rh on cracked servers use a cracked version of rh. If you want it, make it. It's just attacking the item in the frame then replacing it. Or just use an autoclicker lmao.

**Comment by John200410** [comment]
I'm not going to add this
