### ISSUE TITLE
[FEATURE] ViaVersion 1.12.2-1.16.4

### ISSUE THREAD

**Issue by rockeZZergon** [John200410/rusherhack-issues#121]
Its really important thing. There is one in Inertia Client, but i don't want to download it, its not so convient to use a lot of hacks, also Inertia is not compatible with every client, like rusherhack, so i wish it get added there

**Comment by notperry1** [comment]
> Its really important thing. There is one in Inertia Client, but i don't want to download it, its not so convient to use a lot of hacks, also Inertia is not compatible with every client, like rusherhack, so i wish it get added there

inertias compatible with rusherhack it works fine for me kek

**Comment by John200410** [comment]
Will have to look into how to do this. Will probably be in v1.2

**Comment by rockeZZergon** [comment]
> > Its really important thing. There is one in Inertia Client, but i don't want to download it, its not so convient to use a lot of hacks, also Inertia is not compatible with every client, like rusherhack, so i wish it get added there
> 
> inertias compatible with rusherhack it works fine for me kek

its not compatible with pyro

**Comment by CaptainTheBeam** [comment]
it’s compatible just rename pyro to zpyro so it loads after rusherhack

**Comment by notperry1** [comment]
> > > Its really important thing. There is one in Inertia Client, but i don't want to download it, its not so convient to use a lot of hacks, also Inertia is not compatible with every client, like rusherhack, so i wish it get added there
> > 
> > 
> > inertias compatible with rusherhack it works fine for me kek
> 
> its not compatible with pyro

funny thing it actually is also compatible with that

**Comment by John200410** [comment]
Closing this as there is a standalone forge mod to do this. https://www.curseforge.com/minecraft/mc-mods/viaforge
