### ISSUE TITLE
[FEATURE] AutoSilk

### ISSUE THREAD

**Issue by Bluefox187** [John200410/rusherhack-issues#1210]
**What feature would you like to be added.**
AutoSilk

**Is your feature request related to a problem? Please describe.**
A module that automaticly switches to a tool with Silktouch for whitelisted Blocks like Echests, grass, ores etc

**Additional context**

**Comment by 2u9** [comment]
could be an option under Autotool

**Comment by John200410** [comment]
SilkTouch setting added to AutoTool in the next update.
