### ISSUE TITLE
[BUG] Tunnel ESP Renders Lag Behind Where I am

### ISSUE THREAD

**Issue by HausemasterIssue** [John200410/rusherhack-issues#1212]
**Describe the bug**
When I'm up an about zooming around highways at 100km/h+ Tunnel ESP does not render. But, if I stay still for a few minutes it renders. It's almost like it needs to catch up to where I am.

**To Reproduce**
Turn on Tunnel ESP, and go zoom down terrain or a highway at 100km/h+ for a bit.

**Other mods**
List other forge mods you are using (if any):

Future
OptiFine
SqueakerBot
GameSense

**Expected behavior**
Tunnel ESP should always work and render no matter how fast I'm moving, as long as I'm in a loaded chunk it should render immediately.

**Screenshots**
Not really applicable.

**Additional context**
Fix, it's very annoying when base hunting.

**Comment by John200410** [comment]
It polls chunks with a delay to prevent performance loss. What is your render distance?

**Comment by HausemasterIssue** [comment]
My render distance is 8. I believe my PC should be able to handle it without a delay, unless the code is really unoptimized. You could add an option to remove the delay.

**Comment by John200410** [comment]
I have added multithreading to this setting in the next update. It should be much faster
