### ISSUE TITLE
[FEATURE] Reconnect Command

### ISSUE THREAD

**Issue by Bluefox187** [John200410/rusherhack-issues#1214]
**What feature would you like to be added.**
*reconnect / *rejoin

**Is your feature request related to a problem? Please describe.**
If theres a bug that could be fixed through rejoining it could help

**Additional context**
A Command that would leave the server and instatly rejoin to it

**Comment by ZenovJB** [comment]
> **What feature would you like to be added.**
> *reconnect / *rejoin
> 
> **Is your feature request related to a problem? Please describe.**
> If theres a bug that could be fixed through rejoining it could help
> 
> **Additional context**
> A Command that would leave the server and instatly rejoin to it

bro what the fuck it literally takes 2 clicks

**Comment by Bluefox187** [comment]
> bro what the fuck it literally takes 2 clicks 

lazy xD

**Comment by Ozynt** [comment]
If you gonna add this also add a disconnect command then.

**Comment by John200410** [comment]
You can use the "*connect" command to just reconnect to your current server.

*connect <server IP>

**Comment by John200410** [comment]
> If you gonna add this also add a disconnect command then.

I have added a *disconnect command in the next update
