### ISSUE TITLE
[FEATURE] ChorusControl predict esp

### ISSUE THREAD

**Issue by Ozynt** [John200410/rusherhack-issues#1215]
**What feature would you like to be added.**
I would like a esp that predicts were someones chorus tp is gonna tp. 

**Additional context**
Video of it, but a block esp would look better. 

https://user-images.githubusercontent.com/58683893/152617331-784ac17a-924e-4a09-83f9-2ebed60b036e.mp4

**Comment by TwoThreeTwo** [comment]
this has been added in 1.3

**Comment by TwoThreeTwo** [comment]
someone close this

**Comment by Ozynt** [comment]
Where?

**Comment by TwoThreeTwo** [comment]
ChorusControl Module with renderbox esp

**Comment by TwoThreeTwo** [comment]
brain issue occured

**Comment by Ozynt** [comment]
I see

**Comment by John200410** [comment]
This has been added in the next update.
