### ISSUE TITLE
[BUG] *namemc command

### ISSUE THREAD

**Issue by Ozynt** [John200410/rusherhack-issues#1217]
**Describe the bug**
When using the *namemc command it does not open the link in my browser. An option for the link to copy to the clipboard would be good. Im using linux and chromium. 

**To Reproduce**
*namemc (username)

**Expected behavior**
Does not open the link in my browser.

**Comment by Justgamer101** [comment]
then dont use linux

**Comment by John200410** [comment]
When you try to use the command does it return "Failed to open browser"?

**Comment by Ozynt** [comment]
No, there is no response at all.

**Comment by mmvanheusden** [comment]
Works for me on Fedora with Librewolf, (firefox fork) are you using chrome as a snap or flatpak?

**Comment by Ozynt** [comment]
I'm not using chrome. Im using the offical arch chromium package.

**Comment by Ozynt** [comment]
I found out what the issue was. I can't open normal links in Minecraft chat either. But when clicking links chat there is an option to open it in your browser or copy the link to the clipboard. An option like this would be great.
