### ISSUE TITLE
[FEATURE] No Longer Tying HWID to CPU/Memory Clock Speed 

### ISSUE THREAD

**Issue by clockwork04** [John200410/rusherhack-issues#1218]
**What feature would you like to be added.**
Adjusting system clocks/voltages not invalidating HWID 

**Is your feature request related to a problem? Please describe.**
For people who overclock and tweak system clock speed settings often requesting a hwid reset every time an adjustment is made 
is a bit of a pain, shouldn't Vendor/Model/NT Version be enough? or am i big dumb?

**Additional context**
:3

**Comment by John200410** [comment]
It already should not factor in your CPU clock speeds. What OS do you use?

**Comment by clockwork04** [comment]
> It already should not factor in your CPU clock speeds. What OS do you use?

Huh, thats weird im running Windows 10 21H1.. could memory clock have something to do with it?

**Comment by John200410** [comment]
It shouldn't. Would you mind joining the discord and contacting me personally? I would like to look into this more closely.
