### ISSUE TITLE
[BUG] Not all columns with modules fit on the screen

### ISSUE THREAD

**Issue by MapCHiK** [John200410/rusherhack-issues#1219]
not all columns with modules fit on the screen, so one of them (namely "Client") is outside the minecraft window and it is impossible to get it from there. I did everything - changed the resolution on the computer, changed the scale of the interface in minecraft, changed the resolution of minecraft itself, re-entered minecraft. Nothing really helps. (Translated by google translator)
![image](https://user-images.githubusercontent.com/91774323/152976879-b85ba598-ce5b-42b4-99aa-0b65f6fc8c92.png)
Edited: Im dumbfck, I just wrote *clickgui scale 0.8, and all fixed, blyat ya daun

**Comment by system69-e** [comment]
nice monitor

**Comment by John200410** [comment]
Change the ClickGui scale or enable ClickGui clamping.
