### ISSUE TITLE
[FEATURE] EnemyList

### ISSUE THREAD

**Issue by tycrek** [John200410/rusherhack-issues#122]
**What feature would you like to be added.**

Similar to FriendsList but for enemies. Possibly red name highlight in tablist and prioritised over regular players when in w PVP area

**Additional context**

Requested by Blocker on Discord

**Comment by John200410** [comment]
This is the oldest thing on my todolist, I have been procrastinating it for about a year. Will be in v1.2 for real this time.

**Comment by John200410** [comment]
Enemies have been added in the next update.
