### ISSUE TITLE
[FEATURE] InventoryCleaner for Armor Slots

### ISSUE THREAD

**Issue by Infisrael** [John200410/rusherhack-issues#1221]
**What feature would you like to be added.**
A InventoryCleaner for Armor Slots

**Is your feature request related to a problem? Please describe.**
I would like it for the unbreakable dupe that is on 2b2t

**Additional context**
None.

**Comment by HausemasterIssue** [comment]
Yes

**Comment by Justgamer101** [comment]
auto eject

**Comment by browsky300** [comment]
it is patched now

**Comment by Infisrael** [comment]
yes thank you browsky very cool
