### ISSUE TITLE
[BUG] Worlds are glitched

### ISSUE THREAD

**Issue by rusnuker** [John200410/rusherhack-issues#1224]
Singleplayer worlds are not loading properly. There are graphical glitches and missing chunks.

I don't use any other mods. Rusherhack version is rusherhack+ 1.2.3 cracked, Forge version 14.23.5.2859

Simple superflat worlds are generating as normal, but chunks with a village will also glitch.

Screenshot:
![image](https://user-images.githubusercontent.com/49472785/153712382-781ed19f-e8dc-4829-93b5-c6f1507baa34.png)

I also can stuck in missing textures.

**Comment by HausemasterIssue** [comment]
Pay for the client if you wish for the issue to be fixed.

**Comment by ZenovJB** [comment]
> Singleplayer worlds are not loading properly. There are graphical glitches and missing chunks.
> 
> I don't use any other mods. Rusherhack version is rusherhack+ 1.2.3 cracked, Forge version 14.23.5.2859
> 
> Simple superflat worlds are generating as normal, but chunks with a village will also glitch.
> 
> Screenshot:
> ![image](https://user-images.githubusercontent.com/49472785/153712382-781ed19f-e8dc-4829-93b5-c6f1507baa34.png)
> 
> 
> I also can stuck in missing textures.
> 

lel ty for the token lel free nitro lel

**Comment by John200410** [comment]
Piracy is illegal.
