### ISSUE TITLE
[FEATURE] AntiDisconnect

### ISSUE THREAD

**Issue by tycrek** [John200410/rusherhack-issues#123]
**What feature would you like to be added.**

Would require user to hold the Disconnect button for 3 seconds or so before disconnecting. Would prevent misclicks after changing video settings/controls/Forge mod settings.

**Additional context**

Requested by Oxygen169 on Discord

**Comment by John200410** [comment]
Thank you for the suggestion. I was thinking about just making it open an additional yes/no gui asking for your confirmation. What are your thoughts on this?

**Comment by tycrek** [comment]
I like that idea too, maybe an option to choose between both if that's possible

**Comment by ToxicAven** [comment]
Close #83 In favor of this

**Comment by John200410** [comment]
> Close #83 In favor of this

Thank you for pointing this out.

**Comment by John200410** [comment]
This has been added in the next update as a setting to AutoReconnect.

![image](https://user-images.githubusercontent.com/43681932/114295429-340b3b80-9a73-11eb-8558-3aab83e8e29a.png)
