### ISSUE TITLE
[FEATURE] PistonPush and PistonCrystal

### ISSUE THREAD

**Issue by 06d** [John200410/rusherhack-issues#1230]
Piston push is when you use the piston to push someone out of the hole
Piston crystal is pushing a crystal into a person's hole

Is very useful on clone servers when 2b spawn is dead

**Comment by ZenovJB** [comment]
HAHAHAHAH

**Comment by voidinqalt** [comment]
**06d: "**my friend zprestige is a bad coder and his pasted pistonpush does not work so I need john to add it**"**

**Comment by jennifer-uwu** [comment]
duplicate #271
