### ISSUE TITLE
[FEATURE] Position simple mode

### ISSUE THREAD

**Issue by Ozynt** [John200410/rusherhack-issues#1233]
**What feature would you like to be added.**
A simple mode for the position hud element. Shown below

**Is your feature request related to a problem? Please describe.**
I think it's way easier reading the coords displayed this way and it's not often needed to see the last decimals.

**Additional context**
Like this
![image](https://user-images.githubusercontent.com/58683893/154804534-8e837c16-ddbb-4eec-97f8-4c3b5fa68cb6.jpeg)

**Comment by John200410** [comment]
This has been added in the next update.
