### ISSUE TITLE
[FEATURE]Auto Rubberband Boatfly Disable

### ISSUE THREAD

**Issue by TheRedBlocker** [John200410/rusherhack-issues#124]
**What feature would you like to be added.**

It would count the number of times you have rubberbanded while boatflying and disable boatflying when you reach x amount of times. Obviously toggleable and would have a default stop point but would be able to be changed. Could also have a feature that would decide whether to just stop boatfly or stop boatfly and get you out of the boat.

**Is your feature request related to a problem? Please describe.**

When boatflying on 2b, after a certain amount of times rubberbanding you will disconnect.

**Comment by John200410** [comment]
Thank you for the suggestion but this does not seem like it will help with disconnects. Does disabling it manually prevent disconnects?

**Comment by TheRedBlocker** [comment]
Yes. When you start rubberbanding it is very likely you will dc, but if you stop boatfly and start it again you don't get dced. Sometimes you seem to need to get out and break the boat as well.

**Comment by John200410** [comment]
I will probably add a consecutivelagback setting that will dismount and remount the boat once you lagback a certain amount of times within a short time

**Comment by John200410** [comment]
ConsecutiveLagBack setting has been added to v1.1.2
