### ISSUE TITLE
[BUG] HUD position while fullscreen/not fullscreen

### ISSUE THREAD

**Issue by joeengo** [John200410/rusherhack-issues#1240]
**Describe the bug**
When I unfullscreen, and then go back into fullscreen all my HUD elements are positioned weirdly

**To Reproduce**
1. unfullscreen minecraft
2. full screen minecraft
3. should have messed up the hud elements positions

**Other mods**
List other forge mods you are using (if any):
kami blue
future
real time translation mod
optifine
baritone

**Expected behavior**
the hud elements should go back to where they came from when going back in fullscreen.

**Screenshots**
video: https://streamable.com/e5d1rg

**Additional context**
n/a

**Comment by nossravgni** [comment]
I have experienced the same issue

**Comment by John200410** [comment]
Disable the Hud Clamping setting.
