### ISSUE TITLE
[BUG] ElytraFly2b2tNew Game Crash

### ISSUE THREAD

**Issue by FuzzyRussian** [John200410/rusherhack-issues#1241]
If you disable the new elytra fly module while in the main menu it crashes your client. I sent the crash report via discord dms. 

It should be noted the module was doing the weird timer thing.

Yours truely,
-FuzzyRussian xoxo

loaded mods:
![image](https://user-images.githubusercontent.com/80669379/155451216-57a76c61-d824-4a5f-a11e-0aa8cbcfe81e.png)

**Comment by John200410** [comment]
fixed
