### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by Blur-coder69** [John200410/rusherhack-issues#1243]
**What feature would you like to be added.**
You can control c to copy your config and if your pasting a config you can use control v to paste that config into your module

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to do it manually since there's no module txt

**Comment by Justgamer101** [comment]
rusherhack folder

**Comment by John200410** [comment]
You can find the module profile config files at .minecraft/rusherhack/ModuleProfiles/ folder.
