### ISSUE TITLE
Using nametags will crash or affect other modules

### ISSUE THREAD

**Issue by moserkoter** [John200410/rusherhack-issues#1249]

**Comment by John200410** [comment]
Can you elaborate? Can you upload a crash log? How exactly does it affect other modules?

**Comment by ZenovJB** [comment]
wise

**Comment by moserkoter** [comment]
> 能详细说说吗？你能上传一份事故日志吗？具体是如何影响其他模块的？

I can tell you in a little detail: when I open the GUI and click on nametags, 1 GUI interface will run around 2 If you turn on ESP, the framework of the task will be separated from the player itself. 3 I want to say again that the system will not crash, but it will be proposed to the server that I attacked the server

**Comment by John200410** [comment]
Can you please upload a video showcasing the issue?

**Comment by moserkoter** [comment]
> 你能上传一段展示这个问题的视频吗？

> Can you please upload a video showcasing the issue?

I tried to modify it myself and it has been solved

**Comment by moserkoter** [comment]
I tried to modify it myself and it has been solved

**Comment by moserkoter** [comment]
> Can you please upload a video showcasing the issue?

I tried to modify it myself and it has been solved
