### ISSUE TITLE
[FEATURE]No Render Additions

### ISSUE THREAD

**Issue by TheRedBlocker** [John200410/rusherhack-issues#125]
**What feature would you like to be added.**
A detailed explanation of what this feature should be.
This would add additional options to no render.
- an option to not see tile entities (prevents etable lag)
- an option to not see certain blocks. Would work like search blocks, but instead of highlighting/making a tracer to them it would not render them for you
**Is your feature request related to a problem? Please describe.**
Certain things cause fps lag, and that I would rather not have. 
**Additional context**

**Comment by mestupid** [comment]
NoFallingBlocks would also be useful, could be an option under NoRender

**Comment by TheRedBlocker** [comment]
Also an addition to this would be any entities.

**Comment by John200410** [comment]
Thank you for the suggestions. I will be able to add a limit to tileentities and the fallingblock setting to norender by v1.1.2, however the other settings will have to wait for v1.2

**Comment by ToxicAven** [comment]
#51 Similar, idk if it should be closed in favor tho

**Comment by John200410** [comment]
TileEntities limit was added a while ago
