### ISSUE TITLE
[BUG] alternatewhen  in autototem doesnt work

### ISSUE THREAD

**Issue by SoggyBacco** [John200410/rusherhack-issues#1250]
alternatewhen doesnt have any effect on your offhand switching when it should make autototem only swap to crystals when ca is on

i remember this working with the old ca so it was probably never updated to work with the rewritten ca

**Comment by John200410** [comment]
What are your AutoTotem settings?

**Comment by SoggyBacco** [comment]
mode: health
hp: 16
absorbtioncheck
alternateitem: crystal
alternatewhen/requiresautocrystal
falldist: 20
delay:0
inv/hotbarprio/eating

it still holds crystals when ca is off

**Comment by John200410** [comment]
Can you please record a video?

**Comment by SoggyBacco** [comment]
first half is what alternatewhen should do based on my cfg, second half is what it actually does

https://user-images.githubusercontent.com/76087383/157411642-9b6f2a2f-2492-4411-95b0-5ab2bdec6088.mp4

**Comment by FluorideHistorian** [comment]
duplicate of #1048
