### ISSUE TITLE
How to use findstronghold?

### ISSUE THREAD

**Issue by moserkoter** [John200410/rusherhack-issues#1254]

**Comment by Mathrandom7910** [comment]
![image](https://user-images.githubusercontent.com/79098706/157880071-ebbc7740-ecac-4c2c-967f-ff93841da7ec.png)
smh, literally run the command

**Comment by moserkoter** [comment]
> ![image](https://user-images.githubusercontent.com/79098706/157880203-d13a7306-9e86-4aaa-abdb-e56d8f7f26f4.png)
> 
> smh, literally run the command

How does it work?

**Comment by ZenovJB** [comment]
> > ![image](https://user-images.githubusercontent.com/79098706/157880203-d13a7306-9e86-4aaa-abdb-e56d8f7f26f4.png)
> > 
> > smh, literally run the command
> 
> How does it work?

nice bait

**Comment by John200410** [comment]
This is not the place to ask for support.
