### ISSUE TITLE
Movement recordable Fakeplayer.

### ISSUE THREAD

**Issue by nossravgni** [John200410/rusherhack-issues#1256]
**What feature would you like to be added.**
A feature on Fakeplayer to be able to record your own moment and then make the fakeplayer replicate it.

**Comment by Vaimok** [comment]
useless bloat.

**Comment by HausemasterIssue** [comment]
Bloat. Sounds like you don't have any friends to test your autocrystal on 💀

**Comment by jennifer-uwu** [comment]
bloat
