### ISSUE TITLE
PopChams

### ISSUE THREAD

**Issue by nossravgni** [John200410/rusherhack-issues#1257]
**What feature would you like to be added.**
PopCHams. Puts a box render on players when they pop a totem

**Additional context**
![PopChams](https://user-images.githubusercontent.com/84351714/158065987-ce255ba5-360f-4fb0-b5dd-a52cafcaf8a4.png)

**Comment by SoggyBacco** [comment]
ugly render and useless bloat, use popcounter

**Comment by TwoThreeTwo** [comment]
Just is not going to add it, he explained many times that he does not want to make this.

**Comment by browsky300** [comment]
John has said before that he will not make this.

**Comment by system69-e** [comment]
🤨

**Comment by jennifer-uwu** [comment]
Hello,
This feature is already implemented in the vanilla game. When a player pops a totem, multiple green particle effects are spawned in an emitter in the players hitbox. You can use these particles to reliably determine when and where a player has popped a totem, therefore adding this feature would be redundant.
Hope this helps -Jenni.
