### ISSUE TITLE
[FEATURE] Free look option in Baritone

### ISSUE THREAD

**Issue by Badinek** [John200410/rusherhack-issues#126]
**What feature would you like to be added.**
Adds Free look option to Baritone

-This would make you be able to look freely while pathing with baritone 

**Is your feature request related to a problem? Please describe.**
It looks weird when the camera just instantly turns where baritone is going.. I used to use Future client before and it had this option under Baritone, so i would like to have it here too (isnt really necessary tho)

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
This has been finished and will be in v1.1.2
