### ISSUE TITLE
[BUG] Hwid bug when after upgrading ram

### ISSUE THREAD

**Issue by DevNoobus** [John200410/rusherhack-issues#1261]
[BUG] Hwid bug when after upgrading ram

**Comment by DevNoobus** [comment]
my Username ingame is NoobusEvolution

**Comment by WarriorCrystal** [comment]
This isn't a bug you just need to ask for a hwid reset at the user page or discord

**Comment by DevNoobus** [comment]
ok

**Comment by DevNoobus** [comment]
could please send link of discord server

**Comment by TwoThreeTwo** [comment]
https://discord.gg/uuAFRGaW

**Comment by TwoThreeTwo** [comment]
Make sure to verify your account in the installer first, then go to #hi and do -fixranks

**Comment by John200410** [comment]
> could please send link of discord server

You can find a link in the installer.
