### ISSUE TITLE
[FEATURE] boat fix yaw

### ISSUE THREAD

**Issue by staelthy** [John200410/rusherhack-issues#1262]
**What feature would you like to be added.**
On impact, your yaw is connected to your boat yaw, its working on boatfly for rusher, but not on entity speed (normal boat usage).
So i suggest a boat yaw fix for normal boat usage like it is on the boatfly module.

**Is your feature request related to a problem? Please describe.**
Its very slow when turning.
**Additional context**
Would enjoy the fix.

**Comment by Ozynt** [comment]
This has been added in the next update.
