### ISSUE TITLE
[FEATURE] Remove AutoSpleef

### ISSUE THREAD

**Issue by TwoThreeTwo** [John200410/rusherhack-issues#1263]
**What feature would you like to be removed.**
Well it's quite obvious, it just mines snow blocks under players feet.
**Is your feature request related to a problem? Please describe.**
Reason? Useless and I don't think anyone even uses it lol.

**Comment by John200410** [comment]
it was made for the spleef arena on 2b2tpvp

I will probably remove it once I create a plugin system
