### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by maximnota** [John200410/rusherhack-issues#1265]
**Describe the bug**
The bug is that i cant see where the client section is

**To Reproduce**
??

**Other mods**
baritone
**Expected behavior**
i should see the client section
**Screenshots**

**Additional context**

**Comment by Ozynt** [comment]
Have you tried *clickgui scale 0.8 ?

**Comment by maximnota** [comment]
no thank you for help

**Comment by Ozynt** [comment]
In the future please ask for support in the discord server or send an email.
