### ISSUE TITLE
[FEATURE] CRYSTAL ESP AND HIGHWAY BUILDER

### ISSUE THREAD

**Issue by 25st** [John200410/rusherhack-issues#1266]
![image](https://user-images.githubusercontent.com/101983425/159168635-accae2a7-14b5-49ad-a8bc-6cd619696d74.png)
"crystal esp like that you can add colours and etc and more" 
also for chat u can add emojis like 💀  and etc

For highway builder its kinda obiv but u can copy from lambda like these 
![image](https://user-images.githubusercontent.com/101983425/159168763-2832b854-7bb5-4478-a88a-8976de992645.png)

Dm ZORUダ#8260 for more ideas/info 
-25st

**Comment by jennifer-uwu** [comment]
Hello,
Crystal customization like you described is already present in the "Chams" module. As for highway building, you should instead find a better use of your time instead of spending $20 a month to place blocks while afk.
Hope this helps -Jenni.
