### ISSUE TITLE
[FEATURE] BreakESP smoother render

### ISSUE THREAD

**Issue by Doogie13** [John200410/rusherhack-issues#1267]
**What feature would you like to be added.**
Smoother render in BreakESP utilising the partial tick float in render events to make the animation calculate progress per frame, not per tick

**Is your feature request related to a problem? Please describe.**
BreakESP otherwise looks somewhat unpleasant

**Additional context**
![image](https://user-images.githubusercontent.com/62295632/159347772-5be1f9f3-8218-45ef-a9d1-6694c9668f5e.png)

**Comment by Doogie13** [comment]
This could also be applied to other renders, just the BreakESP was most obvious since it moves in a predictable way

**Comment by Noctorin** [comment]
Brilliant Doogie

**Comment by TwoThreeTwo** [comment]
*John punching the air rn*

**Comment by John200410** [comment]
Interpolation has been added in the next update: 

https://rusherhack.org/i/huj08ybeoc.mp4

**Comment by Doogie13** [comment]
based
