### ISSUE TITLE
[help] how df do you get better ping with anything please  im desperate 

### ISSUE THREAD

**Issue by ImagingBeingBad** [John200410/rusherhack-issues#1275]
[help] how df do you get better ping with anything please  im desperate 
[help] how df do you get better ping with anything please  im desperate

**Comment by TwoThreeTwo** [comment]
Don't post that stuff here, if you want  better ping, just use ping bypass. Search it up on github 🤡

**Comment by system69-e** [comment]
by becoming better

**Comment by John200410** [comment]
Move closer to the server you want to play. Or play on a server closer to you.

Please do not open issues like this.
