### ISSUE TITLE
[idk] how to insert configs 

### ISSUE THREAD

**Issue by ImagingBeingBad** [John200410/rusherhack-issues#1276]
idk how to insert configs how do you insert these type of configs example

{
"name": "AutoCrystal",
"toggled": true,
"bind": "KEY_RETURN",
"visible": true,
"notify": true,
"break": "true",
"break:mode": "ALL",
"break:priority": "DAMAGE",
"break:range": "5.0",
"break:wallrange": "3.0",
"break:delay": "0",
"break:randomdelay": "0",
"break:minexistticks": "0",
"break:maxexistticks": "0",
"break:mindamage": "4",
"break:maxselfdmg": "9",
"break:raytrace": "false",
"break:inhibit": "true",
"break:antiweakness": "true",
"break:waitforrotate": "false",
"break:whileeating": "true",
"break:whilemining": "true",
"break:render": "true",
"break:render:color": "Rainbow:false,Color:2139096555",
"break:render:outline": "true",
"place": "true",
"place:range": "5.0",
"place:wallrange": "3.5",
"place:targetrange": "6.0",
"place:delay": "0",
"place:instant": "true",
"place:raytrace": "false",
"place:sync": "false",
"place:ignoreterrain": "false",
"place:faceplace": "8",
"place:1.13+": "false",
"place:waitforrotate": "false",
"place:whileeating": "true",
"place:whilemining": "true",
"place:render": "true",
"place:render:damage": "true",
"place:render:damage:scale": "0.62",
"place:render:color": "Rainbow:false,Color:2139096555",
"place:render:outline": "true",
"rotate": "false",
"rotate:breakspeed": "75.0",
"rotate:placespeed": "75.0",
"rotate:randomizespeed": "false",
"rotate:strict": "false",
"targeting:priority": "DAMAGE",
"targeting:prioritizeenemies": "true",
"targeting:range": "12.0",
"targeting:targetarmor": "true",
"targeting:friendprotect": "true",
"targeting:players": "true",
"targeting:hostiles": "false",
"targeting:passives": "false",
"targeting:neutrals": "false",
"targeting:mindamage": "4",
"targeting:maxselfdmg": "9",
"targeting:extrapolation": "2",
"targeting:render": "false",
"targeting:render:color": "Rainbow:false,Color:1073807104",
"targeting:render:outline": "true",
"targeting:targetarmor:durability%": "10",
"targeting:players:ignorecreative": "true",
"autoswitch": "OFF",
"stophp": "4"
},

**Comment by TwoThreeTwo** [comment]
Manually insert the config via in game gui, or if you have a brain, you can edit the actual file
(C:\Users\mommy\AppData\Roaming\.minecraft\rusherhack\ModuleProfiles

**Comment by John200410** [comment]
Stop opening support related issues. This is not the place to ask for support. Link your discord account in the installer and ask for support there.
