### ISSUE TITLE
[FEATURE] not showing gapple potion effects in the potion hud

### ISSUE THREAD

**Issue by 2147483647ms** [John200410/rusherhack-issues#1277]
exactly what it says in the name just not showing all of the gapple effects in the potion hud

**Comment by John200410** [comment]
Unable to reproduce:

![image](https://user-images.githubusercontent.com/43681932/162589381-3442e643-39fd-46a0-bfdf-19d63f20220f.png)

Can you record a video?

**Comment by 2147483647ms** [comment]
> Unable to reproduce:
> 
> ![image](https://user-images.githubusercontent.com/43681932/162589381-3442e643-39fd-46a0-bfdf-19d63f20220f.png)
> 
> Can you record a video?
sorry wasnt very clear in the feature request it works fine the module shows all potion effects i just think it would be a nice quality of life feature if there was an option to not show all of the gapple potion effects because it can sort of be assumed that you will have them nearly all of the time
