### ISSUE TITLE
[FEATURE]Add strict option for Jesus and mode for entity Jesus

### ISSUE THREAD

**Issue by 0popbob** [John200410/rusherhack-issues#128]
Add strict option for Jesus with this the jesus works on 2b i think 
And add entity jesus that works on 2b [Jesus that u can go with horses or donkeys]

**Comment by John200410** [comment]
Thank you for the suggestion

**Comment by John200410** [comment]
I have got it working on water. I just need to make it work on lava and test it while riding a horse.

**Comment by John200410** [comment]
It now works with entities.
