### ISSUE TITLE
[BUG] game crashes when i toggle strafe module from the clickgui in servers list

### ISSUE THREAD

**Issue by GentlemanMC** [John200410/rusherhack-issues#1285]
**Describe the bug**
game crashes when i toggle strafe module from the clickgui in servers list

**To Reproduce**
1-goto servers list
2-press the gui bind to open the gui
3-toggle strafe off/on

**Other mods**
List other forge mods you are using (if any):
none

**Comment by TwoThreeTwo** [comment]
This has been fixed in the next update
