### ISSUE TITLE
[BUG] Antibot removing rusherhack fakeplayer

### ISSUE THREAD

**Issue by CrushedKingoros** [John200410/rusherhack-issues#1287]
**Describe the bug**
rusherhack antibot removing fakeplayer
**To Reproduce**
1. type *fakeplayer
2. turn on rusherhack antibot
3. done
**Other mods**
List other forge mods you are using (if any):
future
**Expected behavior**
rusherhack antibot should not remove fakeplayer
**Screenshots**

**Additional context**

**Comment by Ozynt** [comment]
A setting to ignore fakeplayers would maybe be a good solution.

**Comment by CrushedKingoros** [comment]
> e be a good solutio

i agree

**Comment by system69-e** [comment]
better solution: remove antibot

**Comment by HausemasterIssue** [comment]
I can't think of anyone who uses RusherMod on minigame servers. Still AntiBot is worth keeping.

**Comment by Vaimok** [comment]
wait WHAT antibiot removes bots, thats crazy. this NEEDS to be fixed ASAP!

**Comment by John200410** [comment]
AntiBot is being removed in the next update. If you have any legitimate use-case for it feel free to share it here.

**Comment by HausemasterIssue** [comment]
3 Days of silence Lol, I think you can close this issue now John.
