### ISSUE TITLE
[FEATURE] Cleaner custom font for LogoutSpots

### ISSUE THREAD

**Issue by Chiyun2b** [John200410/rusherhack-issues#129]
LogoutSpots is a good module but the plain minecraft font is janky and not very clean, looks too big from a distance as well, if you were to put in a cleaner font it'd look nicer to use. 👍

**Comment by John200410** [comment]
Thank you for the suggestion. I will add a CustomFont setting to LogoutSpots

**Comment by John200410** [comment]
A CustomFont setting has been added to LogoutSpots in v1.1.2
