### ISSUE TITLE
[FEATURE] make true durability better 

### ISSUE THREAD

**Issue by CR11MP** [John200410/rusherhack-issues#1297]
**What feature would you like to be added.**
i would also like it to have durability for items that shouldn't have damage values
for stuff like untextured snowballs
  

**Is your feature request related to a problem? Please describe.**
no 

**Additional context**
![2022-05-07_01 39 52](https://user-images.githubusercontent.com/103106288/167144891-b7c7394e-ea5c-4635-bccc-202836a0b6bf.png)

screen shots of snowballs with damage values

**Comment by Kiriyaga7615** [comment]
why

**Comment by Ozynt** [comment]
How would this be useful?

**Comment by Smokeybear12** [comment]
Snowballs don't have durability lol

**Comment by Ozynt** [comment]
Yeah, so it makes this so useless.

**Comment by TwoThreeTwo** [comment]
someone close this
