### ISSUE TITLE
[FEATURE] PvpInfo Option 32kDetect

### ISSUE THREAD

**Issue by notperry1** [John200410/rusherhack-issues#13]
**What feature would you like to be added.**
Basically if someone is holding a item in your render distance and if it has 32k enchantments like 32k sharpness it will give a notification that hes holding a 32k and once he swaps slots and its no longer in his hand it will say hes no longer holding a 32k cause i have elementars.com client and i literally only use it for that one module 32kdetect so i thought it'd be a good idea to make this suggestion to add into rusherhack so i don't need to have a extra client for just 1 module.

**Is your feature request related to a problem? Please describe.**
No its not a problem.

**Additional context**
Not that i can think of.

**Comment by John200410** [comment]
This has been added in v1.1.2
