### ISSUE TITLE
[FEATURE] Highway Phase

### ISSUE THREAD

**Issue by rockeZZergon** [John200410/rusherhack-issues#130]
When i was phasing through highways, i found a little feature:
If you don't getting damage, you will get kicked from 2b2t.
But if all player's hitbox inside blocks, that he phasing, and player getting damage, he will not get kicked. I tested it on Y 124-125. But if not all hitbox inside block, and some part of it in air, you will get kicked soon, but you will not get damage.
So my suggestion is to make a similar thing to antikick (you getting tp vertically every tick), but for highway.
That will allow player almost don't get damage and don't get kicked

**Comment by Azurilex** [comment]
can anyone else read what this guy is tryna say lol

**Comment by John200410** [comment]
I don't understand what you are asking for

**Comment by natan515** [comment]
I think that he mean that u will somehow teleport him up inside a block in a way u don't get damage and don't get a kick... Like in boat fly.

**Comment by rockeZZergon** [comment]
yeah

ср, 11 нояб. 2020 г. в 14:21, natan <notifications@github.com>:

**Comment by John200410** [comment]
I don't think it's possible to not take damage while phasing.
