### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by OffeeX** [John200410/rusherhack-issues#1302]
Cannot generate chunk in single player due to skylight setting in NoRender

(yes, i use SinglePlayer for recording purposes)
![Screenshot_1](https://user-images.githubusercontent.com/64991049/168034900-b49c1b08-9ea7-4383-9c23-fe9b6dc64b21.png)

**Comment by HausemasterIssue** [comment]
Turn off the skylight setting, most servers have skylight lag patched.

**Comment by John200410** [comment]
Disable the All sub setting of Skylight.
