### ISSUE TITLE
[FEATURE] Potion Effect Icons

### ISSUE THREAD

**Issue by browsky300** [John200410/rusherhack-issues#1307]
**What feature would you like to be added.**
Option to add potion icons next to the name of the effect in the PotionEffects hud element (screenshot attached below)

**Is your feature request related to a problem? Please describe.**
no it's just something that looks cool

**Additional context**
Example of what it looks like in Pyro https://i.e-z.host/a903a987.png

**Comment by jennifer-uwu** [comment]
bloat

**Comment by HausemasterIssue** [comment]
I would argue not. The potion icons are a much better visual indicator rather than text, in fact just the icon and the time of the potion I think looks better than just text.

**Comment by FluorideHistorian** [comment]
i think it looks good but we will have to wait for john

**Comment by John200410** [comment]
This has been added in the next update.
