### ISSUE TITLE
[BUG] Rusher isn't compatible with with Pyro

### ISSUE THREAD

**Issue by ImKindaSus** [John200410/rusherhack-issues#1314]
**Describe the bug**
I can't start Rusherhack with Pyro 2.0
**To Reproduce**
1.Download and install Pyro and rusher
2.Try to start mc
**Other mods**
List other forge mods you are using (if any): Pyro client

**Expected behavior**
Minecraft starting
**Screenshots**

**Additional context**

**Comment by HausemasterIssue** [comment]
They said it would never happen. They said it was impossible.

**Comment by browsky300** [comment]
This issue is fixed in the next update.

**Comment by TwoThreeTwo** [comment]
John is hot 😩
