### ISSUE TITLE
[BUG] ESP + Nametag in complete wrong location

### ISSUE THREAD

**Issue by javanulled** [John200410/rusherhack-issues#1315]
**Describe the bug**
Nametag in complete wrong location

**To Reproduce**
enter freecam 
go out
doesnt fix itself till you reload game even then sometimes it will just not work

**Other mods**
List other forge mods you are using (if any):
none

**Expected behavior**
esp to not be in the wrong spot of my screen

**Screenshots**

**Additional context**
no
love you john
best dev

**Comment by browsky300** [comment]
Could you send a video or screenshot of it? Also, resetting your optifine settings might help.

**Comment by John200410** [comment]
Unable to reproduce
