### ISSUE TITLE
Ambiance [FEATURE]

### ISSUE THREAD

**Issue by Phantom568** [John200410/rusherhack-issues#1320]
**What feature would you like to be added.**
Ambiance

**Is your feature request related to a problem? Please describe.**
What this does is it will change the color of the game itself kind of like putting a lens on the game.
The reason why adding this would be nice is because by changing the color of the game without having to use a texture pack would be very neat and an overall improvement to how people look at their game.

**Additional context**
![image](https://user-images.githubusercontent.com/74129888/176986056-0fccd0a5-d0cf-4fc1-b448-9befe27a8a13.png)
https://cdn.discordapp.com/attachments/813750678060269648/992310298440646726/IMG_2534.png

Above is with ambiance and without is below 

https://cdn.discordapp.com/attachments/813750678060269648/992310299220783124/IMG_2535.png

**Comment by John200410** [comment]
This has been added in the next update under the Environment module.
