### ISSUE TITLE
[BUG] sound issuenb

### ISSUE THREAD

**Issue by gussysus** [John200410/rusherhack-issues#1332]
everytime I load rusherhack and go to a server or click a button there's no sound and my sound setting are in 100% all of them except for music when i go to a server and fly or mine a block no sounds so fix this its goofy.

**Comment by GentlemanMC** [comment]
delete startup sound file or do *reloadsounds
or both

**Comment by gussysus** [comment]
> delete startup sound file or do *reloadsounds or both

does not work i did both and mine a block and no sound and I'm sure my sound setting is at 100%

**Comment by Ozynt** [comment]
This is probarly not a bug if you would like further support link your discord account in the installer and ask for support there.

**Comment by John200410** [comment]
Highly doubt this is related to rusherhack. Contact support with your game log.
