### ISSUE TITLE
[BUG] Freecam + AntiAFK moving Freecam's Cam instead of players

### ISSUE THREAD

**Issue by synnkfps** [John200410/rusherhack-issues#1335]
**Describe the bug**
Instead of the AntiAFK module move the player, it moves the Freecam camera 

**To Reproduce**
Enable Freecam (im using old), enable AntiAFK (move), activate Freecam, it will move Freecam camera instead of the player

**Other mods**
List other forge mods you are using (if any): OptiFine

**Expected behavior**
Move the player instead of the Freecam Camera

**Comment by John200410** [comment]
Use Freecam mode New. That is why it was created.

**Comment by synnkfps** [comment]
But I use the old one because with it I am able to interact with blocks through the walls

**Comment by John200410** [comment]
It's not possible for this to work with old mode. You must use new mode.

You should be able to interact with blocks in new mode just fine.
