### ISSUE TITLE
[BUG] FeatureList sliding animation doesn't play if element is left-aligned

### ISSUE THREAD

**Issue by hashalite** [John200410/rusherhack-issues#1340]
**Describe the bug**
If the FeatureList element is on the left side of the screen, the sliding animation doesn't play.

**To Reproduce**
1. Put FeatureList on left side of screen
2. Enable animations in FeatureList
3. Toggle a module

**Other mods**
none

**Expected behavior**
Sliding animation plays on both sides of the screen

**Comment by John200410** [comment]
This has been fixed in the next update.
