### ISSUE TITLE
[BUG] FeatureList shifting to the right when not snapped

### ISSUE THREAD

**Issue by hashalite** [John200410/rusherhack-issues#1341]
**Describe the bug**
If the FeatureList is on the right side of the screen and not snapped to anything, enabling a module with a long name will cause the whole element to shift to the right. This can cause it to move partially off-screen if it's close to the edge.

**To Reproduce**
1. Move FeatureList element to the right side of the screen and ensure it isn't snapped to anything
2. Enable a module with a short name (ex. Aura)
3. Enable a module with a longer name (ex. ElytraFly)

**Other mods**
none

**Expected behavior**
FeatureList should stay in the same place

**Comment by John200410** [comment]
This has been fixed in the next update.
