### ISSUE TITLE
[visual update]

### ISSUE THREAD

**Issue by Vai0km** [John200410/rusherhack-issues#1346]
completely rework most if not all visuals. Instead of waiting for future or other anarchy mod to do it first rh should ditch the 2016 visuals style and update visuals to match what 1.8 mods are doing today. Not only should all bix esps and other outdated stuff get updated to modern standars rh should also innovate new visuals effects for combat mods like ca or ka. There is lots of room to make the game especially anarchy aspects of it to not only have simple visuals but also look cool and enjoyable. Most importantly visuals update would make the mod better for all rh users unlike most recent additions like stashsorter and autotrader which are only used by handful of people.

**Comment by TwoThreeTwo** [comment]
Do you think you can provide some images of what you mean? I think if john doesn't read this in a couple days/weeks then he might not know what you mean by this. Unless you're talking about the stuff like ozynt posted in #1342

**Comment by HausemasterIssue** [comment]
If you want something pretty, cool and enjoyable to look at, maybe you should try a girlfriend instead.

**Comment by Mathrandom7910** [comment]
I quite like rh's simplistic visuals. If this is added it should be toggleable between new and old.

**Comment by Bjottt** [comment]
homo
