### ISSUE TITLE
[BUG] Weird scrolling

### ISSUE THREAD

**Issue by ElectroYModz** [John200410/rusherhack-issues#135]
**Describe the bug**
when you setup categories above each others when you scroll down and up they get above each others

**To Reproduce**
You Put Categories Above Each Other And Scroll

**Other mods**
baritone-api-forge-1.2.13.jar
Schematica-1.12.2-1.8.0.169-universal.jar
Autodupe.jar

**Expected behavior**
scroll the entire screen

**Screenshots**
https://hausemaster.is-a.fail/KPlugh.png
https://hausemaster.is-a.fail/OtKP4l.png

**Comment by John200410** [comment]
Proper per-panel scrolling is planned in v1.2

**Comment by John200410** [comment]
New scrolling has been made.

https://www.youtube.com/watch?v=S_OBFgH5ngc
