### ISSUE TITLE
[BUG]  AutoCraft Doesnt work for rockets

### ISSUE THREAD

**Issue by EBSmash** [John200410/rusherhack-issues#1351]
**Describe the bug**
When Using ExtraCraft's "Autocraft" Feature I am unable to craft Firework Rockets.

**To Reproduce**

Enable "ExtraCraft" with the Autocraft setting on true

Get the required materials for fireworks

open a crafting table

doesn't craft rockets

**Expected behavior**
Should craft

**Comment by gargamelius** [comment]
You need to set the recipe with the command "*recipe set fd3firework". Rusherhack is not able to read your mind and know what you want to craft.

**Comment by EBSmash** [comment]
Thank you.

i look forward to the day where mind reading will be implemented

**Comment by EBSmash** [comment]
This is not a valid recipe. I just tried it.

**Comment by gargamelius** [comment]
my bad the command is "*recipe set fd3fireworks" instead of "*recipe set fd3firework"

**Comment by EBSmash** [comment]
ooh plural
ty

**Comment by TwoThreeTwo** [comment]
gonna close it
