### ISSUE TITLE
[FEATURE] ping hud element fix for 2b2t

### ISSUE THREAD

**Issue by 1drw** [John200410/rusherhack-issues#1356]
**What feature would you like to be added.**
A detailed explanation of what this feature should be.
on 2b2t you can no longer see your ping by normal means, all nametags show 0ms but you can see your own ping on tab
make the ping hud element grab your ping from tab instead of how it usually does when ur on 2b
**Is your feature request related to a problem? Please describe.**
i cant see my ping without hitting tab
**Additional context**
this takes like 5 mins to implement lol

**Comment by TwoThreeTwo** [comment]
iirc Hause did something that broke it, you'd have to click tab to actually view it
