### ISSUE TITLE
[BUG] greeter delay not working

### ISSUE THREAD

**Issue by mrking039** [John200410/rusherhack-issues#136]
Any delay set on greeter does not work

**Other mods**
baritone api forge 1.2.13
fpsreducer 1.12.2 1.9
lunatriuscore 1.12.2 1.2.0.42
mapwriter 1.12.2 2.8.2
schematica 1.12.2 1.8.0.168
wdlforge 4.0.1.7 snapshot
future 2.9

**Comment by John200410** [comment]
Thank you for the report

**Comment by John200410** [comment]
This has been fixed in the next update.
