### ISSUE TITLE
Config cloud save

### ISSUE THREAD

**Issue by aledlb8** [John200410/rusherhack-issues#1363]
**What feature would you like to be added.**
A config cloud save to share/get configs faster and easy

**Is your feature request related to a problem? Please describe.**
Yes, my computer got a factory reset and i lost all my config 😭😭😭

**Additional context**
In the module profiles should be a option saying "cloud configs" and show all the available cloud configs, aswell as private configs, and a search bar to get configs faster

**Comment by TwoThreeTwo** [comment]
duplicate issue of #189
