### ISSUE TITLE
[FEATURE] Lists in the hud extending the module list up when on the bottom of the screen.

### ISSUE THREAD

**Issue by VoidBite1** [John200410/rusherhack-issues#1373]
**What feature would you like to be added.**
When you have a list on the bottom side part of the screen, things like the BindList and ModuleList, when you enable/add another thing to the list, it adds it and the list extends down, going ofscreen, even though you have it on the bottom part of the screen, it even gets properly sorted the other way around, it just doesn't extend the list the correct way.

**Is your feature request related to a problem? Please describe.**
Yea, it goes ofscreen.

**Additional context**
nope

**Comment by TwoThreeTwo** [comment]
HUD -> Clamping

This fixes the issue where it goes off screen and instead lags it back to the point where it stays at the point where it is visible and whenever a new bind is added will bring the old binds upwards and then bring to the same pos as the old one.
