### ISSUE TITLE
Elytra Replace

### ISSUE THREAD

**Issue by TheSpireXD** [John200410/rusherhack-issues#1381]
for me this would be an amazing module, when activated much like burrow it would immediately turn off and replace your chestplate with and elytra if you were wearing an elytra and replace your elytra with a chestplate if you were wearing elytra

its annoying when youre getting crystaled and you want to fly away

**Comment by VoidBite1** [comment]
You said something wrong, its "replace your chestplate with and elytra if you were wearing an chestplate"

**Comment by browsky300** [comment]
you can do this with autoarmor and making a macro for the command "autoarmor elytrapriority"
