### ISSUE TITLE
[FEATURE] Emojis inside of in game chat

### ISSUE THREAD

**Issue by CozyMeli-gitv2** [John200410/rusherhack-issues#1386]
**What feature would you like to be added.**
A feature that allows you to use emojis inside of game chat. Such as, if you want to type a skull emoji when someone in chat says something stupid, you can just send ":skull:" in chat, and once it is typed out, the module would change it to the skull emoji image, and anyone else with the module on would see that too.

Having a folder of all the latest emojis to use would be nice, and would be a great feature.

Other clients have this, but if rusher had it to, it would be nice. Other clients also don't have all the emojis, and honestly it adds potential to do it right. Just grab a folder full of the latest emojis for the module to reference, and a happy day. 

**Is your feature request related to a problem? Please describe.**
Nope!

**Additional context**
None really.

**Comment by CozyMeli-gitv2** [comment]
Github makes emoji names to an emoji, but the skull emoji that you see was meant to say ": skull :", just without the spaces.

**Comment by ozyntmc** [comment]
no thanks

**Comment by CozyMeli-gitv2** [comment]
Why not lol, it would be a cool module to have

**Comment by ozyntmc** [comment]
It would not be cool to add bloat. When plugins will be implemented a plugin for this could be made. Use this for now https://github.com/2b2t-Utilities/emoji-api

**Comment by CozyMeli-gitv2** [comment]
Fair enough.

**Comment by VoidBite1** [comment]
> It would not be cool to add bloat. When plugins will be implemented a plugin for this could be made. Use this for now https://github.com/2b2t-Utilities/emoji-api

It isn't really bloat, like its not the most usefull, but it isn't bloat.

**Comment by CozyMeli-gitv2** [comment]
I mean after all we have animations on extra chat. Like if an addition to the extra chat module is bloat, why do we have things like animations available? I just would think it is such a small potential addition. Just my thought though.
