### ISSUE TITLE
[FEATURE] FIX ESP DOUBLE CHESTS

### ISSUE THREAD

**Issue by Santipro64** [John200410/rusherhack-issues#1395]
**What feature would you like to be added.**
I would like that dub chests don't have that line between the two chesst when having ESP enabled because it is very annoying.

**Is your feature request related to a problem? Please describe.**
It's frustating that line between the dub chest.

**Additional context**
This is how it looks
![image](https://user-images.githubusercontent.com/97467716/201777973-a2a7930b-ee3b-4b09-82aa-5fa96104b9fc.png)

This is how i would like it looked.
![image](https://user-images.githubusercontent.com/97467716/201778052-72f56f1f-b38c-44a2-87de-930548808494.png)

**Comment by Santipro64** [comment]
This
![image](https://user-images.githubusercontent.com/97467716/201778148-576a6e5c-ae2d-4d2b-a9f6-b6ba1b520177.png)

To This
![image](https://user-images.githubusercontent.com/97467716/201778188-c542e10a-9fde-46ef-af4d-a964a6eb002c.png)

**Comment by John200410** [comment]
Use ESP mode Shader.
