### ISSUE TITLE
command with the rusherbot or bot command in the #bot-commands to check your code usages

### ISSUE THREAD

**Issue by HopityHop321** [John200410/rusherhack-issues#1397]
**What feature would you like to be added.**
a *codeusage command in either rusherbot dms or the #bot-commands channel so we don't have to dm john or obey juan cannoli

**Is your feature request related to a problem? Please describe.**
N/A [...]

**Additional context**
N/A.

**Comment by browsky300** [comment]
this can't be done due to how the code system works
