### ISSUE TITLE
[BUG] Elytrafly causes desyncs 

### ISSUE THREAD

**Issue by GentlemanMC** [John200410/rusherhack-issues#1398]
**Describe the bug**
the elytrafly module gets me to desync and get kicked .

**To Reproduce**
1-set elytafly mode to control
2-set elyrafly -> vertical -> aim
3-get to fly on the air
4-press space
5-it will go down and cause you to desync

**Other mods**
List other forge mods you are using (if any):
optifine

**Expected behavior**
dont desync lol

**Screenshots**
[Here is a video of it happening](https://streamable.com/768fu4)

**Additional context**
i disabled every other module and tried every combination of settings on the elytrafly module it still causes me to desync no matter what my config is

also btw some other users have that issue 
even when elytrafly -> vertical is set to jump (Jaydn)

**Comment by GentlemanMC** [comment]
Bump 😭

**Comment by John200410** [comment]
You aren't supposed to hold space when using aim vertical mode.
