### ISSUE TITLE
[FEATURE] auto chunk reload in boatfly

### ISSUE THREAD

**Issue by Badinek** [John200410/rusherhack-issues#140]
**What feature would you like to be added.**
something like auto chunk reload under boatfly - reloads chunks with F3 + A every (x) seconds 

**Is your feature request related to a problem? Please describe.**
chunks sometimes dont appear in boatfly and that feels kinda weird, it can be fixed by reloading them tho, so i got this idea

it always looks weird when you fly in invisible chunk and i dont wanna press F3 + A every 10 seconds xd

**Comment by John200410** [comment]
I do not think this is necessary. You can probably speed up the chunk loading by using Optifine and tweaking the settings.
