### ISSUE TITLE
[BUG] AntiDisconnect bug

### ISSUE THREAD

**Issue by GentlemanMC** [John200410/rusherhack-issues#1407]
**Describe the bug**
game crashes when i press the "quit game" button in the mainmenu

**To Reproduce**
enable AntiDisconnect module
enable the server quit setting
press "quit game" button in the mainmenu

**Expected behavior**
to show the "are you sure you want to close the game" notification instead of the "are you sure you want to disconnect" and not crashing

**Screenshots**

https://user-images.githubusercontent.com/76640636/209963846-ac92d9f4-6364-4d0e-9b6e-33402f43edf8.mp4

**Comment by John200410** [comment]
Fixed in the next update
