### ISSUE TITLE
[FEATURE] nhack GUI look and background particle system

### ISSUE THREAD

**Issue by L-Nadav** [John200410/rusherhack-issues#141]
**What feature would you like to be added.**
I really did like the old GUI and much prefer on the new one, perhaps just add an option to do this in the settings? I also really liked the old particle background like in b11, I understand why they were removed but adding them back would be very nice!

**Additional context**
I know a couple people who would like this!

**Comment by John200410** [comment]
I plan to add particles in v1.2. I'm not too sure about bringing back the nhack gui however.

**Comment by John200410** [comment]
Particles were added, forgot to mention.

**Comment by omegabr99** [comment]
john pls add le nhack gui back plz

**Comment by jumboman32** [comment]
Custom GUI themes are on the way 🐢
