### ISSUE TITLE
[BUG] Aura doesnt attack players while ur in boat

### ISSUE THREAD

**Issue by Badinek** [John200410/rusherhack-issues#142]
**Describe the bug**
aura doesnt hit players at all while ur in boat

**To Reproduce**
get in boat go near player and enable aura, nothing happens

**Other mods**
List other forge mods you are using (if any):
pyro, optifine, baritone

**Expected behavior**
i expect the aura to hit the player xddd

**Comment by John200410** [comment]
Thank you for the report

**Comment by John200410** [comment]
This has been fixed in v1.1.3
