### ISSUE TITLE
Add auto obsidian[FEATURE]

### ISSUE THREAD

**Issue by Natan515** [John200410/rusherhack-issues#145]
**What feature would you like to be added.**
I would like to add autobosidian so it will automatically mine obsidian and will be connect to baritone so when baritone is out of obsidian and u tell the autoobsidian to mine 2 stucks, it will mine 2 and keep working on baritone and when the inventory will have no more obsidian it will mine 2 stucks again, afk, look at kami blue for more info.

**Is your feature request related to a problem? Please describe.**
Yes, use rusher hack while being completly afk

**Additional context**
This could be a very nice additonal to the client.

**Comment by John200410** [comment]
I think I would rather have it look for any type of blocks if you are out of them and are required for the current baritone task. Will make this a setting under the Baritone module and will also need a better name.

**Comment by ToxicAven** [comment]
'EnderChestFarmer'

**Comment by natan515** [comment]
BlockFarmer
