### ISSUE TITLE
[FEATURE]Add Autopilot/baritone for boats 

### ISSUE THREAD

**Issue by 0popbob** [John200410/rusherhack-issues#147]
**What feature would you like to be added.**
Add autopilot is a option that u can go with baritone in boat on pyro, i think u need add this for users plus cuz is a strong hack for movement and this is a option for antiafk too

![autopilotPyro](https://user-images.githubusercontent.com/70427500/99145669-57ea6280-2636-11eb-9725-f81e1fcbb84f.png)
Like that

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by ToxicAven** [comment]
Semi replica of #48

**Comment by John200410** [comment]
Closing this for now.
