### ISSUE TITLE
Another pasanger in boat fly properly work[FEATURE]

### ISSUE THREAD

**Issue by natan515** [John200410/rusherhack-issues#148]
**What feature would you like to be added.**
Won't be lagy when u take another guy with u in boat fly when his boat fly is off or on idk.

**Is your feature request related to a problem? Please describe.**
Ye, u get buggy and disconnect when u have another guy in ur boat fly.

**Additional context**
Can be nice having another guy with u, easy and safer travel.

**Comment by John200410** [comment]
This is not possible to my knowledge.
