### ISSUE TITLE
[FEATURE]gap on sword

### ISSUE THREAD

**Issue by theoplegends** [John200410/rusherhack-issues#150]
**What feature would you like to be added.**
gap on sword option for autototem settings

**Is your feature request related to a problem? Please describe.**
im always frustrated when i gotta switch to a gap when swording someone in 2b2tpvp

**Additional context**
just make it hold a gap in offhand when ur hodling a sword in ur main hand

**Comment by John200410** [comment]
Thank you for the suggestion. I will add this as a setting to AutoTotem.

**Comment by jumboman32** [comment]
I think instead of like 'if holding sword then gap' it should be hold right click to put gap in offhand like future has bc i break crystals w my sword if i have weakness

**Comment by jumboman32** [comment]
Merging.
