### ISSUE TITLE
[BUG] Wither skeleton targetting

### ISSUE THREAD

**Issue by ctoons** [John200410/rusherhack-issues#157]
**Describe the bug**
There is no option for combat modules to attack Wither Skeletons

**To Reproduce**
 try hitting a wither skeleton with kill aura

**Other mods**
only rhack

**Screenshots**
https://www.youtube.com/watch?v=sfYdeVIWxqM&feature=youtu.be&ab_channel=puncy

**Comment by John200410** [comment]
Thank you for reporting this.

**Comment by John200410** [comment]
Fixed in v1.1.3
