### ISSUE TITLE
[FEATURE] swap delay under autotool

### ISSUE THREAD

**Issue by Badinek** [John200410/rusherhack-issues#158]
**What feature would you like to be added.**
Swap delay under autotool module- customizable delay between switching tools 

**Is your feature request related to a problem? Please describe.**
sometimes it swaps the item too fast and it doesnt let me break the block. means autotool doesnt work half the time

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
Can you record a video of it not working?

**Comment by John200410** [comment]
Cannot reproduce the problem. Closing issue
