### ISSUE TITLE
[FEATURE] Auto Boatfly toggle on disconnect

### ISSUE THREAD

**Issue by Quelcom1** [John200410/rusherhack-issues#159]
**What feature would you like to be added.**
On 2b2t, if you get disconnected while you have the module Boatfly enabled, upon relog you will be glitched and have to relog again. 

**Is your feature request related to a problem? Please describe.**
Problem is sometimes I get disconnected, and realise i forgot to toggle boatfly and have to requeue.

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
This has been added in v1.1.3
