### ISSUE TITLE
[FEATURE] HoleFiller improvements

### ISSUE THREAD

**Issue by KrispyBigPvp** [John200410/rusherhack-issues#16]
**What feature would you like to be added.**
A detailed explanation of what this feature should be. ight bet listen in, you know how your hole filler absolutely shits on ppl, well its fire and all but it should have an option to ignore players in a hole, players in range ect

**Is your feature request related to a problem? Please describe.**

**Additional context**

Banging your head against a wall for one hour burns 150 calories.

**Comment by John200410** [comment]
What do you mean by "ignore players in range", in range of what?

**Comment by KrispyBigPvp** [comment]
like let’s say if there’s 4 ppl in holes near you, you can set it so it will only hole fill the nearest player or wtv

**Comment by gcurtiss** [comment]
@John200410 Can we milestone this?

**Comment by jumboman32** [comment]
not relevant at this point
