### ISSUE TITLE
[FEATURE] lava mode under waterspeed

### ISSUE THREAD

**Issue by Badinek** [John200410/rusherhack-issues#160]
**What feature would you like to be added.**
A detailed explanation of what this feature should be.
Lava mode under waterspeed (would make water speed work on lava), possibly rename to liquidwalk or something like this. also "both" mode to work on both water and lava

**Is your feature request related to a problem? Please describe.**
today i wanted to kill a newfag but he was just running away with futures jesus bypass on lava, so i thought this would be cool

**Additional context**

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
This has been made and will appear in the next update.
