### ISSUE TITLE
[FEATURE] Rainbow Rendering On More Modules

### ISSUE THREAD

**Issue by Azurilex** [John200410/rusherhack-issues#161]
**What feature would you like to be added.**
Rainbow rendering feature on more modules. AutoCrystal and BlockOutline have a rainbow option for rendering, it'd be awesome if we could get the same for some of the following;

AutoTrap,
AutoSurround,
Scaffold,
BreakESP,
NewChunks,
etc.

There's probably a few more that I'm missing but you get the idea.

**Is your feature request related to a problem? Please describe.**
No.

**Additional context**
N/A

**Comment by John200410** [comment]
Thank you for the suggestion. However, I already plan to rewrite the color settings to automatically include a rainbow setting for every color setting.
