### ISSUE TITLE
[FEATURE]Add Void ESP PLS

### ISSUE THREAD

**Issue by 0popbob** [John200410/rusherhack-issues#165]
**What feature would you like to be added.**
Add void ESP for esp renders

**Comment by John200410** [comment]
Thank you for the suggestion, I will add this as a setting to HoleESP.

**Comment by John200410** [comment]
This has been made and will appear in v1.1.3
![image](https://user-images.githubusercontent.com/43681932/101231601-5252cc00-367a-11eb-8361-fd14883e5dd3.png)
