### ISSUE TITLE
[FEATURE] Welcome text  HUD and that symmetrical thing that normally on Visual studio

### ISSUE THREAD

**Issue by y4ndex1** [John200410/rusherhack-issues#166]
i want that welcome thing and other 10k people that bought the client. Also it will allign (sorry if spelled wrong i dont know english well) to make it the same and not mess some pixels. I could'nt explain it that well hope you understand and make it

**Comment by John200410** [comment]
What welcome thing?

**Comment by John200410** [comment]
Will re-open when more information is provided.
