### ISSUE TITLE
[FEATURE] lava avoid for boatfly

### ISSUE THREAD

**Issue by Badinek** [John200410/rusherhack-issues#167]
**What feature would you like to be added.**
makes you unable to fly into lava with boatfly 

**Is your feature request related to a problem? Please describe.**
sometimes when i fly on 2b spawn i accidentally bump into lavafall and the boat burns, so i was wondering if its possible to do something like this

**Comment by John200410** [comment]
Thank you for the suggestion

**Comment by ToxicAven** [comment]
Duplicate of #80

**Comment by Badinek** [comment]
> Duplicate of #80

who cares lol

**Comment by ToxicAven** [comment]
> > Duplicate of #80
> 
> who cares lol

To clean up Issues that are not important, because the issues are basically john's todo list

**Comment by John200410** [comment]
Closing in favor of #80
