### ISSUE TITLE
[FEATURE] PotionBait / PotionFake

### ISSUE THREAD

**Issue by Neroxy157** [John200410/rusherhack-issues#168]
While CrystalPVPing, some people usually jump in a hole right next to you and start SwordPVPing. Most of the time, if you drink a strength potion they slightly fallback and wait for your strength effect to expire which results in no damage and a valuable potion lost. If there was a feature called PotionBait that can mess with the packets and fake the potion drinking or make it longer than usual this could both scare them off and avoid losing a potion. It would be really useful if added.

**Comment by John200410** [comment]
You would have to be holding the potion either way so I do not think this is worth adding. 

> or make it longer than usual
this is not possible.
