### ISSUE TITLE
[BUG] Elytrafly stops working when freecamming.

### ISSUE THREAD

**Issue by gcurtiss** [John200410/rusherhack-issues#17]
**Describe the bug**
Elytrafly stops working when freecamming.

**To Reproduce**
1. Turn on ElytraFly and take off.
2. Turn on freecam.
3. Drop.

**Other mods**
Pyro, but repro'd without Pyro.

**Expected behavior**
Freecam around while suspended mid-air.

**Comment by John200410** [comment]
Fixed in v1.1
