### ISSUE TITLE
[FEATURE]Boatl fly bypass

### ISSUE THREAD

**Issue by natan515** [John200410/rusherhack-issues#170]
**What feature would you like to be added.**
I would like that boat fly bypass would be added, it is possible because it does work on the ground it just gets me back sometimes but still much faster than walking but what I'm rly asking is autopilot for ground level for easy travel.

**Is your feature request related to a problem? Please describe.**
Ye hause disabled boat fly but not completly.

**Additional context**
Could be very epic and much better than stupid pyro client lol

**Comment by ToxicAven** [comment]
People Have been looking for an ElytraFly bypass since They got patched, Unfortunately same goes for boatfly. It comes out when ever a dev figures out a way around it.

**Comment by John200410** [comment]
BoatFly bypass is not possible.
