### ISSUE TITLE
[FEATURE]Hotbar Replenish Additions

### ISSUE THREAD

**Issue by TheRedBlocker** [John200410/rusherhack-issues#174]
**What feature would you like to be added.**
The first thing I would like added is more options for items be replenished in your hotbar(rockets, gaps). + **ALL**

The second thing I would like is to be able to set a kit for it similar to regear module. 

**Is your feature request related to a problem? Please describe.**
Yes, I've noticed that sometimes xp will replace echests or crystals in my hotbar and this is very annoying while pvping.

**Comment by John200410** [comment]
Thank you for the suggestions

**Comment by ToxicAven** [comment]
Better version of #164

**Comment by John200410** [comment]
This has been added in the next update:
![image](https://user-images.githubusercontent.com/43681932/132106764-47aaa505-7c92-4faf-a793-99623f11ad06.png)
