### ISSUE TITLE
[BUG] Freecam Direction

### ISSUE THREAD

**Issue by ItsYesnik** [John200410/rusherhack-issues#175]
Hey,

First off, thanks for all the awesome work you do on this client! 

I did notice Freecam now updates the position of where the Freecam is, which is awesome. However, it does not update the direction. The direction is still that of the main account. I am unsure if this should be new feature or bug.

Thanks again!

**Comment by John200410** [comment]
Thank you for the report.

**Comment by John200410** [comment]
This has been fixed in v1.1.3
