### ISSUE TITLE
[BUG] Speed Config Save

### ISSUE THREAD

**Issue by HeXaNi** [John200410/rusherhack-issues#176]
**Describe the bug**
When restarting the game, the entire config for speed besides enabled or disabled is reset.
**To Reproduce**
Change some settings for speed
Restart game
**Other mods**
List other forge mods you are using (if any):
Optifine & Baritone
**Expected behavior**
Restarting the game would still keep my hotkey and settings for speed.
**Screenshots**

**Additional context**

**Comment by John200410** [comment]
I have found the cause of this. Working on a fix now.

**Comment by John200410** [comment]
This has been fixed and will be in a silent patch today.
