### ISSUE TITLE
[FEATURE] Old portal search. (Notifies you when there used to be a portal in a chunk)

### ISSUE THREAD

**Issue by ongoingotrich** [John200410/rusherhack-issues#177]
This would be a module that when used will send you notifications if a chunk you have loaded previously had a portal in it but no longer does. This would be useful as many players break there portals when they make a base or the stash. This is possible because a server packet is sent to the client on chunk load. I don’t remember the name of this packet but I know it exist. Add this it would be great

**Comment by y4ndex1** [comment]
very cool idea

**Comment by John200410** [comment]
I don't really think this will be worth adding.
