### ISSUE TITLE
OpenGL Error 1286 Invalid Framebuffer Operation

### ISSUE THREAD

**Issue by CaptainTheBeam** [John200410/rusherhack-issues#178]
GIves me this error about every 1 - 2 seconds in chat after I was turning some modules on and off.

Here is a screenshot

![Screenshot (633)](https://user-images.githubusercontent.com/44644425/100547001-6b9ae900-3232-11eb-9f8a-5800ab66ae7a.png)

**Comment by CaptainTheBeam** [comment]
After loading into the server it actually makes my entire screen black so i cant see anything

**Comment by John200410** [comment]
What modules were you turning on/off? Do you have fast render enabled in optifine?

**Comment by CaptainTheBeam** [comment]
Just render modules, like esp and tracers. And I dont think I have fast render enabled in optifine unless its a default setting.

**Comment by John200410** [comment]
Check if you have fast render enabled. Also it is definitely one of the render modules, try the process of elimination and see which one is causing it.

**Comment by John200410** [comment]
Can you check if it still happens when you turn off Storages? Also upload optionsof.txt in your Minecraft directory.
