### ISSUE TITLE
[FEATURE] Basefinder Semi-AFK Mode

### ISSUE THREAD

**Issue by HeXaNi** [John200410/rusherhack-issues#179]
**What feature would you like to be added.**
An option under basefinder that turns itself off when it comes across a potential base. (Might be resume function but as far as I can tell, that doesn't do anything.) Could be useful for secondary monitor operation but still not completely AFK. Something that would stop the searching if it comes across a random shulker that may contain items, but nothing big enough to warrant a coords save.

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by jumboman32** [comment]
Merged with #892
