### ISSUE TITLE
Texture Viewing While Chams [BUG] 

### ISSUE THREAD

**Issue by slol2** [John200410/rusherhack-issues#180]
While using chams (wireframe)  you cannot view any textures

john said problem with the client so probably don't

Chams over the player

**Comment by John200410** [comment]
Thank you for reporting this.

**Comment by John200410** [comment]
This has been fixed in the next update.

![image](https://user-images.githubusercontent.com/43681932/118741945-7582c980-b81d-11eb-8211-d327459e981d.png)
