### ISSUE TITLE
[FEATURE]Blacklist/No unbreakables for Auto Tunnel

### ISSUE THREAD

**Issue by tweefruitguy** [John200410/rusherhack-issues#181]
**What feature would you like to be added.**
Blacklist of blocks auto tunnel will try to break 

**Is your feature request related to a problem? Please describe.**
Auto tunnel stuck breaking portal blocks simple fix could be added to skip those and other blocks

**Comment by John200410** [comment]
v1.1.3 excludes bedrock from autotunnel.
