### ISSUE TITLE
Mode double for hole esp.

### ISSUE THREAD

**Issue by chaze4** [John200410/rusherhack-issues#184]
There is the usual hole esp, but there are holes consisting of two blocks, if you stand between them, then you cannot put a crystal there. This is implemented in the pyro client. And I would also like to see with square holes of four blocks. This mode will be very useful in cpvp.
![12](https://user-images.githubusercontent.com/75410639/100987264-b6d13680-3567-11eb-9d4c-83f684a29cb5.png) 
![13](https://user-images.githubusercontent.com/75410639/100987291-c0f33500-3567-11eb-894a-17dca893878a.png)
![14](https://user-images.githubusercontent.com/75410639/100987297-c3ee2580-3567-11eb-81aa-805182cc3ed6.png)

**Comment by y4ndex1** [comment]
👍

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
This has been added in the next update.

![image](https://user-images.githubusercontent.com/43681932/117853808-d5460700-b256-11eb-815f-0e561198df3f.png)
