### ISSUE TITLE
[FEATURE] tamed animals  in coordlogger (plus only)

### ISSUE THREAD

**Issue by Badinek** [John200410/rusherhack-issues#186]
**What feature would you like to be added.**
Option under CoordLogger module Tamed animals- logs coords when tamed animal teleports to its owner (for example dog)

**Is your feature request related to a problem? Please describe.**
once my friend found dog of one known player with a giant group base and the person was online, so he tried doing this but didnt get any coords (different client, i just dont want this to happen to me too and it could be useful)

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
This has been made and will appear in the next patch.
