### ISSUE TITLE
Auto Fish[BUG] 

### ISSUE THREAD

**Issue by UrbAnK1ller** [John200410/rusherhack-issues#187]
**Describe the bug**
A lot of the time the auto won't catch the fish and won't cast, plus doesn't work when you are not in the window.

**To Reproduce**
Steps to reproduce the behavior: just use auto fish

**Other mods**
List other forge mods you are using (if any): none

**Expected behavior**
recast after every use of the rod 
**Screenshots**
https://vimeo.com/user128599951/review/487688763/7e58b07475
**Additional context**

**Comment by John200410** [comment]
The link you have provided doesn't work, and I am unable to reproduce any of these issues. Could you possibly upload a video to youtube?

**Comment by UrbAnK1ller** [comment]
here's a new link. 
https://imgur.com/a/WS1kgTS

**Comment by John200410** [comment]
What server are you playing on? It is possible the server has it patched.
