### ISSUE TITLE
Break ESP Interpolation + Abort (Block Tweaks)[BUG] 

### ISSUE THREAD

**Issue by TheRedBlocker** [John200410/rusherhack-issues#188]
**Describe the bug**
When mining a block, with both break esp and abort on, if you stop mining half way through, and look at a different block, the break esp will show on the block you are looking at and not the block being broken. 

**To Reproduce**
Turn on Block Tweaks -> Abort and Break ESP (render - fill, fill - in, ignore - off). Mine a block and stop half way through. Look at a different block.

**Other mods**
List other forge mods you are using (if any):
Baritone, Schematica (not on)

**Expected behavior**
The ESP should remain on the block that is being broken

**Screenshots**
https://i.gyazo.com/06ba5c12aeeb30e51dacf51df5531772.png

**Additional context**

**Comment by John200410** [comment]
Thank you for reporting this.

**Comment by John200410** [comment]
This has been fixed and will appear in the next patch.
