### ISSUE TITLE
[BUG] Timestamps doesnt render properly with CustomFont chat

### ISSUE THREAD

**Issue by WarriorCrystal** [John200410/rusherhack-issues#191]
**Describe the bug**
when using custom font chat timestamps it renders as the punc color only

**To Reproduce**
change the timestamps color and then toggle customfont chat

**Other mods**
List other forge mods you are using (if any):
Inertia, Wurstplus

**Expected behavior**

**Screenshots**
this is how it renders
![imagen](https://user-images.githubusercontent.com/68621329/101296205-ef3f7180-3800-11eb-84c3-fd97c6f92f6b.png)
and these are my settings
![imagen](https://user-images.githubusercontent.com/68621329/101296232-17c76b80-3801-11eb-94e6-bf73317ceace.png)

**Additional context**

**Comment by jumboman32** [comment]
Was only able to reproduce this issue with the punctuation color being Dark Gray. Seems to be an issue with just that specific color.

**Comment by John200410** [comment]
This has been fixed and will appear in a silent update soon.
![image](https://user-images.githubusercontent.com/43681932/101568272-53e50280-39a0-11eb-9029-59a88014649d.png)
