### ISSUE TITLE
[BUG] 'Firework' ElytraFly doesn't work if looking down.

### ISSUE THREAD

**Issue by jumboman32** [John200410/rusherhack-issues#192]
**Describe the bug**
'Firework' ElytraFly kicking when looking down. The player freezes in the air and is rubberbanding until its kicked.

**To Reproduce**
Use the Firework Mode of Elytra Fly and steeply look down while flying. 

**Other mods**
None Relevant.

**Expected behavior**
I think that it should either lock the pitch at a certain value so it doesn't shoot you into the ground or if it would auto-disable or not be able to use fireworks while looking down.

**Screenshots**
clip of it happening at the end https://youtu.be/O9rFr6RAkUE

**Comment by ignelias** [comment]
same thing happened to me

**Comment by John200410** [comment]
What are your settings?

**Comment by jumboman32** [comment]
> What are your settings?

I was using your config, but I am not having the issue anymore. I would close but if @ignelias is still having problems, I'd keep it open.

**Comment by John200410** [comment]
If you use the Spoof setting then this issue shouldn't happen, @ignelias does this happen to you with spoof enabled?
