### ISSUE TITLE
[FEATURE] Server Time in HUD Editor

### ISSUE THREAD

**Issue by jumboman32** [John200410/rusherhack-issues#193]
**What feature would you like to be added.**
A server time module in the HUD Editor or just an option under the current time module.

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
This has been added in the next update.

**Comment by jumboman32** [comment]
I mean't like the time in Minecraft.

**Comment by John200410** [comment]
I know. I wrote it yesterday and it is coming in the next update.
