### ISSUE TITLE
[BUG] xray doing weird things to opened schematicas

### ISSUE THREAD

**Issue by Badinek** [John200410/rusherhack-issues#195]
**Describe the bug**
xray breaks loaded schematicas for some reason

**To Reproduce**
1. open some schematica using schematica mod
2. enable xray
3. after some while preview blocks in schematica start disappearing, after realoading chunks or just random

**Other mods**
schematica, the other mod u need for schematica, atom, rusherhack, kami atom

**Expected behavior**
i excepted the preview blocks to not disappear

**Screenshots**
posted on discord

**Comment by John200410** [comment]
Not sure if I can do anything about this.
