### ISSUE TITLE
Guiblur [FEATURE]

### ISSUE THREAD

**Issue by Cooliokid** [John200410/rusherhack-issues#196]
**What feature would you like to be added.**
A option either in Hud or its own module that blurs all guis not just the rusherhack gui option and it will blur all in game guis like inventory, chat, and menu

**Is your feature request related to a problem? Please describe.**
Particles is very similar to this as that show particles in all guis like

**Comment by John200410** [comment]
Currently, there is a standalone forge mod that does exactly this https://www.curseforge.com/minecraft/mc-mods/blur (has customizable gradient colors, etc). I'm not sure if I want to add this but if I ever change my mind then I will re-open this issue.
