### ISSUE TITLE
[FEATURE] Item & Hand view model

### ISSUE THREAD

**Issue by Papa-Quill** [John200410/rusherhack-issues#198]
**What feature would you like to be added.**
Item & Hand view model: Lets you change the position, size and rotation of items in your hand, as well as your hand.

**Is your feature request related to a problem? Please describe.**
Many clients have item view model but not many have hand view model and I'd like to see it and use it in Rusherhack.

**Additional context**
Please make sure to make the mainhand viewmodel and the offhand viewmodel seperate.

**Comment by jumboman32** [comment]
Also a switch option would be cool, so you have mainhand on the left.

**Comment by Cooliokid** [comment]
https://github.com/John200410/rusherhack-issues/issues/117

**Comment by John200410** [comment]
Duplicate of #117 sort of, I will close this in favor of that and will add a hand setting there.
