### ISSUE TITLE
[BUG] Fishing Rod Trajectory

### ISSUE THREAD

**Issue by jumboman32** [John200410/rusherhack-issues#199]
**Describe the bug**
The trajectory shown for a fishing rod is broken and it is about 2x the length from where the bobber lands.

**To Reproduce**
1. Turn on 'Trajectories'
2. Hold a Fishing Rod

**Comment by John200410** [comment]
Thank you for reporting this.

**Comment by John200410** [comment]
This has been fixed in v1.2

https://rusherhack.org/i/98hoh5qgfq.mp4
