### ISSUE TITLE
ESP Mainhand Texture Glitch

### ISSUE THREAD

**Issue by ToasterBathMaster** [John200410/rusherhack-issues#2]
**Describe the bug**
When I have ESP set on "outline" and enabled, the object in my mainhand will lose its texture and turn black.

**To Reproduce**
Turn on ESP, set it to Outline (on rhack). I am also using Pyro's itemviewmodel but enabling that doesn't fix the issue.

**Expected behavior**
The item in your mainhand should lose its color and turn black.

**Screenshots**
I don't have any.

**Comment by John200410** [comment]
What other render modules do you have enabled? (For other mods too)

**Comment by John200410** [comment]
This is the first time I'm hearing this report so I think this must be some sort of GL state management issue from another client.

**Comment by John200410** [comment]
Issue resolved on Discord
