### ISSUE TITLE
[FEATURE] RichPresence Improvements

### ISSUE THREAD

**Issue by ToxicAven** [John200410/rusherhack-issues#200]
**What feature would you like to be added.**
Add a few extra options to RichPresence, such as 2b Queue, Dimension, Health, Username, Hunger, Actively attacking, And Location.

**Comment by ToxicAven** [comment]
Semi-Replica of #82 , with more features.

**Comment by John200410** [comment]
I will keep both of these open. I intend on making the RichPresence fully customizable with placeholder you can use. However I don't think Location is a smart one to add.

**Comment by John200410** [comment]
RichPresence as been rewritten in the next update, with fully customizable text.
