### ISSUE TITLE
offhand swing

### ISSUE THREAD

**Issue by ignelias** [John200410/rusherhack-issues#202]
swing with offhand like in xulu

**Comment by John200410** [comment]
Is it purely cosmetic? I will probably make a Swing module and combine it with things like NoSwing.

**Comment by ignelias** [comment]
yeah cosmetic

**Comment by Lempity** [comment]
add this please

**Comment by ignelias** [comment]
yes

**Comment by John200410** [comment]
This has been added in the next update.
