### ISSUE TITLE
issues saving configs for some modules

### ISSUE THREAD

**Issue by ignelias** [John200410/rusherhack-issues#203]
**Describe the bug**
sometimes strafe gets reset and unbinded and friends reset(used to happened with logout spots and got fixed).

**To Reproduce**
close the game

**Other mods**
none relevant 

**Expected behavior**
config no save

**Screenshots**
uh

**Additional context**
a

**Comment by John200410** [comment]
Friends resetting has been fixed. Duplicate of #176
