### ISSUE TITLE
[FEATURE] Spammer "InOrder" setting

### ISSUE THREAD

**Issue by tycrek** [John200410/rusherhack-issues#204]
**What feature would you like to be added.**
Instead of random lines, run the Spammer file line by line.

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by Chiyun2b** [comment]
In the Spammer module could you make it so you could spam /w's on 2b2t which lets you spam a custom message and keeps up with the 2b2t spambot so it doesn't get you kicked?

**Comment by John200410** [comment]
> In the Spammer module could you make it so you could spam /w's on 2b2t which lets you spam a custom message and keeps up with the 2b2t spambot so it doesn't get you kicked?

#224 does this

**Comment by John200410** [comment]
A mode setting has been added to Spammer and will appear in the next update.
