### ISSUE TITLE
Avoid for Anti-Afk[FEATURE]

### ISSUE THREAD

**Issue by TheRedBlocker** [John200410/rusherhack-issues#206]
**What feature would you like to be added.**
Exactly what it sounds like, if you have movement/baritone enabled in anti-afk configs, it would not walk you off edges, into water/lava, or anything else that could kill you. Would either be automatically built in or a toggleable option (probably).

**Is your feature request related to a problem? Please describe.**
Don't want to die while anti-afking.

**Comment by John200410** [comment]
Will probably just build this into the setting.

**Comment by John200410** [comment]
This should not be an issue with the new algorithm in the next update.
