### ISSUE TITLE
[FEATURE] new efly mode and better efly

### ISSUE THREAD

**Issue by Badinek** [John200410/rusherhack-issues#207]
**What feature would you like to be added.**
Since firework mode uses too much of fireworks and its not that good for normal flying in ow/open nether, i thought about new mode that wouldnt maintain your Y but would use firework everytime the efly speed goes under your set min limit (for example, under 100km/h, it would use a firework and repeat)
so i would make a new mode (idk how it would be called) and make it do this.
better efly- 
1. option to takeoff only by pressing space once and not holding it, would make taking off on highway easier
2. make the efly get back into elytra pos everytime it glitches you out of  elytra pos back to normal pos
3. if you start rubberbanding with firework mode, it would stop using fireworks and wait for the rubberbands to stop, then use fireworks again (and maybe fix the disconnects when this happens too)

**Is your feature request related to a problem? Please describe.**
1. while taking off on highway, holding space is pretty annoying cause when you get into elytra pos and u dont stop holding space you fly into nether ceiling, so i think only pressing space once to get into elytra pos would be better
2. sometimes it randomly glitches you out of elytra pos for no reason few times while flying, idk if this is some anticheat problem but if you make it just get into efly pos automatically while having elytrafly on it would prevent this for sure
3. this sometimes happens and if i dont turn off elytrafly soon enough it kicks me and wastes fireworks, so this would be cool

**Comment by John200410** [comment]
Thank you for the suggestions. 

> holding space is pretty annoying cause when you get into elytra pos and u dont stop holding space you fly into nether ceiling

This will be solved in an upcoming silent update as I have made it so holding space won't make you go up for the first second.

**Comment by Badinek** [comment]
alright, thank you. but wouldnt adding option to start the takeoffing only by pressing space once be better? it was in other clients like this and its not like someone has efly module nonstop enabled.

**Comment by John200410** [comment]
That will still be added.

**Comment by John200410** [comment]
This has been added in the next update.
