### ISSUE TITLE
[FEATURE] Hud alignment

### ISSUE THREAD

**Issue by tycrek** [John200410/rusherhack-issues#208]
**What feature would you like to be added.**

Ability to change text alignment of MacroList and BindList to left (current), centre, or right (would align by the keys instead of the function)

**Comment by John200410** [comment]
Instead of having it specific to these elements, I will probably add a way to change the alignment of all hud elements

**Comment by John200410** [comment]
I have just made it so that it is now based on the quadrant rather than the corner it is snapped to. I will probably also add a setting to override the alignment regardless of the quadrant.

https://rusherhack.org/i/m9zmday5tk.mp4

**Comment by jumboman32** [comment]
Merging.
