### ISSUE TITLE
[BUG] ExtraChat MentionHighlight/Sound

### ISSUE THREAD

**Issue by jumboman32** [John200410/rusherhack-issues#212]
**Describe the bug**
I have an alt named ExtraTab, and someone else has an account named Extratab_ and every time their name appears in chat I am still getting the notification.

**To Reproduce**
Add an '_' to an alt and type in chat on it.

**Other mods**
Irrelevant.

**Expected behavior**
No Highlight/Sound.

**Comment by John200410** [comment]
Thank you for reporting this.

**Comment by John200410** [comment]
This has been fixed.
