### ISSUE TITLE
Entity or mob search [FEATURE]

### ISSUE THREAD

**Issue by Cooliokid** [John200410/rusherhack-issues#215]
**What feature would you like to be added.**
an option either as it own module or in search that would have tracers or highlight specific mob or entity

**Is your feature request related to a problem? Please describe.**
when trying to make a stash it usually takes a while to find a donkey to dupe with and it would also help with finding slime and ghasts for oldfag

**Comment by jumboman32** [comment]
I think just using the entity list would be more helpful than this.

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
Entity support has been added to Search in the next update:

![image](https://user-images.githubusercontent.com/43681932/122635816-eedb3980-d0b3-11eb-8500-097f0eb6eaa8.png)
