### ISSUE TITLE
[FEATURE] Make client version to 1.8.9

### ISSUE THREAD

**Issue by BLUELIGHTTIGER** [John200410/rusherhack-issues#216]
**What feature would you like to be added.**
A detailed explanation of what this feature should be.
--> add version 1.8.9

**Is your feature request related to a problem? Please describe.**
-->no

**Additional context**
-->i am playing on small anarchy server who is in version 1.8.9 and i also like rusherhacks

**Comment by jumboman32** [comment]
Read the FAQ

**Comment by BLUELIGHTTIGER** [comment]
> Read the FAQ

Where is FAQ??

**Comment by John200410** [comment]
No.

This would promote cheating on servers where it is not allowed.

If you want to be able to connect to 1.8 servers you can use the ViaForge mod (https://www.curseforge.com/minecraft/mc-mods/viaforge).
