### ISSUE TITLE
[FEATURE] HUD requests

### ISSUE THREAD

**Issue by Papa-Quill** [John200410/rusherhack-issues#219]
**What features I would like to be added to the HUD.**
1. Make it so HUD modules have a setting to flip them (Left Center Right)
2. Add scrolling in the HUD manager
3. Player viewer mode forward is broken (for me at least)
4. Corner dragging scaling for HUD features
5. Ability to add and remove background for HUD modules (like a transparent darker background for the text or inventory or whatever)
6. Greeter, a HUD module that says Welcome, (appends player's username). Use this for an example https://cdn.discordapp.com/attachments/472223564796264448/786994243292889098/unknown.png
7. Target HUD, displays a new information box on the closest player target such as health, armor durability, ping, if their feet are protected, totems popped, if they have strength effect on, what items are in their hand, nametag and anything else useful you can think of. Make sure you can toggle on and off what information shows up.

**Comment by John200410** [comment]
Thank you for the suggestions.

**Comment by John200410** [comment]
So far the scrolling has been added in the Hud Manager.

I'm not too sure if I would be willing to add a "Greeter" hud element though.

**Comment by Mishi04** [comment]
add Target hud 🥺🥺🙏🙏

**Comment by John200410** [comment]
Background customization is added in the next update. The other things have been added/fixed or have other issues opened about them
