### ISSUE TITLE
[FEATURE] BlockTweaks Option BuildHeight

### ISSUE THREAD

**Issue by Oecher1** [John200410/rusherhack-issues#22]
**What feature would you like to be added.**
Basically in salhack there's a module called buildheight it just lets you interact with blocks at build height like enderchests etc basically just changes the interact packet from interacting at the top to the side of the block to open it i just thought this would be a good suggestion to well suggest but idk.

**Is your feature request related to a problem? Please describe.**
Nope not a issue.

**Additional context**
Idk just looking through salhack and saw rusherhack didn't have this.

**Comment by John200410** [comment]
Thank you for the suggestion

**Comment by John200410** [comment]
This has been added in v1.1
