### ISSUE TITLE
[FEATURE] better packetfly

### ISSUE THREAD

**Issue by Badinek** [John200410/rusherhack-issues#221]
**What feature would you like to be added.**
better packetfly for 2b2t that wont kick when going up and is smooth

**Is your feature request related to a problem? Please describe.**
in the new future client update packetfly is better, smooth and kinda fast without kicks, (both phasing and normal walking in air) so i was wondering if its possible to improve rusherhack packetfly. rh packetfly kicks when going up too long and for some reason it kicks when you phase too long

**Comment by John200410** [comment]
I plan to rewrite PacketFly in v1.2, so I can try optimizing it for 2b2t.

**Comment by John200410** [comment]
Hello,

PacketFly has been rewritten in the next update.
