### ISSUE TITLE
[features and bugs] A lot of stuff

### ISSUE THREAD

**Issue by FarmerJoe2b2t** [John200410/rusherhack-issues#222]
make fast xp a fastplace setting
make search use block color like future
chams is kinda buggy - https://postimg.cc/zbySc5kr (image)
new speed mode, similar to liquidbounce ncp hop, that combines on ground and strafe
autowalk baritone option to use #thisway, and command to set autowalk destination to rusherhack waypoints
add steal and put all buttons for chests and shulkers, like in wurst
add option to delete previous chat toggle notifications
add chat timestamps option to not timestamp messages that aren't sent by a player
make greeter an announcer setting

**Comment by tycrek** [comment]
> combine clientsidetime and fullbright

nono don't do this, they are better separated. They do different things anyways so makes no sense to merge them

> make no sould lag a norender setting

these do completely different things

**Comment by John200410** [comment]
Thank you for this list. I will comment when I made progress on some of these things

**Comment by John200410** [comment]
I've done a lot of the things and removed them from your issue as time goes on. But I think it would be better if you just made separate issues for each of these.
