### ISSUE TITLE
holefilter for 2 wide block holes

### ISSUE THREAD

**Issue by i-dont-have-any-good-names** [John200410/rusherhack-issues#223]
add a thing to make it cover 2 block wide holes because people get into one and they are able to cover them selfs

**Comment by TheRedBlocker** [comment]
also for 2 block tall holes

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
> also for 2 block tall holes

HoleFiller already fills these.
https://rusherhack.org/i/rde9tol7uj.mp4

**Comment by John200410** [comment]
Doubles setting has been added to HoleFiller in the next update.
