### ISSUE TITLE
[FEATURE] HUD Editor Scrolling

### ISSUE THREAD

**Issue by Papa-Quill** [John200410/rusherhack-issues#225]
**What feature would you like to be added.**
I don't like having to change my HUD scale to small everytime I wanna reach the settings at the bottom of the HUD editor and being able to scroll in it would just make my life and others so much easier

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
This has been made.
https://rusherhack.org/i/q9k7n0ejlb.mp4
