### ISSUE TITLE
[FEATURE] Placed Illegal ESP

### ISSUE THREAD

**Issue by evildonjr** [John200410/rusherhack-issues#228]
A ESP that highlights for example bedrock over y level 5 and end portal frames.

I've already made coded a module for it myself using seppuku base, the problem with that is Seppuku isn't compatible with Rusherhack. You can message me on discord (Sanku#0789), if you want the code, but you could probably do it yourself easily.

**Comment by John200410** [comment]
Thank you for the suggestion. I will probably make this a setting under Search.

**Comment by John200410** [comment]
I will also add a setting for water in the nether.

**Comment by John200410** [comment]
This has been added in v1.2

**Comment by ItsYoungDaddy** [comment]
epic
