### ISSUE TITLE
custom main menu

### ISSUE THREAD

**Issue by HermanGoring** [John200410/rusherhack-issues#229]
**What feature would you like to be added.**
A custom main menu where you could customise where the buttons are, in this case maybe a windows 98?
https://static.wikia.nocookie.net/windows/images/8/80/W98-2.png/revision/latest?cb=20191005212338

Heres an example. maybe internet explorer could be multiplayer and my computer to be singleplayer?
**Is your feature request related to a problem? Please describe.**
No it is not

**Additional context**
Yes rlly any theme. make it ultra customisable

**Comment by John200410** [comment]
I don't think this would be something worth adding.

This forge mod (https://www.curseforge.com/minecraft/mc-mods/custom-main-menu) allows for fairly extensive customization of the main menu. You can probably use this to achieve what you are looking for.
