### ISSUE TITLE
[FEATURE] ChestSwap

### ISSUE THREAD

**Issue by 71uaq3u** [John200410/rusherhack-issues#231]
**What feature would you like to be added.**
chestswap

**Is your feature request related to a problem? Please describe.**
so if u have ur elytra on and toggle chestswap then ur chestplate equips and if u have ur chestplate on and u toggle it then ur elytra gets on

**Additional context**
no lol

**Comment by John200410** [comment]
You can just make a macro to toggle the Elytra Priority setting under AutoArmor.
