### ISSUE TITLE
[FEATURE] Waypoints command improvements

### ISSUE THREAD

**Issue by tycrek** [John200410/rusherhack-issues#232]
**What feature would you like to be added.**

- `*waypoints del`: instead of deleting **all** waypoints of a name, delete the one(s) only in the current server.
- `*waypoints list`: only show waypoints for the current server

Edit: `*waypoints list` doesn't show proper coordinates:
![image](https://user-images.githubusercontent.com/29926144/102505116-daec4780-403e-11eb-9251-99566fe7ec1b.png)

**Comment by John200410** [comment]
Thank you for the suggestions.

**Comment by John200410** [comment]
These things have been done in the next update.
