### ISSUE TITLE
[NoRender] particles remove 

### ISSUE THREAD

**Issue by thebruhmoment** [John200410/rusherhack-issues#233]
**What feature would you like to be added.**
this feature completely removes particles when you break blocks 

**Is your feature request related to a problem? Please describe.**
Particles is fine when you break like 1 block or just few long to break blocks.
but when you need to mine fast blocks like stone/netherrack it creates ~ 128 particles
for every single block you break and it highly decrease my fps from 320/120 to 300 /30 and game becomes
freezing and lagging very much

**Additional context**
![2020-12-17 21-33-32](https://user-images.githubusercontent.com/65070996/102535024-491d2280-40b0-11eb-8924-e0f29ecbd8dd.gif)
(sorry for that bruh quality of gif)

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
This has been added in the next update.
https://rusherhack.org/i/5zrkftt1f8.mp4
