### ISSUE TITLE
[FEATURE]AntiCrystal

### ISSUE THREAD

**Issue by xDeonn** [John200410/rusherhack-issues#234]
**What feature would you like to be added.**
AntiCrystal - Places stone buttons/webs/torches on obsidian and bedrock where placing a crystal would hurt you

**Is your feature request related to a problem? Please describe.**
no, not really. it seems useful though

**Additional context**

**Comment by ToxicAven** [comment]
Ok, This is a cool idea. Is this in any other client, Or is this an original Idea?

**Comment by xDeonn** [comment]
i am not sure, i have never seen it so i guess its original.

**Comment by John200410** [comment]
I'm not too sure if I want to add this but I may consider it. Will leave this issue open for now so other people can leave their input here.

**Comment by Papa-Quill** [comment]
Also with pressure plates too. I've seen this used like once or twice but with pressure plates.

**Comment by FarmerJoe2b2t** [comment]
Use surround

**Comment by y4ndex1** [comment]
> Use surround

🤣 you wont have godmode when you use surround
