### ISSUE TITLE
[FEATURE] InventoryCleaner

### ISSUE THREAD

**Issue by Papa-Quill** [John200410/rusherhack-issues#238]
**What feature would you like to be added.**
Allows you to add items to a list like search where it will automatically throw that item out for you. For an example, empty potion bottles, or seeds, or rabbits foot. Things you don't want filling up your inventory to be automatically thrown out for you.

**Comment by John200410** [comment]
Thank you for the suggestion. Probably just going to call this InventoryCleaner though.

**Comment by John200410** [comment]
This has been added in the next update.
