### ISSUE TITLE
[FEATURE] SelfBlock

### ISSUE THREAD

**Issue by ignelias** [John200410/rusherhack-issues#24]
when you turn it on and jump it places a block under you and glitches you in it so nobody can get in your hole

**Comment by FluorideHistorian** [comment]
hey xulu just added that

**Comment by John200410** [comment]
I will need a better name for the module

**Comment by ignelias** [comment]
maybe like selfblock

**Comment by John200410** [comment]
This has been finished and will ship in the next update.
https://www.youtube.com/watch?v=pJxhHuNMgNI

**Comment by Oecher1** [comment]
> This has been finished and will ship in the next update.
> https://www.youtube.com/watch?v=pJxhHuNMgNI

i will waste my life going to those coords just to place a sign kek
