### ISSUE TITLE
[BUG] Hitbox ignore setting

### ISSUE THREAD

**Issue by FarmerJoe2b2t** [John200410/rusherhack-issues#245]
Hitbox ignore settings are inverted for tools. 
If I have pickaxes or swords enabled, it won't ignore hitboxes while I am holding that tool, but it will if I turn the setting off.

**Comment by John200410** [comment]
Thank you for reporting this. Will probably backport this once I fix it.

**Comment by John200410** [comment]
This issue has been solved in v1.2. May end up backporting it.
