### ISSUE TITLE
[FEATURE] Save rusher output to separate log file

### ISSUE THREAD

**Issue by tycrek** [John200410/rusherhack-issues#249]
**What feature would you like to be added.**

Any log output or notifications etc that Rusher sends, save to a separate file that isn't latest.log. Would help to look at stash logger, etc without looking through game chat as well

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
This has been finished and will appear in the next update.

![image](https://user-images.githubusercontent.com/43681932/103051147-208ba180-4564-11eb-8c99-f2a02dbe3c92.png)
