### ISSUE TITLE
[FEATURE] YouTube player HUD module

### ISSUE THREAD

**Issue by Papa-Quill** [John200410/rusherhack-issues#250]
**What feature would you like to be added.**
A HUD module where you can change the size, volume, and position like any other HUD module. The way it could work is you enter a command with a YouTube link and when you enter the command the YouTube video starts playing. Then make so you can add other videos to the playlist so that after one video is done it will auto play to the next. I think it'd be really cool to watch someone's stream while you walk down a highway or just listen to music while you're pvping. Some examples of commands are:
*youtube add (video URL)
*youtube del (video URL or number in the playlist)
*youtube pause (pauses video)
*youtube play (starts video)
*youtube goto (time to go to in the video)
*youtube skip (goes to the next video in the playlist)
*youtube save (name) (saves current playlist)
*youtube load (name) (loads the list of URLs saved for that playlist name, so if you want to hear a certain music playlist you can)
*youtube list (shows all videos in the current playlist)

**Comment by John200410** [comment]
Thank you for the suggestion. I honestly have no idea how I would do this and searching on google leads me to belive this would be very hard. Going to close this for now and may re-open it if I find a way to do this.
