### ISSUE TITLE
[FEATURE] Search Bar In The ClickGUI.

### ISSUE THREAD

**Issue by Jopplo** [John200410/rusherhack-issues#251]
**What feature would you like to be added.**
A search bar in the ClickGUI to easily find cheats.

**Is your feature request related to a problem? Please describe.**
It can be a real pain to try and find some cheat, this would easily solve this.

**Additional context**
It is a popular feature that a lot for other clients have.

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
This has been added in the next update:

https://www.youtube.com/watch?v=q3dxpQvpaYQ
