### ISSUE TITLE
[FEATURE] search blocks command

### ISSUE THREAD

**Issue by FarmerJoe2b2t** [John200410/rusherhack-issues#252]
Add the searchblocks command to the *help command list and remove the space

**Comment by John200410** [comment]
I will add module commands to *help, however, I don't plan on removing the space

**Comment by John200410** [comment]
All module commands have now been added to the Help command:

![image](https://user-images.githubusercontent.com/43681932/121589226-d3fa2c80-ca04-11eb-981b-bad6ad200098.png)
