### ISSUE TITLE
[FEATURE] autocrystal aimstep

### ISSUE THREAD

**Issue by FarmerJoe2b2t** [John200410/rusherhack-issues#253]
slow down autocrystal rotations by only rotating a certain number of degrees each tick, i'm not sure if this would help but the current autocrystal desyncs sometimes on 2b after placing for several seconds so it's probably worth a try

**Comment by John200410** [comment]
I will give this a try when AutoCrystal gets rewritten.

**Comment by John200410** [comment]
This has been done in the next update.
