### ISSUE TITLE
[BUG] ElytraFly + Breadcrumbs

### ISSUE THREAD

**Issue by jumboman32** [John200410/rusherhack-issues#255]
**Describe the bug**
Breadcrumbs does not work with ElytraFly2b2t as it makes a new trail each time you are rubberbanded.

**To Reproduce**
1. Turn on Breadcrumbs and ElytraFly2b2t.
2. Fly.

**Other mods**
None, relevant.

**Comment by John200410** [comment]
Thank you for reporting this.

**Comment by John200410** [comment]
This has been fixed.
