### ISSUE TITLE
[FEATURE] Scaffold Slab Compatibility

### ISSUE THREAD

**Issue by ItzDawnfall** [John200410/rusherhack-issues#256]
**What feature would you like to be added.**
While using the Scaffold module, you would be able to walk with slabs in hand and have them placed in front of you so you can smoothly walk an place them

**Is your feature request related to a problem? Please describe.**
Not able to use slabs with scaffold

**Additional context**
I use slabs in a road design I use and Scaffold makes it much easier to place

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
This has been done in the next update.
