### ISSUE TITLE
[FEATURE] Discord Whitelist using Discord ID.

### ISSUE THREAD

**Issue by exwundee** [John200410/rusherhack-issues#257]
When whitelisting a user via. the launcher, sometimes certain unicode characters are not recognized and it won't allow the user to receive the **whitelisted** role on the discord server.

A way around this, would to allow the user to put their Discord ID as an alternative. It shouldn't be in a separate field, but should be recognized and attempted if there is no # character in the submitted input field.

**Comment by exwundee** [comment]
Right now the only work around is to change your discord username, but most users may not know this and will cause an influx in issues that could be easily fixed with this implement.

![image](https://user-images.githubusercontent.com/36908791/103070730-1f706980-4590-11eb-81d1-72183831b069.png)

**Comment by John200410** [comment]
I plan to do this when I rewrite the installer

**Comment by Floppinqq** [comment]
why ppl uses emoji in nickname btw

**Comment by John200410** [comment]
This is no longer a problem.
