### ISSUE TITLE
[FEATURE] Selfweb

### ISSUE THREAD

**Issue by Oecher1** [John200410/rusherhack-issues#26]
**What feature would you like to be added.**
Basically if your in a hole and you toggle the module selfweb it will place a web in your hole so if someone's trying to get in it takes way longer and you have a lot more time to crystal them while there hitbox is still not in the hole from the cobweb it can be very useful in certain situations.

**Is your feature request related to a problem? Please describe.**
Nope.

**Additional context**
Looking through other clients and saw rusherhack didn't have this module cause selfweb is very useful in certain situations.

**Comment by John200410** [comment]
I will probably make this an option in AutoWeb when I make that.

**Comment by Oecher1** [comment]
> I will probably make this an option in AutoWeb when I make that.

ok

**Comment by John200410** [comment]
The AutoWeb module has been created. Expect in in v1.1
