### ISSUE TITLE
Basefinder Improvements

### ISSUE THREAD

**Issue by Snoww32** [John200410/rusherhack-issues#261]
Please add in droppers and dispensers into basefinder, and also allow me to turn down the amount of hoppers, as I can only turn it to 0 or 3, not like 1. Its difficult to drag most of the sliders on basefinder to like 1 tbh.

**Comment by John200410** [comment]
Thank you for the suggestion.

>  I can only turn it to 0 or 3, not like 1

You can change it to an exact value via command. *basefinder hoppers 1

**Comment by jumboman32** [comment]
Merged with #892
