### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by gargamelius** [John200410/rusherhack-issues#264]
**What feature would you like to be added.**
pls add the option to edit the thickness of tracers in the search module

**Is your feature request related to a problem? Please describe.**
I like my tracers thick af but sadly thats not possible rn :(

**Additional context**
the option is already in the module tracers so it only makes sense to add it to search

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
I have now made them use the thickness defined in the Tracers module.
