### ISSUE TITLE
[BUG] criticals not working

### ISSUE THREAD

**Issue by Badinek** [John200410/rusherhack-issues#268]
**Describe the bug**
its probably not a bug, but if i have criticals enabled, it doesnt register the hit 80% of the time, and when it finally does its not even critical hit (on 2b2t, yes i have strict enabled). in future it does the critical 90% of the time, so im pretty sure this can be improved.

**To Reproduce**
enable criticals module and try to hit entities

**Other mods**
atom optifine baritone schematica

**Expected behavior**
i expect the criticals module to actually do critical hits and not just make me unable to hit

**Comment by John200410** [comment]
Thank you for reporting this. I will try improving it.

**Comment by John200410** [comment]
This has been fixed and has been backported to v1.1.3
