### ISSUE TITLE
[FEATURE] make the health bar thickness scale with distance

### ISSUE THREAD

**Issue by FarmerJoe2b2t** [John200410/rusherhack-issues#269]
![2020-12-23_13 09 55](https://user-images.githubusercontent.com/52103622/103159987-f58c9200-479d-11eb-8ce2-096b040021b0.png)

**Comment by John200410** [comment]
Would you prefer it using the same thickness of the box?

**Comment by FarmerJoe2b2t** [comment]
yes

**Comment by John200410** [comment]
A setting has now been added to change the thickness of the Health bar
