### ISSUE TITLE
[FEATURE] Different colour for not drawn modules in *modules

### ISSUE THREAD

**Issue by tycrek** [John200410/rusherhack-issues#27]
**What feature would you like to be added.**
Any module that has `drawn` set to `false` should have a different colour in the `*modules` command.

**Comment by John200410** [comment]
This has been completed for v1.1

Modules that are not visible on the FeatureList will now show up in a darkened version of their original color

![image](https://user-images.githubusercontent.com/43681932/95767787-41da3280-0c83-11eb-8e28-90fa898a4b0a.png)

**Comment by tycrek** [comment]
Looks great!
