### ISSUE TITLE
[FEATURE] Add a zig zag option to basefinder

### ISSUE THREAD

**Issue by Gqlactic** [John200410/rusherhack-issues#273]
**What feature would you like to be added.**
Essentially, If I wanted to search all possible locations from a specific coordinate range off of an axis out to world border or something. Say I wanted to search between 30k - 50k blocks off of the axis I could set that with a command as a coordinate range, then the basefinder would start at 30k off the axis and then move to 50k blocks off it, then it would turn 90 degrees and go out further on the axis a bit just past render distance or whatever, then it would go back to 30k and so forth. It will keep searching every possible location between 30k - 50k off the axis all the way out to world border or when i stop it.

**Is your feature request related to a problem? Please describe.**
No, it is not related to a problem, I just thought it could be a more effective way of finding bases/stashes with basefinder.

**Additional context**
N/A

**Comment by John200410** [comment]
Thank you for the suggestion. Not sure when I will be able to implement this.

**Comment by jumboman32** [comment]
Merged with #892
