### ISSUE TITLE
[FEATURE] Basefinder option

### ISSUE THREAD

**Issue by moom0o** [John200410/rusherhack-issues#275]
**What feature would you like to be added.**
A detailed explanation of what this feature should be.

An option to basefinder to NOT check the chunks for shulkers/chests/etc

**Is your feature request related to a problem? Please describe.**

Yes, my framerate is shit when I'm using basefinder to worlddownload. (especially at spawn)

**Additional context**

**Comment by jumboman32** [comment]
Just turn the variables to 0.

**Comment by John200410** [comment]
You can set the settings to 0 and it won't try to log them.
