### ISSUE TITLE
[FEATURE] Setting for Nametags under ESP

### ISSUE THREAD

**Issue by OliverIGuess** [John200410/rusherhack-issues#276]
**What feature would you like to be added.**
There should be an option to toggle nametags being displayed by the ESP module.
This could be implemented by making an nametags switch under the ESP module that can be turned on and off.

**Is your feature request related to a problem? Please describe.**
Not really, no.

**Additional context**
This can be helpfull so people using ESP and Nametags at the same time will still have their info in the ESP but can toggle so the Nametags don’t overlap.
And all in all it would be a quality of live improvement.

**Comment by John200410** [comment]
I'm assuming you are referring to the CSGO mode?

**Comment by OliverIGuess** [comment]
Yes.
We talks about this in he discord and you said, you could implement this feature and that i should make a GitHub post about it.

**Comment by John200410** [comment]
This is no longer needed. The ESP module was improved.
