### ISSUE TITLE
[BUG] cannot bind modules to mouse buttons

### ISSUE THREAD

**Issue by FarmerJoe2b2t** [John200410/rusherhack-issues#278]
the module will stop listening fora a key press if you press a mouse button, even if it is something other than left or right click, and the bind command returns no message when you try to bind to a mouse button

**Comment by John200410** [comment]
You can bind them but it has to be done via command for now until I write a new bind system.

**Comment by John200410** [comment]
This has been fixed since the bind system has been revamped.
