### ISSUE TITLE
[BUG]  Jump vertical option

### ISSUE THREAD

**Issue by drboy2005** [John200410/rusherhack-issues#280]
The jump option on the vertical feature for elytrafly does not work no matter what, not even single player worlds. i tried it in many anarchy servers and it does not work. So I believe its a client issue. Thanks.

**Comment by John200410** [comment]
I will look into this. I believe this issue is related to the obfuscation as it doesn't happen in my development environment.

**Comment by John200410** [comment]
I have found the issue and it has been fixed. Will backport this to the current version eventually.
