### ISSUE TITLE
Black List Tab Feature [FEATURE]

### ISSUE THREAD

**Issue by SilverEyes100** [John200410/rusherhack-issues#281]
A feature which will allow you to add a player to blacklist

Adding a player to a "blacklist" it will make their name the color red when pressing tab on a Minecraft server. In the drop down menu, you can make Auto Crystal turn on when in range of the player. Also within the drop down menu, you can turn on "Notify" option; this notify you when black listed players have joined the server.

**Additional context**
- *blacklist add [playername]
- *blacklist del [playername]

**Comment by ItzDawnfall** [comment]
The Notify part of this could be combined with my suggested idea, FriendNotifier as well. #272

**Comment by SilverEyes100** [comment]
> The Notify part of this could be combined with my suggested idea, FriendNotifier as well. #272

Y

**Comment by SilverEyes100** [comment]
> The Notify part of this could be combined with my suggested idea, FriendNotifier as well. #272

I agree this would be nice.

**Comment by John200410** [comment]
I will classify this as an extension of #122.

**Comment by jumboman32** [comment]
This was added in as *enemy
