### ISSUE TITLE
Render Tweaks[FEATURE]

### ISSUE THREAD

**Issue by y4ndex1** [John200410/rusherhack-issues#286]
basicly  a ton of new render features that would be useful for pvp and more minimalistic. 
- NoSwingAnim (complety removes swing animation with diff modes like  swordswing on eating on

i got this idea from xulu client and its  pretty decent so ill be happy if this get added for v1.2

**Comment by chaze4** [comment]
Dude, you can choose your main hand in minecraft settings...

**Comment by y4ndex1** [comment]
> Dude, you can choose your main hand in minecraft settings...

holy shit im dumb  i edited it out ty tho

**Comment by FarmerJoe2b2t** [comment]
there is already a module do disable the swing animation

**Comment by John200410** [comment]
Player -> NoSwing. Make sure you have the Strict setting enabled.
