### ISSUE TITLE
[FEATURE] Highlight Shulkers in Chests

### ISSUE THREAD

**Issue by Snoww32** [John200410/rusherhack-issues#289]
Thats it, just highlight shulkers in chests because I sometimes miss them.

**Comment by John200410** [comment]
Thank you for the suggestion. Will probably add this as a setting to ExtraChest

**Comment by John200410** [comment]
This has been added as a setting to ExtraTooltip in the next update:
![image](https://user-images.githubusercontent.com/43681932/112736162-ed6ffa00-8f26-11eb-841b-5cdd864c750a.png)
