### ISSUE TITLE
[FEATURE] Show active config profile in HUD

### ISSUE THREAD

**Issue by tycrek** [John200410/rusherhack-issues#29]
**What feature would you like to be added.**
Basically the title. In the HUD manager, have an option to display the active config profile

**Comment by John200410** [comment]
Thank you for the suggestion

**Comment by John200410** [comment]
This has been finished and will appear in the next update.
![image](https://user-images.githubusercontent.com/43681932/96526378-58682700-124b-11eb-9331-7cbb248b6092.png)
