### ISSUE TITLE
[BUG] autotrap

### ISSUE THREAD

**Issue by Badinek** [John200410/rusherhack-issues#295]
**Describe the bug**
autotrap tries to place blocks on ender chest (happens to other blocks like furnace/crafting table/ench table) without sneaking, which results in kick on servers (it keeps opening and closing the gui fast  so you get kicked)

**To Reproduce**
if player stands next to an echest and you try to autotrap him, it will happen (tries to place the obsidian on top of the ender chest)

**Other mods**
List other forge mods you are using (if any):
atom schematica optifine

**Expected behavior**
make it not kick and place with sneaking

**Screenshots**
dont have any

**Additional context**

**Comment by John200410** [comment]
Thank you for reporting this.

**Comment by John200410** [comment]
This has been fixed in v1.2
