### ISSUE TITLE
[BUG] *peek does not show enchants.

### ISSUE THREAD

**Issue by gcurtiss** [John200410/rusherhack-issues#3]
**Describe the bug**
*peek does not show enchants.

**To Reproduce**
1. Fill a shulker with enchanted items.
2. Do *peek.
3. See error.

**Other mods**
List other forge mods you are using (if any): Pyro

**Expected behavior**
Expected to see enchants.

**Comment by John200410** [comment]
![image](https://user-images.githubusercontent.com/43681932/93687680-747e7a00-fa8d-11ea-8a2f-c2831077d150.png)
Cannot reproduce. Try removing Pyro to see if the issue is resolved

**Comment by gcurtiss** [comment]
Removing Pyro solved the issue, will take it up with them.
