### ISSUE TITLE
[FEATURE] MacroList (similar to BindList)

### ISSUE THREAD

**Issue by tycrek** [John200410/rusherhack-issues#30]
**What feature would you like to be added.**
Pretty much the same thing as BindList HUD module but for Macros.

**Comment by John200410** [comment]
Thank you for the suggestion

**Comment by John200410** [comment]
This has been added in v1.1.1
![image](https://user-images.githubusercontent.com/43681932/97733816-b4824500-1aae-11eb-874f-6442a6114587.png)
