### ISSUE TITLE
[FEATURE] AutoEat Both/Auto Mode

### ISSUE THREAD

**Issue by jumboman32** [John200410/rusherhack-issues#301]
**What feature would you like to be added.**
A different option besides Hunger/Health, that can use both of those options.

**Is your feature request related to a problem? Please describe.**
It's annoying to have it on Health mode because it won't eat until you start starving if you're AFK.

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
This has been added in v1.2
