### ISSUE TITLE
better chat notifications[FEATURE]

### ISSUE THREAD

**Issue by y4ndex1** [John200410/rusherhack-issues#303]
rainbow [rusherhack] and it doesnt fill up the chat like instead of 2 lines 1 enabled 1 disabled just change 1 line

**Comment by John200410** [comment]
Thank you for the suggestion. I plan on making it use the color of your ClickGui.

> it doesnt fill up the chat like instead of 2 lines 1 enabled 1 disabled just change 1 line
What do you think would be a good name for this setting?

**Comment by y4ndex1** [comment]
> Thank you for the suggestion. I plan on making it use the color of your ClickGui.
> 
> > it doesnt fill up the chat like instead of 2 lines 1 enabled 1 disabled just change 1 line
> 
> What do you think would be a good name for this setting?

Chat Notifications under HUD is prob a good idea, or in colors.

**Comment by John200410** [comment]
No I don't think that would be a good name for that setting. I need a name for the setting that would toggle the one notification maximum thing.

**Comment by y4ndex1** [comment]
> No I don't think that would be a good name for that setting. I need a name for the setting that would toggle the one notification maximum thing.

I dunno, maybe make it unchangable and turned on by default? and the color could be changed in colors or clickgui color syned

**Comment by John200410** [comment]
>  maybe make it unchangable

This is retarded. I believe in choice and I want it to be toggleable.

**Comment by jumboman32** [comment]
Merging
