### ISSUE TITLE
[FEATURE] AutoTotem Improvements

### ISSUE THREAD

**Issue by notperry1234567890** [John200410/rusherhack-issues#307]
**What feature would you like to be added.**
Two new options.
Run In Guis. Basically if your in the clickgui of future,rusherhack,phobos whatever it wont work and well that can be a issue sometimes.
Check Absorption. If you have the autototem on health mode and like have the health at 13 when you have absorption that makes your health above 13 it wont switch it only checks the actual health not also the absorption health which is very annoying in fights i lose lots of chances to pop them even when i'm above 13 health with absorption so it would be nice to at least see this one added.

**Is your feature request related to a problem? Please describe.**
Eh kinda a problem in pvp the only things that's a really big issue is the absorption one.

**Additional context**
Was testing out AutoTotem and found these two small issues.

**Comment by John200410** [comment]
Thank you for the suggestions.

**Comment by John200410** [comment]
I have just fixed it not working in GUIs.

**Comment by John200410** [comment]
I have just added an AbsorptionCheck setting aswell.

**Comment by notperry1234567890** [comment]
> I have just added an AbsorptionCheck setting aswell.

lets goooo
