### ISSUE TITLE
[FEATURE] FallDistance mode for AutoTotem

### ISSUE THREAD

**Issue by Floppinqq** [John200410/rusherhack-issues#308]
using offhand gap i died so many times because fall damage :(
add FallDistance to when player is from the falldistance value from ground, automatically change to totem to you dont die by fall damage

**Comment by John200410** [comment]
Thank you for the suggestion. I will make it so AutoTotem will switch back to a totem if you have fallen 5 blocks until you hit the ground.

**Comment by John200410** [comment]
This has been added in the next update.
