### ISSUE TITLE
[FEATURE] Disabled/Enabled Modules color in BindList

### ISSUE THREAD

**Issue by Floppinqq** [John200410/rusherhack-issues#309]
change what ill be the color if the module is enabled or disabled

![image](https://user-images.githubusercontent.com/76592418/103683116-8a467b00-4f68-11eb-88d9-4df0176be1cf.png)

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
This has been added in the next update.
