### ISSUE TITLE
[FEATURE] DurabilityAlert

### ISSUE THREAD

**Issue by Oecher1** [John200410/rusherhack-issues#31]
**What feature would you like to be added.**
Pretty simple just alerts you when your armor durability is below a certain point it could be customizable maybe idk i just forget sometimes lmao.

**Is your feature request related to a problem? Please describe.**
No.

**Additional context**
Elementars has this so i just thought id suggest it here.

**Comment by John200410** [comment]
This is already in RusherHack. Chat -> ArmorAlert

**Comment by Oecher1** [comment]
> This is already in RusherHack. Chat -> ArmorAlert

oh didn't see sorry
