### ISSUE TITLE
Restart notifs that send you a text. PLUS ONLY

### ISSUE THREAD

**Issue by ongoingotrich** [John200410/rusherhack-issues#313]
Just sends a Text msg to your number when 2b2t is restarting. Would be a plus feature.

**Comment by Floppinqq** [comment]
already have

**Comment by FarmerJoe2b2t** [comment]
lolritterbot already has discord notifications that can mention a role, just add it to a private server

**Comment by tycrek** [comment]
> 
> 
> lolritterbot already has discord notifications that can mention a role, just add it to a private server

This is definitely the way to go. Any sort of SMS service would be an added cost to John (using something like Twilio).

**Comment by John200410** [comment]
I have no intention of adding this.
