### ISSUE TITLE
[FEATURE] Move While in GUI's

### ISSUE THREAD

**Issue by SilverEyes100** [John200410/rusherhack-issues#317]
A Feature will allow you to move while in GUI's
 
Kami Blue has this feature. In GUI's such as your inventory GUI, you can no longer move your player. What this feature will do is it will allow you still to move even when in user interfaces.

Example of certain Graphical User Interfaces which stop your players motion -
•Inventory 
•Chest
•Ender Chest
•Crafting Table
•Furnace
•Dropper
•Hopper
•Shulker Boxes

**Additional context**
•Chat will not be affected by this mod as you need to use your key board to type

**Comment by Floppinqq** [comment]
InventoryMove? if it is, already have, lol.

**Comment by Floppinqq** [comment]
![image](https://user-images.githubusercontent.com/76592418/103717190-9e5b9e00-4fa3-11eb-9be2-5d945c3d464f.png)

**Comment by SilverEyes100** [comment]
> InventoryMove? if it is, already have, lol.

Lol my bad
