### ISSUE TITLE
[FEATURE] ViewModel Hand 

### ISSUE THREAD

**Issue by ItzDawnfall** [John200410/rusherhack-issues#319]
**What feature would you like to be added.**
A setting under ViewModel where you can toggle if you want your viewmodel setting to apply to your hand

**Additional context**
I prefer the viewmodel not applying to my hand, an example is below of what it currently is like. 
![image](https://user-images.githubusercontent.com/35278501/103728951-29cd3300-4f94-11eb-9dcf-df3c60c24e83.png)
![image](https://user-images.githubusercontent.com/35278501/103728964-2e91e700-4f94-11eb-8a79-5e8ccce98c92.png)

**Comment by y4ndex1** [comment]
agreed

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
This has been added and will appear in the next update.
