### ISSUE TITLE
[BUG] AutoTool With Cobwebs

### ISSUE THREAD

**Issue by Oecher1** [John200410/rusherhack-issues#32]
**Describe the bug**
Was pvping and trying to mine cobwebs and saw autotool doesn't switch to sword for cobwebs which makes it a little harder with selfweb pvpers this isn't a major issue but might aswell report it.

**To Reproduce**
Steps to reproduce the behavior:  Place a cobweb have a sword in your hotbar and it wont switch to it when mining the cobweb.

**Other mods**
List other forge mods you are using (if any): Future, Potentia, Elementars, Germa, Optifine, Baritone.

**Expected behavior**
To switch to sword when mining cobwebs.

**Screenshots**

**Additional context**
Was pvping and saw it doesn't switch to sword for cobwebs.

**Comment by John200410** [comment]
Thank you for reporting this

**Comment by John200410** [comment]
Just fixed this. Will be in the next update
