### ISSUE TITLE
[FEATURE] HotbarReplenish All

### ISSUE THREAD

**Issue by ItzDawnfall** [John200410/rusherhack-issues#320]
**What feature would you like to be added.**
A toggleable setting where when on, it will continue to refill any item/block instead of just the few selectable 

**Additional context**
I'm a builder on 2b2t so I often have to transfer items from my inventory to my hotbar to continue my build. This could be easier, minimizing the amount of times I need to go back to my inventory. Pyro has a module similar to this called "Refill".

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by jumboman32** [comment]
Merging
