### ISSUE TITLE
[FEATURE] AutoEat OnBurning Setting

### ISSUE THREAD

**Issue by ToxicAven** [John200410/rusherhack-issues#324]
**What feature would you like to be added.**
A Setting for AutoEat that will eat Golden Apples When Burning.

**Is your feature request related to a problem? Please describe.**
When AutoWalking on highways, you can fall into lava/walk through lava. having this on will prevent armor damage.

**Additional context**
Maybe make it an extension module of GoldenApple Mode

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
This has been added in the next update.
