### ISSUE TITLE
[BUG] AutoTool prioritises inventory over hotbar

### ISSUE THREAD

**Issue by Azrn** [John200410/rusherhack-issues#325]
**Describe the bug**
If a player, with the AutoTool module turned on, tries to mine a block with one pickaxe in the hotbar and one in the inventory, the AutoTool module favors the pickaxe in the inventory. The AutoTool also switches to the pickaxe in your inventory even if that pickaxe has worse enchantments than the one in your hotbar.

**To Reproduce**
Have one pickaxe in your hotbar and another in your inventory. Try to mine a block with nothing in your hand. The AutoTool will place the pickaxe from your inventory in your hotbar instead of choosing the pickaxe which is already in your hotbar.

**Expected behavior**
The AutoTool should instead choose the pickaxe that is already in your hotbar or the pickaxe which has the best enchantments.

**Video to show bug**
https://user-images.githubusercontent.com/42968785/104054210-f76a4280-51ec-11eb-86fd-c5fd9e4931e7.mp4

**Comment by John200410** [comment]
Thank you for reporting this.

**Comment by John200410** [comment]
This has been fixed in the next update.

https://rusherhack.org/i/57evf8vjx7.mp4
