### ISSUE TITLE
[FEATURE] NoSlow with AutoWalk does not work while eating

### ISSUE THREAD

**Issue by tycrek** [John200410/rusherhack-issues#326]
**Describe the bug**

NoSlow (Item, Strict, and 2b2t enabled) still slows down while eating food with AutoWalk. Walking normally with the W key works as expected.

**To Reproduce**

1. Turn on NoSlow with Item, Strict, and 2b2t enabled
2. Try to eat while moving with AutoWalk

**Other mods**

- Kami Blue (sort of)

**Expected behavior**

- Don't slow down kek

**Comment by John200410** [comment]
Thank you for reporting this. I believe this is related to #312

**Comment by John200410** [comment]
This has been fixed.
