### ISSUE TITLE
[BUG] potion effect hud element not showing the effect tier

### ISSUE THREAD

**Issue by Badinek** [John200410/rusherhack-issues#329]
**Describe the bug**
i was next to 5 beacons with some effect (i think it was haste II speed II  resistance II strenght II and others) and the rusherhack potion effect hud element said these effects are only I tier (haste I speed I resistance I strenght I) 

**To Reproduce**
enable rusherhack potion effects in hud and stand next to the beacon, for some reason it says only tier I

**Other mods**
atom and forgehax (i use only one module in forgehax and i dont think it would break it) optifine baritone

**Expected behavior**
i expect the hud element to show the correct tier

**Screenshots**
in this screenshot im standing next to the beacon, in inventory it says speed, strenght, resistance and haste II but in rusherhack hud element its all tier I https://imgur.com/a/r2piH1B

**Comment by John200410** [comment]
Thank you for reporting this.

**Comment by John200410** [comment]
This has been fixed. Also changed formatting a bit.

![image](https://user-images.githubusercontent.com/43681932/104259528-98f0ce80-544f-11eb-8f84-c3d277184764.png)
