### ISSUE TITLE
[BUG] NoRender > Weather still shows droplets on the ground and plays rain sounds

### ISSUE THREAD

**Issue by tycrek** [John200410/rusherhack-issues#33]
**Describe the bug**
NoRender > Weather still shows droplets on the ground and plays rain sounds.

**To Reproduce**
Turn on NoRender Weather and wait for rain

**Other mods**
Too many to count but others have had this issue as well before the Issues repo existed

**Expected behavior**
Don't see droplets

**Screenshots**
![](https://cdn.discordapp.com/attachments/756243703139401770/763928719839723560/unknown.png)

**Additional context**
I'm hungry

**Comment by John200410** [comment]
Thank you for reporting this bug.

**Comment by John200410** [comment]
This has been fixed in the next update.
