### ISSUE TITLE
[FEATURE] “Activate at Y” Setting for Avoid (Void)

### ISSUE THREAD

**Issue by jumboman32** [John200410/rusherhack-issues#330]
**What feature would you like to be added.**
Make it an option to only activate antivoid at a lower Y level so it isn't triggered if you fly over a void hole and it sends you into the sky.

**Comment by John200410** [comment]
I will add a hard coded check to just check if the player is below y level 5.

**Comment by John200410** [comment]
This has been done and will appear in the next update.
