### ISSUE TITLE
[BUG] (Main Menu) Alt-Manager stucks with Replaymod

### ISSUE THREAD

**Issue by rockeZZergon** [John200410/rusherhack-issues#333]
![image](https://user-images.githubusercontent.com/64991049/104168556-e4cb5580-5406-11eb-83ea-8f8590fb6a31.png)
There is 2 button at the same position, so when i click it, 2 windows open (first rusherhack, and then replay mod), and only when i press ESC, alt manager close. Alt-manager button overrides Replay-mod button.
![image](https://user-images.githubusercontent.com/64991049/104168665-12b09a00-5407-11eb-88d9-e861104875da.png)

**Comment by John200410** [comment]
There's nothing I can do about this. There are differences in the button placement code depending on what version of ReplayMod you use. So if I fix it on my version of ReplayMod, it may not fix it for yours. You can just disable the alt manager button.
