### ISSUE TITLE
[BUG] Coping 

### ISSUE THREAD

**Issue by CaptainTheBeam** [John200410/rusherhack-issues#336]
**Describe the bug**

John needs to learn to cope when he’s wrong and not baby rage and mute me 

**To Reproduce**

Win an argument against john 

**Other mods**
List other forge mods you are using (if any):

not rusherhack

**Expected behavior**

You to get muted 

**Screenshots**

idc

**Additional context**

**Comment by Crystallinqq** [comment]
Still unfixed. No reason to close.
