### ISSUE TITLE
[FEATURE] EChest Farmer

### ISSUE THREAD

**Issue by WarriorCrystal** [John200410/rusherhack-issues#337]
**What feature would you like to be added.**
A detailed explanation of what this feature should be.
A module that places echests and breaks them

**Is your feature request related to a problem? Please describe.**
i don't want to farm echest mannually

**Additional context**

**Comment by John200410** [comment]
I plan on making an AutoFarm module, maybe I could add a mode for ender chests.

**Comment by Mishi04** [comment]
lol

**Comment by Ozynt** [comment]
This issue will be merged into #679
