### ISSUE TITLE
[FEATURE] Basefinder on foot should use baritone

### ISSUE THREAD

**Issue by lupettohf** [John200410/rusherhack-issues#339]
As the title says, some servers don't allow elytra on foot basefinder is dumb af.

if baritone is present
baritone_abasefinder

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by lupettohf** [comment]
Thanks for your support.

**Comment by John200410** [comment]
Did you mean to close this?

**Comment by lupettohf** [comment]
> Did you mean to close this?

Sorry hit close with comment.

**Comment by jumboman32** [comment]
Merged with #892
