### ISSUE TITLE
[FEATURE] AutoEXP Improvements

### ISSUE THREAD

**Issue by notperry1234567890** [John200410/rusherhack-issues#34]
**What feature would you like to be added.**
First of all lets say you run out of exp when that happens the autoexp does nothing it wont put back armor and will stay on so like maybe make it if you run out of exp just make it put back on your armor and toggle off and say you don't have any exp left. Second if possible can you make autoexp automatically grab exp out of your inventory and put it in a certain slot maybe that slot it changes to could be customizable or something idk i was just pvping and ran out of exp and saw it doesn't put your armor back on just sits there so kinda makes it a bit harder when using it cause if you run out of exp you gotta toggle it off and put your armor back on.

**Is your feature request related to a problem? Please describe.**
Eh not really related to a "problem".

**Additional context**
Pvping and was just suggesting small things that could help.

**Comment by Oecher1** [comment]
> **What feature would you like to be added.**
> First of all lets say you run out of exp when that happens the autoexp does nothing it wont put back armor and will stay on so like maybe make it if you run out of exp just make it put back on your armor and toggle off and say you don't have any exp left. Second if possible can you make autoexp automatically grab exp out of your inventory and put it in a certain slot maybe that slot it changes to could be customizable or something idk i was just pvping and ran out of exp and saw it doesn't put your armor back on just sits there so kinda makes it a bit harder when using it cause if you run out of exp you gotta toggle it off and put your armor back on.
> 
> **Is your feature request related to a problem? Please describe.**
> Eh not really related to a "problem".
> 
> **Additional context**
> Pvping and was just suggesting small things that could help.

oh and also if you can make it throw the exp faster cause it throws slower then even using fastexp in the gui

**Comment by John200410** [comment]
If you use AutoArmor then this should not be a problem. I will still make it throw EXP faster.
