### ISSUE TITLE
[FEATURE] 1.8 Sword Blocking

### ISSUE THREAD

**Issue by clockwork04** [John200410/rusherhack-issues#340]
**What feature would you like to be added.**
A detailed explanation of what this feature should be.

when right-clicking with a shield equipped instead of having a shield in your view the item your holding is tilted towards your face resembling old pre-1.9 sword blocking

**Is your feature request related to a problem? Please describe.**

Shields block the player's view worse than a sword while blocking (especially while active), and walking around with a shield taking up the bottom left corner of your view 24/7 is fucking annoying (shield hide just makes it worse as then I forget I have it equipped in the first place)  

**Additional context**

If you would like to see a working example of this i believe impact has it as a feature

**Comment by John200410** [comment]
This is already in the client.
