### ISSUE TITLE
[FEATURE] Baritone with ElytraFly

### ISSUE THREAD

**Issue by Floppinqq** [John200410/rusherhack-issues#341]
a method to be able to use baritone with elytrafly

**Comment by CursedEvolve** [comment]
i would love this

**Comment by Avanatiker** [comment]
Good luck rewriting the whole baritone code lol. Pathfinding is only for walking

**Comment by Avanatiker** [comment]
Its not even supporting horse riding ;)

**Comment by CursedEvolve** [comment]
i mean like i dont think john has a life lmao, he prolly just codes rusherhack and casually play 2b.

**Comment by John200410** [comment]
https://github.com/cabaletta/baritone/issues/
