### ISSUE TITLE
[FEATURE] nametags Y offset

### ISSUE THREAD

**Issue by Badinek** [John200410/rusherhack-issues#343]
**What feature would you like to be added.**
setting under nametags to vertically change the position of them

**Is your feature request related to a problem? Please describe.**
not related to rusherhack but i use other clients image esp (replaces player models with images) and the nametags overlap with the image a bit so yeah

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
This has been added in the next update.
