### ISSUE TITLE
[FEATURE] Easy Pearl

### ISSUE THREAD

**Issue by WarriorCrystal** [John200410/rusherhack-issues#347]
**What feature would you like to be added.**
A detailed explanation of what this feature should be.
A module that throws a epearl when the keybind is pressed

**Is your feature request related to a problem? Please describe.**

**Additional context**
a inventoy mode that switches a slot of your hotbar with epearls then it throws the pearl and puts the old item in that slot back

**Comment by John200410** [comment]
This is already in the client. MiddleClick -> Pearl
