### ISSUE TITLE
[FEATURE] Mob/Entity Notifier

### ISSUE THREAD

**Issue by MrHakan** [John200410/rusherhack-issues#349]
**What feature would you like to be added.**
Mob/Entity Notifier 
plays a sound when selected mob/entity cames into render distance

**Is your feature request related to a problem? Please describe.**

It will help for finding mobs/entities

**Comment by John200410** [comment]
I plan on adding the ability for Search to search for entities, I guess I will just add a Sound setting.

**Comment by John200410** [comment]
This has been added in the next update.
