### ISSUE TITLE
[FEATURE] Quiver

### ISSUE THREAD

**Issue by notperry1234567890** [John200410/rusherhack-issues#35]
**What feature would you like to be added.**
Basically you got bow and strength and speed arrows it will automatically shoot them above you ofc not fully drawn just a bit so it goes down fastly and hits you but also makes it so it puts like weakness arrows or other crap in your crafting slots so it doesn't shoot yourself with bad effects arrows you don't have to add this but it just seems useful.

**Is your feature request related to a problem? Please describe.**
Not really a "problem".

**Additional context**
Idk just saw pyro users using it and it does seem useful in some cases.

**Comment by gcurtiss** [comment]
Thanks for your suggestion. You can achieve this with BowSpam currently. I'll be leaving the issue open for @John200410 to decide on, but I don't believe this is necessary.

**Comment by John200410** [comment]
Will need a better name for this.

**Comment by ProfKambing** [comment]
oh nvm

**Comment by John200410** [comment]
This has been added in the next update.
