### ISSUE TITLE
[FEATURE] AutoTrade

### ISSUE THREAD

**Issue by MrHakan** [John200410/rusherhack-issues#350]
**What feature would you like to be added.**
Automaticly trades with villagers

*autotrade set rotten_flesh_to_emerald

*autotrade set chicken_to_emerald

**Is your feature request related to a problem? Please describe.**
It will save time while trading with villagers

**Comment by John200410** [comment]
Thank you for the suggestion. I will most likely add this as a setting under AutoCraft.

**Comment by FluorideHistorian** [comment]
this has been added in the next update
![autotrade](https://user-images.githubusercontent.com/68972754/177057172-60b1a40c-8ae2-4050-9a4b-81c9a38a9ee8.PNG)

**Comment by TwoThreeTwo** [comment]
WOOOOOOOOOOOOOOOOOOOOOO

**Comment by MrHakan** [comment]
Bruh 2 years ago

**Comment by TwoThreeTwo** [comment]
Uwu mommy

**Comment by vhakan** [comment]
naber
