### ISSUE TITLE
[Search for Modules]

### ISSUE THREAD

**Issue by YeahOMA** [John200410/rusherhack-issues#351]
I would like some sort of Search bar to be added to RusherHack as it is very hard to locate modules.

Basically whenever you search for a module the best suiting module will remain on the ClickGUI, all the modules that don't fit the search will dissapear. KAMIBlue has a search bar like this.

Sort of, it'll be much easier to search and find modules.

**Comment by browsky300** [comment]
Yeah, this would be really useful. Just wondering, do you mean like a separate search bar as in inertia, or where you just type the name in and it highlights the modules, as in Impact?

**Comment by YeahOMA** [comment]
Anything will be fine.

**Comment by browsky300** [comment]
Nevermind, someone already suggested this feature and John will be adding it.
Duplicate of #251.

**Comment by John200410** [comment]
Duplicate of #251
