### ISSUE TITLE
[BUG] Spammer does not read Unicode characters properly

### ISSUE THREAD

**Issue by tycrek** [John200410/rusherhack-issues#353]
**Describe the bug**

When using Unicode characters in a spammer file, they do not show the same as when copy/pasted

![image](https://user-images.githubusercontent.com/29926144/104642795-9ddc9a80-5668-11eb-94dc-d14e084b71e5.png)

**Comment by John200410** [comment]
Unable to reproduce.

![image](https://user-images.githubusercontent.com/43681932/105419971-90e21d00-5c0d-11eb-8ec5-8ef8891d1320.png)

What Unicode character are you trying to use? Does it work when you create the file with the `*spammer file create` command?
