### ISSUE TITLE
[FEATURE] World Downloader

### ISSUE THREAD

**Issue by Endit32** [John200410/rusherhack-issues#355]
**World Downloader**
A module that simply downloads loaded chunks when enabled.

**Only one mod out there that does this.**
No client that I know of has this module, plus the only other mod out there that does this has pretty shit compatibility.

**Comment by Natan515** [comment]
There is a mod for this... Adding this is a real waste of time

**Comment by racoonersssss** [comment]
> There is a mod for this... Adding this is a real waste of time

fax

**Comment by John200410** [comment]
There are standalone forge mods for this.

**Comment by vNeonCode** [comment]
Question.. anyone have the link for the 1.12.2 one? Or any 1.12.2 forge world downloader mod?

**Comment by Natan515** [comment]
U know u can just delete the comments right?

**Comment by jumboman32** [comment]
http://www.mc-mod.net/world-downloader-mod/
