### ISSUE TITLE
[FEATURE] Anchor

### ISSUE THREAD

**Issue by SewerHatch** [John200410/rusherhack-issues#358]
I suggest a setting to step module that gonna nullify your momentum and pull toward a hole when you jump above it. Currently reverse step only works when you are on ground which isnt rlly helpful in cpvp

**Comment by John200410** [comment]
Thank you for the suggestion. I'm probably just going to add another setting to step for this instead of building it into Reverse.

**Comment by John200410** [comment]
This has been added in the next update.
