### ISSUE TITLE
[BUG] Inventory on top of player list

### ISSUE THREAD

**Issue by ItzDawnfall** [John200410/rusherhack-issues#359]
**Describe the bug**
When you have the inventory on, it is shown over the Tab list and blocks certain players

**To Reproduce**
Steps to reproduce the behavior: 1. Turn on inventory from HUD Manager and drag it to near the top of the screen 2. Press Tab

**Other mods**
List other forge mods you are using (if any): ReplayMod (not in a replay), OptiFine, Schematica, Journeymap, LunatriusCore

**Expected behavior**
Tab keeps inventory under the player list so I can properly see

**Screenshots**
![image](https://user-images.githubusercontent.com/35278501/104831604-61af6280-583f-11eb-9c47-c86d9920193a.png)

**Comment by John200410** [comment]
This has been fixed in the next update:
![image](https://user-images.githubusercontent.com/43681932/110889447-2029b980-82bc-11eb-9167-c7f88ab52160.png)
