### ISSUE TITLE
[FEATURE] Anchor

### ISSUE THREAD

**Issue by Oecher1** [John200410/rusherhack-issues#36]
**What feature would you like to be added.**
Basically if your like speeding over a hole it will stop all movement over a hole and is kinda useful but idk and probably make a option like toggle off in hole or something im too tired to explain that well lmao.

**Is your feature request related to a problem? Please describe.**
No not a "problem".

**Additional context**
Just requesting some of pyros features to be in rusherhack cause why not xd.

**Comment by gcurtiss** [comment]
Thanks for your suggestion. This is a little vague, could you please explain more once you're more able to do so? Cheers.

**Comment by Oecher1** [comment]
> Thanks for your suggestion. This is a little vague, could you please explain more once you're more able to do so? Cheers.

Basically when you go over a hole it will stop you from moving until you land in the hole

**Comment by John200410** [comment]
Thank you for the suggestion

**Comment by John200410** [comment]
After second thought I am not sure if this is worth adding due to there being an alternative (reverse step). Feel free to change my mind by commenting.

**Comment by Oecher1** [comment]
> After second thought I am not sure if this is worth adding due to there being an alternative (reverse step). Feel free to change my mind by commenting.

nah its fine i don't need it was just suggesting stuff
