### ISSUE TITLE
[FEATURE] Targethud

### ISSUE THREAD

**Issue by fawwaz1234** [John200410/rusherhack-issues#360]
Create an additional square that contains 

viewmodel of targeted player
health of targeted player
totempop of targeted player
armor durability of targeted player
inventory of targeted player

this will give alot of info to the user (rusherhack user) and possibly win fight because of this feature

**Comment by MrHakan** [comment]
and strength , weakness timer

**Comment by John200410** [comment]
What advantage does this give over just using Nametags?
