### ISSUE TITLE
[FEATURE] Aura custom delay

### ISSUE THREAD

**Issue by GentelWither** [John200410/rusherhack-issues#365]
U should add kill aura custom delay so that we type *aura delay {delay in mille second} or make a slider in the clickgui with custom values that will be great if u did it

**Comment by John200410** [comment]
What for? You can already disable the hit delay.

**Comment by GentelWither** [comment]
No i mean custom slider delay in milie seconds cuz it lags sometimes

في الأحد، ٢٤ يناير، ٢٠٢١ ١١:١٥ م John <notifications@github.com> كتب:

**Comment by John200410** [comment]
If the server is lagging you can enable the TPS Sync setting.
