### ISSUE TITLE
[FEATURE] combat and movement and misc mods

### ISSUE THREAD

**Issue by crackcocacola** [John200410/rusherhack-issues#367]
so anvil aura and bed aura which needs no explanation, make reverse step a actual module bcuz that would be cool, add more hud options like InvInfo aka PvPResources like pyro and konas and add a target hud that isnt broken that shows if they have strength and if possible how long and shows the armor and dura ofc and if they r able to be citied or be able to use bed aura on and shows a little message if their armor is low, also I dont have plus so idk if its a feature in the module but when you release Item View Model you should add offhand swing like Xulu bcuz thats cool and also add a small welcomer bcuz thats cool and let us hide specific modules in Array List if we cant do that already and this is very cool thing

**Comment by John200410** [comment]
This is very hard to read. Please reopen an issue with readable English.
