### ISSUE TITLE
[FEATURE] NoRender Settings

### ISSUE THREAD

**Issue by charlie9181** [John200410/rusherhack-issues#369]
Would like to request an option added under chams->wireframe to not render fire on other players and also not render items in other players’ hands.

**Comment by John200410** [comment]
Thank you for the suggestions.

**Comment by John200410** [comment]
I think these settings would fit better in NoRender.

**Comment by John200410** [comment]
OnFire and HeldItem settings have been added to NoRender Entities group in the next update.
