### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by KrispyBigPvp** [John200410/rusherhack-issues#37]
**What feature would you like to be added.**
A detailed explanation of what this feature should be. make it so it says rusherhack instead of minecraft on the title screen

**Is your feature request related to a problem? Please describe.**
no

**Additional context**
ok

**Comment by gcurtiss** [comment]
Thanks for your suggestion. However, this isn't achievable with a mod. You can make a texture pack that does this instead.

**Comment by John200410** [comment]
This is achievable with a mod but I have no plans of adding this
