### ISSUE TITLE
[BUG] MentionHighlight resets formatting

### ISSUE THREAD

**Issue by hashalite** [John200410/rusherhack-issues#370]
**Describe the bug**
When MentionHighlight is enabled, messages containing your username are reset to default formatting/colors.  This can make death messages look strange.

**To Reproduce**
Die on a server with colored death messages.

**Expected behavior**
Only the username color is changed, not the rest of the message.

**Comment by John200410** [comment]
Thank you for reporting this.

**Comment by John200410** [comment]
This has been fixed in the next update.
![image](https://user-images.githubusercontent.com/43681932/113056618-02909700-917a-11eb-99cf-4846db0bdd12.png)
