### ISSUE TITLE
[FEATURE] Average Speed Reading

### ISSUE THREAD

**Issue by ItsYesnik** [John200410/rusherhack-issues#372]
I think an average speed reading would be cool. So that way we can tell the average KPH we go in a time frame is. Maybe have a way to restart the count/interval too so that way it can be cleared to restart the average. (I am curious as to my average speed per hour given the eFly lagbacks and such)

**Comment by John200410** [comment]
Thank you for the suggestions.

**Comment by John200410** [comment]
This has been added in the next update:

https://rusherhack.org/i/wglpwikn4n.mp4
