### ISSUE TITLE
[FEATURE] Declutter HUD with keybind

### ISSUE THREAD

**Issue by CorruptedSeal** [John200410/rusherhack-issues#377]
**What feature would you like to be added.**
Option to declutter/drop the HUD elements with a **keybind** during a screenshot (option to remove all elements including tab gui/ option to remove everything but coords).

**Is your feature request related to a problem? Please describe.**
When taking a screenshot you can only remove elements individually or drop everything with F1. Feature would allow the player to quickly remove RusherHack HUD elements for screenshots.

**Additional context**
N/A

**Comment by John200410** [comment]
I can probably just make the Hud module toggleable.

**Comment by John200410** [comment]
This has been done in the next update.
