### ISSUE TITLE
[FEATURE] NoRender additions

### ISSUE THREAD

**Issue by Papa-Quill** [John200410/rusherhack-issues#385]
**What feature would you like to be added.**
NoRender projectiles - wither skull projectiles, snowballs, ender pearls, arrows, fire charges, thrown potions. Make sure you can choose to disable specific ones like if someone only wants no render wither skulls.
NoCluster - Changes the opacity of entities when inside your player, making it easier to see when there are multiple people in one hole. Make the opacity controllable through a slider and an option to make armor disappear as well when inside a player. 
NoRender Mobs - have an option to no render passives, friendly, hostile, bosses, and useless mobs.
Useless mobs would be bats, rabbits, parrots.
NoRender liquid - removes water and lava from rendering
NoRender beacon beams - The beam that comes from activated beacons
NoRender XP - Bottles and orbs

**Comment by John200410** [comment]
Thank you for the suggestions.

**Comment by jumboman32** [comment]
+Potion Particles

**Comment by John200410** [comment]
Projectiles, Liquid, BeaconBeam, XP, and NoCluster settings have been added in the next update. I don't think the other things are too necessary.
