### ISSUE TITLE
AutoSwitch/hotbar randomizer

### ISSUE THREAD

**Issue by MrNooner** [John200410/rusherhack-issues#386]
**What feature would you like to be added.**
Randomly places blocks from your hotbar. great for building truly random paths, decoration patterns or anything else.

Is your feature request related to a problem? Please describe.
wurst is the only client with it and fuck wurst

Additional context
would be based

**Comment by John200410** [comment]
This seems to niche to be a good fit in rusherhack. May re-open if people disagree.
