### ISSUE TITLE
[FEATURE] Search Color Customization

### ISSUE THREAD

**Issue by hashalite** [John200410/rusherhack-issues#391]
**What feature would you like to be added.**
As far as I can tell, there is no way to set separate colors for different search blocks, making it difficult to distinguish between them.  Future's solution to this problem is having pre-set colors for each block, so the player doesn't need to set them manually.  I think a better solution would be to offer a `*search gui` where the player can add/remove blocks and customize colors.

**Is your feature request related to a problem? Please describe.**
I cannot distinguish different blocks when using the search module.

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
I will also have the default colors set to the color of the block, defined by the color that appears on maps.

**Comment by hashalite** [comment]
> defined by the color that appears on maps.

Some blocks are transparent on maps, including nether portals.  You should probably hard code colors for them

https://minecraft.fandom.com/wiki/Map_item_format#Color_table

**Comment by John200410** [comment]
This has been added in the next update: https://www.youtube.com/watch?v=_jSb3Br1fiE
