### ISSUE TITLE
[BUG] Far end of tracers bobbing

### ISSUE THREAD

**Issue by hashalite** [John200410/rusherhack-issues#394]
**Describe the bug**
If view bobbing is enabled, the ends of the tracers (the part connected to the player, not the crosshair) bob up and down with movement.

**To Reproduce**
1. Enable view bobbing
2. Set tracers to body (it is most visible in this mode)
3. *fakeplayer
4. Run around and observe the far end of the tracer

**Other mods**
Optifine

**Expected behavior**
Tracers remain at the same position on the player regardless of view bobbing.

**Screenshots**
[https://www.youtube.com/watch?v=plgDs4hat00](https://www.youtube.com/watch?v=plgDs4hat00)

**Comment by John200410** [comment]
Thank you for reporting this.

**Comment by John200410** [comment]
This has been fixed in the next update.
