### ISSUE TITLE
[BUG] AutoEXP doesn't work with other languages 

### ISSUE THREAD

**Issue by ItzDawnfall** [John200410/rusherhack-issues#395]
**Describe the bug**
AutoEXP says there is no mending on the armor if Mending is in another language 

**To Reproduce**
Change language to where mending is different, degrade armor, turn on AutoEXP 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by John200410** [comment]
Thank you for reporting this.

**Comment by John200410** [comment]
This has now been fixed.
