### ISSUE TITLE
[FEATURE] ViewModel Rotate for each axis

### ISSUE THREAD

**Issue by tycrek** [John200410/rusherhack-issues#396]
**What feature would you like to be added.**

Instead of one slider for all 3 axis, each axis should have an individual slider. The slider should be hidden if the axis is not enabled.

![image](https://user-images.githubusercontent.com/29926144/106177466-c4fd9680-6155-11eb-88cd-643b455b6c90.png)

**Comment by John200410** [comment]
Thank you for the suggestion.

I will probably just remove the toggles and only have the sliders, since rotating 0 degrees won't change anything anyway.

**Comment by tycrek** [comment]
ahhh good idea

**Comment by John200410** [comment]
This has been done and will be in the next update.

https://rusherhack.org/i/ef6camd9my.mp4
