### ISSUE TITLE
[FEATURE/BUG?] Smarter AntiHunger

### ISSUE THREAD

**Issue by tycrek** [John200410/rusherhack-issues#397]
**What feature would you like to be added.**

AntiHunger works great for movement but causes issues while mining blocks. It could be improved by implementing a method similar to [Kami Blue](https://github.com/kami-blue/client/blob/2b6483655b4f0faa68b9a7905670bfe146b80cf4/src/main/java/me/zeroeightsix/kami/module/modules/movement/AntiHunger.kt#L32) where it does not apply AntiHunger while the player is mining.

**Comment by John200410** [comment]
Thank you for the suggestion. I am going to close #335 in favor of this.

**Comment by John200410** [comment]
This has now been added.
