### ISSUE TITLE
[FEATURE] Add an AutoDisable Feature onto AutoFish.

### ISSUE THREAD

**Issue by Jopplo** [John200410/rusherhack-issues#398]
**What feature would you like to be added.**
It simply put, auto disables AutoFish whenever a fishing rod gets below a set duriblity.

**Is your feature request related to a problem? Please describe.**
I feel it could be insanely useful for new people on anarchy servers if they have a good rod but it just doesn't have mending yet.

**Additional context**
I've never seen this before, but it may already exist.

**Comment by NovaGits** [comment]
cool suggestion

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
This has been added and will be in the next update.
