### ISSUE TITLE
[FEATURE] MobSpawn

### ISSUE THREAD

**Issue by sa6ta6ni6c** [John200410/rusherhack-issues#399]
**What feature would you like to be added.**
It highlights places where mobs can spawn. 

**Is your feature request related to a problem? Please describe.**
N/A

**Additional context**
Pretty useful tho

**Comment by John200410** [comment]
Thank you for the suggestion. I will probably add this as a setting under ESP.

**Comment by John200410** [comment]
Just noticed that this is a duplicate of #45
