### ISSUE TITLE
Step timer bug 2

### ISSUE THREAD

**Issue by ignelias** [John200410/rusherhack-issues#40]
when you use 2 block step with timer on, timer stays on for about a second after you are done doing the 2 block step

**Comment by tycrek** [comment]
Duplicate of #39

**Comment by ignelias** [comment]
it's not

**Comment by John200410** [comment]
It is indeed a duplicate of #39

**Comment by John200410** [comment]
Nevermind its not, but they should be combined instead of making two separate issues.

**Comment by John200410** [comment]
This has been fixed in v1.1
