### ISSUE TITLE
[FEATURE] TargetStrafe

### ISSUE THREAD

**Issue by sa6ta6ni6c** [John200410/rusherhack-issues#400]
**What feature would you like to be added.**
Jumps around a nearby player, useful for pvp

**Is your feature request related to a problem? Please describe.**
N/A

**Additional context**
N/A

**Comment by jennifer-uwu** [comment]
how would this be useful for pvp? jumping will make it very easy for the other player to crystal you

**Comment by John200410** [comment]
This doesn't sound useful at all.

**Comment by 25iscool** [comment]
TargetStrafe is used to break other clients kill auras. 1.8 clients utilise this alot
