### ISSUE TITLE
[FEATURE] Hunt

### ISSUE THREAD

**Issue by sa6ta6ni6c** [John200410/rusherhack-issues#402]
**What feature would you like to be added.**
Uaing barirone to attack nearby players/hostile mobs/passive mobs/neutral mobs - could be configured

**Is your feature request related to a problem? Please describe.**
N/A

**Additional context**
N/A

**Comment by jennifer-uwu** [comment]
#follow command and killaura

**Comment by John200410** [comment]
You can easily use a combination of Baritone's #follow command and Aura to achieve the same thing.
