### ISSUE TITLE
[FEATURE] Unicode support

### ISSUE THREAD

**Issue by sa6ta6ni6c** [John200410/rusherhack-issues#403]
**What feature would you like to be added.**
A detailed explanation of what this feature should be.

**Is your feature request related to a problem? Please describe.**

**Additional context**

**Comment by John200410** [comment]
Unicode support for what?

**Comment by sa6ta6ni6c** [comment]
Hud elements unicode support

**Comment by John200410** [comment]
I still don't know what you mean by that.
