### ISSUE TITLE
[FEATURE] elytrafly animation in elytrafly2b2t

### ISSUE THREAD

**Issue by gargamelius** [John200410/rusherhack-issues#404]
**What feature would you like to be added.**
I would like an option in elytrafly2b2t that reders it like you are flying with an elytra. Kami blue does that and it looks pretty cool.

**Is your feature request related to a problem? Please describe.**
It just looks really wierd to be walking on air.

**Additional context**

**Comment by John200410** [comment]
Packet mode works by spamming elytra open packets, so you are never actually in elytra flight for more than a tick.
