### ISSUE TITLE
[FEATURE] Automatic ElytraFly2b2t Highway Travel

### ISSUE THREAD

**Issue by Quelcom1** [John200410/rusherhack-issues#406]
**What feature would you like to be added.**
The feature is where it automatically travels down a highway - avoiding blocks, etc.
Also, if the barrier cannot be flew past then a automining the barrier could also be helpful.
**Is your feature request related to a problem? Please describe.**
it's annoying when travelling down highway and some person places one block in the middle of the highway, which stops my autowalk. this feature would prevent that, and the automatic travel would just go to the right slightly.

**Comment by John200410** [comment]
Not sure if this would be worth the time to add.

**Comment by jumboman32** [comment]
This is now irrelevant. Should probably close it.
