### ISSUE TITLE
[FEATURE] PacketLogger GUI

### ISSUE THREAD

**Issue by hashalite** [John200410/rusherhack-issues#407]
**What feature would you like to be added.**
A `*packetlogger gui` command that provides an interface for toggling visibility for each packet.  Could probably just be a copy of `*antipacket gui`.

**Is your feature request related to a problem? Please describe.**
Sometimes certain packets are irrelevant to what you are testing and only clutter chat.

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
I have added a window to configure this.
