### ISSUE TITLE
[FEATURE] Manual Offhand

### ISSUE THREAD

**Issue by ghost** [John200410/rusherhack-issues#409]
example: ur autototem is set to mode health and puts crystal in ur offhand.
manual offhand is important when u feel that u r not safe so u press binded key and it pauses ur autototem and put like gapple/totem in ur offhand. 

This module is also in salhack

**Comment by fawwaz1234** [comment]
if u dont understand, try using salhack's offhand so u can understand it better

**Comment by John200410** [comment]
Thank you for the suggestion. I will add a Toggle mode to Autototem that will let you press a keybind to switch between a totem and the alternative item.

**Comment by John200410** [comment]
This has been added in the next update.

**Comment by ProfKambing** [comment]
i made this suggestion lol and deleted the acc

**Comment by Mishi04** [comment]
press f for manual offhand 🤑🤑
