### ISSUE TITLE
[FEATURE] AntiVoid

### ISSUE THREAD

**Issue by Azurilex** [John200410/rusherhack-issues#41]
**What feature would you like to be added.**
If there's holes in bedrock, and you fall in, you get rubberbanded back up. Similar to NoFall on Anti mode, except made for falling in the void.

**Is your feature request related to a problem? Please describe.**
No.

**Additional context**
N/A

**Comment by John200410** [comment]
Will probably add this as a setting to NoFall.

**Comment by John200410** [comment]
This has been finished and added as the "Void" setting in Avoid, will be there next update.
