### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by GentelWither** [John200410/rusherhack-issues#419]
ever considered adding multiplace slider and fastplace slider on the auto crystal module that will be cool if added

**Comment by jennifer-uwu** [comment]
what?

**Comment by GentelWither** [comment]
multiplace ca so it places multi crystals in one time and fastplace for
placing it fast get it ?


‫في الثلاثاء، 2 فبراير 2021 في 5:01 م تمت كتابة ما يلي بواسطة
‪jennifer-uwu‬‏ <‪notifications@github.com‬‏>:‬
