### ISSUE TITLE
[FEATURE] standardized box rendering

### ISSUE THREAD

**Issue by jennifer-uwu** [John200410/rusherhack-issues#420]
Make modules that render boxes, like nuker, scaffold, autocrystal, and autotrap use a module in the client tab to draw boxes, with settings like line width, color, and fill toggle, so that the boxes look the same. This could also be toggleable if people want to have different boxes for different modules.

**Comment by John200410** [comment]
I don't really think this would be a good idea. I would like to hear other's opinions first though.

**Comment by CaptainTheBeam** [comment]
add this jonathon

**Comment by jumboman32** [comment]
color is good enough for me i think there is higher priority stuff than this and it doesn't seem very easy

**Comment by Ozynt** [comment]
Added long time ago.
