### ISSUE TITLE
[FEATURE] AutoCast / Recast for AutoFish

### ISSUE THREAD

**Issue by lifetorrent** [John200410/rusherhack-issues#425]
**What feature would you like to be added.**

An AutoCast option under AutoFish for automatic casting when switching back to a fishing rod, or after nothing has been caught for a set period of time.

**Is your feature request related to a problem? Please describe.**

Sometimes when autofishing while I'm away from my computer the server will either restart or I'll get the usual 6 hour kick and I won't be able to manually recast my fishing rod before getting kicked again. 

Also, every so often it seems that it recasts, but nothing is ever caught (no particles in the water to indicate you're waiting to catch something) which makes it seem like its in some bugged state (not entirely sure what to refer to it as). Manually recasting temporarily resolves this issue.

**Comment by John200410** [comment]
I will add an AutoCast setting.

**Comment by John200410** [comment]
This has been added in the next update.
