### ISSUE TITLE
 [FEATURE] Render on packet mine

### ISSUE THREAD

**Issue by Manesko55** [John200410/rusherhack-issues#426]
**What feature would you like to be added.**
pretty self explanatory, but when you start to mine using packet mine, it will render a box around the block you mined until it has been broken 

**Is your feature request related to a problem? Please describe.**
just a quality of life sorta thing

**Additional context**
nope very simple

**Comment by jennifer-uwu** [comment]
blocktweaks has a setting for rendering breaking

**Comment by John200410** [comment]
BreakESP module already exists.
