### ISSUE TITLE
[FEATURE] Nametags Improvement

### ISSUE THREAD

**Issue by Podrockian** [John200410/rusherhack-issues#428]
**What feature would you like to be added.**
This is a fairly minor issue, but I would like for the nametags module to be improved, with the huge gap between the player name and things like armour being removed or made adjustable.

**Is your feature request related to a problem? Please describe.**
I currently use Future and Rusherhack in combination, but I'm trying to stop using Future since Rusherhack has practically everything I need and more. However, one thing which I much prefer in Future is the nametags module. It looks good, gives all the information I need and I have no complaints, however in Rusherhack, it takes up a lot more space vertically and looks a lot worse in my opinion. [This](https://imgur.com/a/GfZZn2s) image shows that the text in Rusherhack's nametags module takes up significantly more space, which in my opinion looks a lot worse, so it would be great if there was an option to edit the size of the text and the gap between the different lines so there is less of a gap between the armour and the player name. However, the issue doesn't end there as even when the 'Simple Enchants' option is enabled, the issue of the large gap still persists, as shown in [this](https://imgur.com/KCz17Z3) image. If this gap was either removed or made adjustable that would be greatly appreciated. Also, I don't doubt you're aware of this, but just in case, I'll also add that maxed elytra aren't shown as maxed with the Simple Enchants option enabled.

**Comment by John200410** [comment]
The elytra bug with Simple Enchants has been fixed in the next update. Would that solve your issue?

**Comment by Podrockian** [comment]
> The elytra bug with Simple Enchants has been fixed in the next update. Would that solve your issue?

Yeah, it would be nice to be able to adjust the gap between the armour and the player name in nametags so they take up less space and cover over nametags less, but it's an extremely minor nitpick.
