### ISSUE TITLE
[FEATURE] Add LogOut to AutoTrap.

### ISSUE THREAD

**Issue by Jopplo** [John200410/rusherhack-issues#429]
**What feature would you like to be added.**
If someone logs out, and you enable AutoTrap with this setting enabled, then they would be trapped for when they relog.

**Is your feature request related to a problem? Please describe.**
No.

**Additional context**
Saw this on Konas and I feel like it could be really useful in pvp.

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
This has been added in the next update.

https://rusherhack.org/i/7fg8bond5a.mp4
