### ISSUE TITLE
[FEATURE] hand chams

### ISSUE THREAD

**Issue by ghost** [John200410/rusherhack-issues#43]
wireframe hand chams like the ones in ot

**Comment by John200410** [comment]
Thank you for the suggestion

**Comment by Ozynt** [comment]
Add more modes for handchams as mention in issue #1229 .

**Comment by Ozynt** [comment]
![](https://user-images.githubusercontent.com/57899270/154330928-7e524849-e278-4cd6-8a71-3d895e74c004.png)

**Comment by John200410** [comment]
Hand setting has been added to Chams in the next update.
