### ISSUE TITLE
[FEATURE] this is just a concept i dont know if its possible

### ISSUE THREAD

**Issue by fawwaz1234** [John200410/rusherhack-issues#430]
if u can place block without holding a block like scaffold, can u do like autocrystal without holding a crystal? crystal is also a block.

**Comment by FluorideHistorian** [comment]
server side its exactly the same

**Comment by jennifer-uwu** [comment]
swap -> silent

**Comment by fawwaz1234** [comment]
> silent swap mode in autocrystal settings

client side?

**Comment by John200410** [comment]
This is already in the client.
