### ISSUE TITLE
[BUG] timer tpssync

### ISSUE THREAD

**Issue by Toshimichi0915** [John200410/rusherhack-issues#431]
**Describe the bug**
Timer sometimes goes 0 for unknown reason and completely freezes the game when TPS sync is enabled (I'm sure that the server was at 16 TPS or something and i knew the server didn't crash at that time)

**To Reproduce**
Just enable timer with TPS sync enabled on 2b2t and wait for the game to be completely frozen.

**Other mods**
Future
Konas
WorldEdit
Schematica
Optifine

**Expected behavior**
Even with TPS sync, timer should not go below 0.1 (or configurable value) because the game will be completely frozen when the client thinks that the server TPS is 0 (probably because of lagspike)

**Comment by jennifer-uwu** [comment]
stop using other clients before you report a bug

**Comment by Toshimichi0915** [comment]
Obviously there should be bottom game speed limit whatever

**Comment by John200410** [comment]
Thank you for reporting this.

**Comment by John200410** [comment]
This has been fixed in the next update.
