### ISSUE TITLE
[FEATURE] *kit list

### ISSUE THREAD

**Issue by tycrek** [John200410/rusherhack-issues#434]
**What feature would you like to be added.**

Maybe it just got missed but `*kit list` to see your kits. Doesn't have to show the contents, just the names

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by tycrek** [comment]
> 
> 
> Thank you for the suggestion.

also `*kit del` to delete

**Comment by John200410** [comment]
*kit list and del arguments have been added:
![image](https://user-images.githubusercontent.com/43681932/112992250-000c4e00-9136-11eb-8046-493745d44876.png)
