### ISSUE TITLE
[FEATURE] Extratab - OnlyFriends

### ISSUE THREAD

**Issue by thebruhmoment** [John200410/rusherhack-issues#435]
This adds to extratab "Onlyfriends" option which is very useful 
In rusherhack you are able to highlight your friends with ColoredFriends, but if you dont want to turn 
your tab into a mash you cant see if there is your friends online , so onlyfriends deletes every people that is 
not in your friend list from tab

**Comment by thebruhmoment** [comment]
Or "FriendsFirst" so there is no need to delete people , just show friends first

**Comment by bstar16** [comment]
I also wanna suggest adding number ping to extra tab instead of the regular bar ping

**Comment by John200410** [comment]
OnlyFriends setting has been added:
![image](https://user-images.githubusercontent.com/43681932/110543599-8665df00-80f8-11eb-9a2e-709e4f50d589.png)


 All of this stuff will be in the next update.
