### ISSUE TITLE
[BUG] autocrystal placing too many crystals

### ISSUE THREAD

**Issue by jennifer-uwu** [John200410/rusherhack-issues#436]
sometimes auto crystal will place more crystals even if there is already one next to the target that will do a lot of damage and little to no damage to yourself

**Comment by John200410** [comment]
AutoCrystal is currently being rewritten so the logic should be better in the next update.

**Comment by John200410** [comment]
AutoCrystal rewrite will be in the next update. Feel free to re-open if this issue still persists after that update.
