### ISSUE TITLE
[FEATURE] ShulkerPreview2.0 

### ISSUE THREAD

**Issue by thebruhmoment** [John200410/rusherhack-issues#437]
So basically it works like that: when you open shulker it reads whats in it and saves to file and then it reads and shows to you like usual shulkerprewiev
tbh i cant imagine how to make it know what exactly shulker it is because every shulker is named the same with the other but you smort so yea

**Comment by FluorideHistorian** [comment]
this was already added

**Comment by thebruhmoment** [comment]
> this was already added

wait fr? its in will-add or its in client rn?

**Comment by emloisgod** [comment]
> So basically it works like that: when you open shulker it reads whats in it and saves to file and then it reads and shows to you like usual shulkerprewiev
> tbh i cant imagine how to make it know what exactly shulker it is because every shulker is named the same with the other but you smort so yea

this is already a thing, in 'ExtraTooltips' module, enable the cache setting under shulker.

**Comment by thebruhmoment** [comment]
Fuck me
