### ISSUE TITLE
[BUG] Signs not showing up in search

### ISSUE THREAD

**Issue by battlestations1** [John200410/rusherhack-issues#438]
**Describe the bug**
Signs can be added as search blocks, but do not actually work

**To Reproduce**
Try adding signs as search blocks

**Other mods**
Future, ambient sounds, journeymap

**Expected behavior**
For signs to show up as search blocks so for e.g. we can see them underground

**Screenshots**

**Additional context**

**Comment by John200410** [comment]
Thank you for reporting this.

**Comment by John200410** [comment]
This has been fixed in the next update.

![image](https://user-images.githubusercontent.com/43681932/114283641-c0d4db80-9a18-11eb-94be-c29b119eeb94.png)
