### ISSUE TITLE
[BUG] Auto eat doesn't see absorption points as health and will eat based on your normal hearts

### ISSUE THREAD

**Issue by ShaderTheBlackKid** [John200410/rusherhack-issues#439]
**Describe the bug**
Auto eat doesn't see absorption points as health and will eat based on your normal hearts.
**To Reproduce**
Set auto eat to health mode.
**Other mods**
List other forge mods you are using (if any):

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by John200410** [comment]
AutoEat health mode does include the absorption hearts as seen here:
![image](https://user-images.githubusercontent.com/43681932/108291387-38486600-7160-11eb-85d6-e9215e42b0f7.png)
