### ISSUE TITLE
Pause and resume for basefinder also sound notifications [FEATURE]

### ISSUE THREAD

**Issue by iLLiCiTgames** [John200410/rusherhack-issues#44]
It would be great to have a pause/resume option for basefinder so that way when you find something you don't have to start over.
 Also if this could be implemented the option have it play a sound when it comes across shulkers or x amount of chest ect. or maybe have that in a stand alone module by itself.

**Comment by John200410** [comment]
Thank you for the suggestion

**Comment by John200410** [comment]
I have finished adding this and will be in the next update.
