### ISSUE TITLE
[FEATURE] Enemy List Visual Editions

### ISSUE THREAD

**Issue by TheRedBlocker** [John200410/rusherhack-issues#442]
**What feature would you like to be added.**
An option for tracers to show up as a different color for enemies.
An option for nametags to show up as a different color similar to how nametags for friends are blue.

**Comment by John200410** [comment]
Thank you for the suggestions

**Comment by John200410** [comment]
These have now been added and will be in the next update.
![image](https://user-images.githubusercontent.com/43681932/108294142-46e44c80-7163-11eb-97ab-ddbd3cbbeb31.png)

**Comment by TheRedBlocker** [comment]
Can u change default tracer color as well to account for enemies being red?

**Comment by John200410** [comment]
Tracers gets its colors from the Colors module.
