### ISSUE TITLE
[FEATURE] Add or remove items from ESP categories

### ISSUE THREAD

**Issue by battlestations1** [John200410/rusherhack-issues#443]
**What feature would you like to be added.**
To be able to add or remove items/blocks/entities from ESP categories. E.g. in the "other" category it highlights item frames, which is great. However it also highlights XP orbs and firework particles which is a little annoying.

**Is your feature request related to a problem? Please describe.**
No

**Additional context**

**Comment by John200410** [comment]
Thank you for the suggestion. I will probably make an Entities module under the Client category. Does that sound good?

**Comment by battlestations1** [comment]
Awesome thanks John

**Comment by John200410** [comment]
This has been added in the next update:
![image](https://user-images.githubusercontent.com/43681932/131224861-22b977e7-32fd-4ee4-b0bb-72c2f1ebb5e1.png)
