### ISSUE TITLE
[FEATURE] AutoEat > Milk

### ISSUE THREAD

**Issue by SewerHatch** [John200410/rusherhack-issues#444]
Milk setting that help automaticaly get rid of sertain effects like mining fatigue and wither effect

**Comment by ShaderTheBlackKid** [comment]
I don't see how this would be useful since who even carries milk and for the rare occasion if getting mining fatigue you cam manually drink the milk.

**Comment by SewerHatch** [comment]
Me and my group works on project involving elder guardians and we need an automated way to get rid of mining fatigue while using baritone.

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
This has been added in the next update:
https://rusherhack.org/i/3tcnr0bvan.mp4
