### ISSUE TITLE
[BUG] Absorption Hearts Invisible in Freecam

### ISSUE THREAD

**Issue by hashalite** [John200410/rusherhack-issues#445]
**Describe the bug**
When freecam is enabled absorption hearts don't render.

**To Reproduce**
1. Eat gapple
2. Freecam

**Other mods**
none

**Comment by tycrek** [comment]
duplicate of #439

**Comment by hashalite** [comment]
That issue was only talking about a bug with AutoEat before it was renamed. If the two bugs are related, I guess it would make sense to merge them, but I figured they should get separate issues if not.

**Comment by tycrek** [comment]
> 
> 
> That issue was only talking about a bug with AutoEat before it was renamed. If the two bugs are related, I guess it would make sense to merge them, but I figured they should get separate issues if not.

oh woops my bad, read that issue wrong. thanks for pointing that out

**Comment by John200410** [comment]
Thank you for reporting this.

**Comment by John200410** [comment]
This has been fixed in the next update.
