### ISSUE TITLE
[BUG] crosshair rendering problem

### ISSUE THREAD

**Issue by AppleInTheFridge** [John200410/rusherhack-issues#447]
**Describe the bug**
When you set the crosshair to be a dot and move it leaves a trail

**To Reproduce**
crosshair settings:
mode: csgo
length 1.14
width .45 
gap 0
no outline

**Other mods**
List other forge mods you are using (if any):
none

**Screenshots**
https://streamable.com/f96p2h

**Comment by John200410** [comment]
Unable to reproduce.

https://rusherhack.org/i/idv1atddlh.mp4
