### ISSUE TITLE
[FEATURE] Australia

### ISSUE THREAD

**Issue by RemainingToast** [John200410/rusherhack-issues#448]
**What feature would you like to be added.**
Australia, simulate playing in Australia

**Is your feature request related to a problem? Please describe.**
Australia has no problems 10/10 country, nothing to describe.

**Additional context**
Apparently Tasmania is apart of Australia

**Comment by issac4892** [comment]
we really need this right NOW

**Comment by RemainingToast** [comment]
okay I generally wanted the module back but alright

**Comment by fawwaz1234** [comment]
same

**Comment by John200410** [comment]
I don't plan on adding any meme modules. If you really want this then it wouldn't be hard to make a standalone forge mod.

**Comment by FluorideHistorian** [comment]
its in xulu
