### ISSUE TITLE
[BUG] Potion effects dont show amplifier

### ISSUE THREAD

**Issue by Azrn** [John200410/rusherhack-issues#449]
**Describe the bug**
The potion effects in hud editor only shows the duration and not the effect amplifier

**Expected behavior**
The potion effects should show duration and amplifier

**Additional context**
For an easy fix, append the potion amplifier to the potion string (Use the minecraft formatting function to get the amplifier in latin)
Example:
```
import net.minecraft.client.resources.I18n;

...

I18n.format(potion.getPotion().getName()) + " " + I18n.format("enchantment.level." + (potion.getAmplifier() + 1)) + " " + Potion.getPotionDurationString(potion, 1f)
```

**Comment by Badinek** [comment]
this was already made into plus releases and will probably come to 1.2 once its released

**Comment by Azrn** [comment]
Ok thanks!
