### ISSUE TITLE
[FEATURE] LightESP utility

### ISSUE THREAD

**Issue by tycrek** [John200410/rusherhack-issues#45]
**What feature would you like to be added.**

LightESP, similar to every other ESP but highlights areas where the light level might spawn mobs.

Essentially, highlight any areas where the [light level](https://minecraft.gamepedia.com/Light) is below or equal to `7`. This would be tremendously helpful when building bases where you don't want mobs to be able to spawn or also to protect dupe stashes from creepers (been there before, it's not fun).

Yes there are Forge mods like [LLOR](https://www.curseforge.com/minecraft/mc-mods/light-level-overlay-reloaded) but in my opinion it just looks *bad*, plus we really only need to see the values below `7`. Also, most plugins that work for 1.12.2 don't render through walls.

I don't know the source code but it might be easy enough to just copy/paste an existing ESP and just check light levels instead.

**Comment by John200410** [comment]
Thank you for the suggestion, you mentioned that you didn't like how other forge mod's look for this, what would you like it to look like?

**Comment by tycrek** [comment]
Something similar to storage or hole ESP. Main thing is being able to render it through walls which the mod I linked can't do. And maybe a range option would be helpful as well. Instead of a cube (Fill mode) it could be flat against the blocks with low light levels, if that makes sense (I think Salhack has "flat" or "bottom" ESP modes)

**Comment by John200410** [comment]
This has been made and will be in the next update:
![image](https://user-images.githubusercontent.com/43681932/110887045-9b3ca100-82b7-11eb-951e-8dcbc4ddbb8e.png)
