### ISSUE TITLE
[FEATURE] Proximity Disconnect

### ISSUE THREAD

**Issue by ShaderTheBlackKid** [John200410/rusherhack-issues#450]
**What feature would you like to be added.**
A module under Auto Disconnect that has an adjustable range and disconnects when a player comes near you, very useful for tasks at spawn like afk mining obsidian at end spawn or baritone repairing highways etc.

**Is your feature request related to a problem? Please describe.**
I like obsidian, now to get obsidian on oldfag I need to baritone in the end. Now the problem is that some people like to bed bomb at end spawn and do stuff like killing me while I'm AFK and Proximity Disconnect would solve this.

**Comment by browsky300** [comment]
Also would be nice to have this for mobs, with a slider of how close they can get before you disconnect.

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
This has been added and will be in the next update.
![image](https://user-images.githubusercontent.com/43681932/108427426-28d22700-720b-11eb-91bb-7260aa99e383.png)
