### ISSUE TITLE
[FEATURE] "Elytra Only" setting for AutoWalk

### ISSUE THREAD

**Issue by emloisgod** [John200410/rusherhack-issues#451]
**What feature would you like to be added.**
An 'Elytra Only' setting under the auto walk module

**Is your feature request related to a problem? Please describe.**
No, no issue with auto walk this would just be helpful.

**Additional context**
It would be nice for highway travel, only Auto-Walking when you are using an elytra, so you don't have to turn it off when there is a road block or you have to stop.

**Comment by jennifer-uwu** [comment]
just bind autowalk to the same key as elytrafly

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
This has been added and will be in the next update.
