### ISSUE TITLE
[FEATURE] LiveMessage integration

### ISSUE THREAD

**Issue by CrawLeyYou** [John200410/rusherhack-issues#453]
**What feature would you like to be added.**
LiveMessage integration

**Is your feature request related to a problem? Please describe.**
Sorting DM's 

**Additional context**
https://www.youtube.com/watch?v=YlEzqEKURYY

**Comment by jennifer-uwu** [comment]
just use the forge mod?

**Comment by John200410** [comment]
What exactly would you want to be integrated?

**Comment by CrawLeyYou** [comment]
> What exactly would you want to be integrated?

Directly integration in client like baritone

**Comment by John200410** [comment]
No. I'm not going to build it into rusherhack for the same reason I'm not building baritone into rusherhack.
