### ISSUE TITLE
[FEATURE] "random" setting for chatappend

### ISSUE THREAD

**Issue by issac4892** [John200410/rusherhack-issues#454]
**What feature would you like to be added.**
random number added at chatappend

**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/56223465/107867242-9f45f080-6ebc-11eb-9b58-1a2dad28433b.png)
when i use spammer, i get this

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
This has been added in the next update.
![image](https://user-images.githubusercontent.com/43681932/108636705-0fbcb680-7455-11eb-91c8-5f59a75ec08a.png)
