### ISSUE TITLE
[FEATURE] ClientSideTime option to sync with real-world time

### ISSUE THREAD

**Issue by 2bibles2jews** [John200410/rusherhack-issues#455]
**What feature would you like to be added.**
Add an option to the ClientSideTime to sync real world time, if possible.

**Is your feature request related to a problem? Please describe.**
It is not related to a problem at any way.

**Additional context**
(None)

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
This has been written and will be in the next update. You will have to enter your longitude/latitude manually:
![image](https://user-images.githubusercontent.com/43681932/108638240-46e29600-745c-11eb-9aff-e68b7fcc0917.png)
