### ISSUE TITLE
[FEATURE] Particles: Option RemoveCertainScreens

### ISSUE THREAD

**Issue by 2bibles2jews** [John200410/rusherhack-issues#456]
**What feature would you like to be:**
An option to remove the particles from a certain screen, such as Chat, Main Menu, etc.

**Is your feature request related to a problem? Please describe.**
It is related to a problem, I want to keep particles as it is but without having to see it in certain screens such as chat.

**Additional context**

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
A Visibility setting has been added and will be in the next update.
![image](https://user-images.githubusercontent.com/43681932/108639086-a642a500-7460-11eb-8b57-a645cee0422a.png)
