### ISSUE TITLE
[BUG] un-english gets deleted for announcer

### ISSUE THREAD

**Issue by issac4892** [John200410/rusherhack-issues#457]
**Describe the bug**
I get message ``I picked [number] !``
**To Reproduce**
use korean/whatever and do something with announcer on
**Other mods**
List other forge mods you are using (if any):
X
**Expected behavior**
I picked 1 cobblestone!
**Screenshots**

**Additional context**

**Comment by ItzDawnfall** [comment]
I believe his is a server side issue. Some servers (such as 2b2t) don't allow unicode or languages with non-english characters

**Comment by tycrek** [comment]
@ItzDawnfall is correct. 2b2t blocks unicode characters in public chat (though I think whispers work)

**Comment by issac4892** [comment]
is there no way to make announce english instead of korean than?

2021년 2월 15일 (월) 오전 1:23, Josh Moore <notifications@github.com>님이 작성:

**Comment by John200410** [comment]
You will have to change the game's language to English if you don't have a custom name on your items.
