### ISSUE TITLE
[FEATURE] NoRender PotionBubbles or EffectBubbles

### ISSUE THREAD

**Issue by tycrek** [John200410/rusherhack-issues#459]
**What feature would you like to be added.**

Hide the bubbles that show up when you have enchants (such as from potions or gaps). The bubbles make it annoying to take screenshots.

**Comment by jennifer-uwu** [comment]
video settings -> animations -> potion particles

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by jumboman32** [comment]
Merged with #385
