### ISSUE TITLE
[FEATURE] web movement

### ISSUE THREAD

**Issue by Tux8068** [John200410/rusherhack-issues#461]
add "timer" setting to noweb, this is the way you sink faster in webs on 2b2t, i use future's timer speed set at 8. however this can cause you to get disconnected if you move in webs too much, so i suggest making the player not movable while going down (similar to how anchor works)

**read comments**

**Comment by jennifer-uwu** [comment]
+1

**Comment by John200410** [comment]
Thank you for the suggestion

**Comment by jumboman32** [comment]
https://streamable.com/v0a598

something like this to spam downward movement packets and cancel any rotations to prevent setbacks
this would help in crystal pvp since lots of people use webs on 2b now

**Comment by jumboman32** [comment]
web noslow onground setting
"web noslow rubberbands you when you are falling through the web but works well once you are on the ground.
this would be helpful for crystal pvp servers like 2b2t where players use webs frequently"
merging bc similar

**Comment by John200410** [comment]
Strict setting has been added to NoSlow Webs. Will work on the fast falling now.

**Comment by John200410** [comment]
These settings have been added in the next update:
![image](https://user-images.githubusercontent.com/43681932/121622659-636f0200-ca3c-11eb-81ea-c3b1cac2af79.png)
