### ISSUE TITLE
Where is the hud editor or baritone settings

### ISSUE THREAD

**Issue by 0Zonx** [John200410/rusherhack-issues#464]
When I open up rusherhack there is all of the modules but there is no hud editor or baritone settings

**Comment by fawwaz1234** [comment]
are u using cracked one?

**Comment by issac4892** [comment]
comma for hud editor
u maybe need to use the text method for baritone

**Comment by CaptainTheBeam** [comment]
def using the crack

**Comment by ItzDawnfall** [comment]
A question like this would be more fit for the discord, which you should have an invite to in the launcher.

**Comment by fawwaz1234** [comment]
> A question like this would be more fit for the discord, which you should have an invite to in the launcher.

hes cracked

**Comment by y4ndex1** [comment]
using da crack 🤣  rip ur pc got owned by qq

**Comment by FluorideHistorian** [comment]
you the entire monke

**Comment by jennifer-uwu** [comment]
you need the baritone api installed for the baritone integration, and you can open the hud editor by pressing comma
