### ISSUE TITLE
Gapple in hole

### ISSUE THREAD

**Issue by MIshaTheWarlord** [John200410/rusherhack-issues#468]
What feature would you like to be added.
gapple in hole

Is your feature request related to a problem? Please describe.
I like using offhand and all, but totem-failing sucks, so I'd love for this to be a feature

Additional context
Add a setting to auto-totem that automatically puts a gap in your offhand whenever you jump into a hole, and goes back to a totem when you come out.

**Comment by notperry1234567890** [comment]
> What feature would you like to be added.
> gapple in hole
> 
> Is your feature request related to a problem? Please describe.
> I like using offhand and all, but totem-failing sucks, so I'd love for this to be a feature
> 
> Additional context
> Add a setting to auto-totem that automatically puts a gap in your offhand whenever you jump into a hole, and goes back to a totem when you come out.

Tbh would be better to have a hole check that's more customizable like phobos.

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by jumboman32** [comment]
Merging.
