### ISSUE TITLE
[FEATURE] AutoCrystal Damage Indicator

### ISSUE THREAD

**Issue by joeengo** [John200410/rusherhack-issues#469]
i would like a damage indicator like some other clients have (example Wurst+2)

this would show as text at the coloured render on the block your placing crystals on showing how much damage per crystal your doing.

screenshotshowing a example. (edited in photoshop)
![unknown](https://user-images.githubusercontent.com/63791277/108127975-fce86180-70a3-11eb-81a8-d2c5bc9b6539.png)

**Comment by John200410** [comment]
Thank you for the suggestion

**Comment by John200410** [comment]
This has been made and will be in the next update:
![image](https://user-images.githubusercontent.com/43681932/109541431-cf32ed80-7a91-11eb-821d-c8ebc07fd430.png)
