### ISSUE TITLE
[FEATURE] "Smart Tower" for Scaffold

### ISSUE THREAD

**Issue by tycrek** [John200410/rusherhack-issues#470]
**What feature would you like to be added.**

Scaffold towering is pretty janky on 2b with NoGlitchBlocks > Place enabled. A "smart" or "smart tower" setting would automatically disable NGB Place while Space is held and re-enabled when it is released (only re-enabled if it was enabled prior to towering of course)

**Comment by tycrek** [comment]
I can also record a video if that helps

**Comment by MIshaTheWarlord** [comment]
You can also (as a measure if this feature isn't added) have scaffold and noglitchblocks set to the same bind, so  when one turns on, the other turns off.

**Comment by tycrek** [comment]
> 
> 
> You can also (as a measure if this feature isn't added) have scaffold and noglitchblocks set to the same bind, so when one turns on, the other turns off.

yes, but I prefer to have NGB Place enabled when horizontal scaffolding. Right now I use two keys (one for scaffold, one for NGB Place) but an automatic solution would be better

**Comment by John200410** [comment]
Thank you for the suggestion. I will probably just hardcode in a fix for this.

**Comment by John200410** [comment]
This has been fixed.
