### ISSUE TITLE
[BUG] AutoMine

### ISSUE THREAD

**Issue by Badinek** [John200410/rusherhack-issues#472]
**Describe the bug**
AutoMine stops mining if you open some gui (inventory, esc etc.)

**To Reproduce**
enable automine on mode continuous, look on some block (it starts mining) and then open inventory or chat, it stops mining

**Other mods**
List other forge mods you are using (if any):
atom forgehax optifine schematica 

**Expected behavior**
A clear and concise description of what you expected to happen.¨
it should continue mining even if you open gui

**Screenshots**

**Additional context**

**Comment by Jopplo** [comment]
I've been having this same problem. The only way I could figure out to be able to Alt Tab and it still work is by doing F3+P, and what this does is make the game not pause on lost focus.

**Comment by John200410** [comment]
Thank you for reporting this

**Comment by John200410** [comment]
This has been fixed in the next update.
