### ISSUE TITLE
[BUG] Shader ESP shulker contour

### ISSUE THREAD

**Issue by hashalite** [John200410/rusherhack-issues#475]
**Describe the bug**
When using the shader option in ESP, shulkers have an outline around the edges of the model when viewed from a distance.

**To Reproduce**
1. Place shulker
2. Enable ESP on shader mode
3. Walk back ~15 blocks

**Other mods**
Optifine

**Expected behavior**
The outline should only be on the outer edges of the block.

**Screenshots**
![2021-02-21_16 23 16](https://user-images.githubusercontent.com/71229440/108639364-2a495c80-7462-11eb-83c6-866fdf398f10.png)

**Comment by John200410** [comment]
Thank you for reporting this.

**Comment by John200410** [comment]
This has been fixed in the next update.
