### ISSUE TITLE
[FEATURE] Option to disable shader ESP edge glow

### ISSUE THREAD

**Issue by hashalite** [John200410/rusherhack-issues#476]
**What feature would you like to be added.**
When shader ESPs are viewed from a distance, they have a glow around the edges.  It would be nice to be able to disable this if harder edges are preferred.

**Additional context**
![2021-02-21_16 22 37](https://user-images.githubusercontent.com/71229440/108639542-10f4e000-7463-11eb-97e7-4d30102c853c.png)

**Comment by John200410** [comment]
You can already disable this with the Fade setting.
