### ISSUE TITLE
[BUG] config saving bug

### ISSUE THREAD

**Issue by Badinek** [John200410/rusherhack-issues#479]
**Describe the bug**
enabled hud elements dont save if i create config  (so if i have some enabled, disable them and then load the config they are still disabled)

**To Reproduce**
enable some hud elements and create config, then switch to other config and disable all hud elements, then switch back to the first one, no hud elements enabled 

**Other mods**
atom forgehax rusherhack 

**Expected behavior**
i expect them to save if they are enabled

**Comment by John200410** [comment]
Hud elements are not modules. This is intended behavior.
