### ISSUE TITLE
[FEATURE] BoatBot

### ISSUE THREAD

**Issue by gcurtiss** [John200410/rusherhack-issues#48]
**What feature would you like to be added.**
Remember ElytraBot? That, but for boats.

**Additional context**
Contact ElytraBot dev for collaboration?

**Comment by John200410** [comment]
The only thing I remember about ElytraBot was that the code was very bad. I have no intention of collaboration.

That being said I will probably look into doing this for v1.2

**Comment by tycrek** [comment]
The code was garbage and I opened a PR to fix something. Instead of merging in ONE CLICK he copy/pasted without credit. Fully support zero collaboration.

**Comment by John200410** [comment]
Closing this for now.
