### ISSUE TITLE
[FEATURE] some suggestions:

### ISSUE THREAD

**Issue by 06d** [John200410/rusherhack-issues#480]
An "avoid chat" setting for particles. 
"Timezone" setting for client side time. 
Like a textured "blur" when in gui. So the background count be a different type of blur: like "liquid" liquidates the stuff around the GUI. "Geometrical" shows [Something like this](https://images.app.goo.gl/6q6KYTY79hFsTHrQ8) 
Also add search bar to search for modules if you can't find them.

**Comment by 2bibles2jews** [comment]
Based

**Comment by tycrek** [comment]
> An "avoid chat" setting for particles.

![image](https://user-images.githubusercontent.com/29926144/108916574-b33fcf80-75eb-11eb-980d-a50ffa260c88.png)

Unless you mean while chat is open but don't show on that chat area specifically?

**Comment by 06d** [comment]
> > An "avoid chat" setting for particles.
> 
> ![image](https://user-images.githubusercontent.com/29926144/108916574-b33fcf80-75eb-11eb-980d-a50ffa260c88.png)
> 
> Unless you mean while chat is open but don't show on that chat area specifically?

While open, when I open chat with said setting it still creeps into the chat.

**Comment by John200410** [comment]
Please open separate issues instead of bundling them into one.
