### ISSUE TITLE
[FEATURE] AutoWalk PauseOnLag

### ISSUE THREAD

**Issue by tycrek** [John200410/rusherhack-issues#484]
**What feature would you like to be added.**

2 new AutoWalk settings:

- PauseOnLag - Boolean, pause AutoWalk for [delay] if lagback
- Delay - Float, how long to pause for (VisiblePredicate for PauseOnLag)

**Comment by John200410** [comment]
Thank you for the suggestions.

**Comment by John200410** [comment]
This has been added in the next update.
