### ISSUE TITLE
[FEATURE] PVP inventory info on HUD

### ISSUE THREAD

**Issue by crackcocacola** [John200410/rusherhack-issues#486]
inventory info that shows only pvp stuff like crystal and totems and target info bcuz the cool

**Comment by tycrek** [comment]
that is super vague. Do you mean on the HUD or what?

**Comment by 0Yos** [comment]
![image](https://user-images.githubusercontent.com/75744018/110147271-c61c8600-7ddb-11eb-91b1-be9fd2c8d4d9.png)
do you mean something like this?

**Comment by crackcocacola** [comment]
yeah something like that

**Comment by John200410** [comment]
Thank you for the suggestion. I will probably have each of these in separate hud elements.

**Comment by jumboman32** [comment]
Duplicate of TargetHUD issue and InvHud issue.
