### ISSUE TITLE
[BUG] Crash when creating module profiles

### ISSUE THREAD

**Issue by ShaderTheBlackKid** [John200410/rusherhack-issues#488]
**Describe the bug**
Your game crashes when you attempt to create a module profile with a slash / in the name.

**To Reproduce**
Make a new module profile and include a slash / in the name and then attempt to create it.

**Other mods**
Gamesense, W+2, but I'm 99.9% sure this had nothing to do with them.

**Comment by CaptainTheBeam** [comment]
nice name

**Comment by ShaderTheBlackKid** [comment]
Also this isn't anything urgent so no need to add it to 1.2. I don't want to wait until 2022 or early 2023 to play on 1.2 and fixing these bugs take time therefore delaying the release.

**Comment by ShaderTheBlackKid** [comment]
> nice name

Ikr

**Comment by 2bibles2jews** [comment]
> Also this isn't anything urgent so no need to add it to 1.2. I don't want to wait until 2022 or early 2023 to play on 1.2 and fixing these bugs take time therefore delaying the release.

**future client intensifies**

**Comment by John200410** [comment]
Thank you for reporting this.

**Comment by John200410** [comment]
This has been fixed in the next update.
