### ISSUE TITLE
[FEATURE] ElytraBounce/Hopping

### ISSUE THREAD

**Issue by GentleWither** [John200410/rusherhack-issues#489]
**What feature would you like to be added.**
ElytraBounce/Hopping

**Is your feature request related to a problem? Please describe.**
i dont have any probs

**Additional context**
ElytraBounce/hopping mode on ElytraFly like this https://youtu.be/9isqJmcTETQ

**Comment by John200410** [comment]
Why would you do this rather than using the ElytraFly module?
