### ISSUE TITLE
[FEATURE] BedAura 

### ISSUE THREAD

**Issue by jam-in-a-jar** [John200410/rusherhack-issues#490]
Bedaura
It is places beds automaticly and breaks and rotate and you arent kill at bedbombing or in bed pvp

It isnt a problem it is feature

Videos of Bedaura
https://www.youtube.com/watch?v=VRC0GZSIoCI&t=11s

**Comment by CaptainTheBeam** [comment]
i think johns adding this in v1.2 since it was supposed to come in v1.1

**Comment by John200410** [comment]
Duplicate of #8
