### ISSUE TITLE
[FEATURE] ArrayList options

### ISSUE THREAD

**Issue by 2147483647ms** [John200410/rusherhack-issues#492]
![ya](https://user-images.githubusercontent.com/77409841/109435641-f67db200-79e0-11eb-9776-3da3e639f1e0.PNG)
![f](https://user-images.githubusercontent.com/77409841/109435672-2331c980-79e1-11eb-9f1e-6aaabd7f27e5.PNG)
![g](https://user-images.githubusercontent.com/77409841/109435678-2af16e00-79e1-11eb-860b-dda5cfbfe7f1.PNG)
Better arraylist look at the attached pic to see what some of the options might look lie

There would be an option to change between the one we have right now and the new ones

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by jumboman32** [comment]
Metadata was added.
