### ISSUE TITLE
[Feature] Entity speed and jesus

### ISSUE THREAD

**Issue by drboy2005** [John200410/rusherhack-issues#494]
Since hausemaster added the ability for mobs to go in the nether again, i thought it would be cool if pig entity speed was fixed, so you could get through 2 block holes fast. Fixing jesus would be helpful too because help others who dont have elytras base hunt. Thanks

**Comment by CaptainTheBeam** [comment]
for entity speed a bypass would need to be found first and if u want access to the jesus bypass purchase plus

**Comment by John200410** [comment]
It is not possible to go fast on pigs. Jesus "Strict" mode will be in the next update.
