### ISSUE TITLE
[FEATURE] FancyChat MD5 mode

### ISSUE THREAD

**Issue by HermanGoring** [John200410/rusherhack-issues#497]
**What feature would you like to be added.**
FancyChat>MD5 mode

**Is your feature request related to a problem? Please describe.**
Nope. It justs converts your sentence into Md5 to troll people.

**Additional context**
Nope, but I'll like it to be implemented.

**Comment by tycrek** [comment]
```java
public static String getMd5(String input) throws NoSuchAlgorithmException {
	String hashText = new BigInteger(1, MessageDigest.getInstance("MD5").digest(input.getBytes())).toString(16);
	while (hashText.length() < 32)
		hashText = "0".concat(hashText);
	return hashText;
}
```

for john <3

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
This has been made and will be in the next update:
![image](https://user-images.githubusercontent.com/43681932/110891401-e8247580-82bf-11eb-995b-6c8ea49f16c4.png)

**Comment by HermanGoring** [comment]
Epic!
