### ISSUE TITLE
[FEATURE] "Hold scroll" for TabGui

### ISSUE THREAD

**Issue by tycrek** [John200410/rusherhack-issues#5]
**What feature would you like to be added.**
Scroll the item list in TabGui when up/down arrow key is held down. Pretty annoying to spam it. And yes some of us do use TabGui.

**Is your feature request related to a problem? Please describe.**
~~I need money plz send to my paypal~~

**Additional context**
everything out of context

**Comment by John200410** [comment]
This has been added.
https://rusherhack.org/i/1jnohmefva.mp4
