### ISSUE TITLE
[FEATURE] 2b2t queue RPC integration

### ISSUE THREAD

**Issue by emloisgod** [John200410/rusherhack-issues#500]
**What feature would you like to be added.**
When waiting in 2b2t queue, in the "RichPresence" module you should have a setting to set the state as your place in 2b2t queue, rather than just saying your on 2b2t.org

**Is your feature request related to a problem? Please describe.**
No, I just think it would be cool.

**Additional context**
No, I just think it would be cool.

**Comment by tycrek** [comment]
Duplicate of #82
