### ISSUE TITLE
[FEATURE] PacketLogger: ViewCertainPackets

### ISSUE THREAD

**Issue by 2b2t-server** [John200410/rusherhack-issues#502]
**What feature would you like to be added.**
The option to view certain packets in the PacketLogger, In addition to that to save the packets into a file
.
Maybe also add a QueuePeek option to view only people who enter the Queue and leaves, Here's an example:
![Screenshot_20210214-135032_Discord](https://user-images.githubusercontent.com/79129705/110081074-0f48e780-7d94-11eb-8194-c824293e540e.jpg)

**Is your feature request related to a problem? Please describe.**
It is related to a problem. I'm always frustrated when I try to view certain packets, but useless packets that I don't really want to view comes up.

**Additional context**
The time that the player waited in the queue is optional, But I would like to see it in the queuepeek option.

**Comment by John200410** [comment]
Thank you for the suggestions.

**Comment by John200410** [comment]
This has been added in the next update.
