### ISSUE TITLE
[FEATURE] Kill aura disable on crystal place option.

### ISSUE THREAD

**Issue by asdu-uk** [John200410/rusherhack-issues#503]
**What feature would you like to be added.**
A feature that disables killaura whenever autocrystal is placing crystals.

**Is your feature request related to a problem? Please describe.**
Sometimes I'll have killaura on when someone is in a hole, and then once they leave the hole the autocrystal doesn't work too well because killaura is attacking at the same time. 

.

**Comment by John200410** [comment]
Thank you for the suggestion. I will probably hard-code this.

**Comment by John200410** [comment]
This has been done in the next update.
