### ISSUE TITLE
[BUG] scaffold glitching out in liquids 

### ISSUE THREAD

**Issue by Badinek** [John200410/rusherhack-issues#505]
**Describe the bug**
if you use scaffold on top of some liquid (water/lava) it keeps rotating and glitching you

**To Reproduce**
enable scaffold and try to place on some liquid

**Other mods**
List other forge mods you are using (if any):
atom forgehax optifine (i doubt these break it)

**Expected behavior**
i expect the scaffold to work same as normal if possible

**Screenshots**
i made a recording:
https://streamable.com/moeu81

**Additional context**
ez

**Comment by John200410** [comment]
Does this only happen on 2b2t?

**Comment by Badinek** [comment]
i havent tried anywhere else

**Comment by John200410** [comment]
Unable to reproduce:

https://rusherhack.org/i/cz4akzn837.mp4
