### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by HeroGlaucoP** [John200410/rusherhack-issues#508]
**Describe the bug**
when you update the linux kernel it gives you hwid error

**To Reproduce**
update the linux kernel and try to open rusherhack

**Other mods**
none

**Expected behavior**
open without error

**Screenshots**

**Additional context**
i use a rolling release distro so it's really annoying to ask for hwid reset almost everyday

**Comment by John200410** [comment]
The HWID algorithm will be changed in v1.2
