### ISSUE TITLE
[FEATURE] Step vanilla mode

### ISSUE THREAD

**Issue by Mishi04** [John200410/rusherhack-issues#509]
**What feature would you like to be added.**
Add a vanilla mode for step. this would be useful for servers like us.crystalpvp.cc where step only works in vanilla mode

**Is your feature request related to a problem? Please describe.**
I practice pvp on servers where only step works in vanilla mode and I have to use another client just for that module

**Additional context**
N/A

**Comment by jennifer-uwu** [comment]
ncp mode works on vanilla servers

**Comment by John200410** [comment]
Duplicate of #92
