### ISSUE TITLE
[FEATURE] NoRender Options

### ISSUE THREAD

**Issue by notperry1234567890** [John200410/rusherhack-issues#51]
**What feature would you like to be added.**
A NoRender option falling blocks and block overlay first is just you don't render falling blocks like sand or gravel etc can be used as fps lag machines second block overlay is like when your in a block and it covers it up your screen with just a block overlay you can turn on packetfly to remove it but i thought it would be better to have it as a option in NoRender.

**Is your feature request related to a problem? Please describe.**
No.

**Additional context**
.

**Comment by ignelias** [comment]
doesn't salhaxk have that

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
> doesn't salhaxk have that

Why would this matter?

**Comment by Oecher1** [comment]
> doesn't salhaxk have that

i dont use that anymore caused way too much issues cause of the spaghetti code

**Comment by John200410** [comment]
These things have been added already.
