### ISSUE TITLE
[FEATURE] Autoflatten

### ISSUE THREAD

**Issue by carlll2** [John200410/rusherhack-issues#510]
Something that automatically walks in a pattern through set radius/square when turned on and uses nuker/baritone to flatten the area. Maybe also an esp of the area that it will flatten.

Doesn't need to be absolutely perfect as long as it doesn't kill/kick itself.

![autoflatten](https://user-images.githubusercontent.com/65935609/110256434-e75dad80-7f66-11eb-85de-9fcf733329d2.png)

**Comment by John200410** [comment]
You can use baritone to mine a specific area.
