### ISSUE TITLE
[FEATURE] BetterOffhand

### ISSUE THREAD

**Issue by ghost** [John200410/rusherhack-issues#511]
better offhand like in konas

**Comment by fawwaz1234** [comment]
crystalcheck and sum sht yk?

**Comment by notperry1234567890** [comment]
wow what a amazing description

**Comment by ShaderTheBlackKid** [comment]
No one here uses konas so we have no idea what you mean.

**Comment by FluorideHistorian** [comment]
typical konas user moment

**Comment by ProfKambing** [comment]
uuuuuuuuuuuu ghost whos that
