### ISSUE TITLE
[FEATURE] Sprint "Baritone" setting

### ISSUE THREAD

**Issue by tycrek** [John200410/rusherhack-issues#512]
**What feature would you like to be added.**

Setting called "Baritone" within Sprint to toggle Baritone sprint off/on depending on what Rhack Sprint is set to. Right now I have to toggle them each individually if I'm in a spot where I don't want Baritone to be sprinting.

**Comment by John200410** [comment]
I will probably just change the setting when it's toggled similar to Jesus.

**Comment by John200410** [comment]
This has been donate in the next update.
