### ISSUE TITLE
[FEATURE] ExtraTab stuff

### ISSUE THREAD

**Issue by tycrek** [John200410/rusherhack-issues#514]
**What feature would you like to be added.**

- Only Show ... (toggleable dropdown menu. If disabled, neither of the below apply)
  - Friends (just shows friends)
  - Enemies (just shows enemies)
  - (if both are enabled, show both. if neither are enabled but Only Show is enabled, show no one)
- Colors ... (toggleable dropdown menu. If disabled, use defaults)
  - Background (tablist background)
  - Player/List item (the background behind the player name)
  - Player name (the text colour if not applied by Friend or Enemy)

**Comment by John200410** [comment]
Thank you for the suggestions

**Comment by John200410** [comment]
OnlyShow setting has been done. I will work on Colors now.

**Comment by John200410** [comment]
This has been finished and will be in the next update.
![image](https://user-images.githubusercontent.com/43681932/110689120-54b04f00-81b0-11eb-8b46-6fbc2e0b6158.png)

**Comment by tycrek** [comment]
very epic poggers indeed
