### ISSUE TITLE
[FEATURE] Baritone Window & PacketFly modes

### ISSUE THREAD

**Issue by GentleWither** [John200410/rusherhack-issues#515]
**What feature would you like to be added.**
1.ability to access baritone commands from the windows module
2.packetFly mode:factor/mode:fast

**Is your feature request related to a problem? Please describe.**
packetFly is not good for me bcuz it kicks me in every server

**Additional context**
yes i know this is 2 features but im lazy to open two issues

**Comment by tycrek** [comment]
PacketFly Fast mode exists in RusherHack+

**Comment by John200410** [comment]
> ability to access baritone commands from the windows module

Is this really necessary? You would still have to input coordinates to instruct baritone on where to go
