### ISSUE TITLE
[FEATURE] in-game Time HUD

### ISSUE THREAD

**Issue by tycrek** [John200410/rusherhack-issues#517]
**What feature would you like to be added.**
Show in-game time as a HUD module. It's based around current day tick or something iirc

**Additional context**
If possible I'd like to see both system time and in-game world time as separate HUD modules.

**Comment by John200410** [comment]
Thank you for the suggestion. What do you think the name of the hud element should be?

**Comment by tycrek** [comment]
WorldTime or ServerTime maybe?

**Comment by jumboman32** [comment]
Duplicate of #193
