### ISSUE TITLE
[Feature] Ability to change watermark

### ISSUE THREAD

**Issue by ignelias** [John200410/rusherhack-issues#52]
PLEASE PLEAEE PLEASE

**Comment by FluorideHistorian** [comment]
rip -pre

**Comment by ignelias** [comment]
RIP -PRE

**Comment by John200410** [comment]
The ability to change the watermark text will be added.

**Comment by John200410** [comment]
Added ability to change watermark in v1.1.1
![image](https://user-images.githubusercontent.com/43681932/97224675-dd9d8f80-17a7-11eb-8fb9-25619365e865.png)
