### ISSUE TITLE
[FEATURE] Enderman Look

### ISSUE THREAD

**Issue by newaccountpleaseignore** [John200410/rusherhack-issues#520]
**What feature would you like to be added.**
a module which have 2 modes : avoid and aggravate. both can be client or packet. avoid is going to avoid enderman by not looking at them. aggravate will look at them to make them angry.

**Is your feature request related to a problem? Please describe.**
it should be added because it's useful to have a module which doesn't make enderman angry in the end and you don't need a pumpkin in your head to not aggravate them.

**Comment by ShaderTheBlackKid** [comment]
This would be really useful to me on oldfag.org since it would make getting ender pearls in the end wayyy easier.

**Comment by notperry1234567890** [comment]
> **What feature would you like to be added.**
> A detailed explanation of what this feature should be.
> a module which have 2 modes : avoid and aggravate. both can be client or packet. avoid is going to avoid enderman by not looking at them. aggravate will look at them to make them angry.
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> it should be added because it's useful to have a module which doesn't make enderman angry in the end and you don't need a pumpkin in your head to not aggravate them.
> **Additional context**
> Add any other context or screenshots about the feature request here.

better option would to make this built into avoid not a module called enderman look

**Comment by OMEGA228** [comment]
> better option would to make this built into the already existing avoid module and not a new module called enderman look

No, it should not, because he said Enderman Look module contains 2 modes: aggravate and avoid. So you cant place both of these in rhack Avoid module

**Comment by notperry1234567890** [comment]
> > better option would to make this built into the already existing avoid module and not a new module called enderman look
> 
> No, it should not, because he said Enderman Look module contains 2 modes: aggravate and avoid. So you cant place both of these in rhack Avoid module

meh seems like bloat to me tbh idk if he would add

**Comment by John200410** [comment]
I will probably make this a setting in Avoid.

**Comment by newaccountpleaseignore** [comment]
Any info on the module/setting?

**Comment by John200410** [comment]
This has been added in the next update.
