### ISSUE TITLE
[FEATURE] CleanGUI

### ISSUE THREAD

**Issue by quackitiy** [John200410/rusherhack-issues#522]
**CleanGUI**
A module that would make the background in inventory uis, the game menu ui, etc, become completely transparent, instead of a semi-transparent black background.

Example of what cleangui would look like:
![cleangui](https://user-images.githubusercontent.com/73972058/110853341-1fbbff00-8279-11eb-9023-d8efa0e01797.png)
![cleanguimenu](https://user-images.githubusercontent.com/73972058/110853532-5abe3280-8279-11eb-9bbb-3762ee2d0160.png)

**Comment by John200410** [comment]
I will add a setting under norender to hide the gradient background.

**Comment by John200410** [comment]
This has been added in the next update.
