### ISSUE TITLE
[FEATURE] Arrows HUD

### ISSUE THREAD

**Issue by Mishi04** [John200410/rusherhack-issues#525]
**What feature would you like to be added.**
Add arrows hud (works same as tracers but prettier)

**Is your feature request related to a problem? Please describe.**
I use arrows hud because tracers are ugly and rusherhack doesn't have this. I use xulu for only this module

**Additional context**
![2021-03-12_21 28 51](https://user-images.githubusercontent.com/69492405/111012040-4ada4780-837a-11eb-9103-960aba6848f4.png)

**Comment by fawwaz1234** [comment]
thats radar but u can call it arrow esp

**Comment by John200410** [comment]
RusherHack does have this.

Tracers -> Two Dimensional

**Comment by fawwaz1234** [comment]
JOHN STOP ADDING SECRET MODULES FFS
