### ISSUE TITLE
[FEATURE] Anvil Hitboxignore

### ISSUE THREAD

**Issue by ghost** [John200410/rusherhack-issues#527]
when someone anvilaura you, you cant chug gaps because if you hold rightclick it will turn to the anvil gui

**Comment by notperry1234567890** [comment]
> when someone anvilaura you, you cant chug gaps because if you hold rightclick it will turn to the anvil gui

hit the sneak key and u can gap.........................

**Comment by ProfKambing** [comment]
if u sneak while burrowed u will suffocate....................... smart guy

**Comment by notperry1234567890** [comment]
> if u sneak while burrowed u will suffocate....................... smart guy

cc player moment using burrow 🤣

**Comment by ProfKambing** [comment]
ok, notperry1234567890
