### ISSUE TITLE
[FEATURE] Packet Mine Rotations

### ISSUE THREAD

**Issue by FuzzyRussian** [John200410/rusherhack-issues#531]
**What feature would you like to be added.**
Please add a rotation spoof to packet mine so you do not have to stay looking at the block you are trying to mine.

**Is your feature request related to a problem? Please describe.**
When trying to use RH packet mine it will only work if you remain looking at the block trying to be mined. Some form of rotation spoof would be greatly appreciated.

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
This has been added in the next update.
