### ISSUE TITLE
[FEATURE] Unbind feature + bind shortcuts

### ISSUE THREAD

**Issue by rockeZZergon** [John200410/rusherhack-issues#532]
There is few features that rusherhack need so much
First one is not so important, but would be cool, it's unbind option or "reset" button to unbind a module. Yeah i know, you can bind it on key that you don't use, but sometimes you can accidentaly press this key and it will cause some troubles

The second one is bind shortcuts. I mean currently you can use only single key to bind a module, but some times i have no enough free keys to bind something, so i want to use shortcut (ex: Ctrl + G) to activate a module.

**Comment by John200410** [comment]
> unbind option or "reset" button to unbind a module

Press the DELETE or ESCAPE key on your keyboard.

> so i want to use shortcut (ex: Ctrl + G)

If I allow modifiers to be used with binds, then I would have to disable using normal binds while holding shift, control etc. Many people would prefer not doing that since you wouldn't be able to toggle binds while sprinting.
