### ISSUE TITLE
[FEATURE] Packetmine render

### ISSUE THREAD

**Issue by ProfKambing** [John200410/rusherhack-issues#533]
render a box on the block that is been packet mined.

green box - ready to break
red box - not ready to break

this is useful for knowing when the block is gonna break

**Comment by FluorideHistorian** [comment]
already added

**Comment by ProfKambing** [comment]
wait where

**Comment by FluorideHistorian** [comment]
if you have plus its in fastbreak

**Comment by ProfKambing** [comment]
i know its fastbreak, does it have the render thingy i showed?

**Comment by FluorideHistorian** [comment]
yes

**Comment by FluorideHistorian** [comment]
i said in fastbreak

**Comment by ProfKambing** [comment]
ah ok

**Comment by John200410** [comment]
Already in the next update.
