### ISSUE TITLE
[BUG] I cant install it

### ISSUE THREAD

**Issue by Enderboyscool** [John200410/rusherhack-issues#538]
**Describe the bug**
cant install

**To Reproduce**
Steps to reproduce the behavior: Just let me install it

**Other mods**
List other forge mods you are using (if any):

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/74982613/111554685-fea95180-8743-11eb-91b7-f9daea961ed3.png)
![image](https://user-images.githubusercontent.com/74982613/111554699-05d05f80-8744-11eb-90b2-93f462cb0110.png)

**Additional context**

**Comment by John200410** [comment]
Contact support instead of opening an issue. This is for bug reports and suggestions.

**Comment by ProfKambing** [comment]
buy it and join the discord
