### ISSUE TITLE
[BUG] Notifications for SelfBlock

### ISSUE THREAD

**Issue by Oecher1** [John200410/rusherhack-issues#54]
**Describe the bug**
When you toggle selfblock it wont show a notification for toggling/disabling it wont work with chat or hud notifications.

**To Reproduce**
Steps to reproduce the behavior: Turn on self block and it wont show the notification for enabling/disabling it .

**Other mods**
List other forge mods you are using (if any): Future,Potentia,Gamesense,Inertia,Baritone,Elytrabot

**Expected behavior**
Just to show a notification when enabling/disabling selfblock.

**Screenshots**
Nah.

**Additional context**
Was just messing around and found this bug.

**Comment by John200410** [comment]
This is intentional since this is a macro module that just enables and disables instantly.
