### ISSUE TITLE
Crack accounts on account manager

### ISSUE THREAD

**Issue by CreeperBoy066** [John200410/rusherhack-issues#542]
In main menu you have an option to change accounts (Rusherhack account manager) there you can log in whit an account , but you can't log in with an Crack account
The main reason for this suggestion is for playing on servers like gamster.org jartex.fun (crack servers) with hacks without getting ban
on your main account (premium account)
I hope this suggestion will be added

**Comment by FluorideHistorian** [comment]
-duplicate issue
-stop using rusherhack where its not allowed

**Comment by John200410** [comment]
Stop cheating where it's not allowed. RusherHack is made ONLY for anarchy servers like 2b2t.
