### ISSUE TITLE
[FEATURE] AntiAim Speed Spin option

### ISSUE THREAD

**Issue by ProfKambing** [John200410/rusherhack-issues#543]
make it so u can change the speed of spinning

**Comment by ShaderTheBlackKid** [comment]
Just make a spammer file that does something like 
*yaw -90.1
*yaw -90.2
Etc, then select the file and adjust the spammer delay

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
This has been added in the next update.
