### ISSUE TITLE
[FEATURE] Packet mine auto switch

### ISSUE THREAD

**Issue by FuzzyRussian** [John200410/rusherhack-issues#544]
**What feature would you like to be added.**
While using packet mine you can punch a block, wait the appropriate time for it to be mined and then switch to your pickaxe and the block will instantly break. If there could be an option to auto switch added to packet mine that would be fantastic. If it could be a silent switch that would be great as well. Thank you for your time.

**Is your feature request related to a problem? Please describe.**
NA

**Additional context**
Example: https://medal.tv/clips/47021404/d1337HohlO5d

**Comment by John200410** [comment]
You can use AutoTool
