### ISSUE TITLE
[BUG] Breed command does not breed donkeys

### ISSUE THREAD

**Issue by L-Nadav** [John200410/rusherhack-issues#546]
**Describe the bug**
*breed command doesn't work with donkeys and egaps, 

**To Reproduce**
Go to any server, find a couple donkeys and hold egaps, when you type *breed it won't even try and breed them

**Expected behavior**
It should breed them lol

**Comment by John200410** [comment]
Thank you for reporting this.

**Comment by John200410** [comment]
This has been fixed.
