### ISSUE TITLE
[FEATURE] Advanced Offhand

### ISSUE THREAD

**Issue by ProfKambing** [John200410/rusherhack-issues#548]
make a command so you can make custom offhand
                                                               [additional] button (activate only if this button was pressed)
example `*offhand (mainhand) (offhand) (right-click [hold] )`

maybe too complicated but its only a suggestion lol

**Comment by ProfKambing** [comment]
example: if mainhand has (item) offhand go (item)

**Comment by John200410** [comment]
> example: if mainhand has (item) offhand go (item)

What items would you do this for other than swords?

**Comment by ProfKambing** [comment]
if mainhand (pickaxe) offhand (gapple) if right click (hold)

**Comment by Lempity** [comment]
add right click gap and just update offhand.

**Comment by Lempity** [comment]
Separate "Offhand" & "AutoTotem"

**Comment by ProfKambing** [comment]
^^

**Comment by Mishi04** [comment]
> add right click gap and just update offhand.

^^^^

**Comment by jumboman32** [comment]
Merging.
