### ISSUE TITLE
[BUG] HitboxIgnore

### ISSUE THREAD

**Issue by notperry1234567890** [John200410/rusherhack-issues#55]
**Describe the bug**
Basically if you only turn on players in hitboxignore and every other option off it will ignore not only the players hitbox but every single entity hitbox but if you turn off players and turn on crystals and try to mine through crystals it simply wont work i haven't tried the other options but its just kinda buggy ngl.

**To Reproduce**
Steps to reproduce the behavior: Turn on hitboxignore turn off all other options then players and you wont be able to interact with any hitbox of any kind but if you turn off players and crystals it wont ignore crystal hitboxes its just kinda weird.

**Other mods**
List other forge mods you are using (if any): Future,Potentia,Gamesense,Inertia,Optifine,Elytrabot

**Expected behavior**
When turning on players only in hitboxignore to only ignore players hitboxes not every single hitbox and when turning on crystals it would actually ignore crystals.

**Screenshots**
nah

**Additional context**
Was pvping and saw hitboxignore was kinda glitchy so i used a different clients hitboxignore until this is fixed.

**Comment by John200410** [comment]
Hitbox ignore needs a rewrite.

**Comment by John200410** [comment]
missclicked close

**Comment by John200410** [comment]
This has been fixed. In v1.2 the settings have been revamped.
