### ISSUE TITLE
[FEATURE] Some Suggestions

### ISSUE THREAD

**Issue by 06d** [John200410/rusherhack-issues#550]
1 Ender Chest only burrow setting
2 Different ranbow options for different modules/different hole types
3 CityESP that highlights actual city spots and not just the person's surround
4. Burrow with a player head

1 if a person is about to get in your hole it autoburrows
2 Burrows with only an enderchest
3 i kinda want both holes to be rainbow but different saturations, and you can do the same thing with other modules. like pick crystals to have wireframe but the player have fill chams
4. Not really a "burrow" because you don't really need the jumping action but let it place a player head at your feet while in a hole. way less obvious to see and is very easy to make.

**Comment by jumboman32** [comment]
solid suggestions

**Comment by John200410** [comment]
Thank you for the suggestions.

**Comment by John200410** [comment]
Only EnderChests setting has been added to SelfBlock and will be in the next update.

**Comment by Mishi04** [comment]
> Only EnderChests setting has been added to SelfBlock and will be in the next update.

Selfblock enderchest mode is instaburrow?

**Comment by John200410** [comment]
Only Skulls setting has been added to SelfBlock and will be in the next update.

**Comment by John200410** [comment]
> > Only EnderChests setting has been added to SelfBlock and will be in the next update.
> 
> Selfblock enderchest mode is instaburrow?

What do you mean?
