### ISSUE TITLE
Customizable Discord RPC

### ISSUE THREAD

**Issue by CaptainTheBeam** [John200410/rusherhack-issues#551]
Make it so you can change the name and the image on the discord rpc.

Also unban captain from old and unmute me in rusherhack. John u really need stop with this retarded bias against me I didnt do anything and u know it.

**Comment by FluorideHistorian** [comment]
lol cope

**Comment by CaptainTheBeam** [comment]
shush

**Comment by John200410** [comment]
These are not possible to customize as they depend on what the discord application has the name/image set to.
