### ISSUE TITLE
[FEATURE] Hi John How was your day?

### ISSUE THREAD

**Issue by CaptainTheBeam** [John200410/rusherhack-issues#552]
**What feature would you like to be added.**
A detailed explanation of what this feature should be.

Hi John How was your day?

**Is your feature request related to a problem? Please describe.**

Hi John How was your day?

**Additional context**

Hi John How was your day?

**Comment by CaptainTheBeam** [comment]
john stop bullying me in general

**Comment by CaptainTheBeam** [comment]
john mic up in general

**Comment by CaptainTheBeam** [comment]
john stop talking all big you definitely live in the whitest neighbor hood in North Carolina

**Comment by John200410** [comment]
holy shit shut the fuck up

**Comment by CaptainTheBeam** [comment]
can i be unmuted

**Comment by CaptainTheBeam** [comment]
john i sent it

**Comment by Mishi04** [comment]
WTF xDDDDD
