### ISSUE TITLE
[FEATURE] Wither Norender

### ISSUE THREAD

**Issue by bstar16** [John200410/rusherhack-issues#553]
**What feature would you like to be added.**
Norender for withers

**Comment by John200410** [comment]
Do you want to hide the actual wither entities? Or their projectiles?

**Comment by ShaderTheBlackKid** [comment]
He means the projectiles since they tank your fps, same with shulker bullets and others.

**Comment by bstar16** [comment]
no i don’t mean the projectiles i mean the actual wither

**Comment by John200410** [comment]
Can you provide a use-case?

**Comment by bstar16** [comment]
well if there’s a large amount of withers or your spawning large amounts of withers it can lag your game

**Comment by jumboman32** [comment]
Merging.

**Comment by jumboman32** [comment]
was a duplicate 😤
