### ISSUE TITLE
dispensor a32k[FEATURE]

### ISSUE THREAD

**Issue by phobological** [John200410/rusherhack-issues#556]
**What feature would you like to be added.**
Dispensor auto32k for servers with 32k meta like ECME and impurity.  examples: yakgod.cc, badlion+, bruce client, Impact+ and much more

**Is your feature request related to a problem? Please describe.**
No problem, jsut a request.

**Comment by FluorideHistorian** [comment]
no

**Comment by phobological** [comment]
> no

its an idea jesus

**Comment by FluorideHistorian** [comment]
pretty sure this is either a duplicate issue or john doesnt want to add it

**Comment by dldlglglgluyl** [comment]
lol

**Comment by Mishi04** [comment]
duplicate of #19
