### ISSUE TITLE
[FEATURE] customisable watermark ([Rusherhack]) 

### ISSUE THREAD

**Issue by Tux8068** [John200410/rusherhack-issues#558]
I'd like the rusherhack watermark to be able to be customised, i want it so you can change the name, colour and make it rainbow as well? I think this looks nice and we've paid for a client so I don't want a watermark hard coded into it.

**Comment by jumboman32** [comment]
*watermark ______

**Comment by John200410** [comment]
You can already customize it. Toggle the "Custom" setting and use the *watermark command.
