### ISSUE TITLE
[FEATURE] better control mode

### ISSUE THREAD

**Issue by Tux8068** [John200410/rusherhack-issues#559]
I want control mode to act more like kamiblues, in kamiblue it drops you down but brings you back up to stay on the same level (while having the really nice feet animations, mode aim uses the upward current of the elytrafly while going up in normal aim mode (this beings it up much faster)

**Comment by ProfKambing** [comment]
yes kami blue is strong

**Comment by John200410** [comment]
> mode aim uses the upward current of the elytrafly while going up in normal aim mode

I am confused what you mean by this. Could you provide a video?

**Comment by John200410** [comment]
More information needed.
