### ISSUE TITLE
[BUG] HoleFiller

### ISSUE THREAD

**Issue by Oecher1** [John200410/rusherhack-issues#56]
**Describe the bug**
Was pvping and saw that when using hole filler it would still try to place obsidian in a hole even if a player was standing there already so it messes up clients rotations etc etc.

**To Reproduce**
Steps to reproduce the behavior: Have a player stand in a hole turn on holefiller and it will keep trying to place it even though theres a player already there so it wont fill in other holes near there and will mess up other clients rotations.

**Other mods**
List other forge mods you are using (if any):Future,Potentia,Inertia,Gamesense,Optifine,Baritone,Elytrabot

**Expected behavior**
Didn't expect it to keep trying to place obsidian when a player was in the hole i expected it would just skip past them and fill the other holes.

**Screenshots**
Wont help really.

**Additional context**
Was pvping and saw that it would still try to place obsidian if a player was standing in the hole so it kinda messes up with rotations and wont get other holes that aren't filled yet.

**Comment by John200410** [comment]
This has been fixed in v1.1.1
