### ISSUE TITLE
Basefinder logs spawner chests

### ISSUE THREAD

**Issue by UnknownAstronaut** [John200410/rusherhack-issues#567]
Basefinder logs dungeon chests. I have 10 chest setting but i still get notifications even spawner chests are in different chunks. Kami's stashlogger is much smarter.

**Comment by jumboman32** [comment]
You will find a lot of dungeons near each other, and there is nothing you can do about world generation. Raise the chest limit.

**Comment by jumboman32** [comment]
and duplicate of #565

**Comment by John200410** [comment]
Duplicate of #81
