### ISSUE TITLE
[FEATURE] Stopwatch For 6hr kick

### ISSUE THREAD

**Issue by jumboman32** [John200410/rusherhack-issues#568]
**What feature would you like to be added.**
Automatically starting stopwatch when you connect to 2b2t.

**Is your feature request related to a problem? Please describe.**
It would be nice to know when the 6 hour kick is coming up.

**Comment by John200410** [comment]
Very similar to #210 

Most likely just going to add an "AutoStart" setting which makes it automatically start when you join a server
