### ISSUE TITLE
[BUG] SelfBlock

### ISSUE THREAD

**Issue by Oecher1** [John200410/rusherhack-issues#57]
**Describe the bug**
Selfblock will still make you jump even if you dont have blocks in your hotbar minor annoyance but not any huge bug was just reporting it.

**To Reproduce**
Steps to reproduce the behavior: Don't have any blocks in your hotbar and turn on selfblock and it will still make you jump.

**Other mods**
List other forge mods you are using (if any): Future,Potentia,Inertia,Gamesense,Optifine,Baritone,Elytrabot

**Expected behavior**
Just expected it to say i don't have any blocks without still making me jump.

**Screenshots**
Nope.

**Additional context**
Was messing around and found this small bug.

**Comment by John200410** [comment]
This has been fixed in v1.1.1
