### ISSUE TITLE
[FEATURE] autoez/autogg customizable

### ISSUE THREAD

**Issue by Mishi04** [John200410/rusherhack-issues#570]
**What feature would you like to be added.**
the same as autotoxic but with customizable messages (same as wp2 autoez or gamesense autogg)

**Is your feature request related to a problem? Please describe.**
n/a

**Additional context**
n/a

**Comment by ProfKambing** [comment]
nigga u blind? go .minecraft/rusherhack/autotoxic and you'll find it

**Comment by jumboman32** [comment]
Close.

**Comment by notperry1234567890** [comment]
monkey

**Comment by John200410** [comment]
You can already modify the messages.
