### ISSUE TITLE
[BUG] Potential saving issue?

### ISSUE THREAD

**Issue by GentleWither** [John200410/rusherhack-issues#572]
**Describe the bug**
Friends ,waypionts , and regear wont save deletion of stuff so when i delete a waypiont or a regear kit and restart my minecraft i find the kit/waypiont/friend not removed

**To Reproduce**

**Other mods**
oyvey ,gamesense

**Expected behavior**
idk what to put here

**Screenshots**
noone

**Comment by John200410** [comment]
What exactly are you trying to delete? I'm not able to reproduce any of these.

**Comment by GentleWither** [comment]
yes saving issue
friends and waypoints wont save

**Comment by ShaderTheBlackKid** [comment]
If your game crashes it won't save ofc, you prolly had your game crash/you didn't press "Quit Game" on the title screen

**Comment by GentleWither** [comment]
it doesnt crashes i press the "quit game" button

**Comment by GentleWither** [comment]
i did press the "quit game" button 
still wont save

**Comment by John200410** [comment]
Unable to reproduce.
