### ISSUE TITLE
[FEATURE] PacketMine packet renderer and rotation (for strict servers)

### ISSUE THREAD

**Issue by system69-e** [John200410/rusherhack-issues#574]
packet renderer just highlights the block you are want to packetmine with for example red and then whenever its ready to get mined turns green.
and rotations for 2b and strict servers because it fails most of the time

**Comment by John200410** [comment]
Rotations setting already has an issue open - #531 

I will add the color things.

**Comment by John200410** [comment]
Closing in favor of #579
