### ISSUE TITLE
customizable hud scale ( without changing minecraft gui scale)

### ISSUE THREAD

**Issue by UnknownAstronaut** [John200410/rusherhack-issues#576]
**What feature would you like to be added.**
customizable hud scale ( without changing minecraft gui scale)

**Is your feature request related to a problem? Please describe.**
I wanna minacraft gui scale normal, but small rh hud

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
This has been added in the next update.
