### ISSUE TITLE
[FEATURE] FastBreak Indicator

### ISSUE THREAD

**Issue by jumboman32** [John200410/rusherhack-issues#579]
**What feature would you like to be added.**
A FastBreak indicator that changes color when the block is done being mined.

ref: https://youtu.be/Lr0AqFOEPp8?t=108

**Comment by jumboman32** [comment]
similar to #531 but needed a clear explanation and example

**Comment by John200410** [comment]
> already added, close this

this is different

**Comment by ProfKambing** [comment]
But thats what i said bruh

**Comment by John200410** [comment]
This has been added in the next update.
https://rusherhack.org/i/4el9z4jyue.mp4
