### ISSUE TITLE
[FEATURE] AutoMount mules

### ISSUE THREAD

**Issue by GentleWither** [John200410/rusherhack-issues#584]
**What feature would you like to be added.**
mules into autoMount
**Is your feature request related to a problem? Please describe.**
i cant put chests on mules :(
**Additional context**
add it and automount will be based af

**Comment by John200410** [comment]
Thank you for the suggestion. In the next update I have made the "Donkeys" setting work with Mules.

**Comment by GentleWither** [comment]
Friends and waypoints wont safe deletion of stuff

في السبت، ٣ أبريل، ٢٠٢١ ٩:٤١ ص John ***@***.***> كتب:
