### ISSUE TITLE
[BUG] NoFall bucket

### ISSUE THREAD

**Issue by kono7** [John200410/rusherhack-issues#585]
**Describe the bug**
When it uses the water bucket it only places client sided water

**To Reproduce**
Jump off a height

**Other mods**
None

**Expected behavior**
The water places normally and stops fall damage

**Screenshots**
https://streamable.com/ucb9mi

**Additional context**
None

**Comment by ongoingotrich** [comment]
Are you retarted Minecraft does not work like that. Lol what a clown

**Comment by ongoingotrich** [comment]
Also John unblock me and close this issue

**Comment by kono7** [comment]
sorry bro im "retarted" :(((

**Comment by John200410** [comment]
It does work. In this video it looks like the server's anticheat flagged you.

**Comment by ongoingotrich** [comment]
He has a packet canceler on lol

**Comment by kono7** [comment]
nope i dont
