### ISSUE TITLE
The keybind doesn't work

### ISSUE THREAD

**Issue by Amoureaux** [John200410/rusherhack-issues#586]
I tried pressing everything i could think of: p rshift ~, but none worked
When i tried to change the keybind with the command, again, it didn't work

**Comment by ProfKambing** [comment]
is this the cracked version?

**Comment by Badinek** [comment]
this has happened to me in the past, did your internet go off? anyways the only things you can do is wait until it works again or restart game i guess

**Comment by ShaderTheBlackKid** [comment]
Which version?
