### ISSUE TITLE
suicide option for CA[FEATURE]

### ISSUE THREAD

**Issue by phobological** [John200410/rusherhack-issues#587]
**What feature would you like to be added.**
A setting on autocrystal that turns maxdamage off for suicide bombing/
**Is your feature request related to a problem? Please describe.**
nope i just wanna suicide bomb

**Comment by Mishi04** [comment]
ac will be rewritten xd

**Comment by notperry1234567890** [comment]
> **What feature would you like to be added.**
> A setting on autocrystal that turns maxdamage off for suicide bombing/
> **Is your feature request related to a problem? Please describe.**
> nope i just wanna suicide bomb

phobos be like

**Comment by ShaderTheBlackKid** [comment]
Just turn the max self damage to like 100 then it basically won't take self damage in to account

**Comment by phobological** [comment]
> Just turn the max self damage to like 100 then it basically won't take self damage in to account

max you can set is 10 i think

**Comment by ProfKambing** [comment]
Bruh are u dumb *autocrystal max 36

**Comment by phobological** [comment]
> Bruh are u dumb *autocrystal max 36

kk
