### ISSUE TITLE
[FEATURE] AutoIgnore IgnoreFriend setting

### ISSUE THREAD

**Issue by wce2005a** [John200410/rusherhack-issues#588]
**What feature would you like to be added.**
Add something in autoignore to not ignore friended people, like exclusions but for lazy people

**Is your feature request related to a problem? Please describe.** No
Too lazy to add people to exclusions and would rather have it so people who are added as friends are ignored

**Comment by Mishi04** [comment]
bruh. AppData/roaming/.minecraft/rusherhack/AutoIgnore/Exclusions.txt

**Comment by wce2005a** [comment]
> bruh. AppData/roaming/.minecraft/rusherhack/AutoIgnore/Exclusions.txt

That's why I made this request, I would rather it just ignore friends then me adding specific exclusions, saves time
I know, i'm being lazy.

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
This has been added in the next update.
