### ISSUE TITLE
Totem Pop Notifier[FEATURE]

### ISSUE THREAD

**Issue by 987654323456** [John200410/rusherhack-issues#59]
**What feature would you like to be added.**
The feature would tell you when another player pops a totem and would keep track of how many they have popped. It would send either in chat or as a notification depending on player preference. 
**Is your feature request related to a problem? Please describe.**
It is annoying when pvping and you don't know how many totems your opponent has popped. 
**Additional context**
n/a

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
whoops missclicked close

**Comment by Azurilex** [comment]
I second this, would also be cool if there was an option to notify you about how many totems **you're** popping

**Comment by John200410** [comment]
I have finished this and it will appear in the next update.
