### ISSUE TITLE
Is it possible to transfer rusher hack from one device to the other

### ISSUE THREAD

**Issue by ZoomGC** [John200410/rusherhack-issues#592]
Is it possible to transfer rusherhack from one computer to another, as I heard something about HWID verification

**Comment by ZoomGC** [comment]
Sorry if this doesn’t follow a certain template or something, I just really wanted to know this

**Comment by RemainingToast** [comment]
ask support hwid reset inside the discord

**Comment by John200410** [comment]
Use this for suggestions/bug reports. For questions ask support.
