### ISSUE TITLE
Console doesn't work with large minecraft gui scale 

### ISSUE THREAD

**Issue by UnknownAstronaut** [John200410/rusherhack-issues#593]
Console does not show actions on large minecraft scale
![image](https://user-images.githubusercontent.com/81522942/113509276-668dd380-955d-11eb-84e9-d967aa21cc03.png)

**Comment by jumboman32** [comment]
I was not able to replicate it. Did you resize your Minecraft window?

**Comment by John200410** [comment]
What other mods are you using? What is the size of your monitor?
