### ISSUE TITLE
[BUG] AutoEat Both Mode does not work for health.

### ISSUE THREAD

**Issue by jumboman32** [John200410/rusherhack-issues#595]
**Describe the bug**
AutoEat 'Both' mode does not work.

**To Reproduce**
1. Toggle AutoEat both
2. Get your health below threshold

**Other mods**
None relevant.

**Expected behavior**
AutoEat should make you eat.

**Screenshots**
[reproducing it](https://youtu.be/61JD5sPfXO4)
edit: fixed link

**Comment by John200410** [comment]
Thank you for reporting this.

This has been fixed in the next update.
