### ISSUE TITLE
[FEATURE] draw box on targeted entities in trajectories

### ISSUE THREAD

**Issue by blameinhim** [John200410/rusherhack-issues#596]
i would like to see a indication like a box being drawn on players in trajectories module in stead of a line.

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
This has been added in the next update:
![image](https://user-images.githubusercontent.com/43681932/122691107-7bdcda80-d1fb-11eb-8841-e2a97494a9c1.png)
