### ISSUE TITLE
[FEATURE] EntityList Improvements

### ISSUE THREAD

**Issue by jumboman32** [John200410/rusherhack-issues#598]
**What feature would you like to be added.**
1. The EntityList to be sorted from bottom to top so it can be used at the bottom of the HUD.
2. A color preset so it can be used a text radar. ([example](https://gyazo.com/6f3bb993d2eee41071ee277357a1cbf9))
3. Customizable/Sortable metadata (health, distance, ping, etc)

[second example](https://gyazo.com/7e2e3411e8554bda0d5851c8efc408bf)

**Merged from tycrek's issue**
I'd like to see players and mobs but not items (screenshot grabbed from ESP)

![image](https://user-images.githubusercontent.com/68603817/123661002-28bde580-d802-11eb-8c12-ab19fce1517f.png)

**Comment by John200410** [comment]
Thank you for the suggestions.

**Comment by John200410** [comment]
These things have been added in the next update.
