### ISSUE TITLE
[FEATURE] Tickrate option for TPS in HUD Editor

### ISSUE THREAD

**Issue by jumboman32** [John200410/rusherhack-issues#599]
**What feature would you like to be added.**
An option for the TPS HUD element to be switched to the tickrate.

**Comment by ToxicAven** [comment]
https://github.com/kami-blue/client/pull/2143

**Comment by jennifer-uwu** [comment]
bloat

**Comment by jumboman32** [comment]
> bloat

sorry i know newer players are used to only using TPS but we should be more inclusive of those who are not new to anarchy

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
This has been added in the next update:

![image](https://user-images.githubusercontent.com/43681932/131428621-fde0ea57-7984-4778-b805-f41503ad3e0d.png)
