### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by krispydreams** [John200410/rusherhack-issues#6]
**What feature would you like to be added.** something to do with spotify or any music related program
A detailed explanation of what this feature should be. make it so while you're in game you can do something like *spotify play "song name" or something with *skip *pause *replay 

**Is your feature request related to a problem? Please describe.** yes its not in the client already
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] why isnt this in the client

**Additional context**
Add any other context or screenshots about the feature request here. john give me plus

**Comment by John200410** [comment]
Spotify integration is not going to be added due to it being against their terms to use the Spotify API for commercial products.

**Comment by ProfKambing** [comment]
https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/master/LICENSE

**Comment by John200410** [comment]
> https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/master/LICENSE

That's just a client for the API, not the actual Spotify API. You can read more about the limitations of the Spotify API here: https://developer.spotify.com/terms/

**Comment by John200410** [comment]
https://github.com/John200410/rusherhack-spotify
