### ISSUE TITLE
[BUG] Avoid (Void) does not work if in water

### ISSUE THREAD

**Issue by jumboman32** [John200410/rusherhack-issues#600]
**Describe the bug**
Avoid (Void) does not work if you are underwater.

**To Reproduce**
Jump into void that is covered with water.

**Other mods**
Not relevant.

**Expected behavior**
Avoid should Avoid the void.

**Screenshots**
[Example](https://youtu.be/vcmowdIhxdE)
[Example (2b)](https://medal.tv/clips/48353918/d1337gdmCbt8)

**Comment by jumboman32** [comment]
https://gph.is/g/4DkgApw chog

**Comment by John200410** [comment]
Thank you for reporting this.

**Comment by John200410** [comment]
This has been fixed in the next update.
