### ISSUE TITLE
[FEATURE] better strafe

### ISSUE THREAD

**Issue by Badinek** [John200410/rusherhack-issues#602]
**What feature would you like to be added.**
something like smarter strafe- it would stop strafing if theres block above you (so it doesnt lag back)

**Is your feature request related to a problem? Please describe.**
yes sometimes when im strafing and i go over 2 blocks hole i get rubberbanded because strafe, i know i can just turn it off and then on again but too lazy

**Comment by John200410** [comment]
I will add a setting to not speed-up while a block is above your head. Do you have any suggestions for a name for this setting?

**Comment by Badinek** [comment]
> I will add a setting to not speed-up while a block is above your head. Do you have any suggestions for a name for this setting?

uhh... antirubberband or antiglitch? idk sorry

**Comment by Ozynt** [comment]
mentioned in later issue #972
