### ISSUE TITLE
[FEATURE] More Chams Options

### ISSUE THREAD

**Issue by Lempity** [John200410/rusherhack-issues#604]
**What feature would you like to be added.**
Also having held items option for chams
**Is your feature request related to a problem? Please describe.**
None of the white held item chams.
**Additional context**
![2021-04-06_09 44 17](https://user-images.githubusercontent.com/71273838/113729821-fa29e600-96bc-11eb-906b-43c2abed1e75.png)

**Comment by jumboman32** [comment]
Similar to #43

**Comment by John200410** [comment]
Duplicate of #369
