### ISSUE TITLE
Piston aura

### ISSUE THREAD

**Issue by UnknownAstronaut** [John200410/rusherhack-issues#606]
**What feature would you like to be added.**
Piston aura

**Additional context**
Piston aura

**Comment by Mishi04** [comment]
bruh

**Comment by RemainingToast** [comment]
Who aura

**Comment by FluorideHistorian** [comment]
duplicate issue

**Comment by ShaderTheBlackKid** [comment]
Check the previous issues before making your own. Your not the only one who wants piston aura and duplicate issue

**Comment by obamagaming2069** [comment]
piston aura user = enjoy the pipebomb in your mailbox soon

**Comment by Mishi04** [comment]
> piston aura user = enjoy the pipebomb in your mailbox soon

^^^

**Comment by jumboman32** [comment]
Reference #271

**Comment by tycrek** [comment]
Duplicate of #271. There's a search bar people, use it.
