### ISSUE TITLE
[BUG] hwid is incorrrect

### ISSUE THREAD

**Issue by shadownightfury5** [John200410/rusherhack-issues#607]
**Describe the bug**
Says my hwid is incorrect

**To Reproduce**
Steps to reproduce the behavior: nothing

**Other mods**
List other forge mods you are using (if any): none

**Comment by Mishi04** [comment]
use #support

**Comment by John200410** [comment]
Contact support for support inquires. Only use this for suggestions and bug reports.

**Comment by shadownightfury5** [comment]
I cant find support or a link to the discord

**Comment by John200410** [comment]
Support email is on the website.
