### ISSUE TITLE
[FEATURE] Packet Fast Break Enhancements

### ISSUE THREAD

**Issue by Lempity** [John200410/rusherhack-issues#608]
**What feature would you like to be added.**
Add it so when you can insta break a block with packet fastbreak the render turns green

**Is your feature request related to a problem? Please describe.**
Request

**Additional context**
![2021-04-09_10 09 58](https://user-images.githubusercontent.com/71273838/114201468-d57f7980-991b-11eb-8ee4-cce9ebd30336.png)

**Comment by Mishi04** [comment]
This has been added in the next update

**Comment by ShaderTheBlackKid** [comment]
Ffs read the previous issues since this is already added

**Comment by jumboman32** [comment]
Duplicate of #579

**Comment by John200410** [comment]
Duplicate of #579
