### ISSUE TITLE
Echest Memory Preview[FEATURE]

### ISSUE THREAD

**Issue by ghost** [John200410/rusherhack-issues#61]
**What feature would you like to be added.**
A detailed explanation of what this feature should be.
Would show you what is in your enderchest/shulkerboxes. While it doesn't work on 2b its useful for other servers. Additionally, on 2b, it would remember what was in it and be able to show it to you. Even possibly showing it to you when you look at the shulker that is sitting on the ground. 
**Is your feature request related to a problem? Please describe.**

**Additional context**
The showing whats in the shulkers on the ground is in summit, but it could be improved more.

**Comment by John200410** [comment]
Thank you for the suggestion

**Comment by Ozynt** [comment]
Added in the 1.3 release.
