### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by HeroicMir** [John200410/rusherhack-issues#610]
BetterHotbar:It is a feature on inertia client and it improves the look of your hotbar without the need of a texturepack

**Is your feature request related to a problem? 
No

**Additional context**
![B3A75158-280B-4E8F-AD41-1040339D8DB8](https://user-images.githubusercontent.com/82244315/114250854-bc240f00-99a7-11eb-8c1a-3735e6d0feb7.jpeg)

**Comment by Mishi04** [comment]
Ur using hacks in aspiria mc 🧐

**Comment by FluorideHistorian** [comment]
why do you have a screenshot of someone cheating on your phone

**Comment by John200410** [comment]
Please open a new issue with a better screenshot.
