### ISSUE TITLE
[FEATURE] Searchbar Outline

### ISSUE THREAD

**Issue by hashalite** [John200410/rusherhack-issues#615]
**What feature would you like to be added.**
A colored outline around the clickgui searchbar.

![AA551417-5DF7-46FF-B8E1-5FE1C7F10337](https://user-images.githubusercontent.com/71229440/114292871-b0941f00-9a5f-11eb-966a-62d28cec42ed.jpeg)

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
This has been added in the next update.
