### ISSUE TITLE
[FEATURE] Speed OnGround - 2b2t

### ISSUE THREAD

**Issue by 2b2t-server** [John200410/rusherhack-issues#616]
**What feature would you like to be added.**
A OnGround Speed option for 2b2t.org, like the Future Client one.

**Is your feature request related to a problem? Please describe.**
When I turn on Speed OnGround on 1x2 tunnels, it lags me back to my original position.

**Additional context**
If the option can be added into the OnGround without an option to turn it on/off, I will also accept it.

**Comment by John200410** [comment]
Turn off timer setting and it will work in 2x1 tunnels.
