### ISSUE TITLE
timer doesnt increase my speed anymore

### ISSUE THREAD

**Issue by RubyTheDutchie** [John200410/rusherhack-issues#617]
Describe the bug:
I'm moving at normal speed with timer active and it is set to 4 with tps sync off my jump/drop speed when I jump is increased and interaction but not my movement speed

How did it happen:
It started after I logged back on 9b9t after hopping off for a bit and is constant

Other mods:
Optifine, Baritone

Expected behavior:
to have my movement speed increased by timer

**Comment by SewerHatch** [comment]
it might be not related but timer doesnt work when you have elytra fly on

**Comment by RubyTheDutchie** [comment]
> it might be not related but timer doesnt work when you have elytra fly on

ok ill check if i might have forgotten to turn it off or somethin tomorrow

**Comment by John200410** [comment]
Turn off the UseTimer settings for these modules.
