### ISSUE TITLE
[FEATURE] Long jump auto disable button

### ISSUE THREAD

**Issue by UnzorZ** [John200410/rusherhack-issues#619]
**What feature would you like to be added.**
A button that allows you to auto disable long jump when used like future

**Is your feature request related to a problem? Please describe.**
Just for comfort

**Additional context**
Image taken from the future client: https://imgur.com/KatUP8s

**Comment by John200410** [comment]
I assume it would toggle the module when you rubberband?

**Comment by UnzorZ** [comment]
yeah, and it toggle the module when you use it. if you use it it will automatically disable it

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by Ozynt** [comment]
Added long time ago.
