### ISSUE TITLE
Chams dynamic mode and friend colour[FEATURE]

### ISSUE THREAD

**Issue by Finstaaa** [John200410/rusherhack-issues#62]
Add dynamic mode to Chams mode fill - this changes the colour of the fill depending on how close the entity is like with tracers (green far away, orange medium distance, red close) 

Add friend colour options - make it so with Chams mode fill friended players appear as a different selectable colour

**Comment by John200410** [comment]
Thank you for the suggestion

**Comment by John200410** [comment]
This has been added to v1.1.1
