### ISSUE TITLE
[FEATURE] better packetfly phase

### ISSUE THREAD

**Issue by 278x** [John200410/rusherhack-issues#623]
**What feature would you like to be added.**
better phase in packetfly

**Is your feature request related to a problem? Please describe.**
when i use packetfly it doesnt phase and kicks me when i try to long but moving around and going up works normally

**Additional context**

**Comment by ShaderTheBlackKid** [comment]
Config issue probably

**Comment by 278x** [comment]
i have tried every config doesnt work

**Comment by John200410** [comment]
Duplicate of #221
