### ISSUE TITLE
[FEATURE] More Animations

### ISSUE THREAD

**Issue by Tux8068** [John200410/rusherhack-issues#625]
1) add the bow hit animation, like when you hit something your bow dips down idk how to explain it  basically to recreate it on 1.12.2 you hit something at the same time you bow it
2) add 1.16 drop animation where your hand Goes up

**Comment by John200410** [comment]
Can you please provide video examples?

**Comment by WarriorCrystal** [comment]
i think he means
1. this 1.7 animations for eating/bow charging https://www.youtube.com/watch?v=zhLP0jhAoV4 2:54
2. in 1.16 theres a different animation for dropping items where your hand goes up
