### ISSUE TITLE
[FEATURE] Make EntityList combine duplicates

### ISSUE THREAD

**Issue by hashalite** [John200410/rusherhack-issues#630]
**What feature would you like to be added.**
Instead of showing the same entity multiple times, show it once with a number indicator.

**Is your feature request related to a problem? Please describe.**
If you have the "Max" setting set low, groups of the same entity can prevent you from seeing other entities.

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
This has been added in the next update:

![image](https://user-images.githubusercontent.com/43681932/150903901-819f2b10-286d-4c89-9f03-6f665e1d5b02.png)
