### ISSUE TITLE
[BUG] NoRender Weather Flickering

### ISSUE THREAD

**Issue by hashalite** [John200410/rusherhack-issues#631]
**Describe the bug**
The NoRender Weather setting causes the sky to flicker periodically.

**To Reproduce**
Turn on NoRender Weather and look at the sky.  The bug happens infrequently, so you will probably have to wait.

**Other mods**
Future, Konas

**Comment by John200410** [comment]
Thank you for reporting this.

**Comment by John200410** [comment]
This has been fixed in the next update.
