### ISSUE TITLE
New feature

### ISSUE THREAD

**Issue by Bananapants37** [John200410/rusherhack-issues#633]
So clients like Konas and Pyro client have a hud feature whenever you attack someone it shows how many totems they have popped, health and if they are vulnerable to damage. Here is an example. Thanks :)
![Screenshot 2021-04-13 at 02 25 15](https://user-images.githubusercontent.com/78431215/114506348-a90b7c00-9bff-11eb-8cab-649093cec498.png)

**Comment by Mishi04** [comment]
targethud lol

**Comment by Mishi04** [comment]
John thinks that is useless

**Comment by jumboman32** [comment]
Nametags for disabled people 👎

**Comment by ProfKambing** [comment]
bro i suggested this like a long time ago and john didnt like it

**Comment by tycrek** [comment]
Duplicate of #545 and #360
