### ISSUE TITLE
[FEATURE] Chest Steal Gui button

### ISSUE THREAD

**Issue by dansfilms** [John200410/rusherhack-issues#634]
When in the chest gui can there be a button to toggle Chest Steal and Chest Store to just steal or store all possible the items from the chest

![chrome_3enuNtu8vF](https://user-images.githubusercontent.com/65269878/114571739-3ad7bf80-9cba-11eb-9e36-f0dec2d7bc4b.png)

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by Ozynt** [comment]
Added in the next update.
