### ISSUE TITLE
[BUG][FEATURE] CA selfweb targeting problem

### ISSUE THREAD

**Issue by end41r** [John200410/rusherhack-issues#635]
When an enemy is not in a surround and there is place to place crystals and the enemy selfwebs, rusher stops targeting to this enemy and doesnt place crystals (but he can lol)

Add a check if there is a free place of players surround, that can damage and ignore selfblock or selfweb.

List other forge mods you are using (if any):
Kami Blue (only render)

Expected:
Killing player while he sits in selfblock/selfweb without surround parts
![Снимок экрана 2021-04-13 в 17 25 01](https://user-images.githubusercontent.com/82461251/114578473-2fb26e80-9c7d-11eb-8594-3f1830d939e4.png)

**Comment by John200410** [comment]
Thank you for reporting this.

**Comment by John200410** [comment]
This has been fixed in the next update.

https://rusherhack.org/i/l6o7egxzjb.mp4
