### ISSUE TITLE
[FEATURE] auto onground 2x1

### ISSUE THREAD

**Issue by wce2005a** [John200410/rusherhack-issues#636]
**What feature would you like to be added.**
automatically switch to onground setting or something like that, a mode to make it so you dont switch from bhop to onground, like a 2x1check or something.

**Is your feature request related to a problem? Please describe.**
Annoying to switch to onground mode from a speed mode for 2x1 holes, especially in PvP.

**Comment by ShaderTheBlackKid** [comment]
Just make a macro to switch the modes

**Comment by wce2005a** [comment]
the suggestions i make are for lazy cunts

**Comment by John200410** [comment]
I don't think this would be worthwhile to add. It would be pretty easy to make a macro for this to switch the mode.
