### ISSUE TITLE
[FEATURE] hide suffocation screen in norender

### ISSUE THREAD

**Issue by kono7** [John200410/rusherhack-issues#638]
**What feature would you like to be added.**
An option to hide the block that covers your screen while suffocating

**Is your feature request related to a problem? Please describe.**
It is slightly annoying when the screen is covered and I cannot see anything

**Comment by Mishi04** [comment]
> **What feature would you like to be added.**
> An option to hide the block that covers your screen while suffocating
> 
> **Is your feature request related to a problem? Please describe.**
> It is slightly annoying when the screen is covered and I cannot see anything
> 
> 

You can use noclip and f5

**Comment by ShaderTheBlackKid** [comment]
You can use phase

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
This has been done in the next update.
