### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by Lempity** [John200410/rusherhack-issues#639]
**What feature would you like to be added.**
Ability to turn off AutoReconnect button

**Is your feature request related to a problem? Please describe.**
Using multiple autorecconect buttons looks terrible and in most clients you cant turn it off

**Additional context**
Future+Rusher autoreconnect buttons :face_vomiting: 
![javaw_clUaH9zpwI](https://user-images.githubusercontent.com/71273838/114656738-3e684800-9cb4-11eb-998e-8cb4cbb6d15c.png)

**Comment by Mishi04** [comment]
why did you close this?

**Comment by FluorideHistorian** [comment]
ez solution just stop using other clients

**Comment by Mishi04** [comment]
> ez solution just stop using other clients

^ future is Bad

**Comment by ProfKambing** [comment]
config issue, future is good

**Comment by FluorideHistorian** [comment]
brain issue, future is bad

**Comment by jumboman32** [comment]
> why did you close this?

https://gyazo.com/e63e8ed3f84bb4bb889bf589cf3c1d54

**Comment by Lempity** [comment]
> > why did you close this?
> 
> https://gyazo.com/e63e8ed3f84bb4bb889bf589cf3c1d54

because the problem is no longer valid
