### ISSUE TITLE
[FEATURE] AntiBoatBan

### ISSUE THREAD

**Issue by HermanGoring** [John200410/rusherhack-issues#640]
**What feature would you like to be added.**
AntiBoatBan

**Is your feature request related to a problem? Please describe.**
Nope. Just try to find a workaround for boatbans if i accidentally fall into em when boatbanning people.

**Additional context**
boatban go brrr

**Comment by jumboman32** [comment]
what the fuck

**Comment by system69-e** [comment]
workaround: dont be fucking retarded

**Comment by tycrek** [comment]
you do realize that's a server side problem right? vote for closing
