### ISSUE TITLE
[FEATURE] AnomalyFinder/IllegalFinder

### ISSUE THREAD

**Issue by HermanGoring** [John200410/rusherhack-issues#641]
**What feature would you like to be added.**
A feature that detects unusually large bedrock patches, illegal bedrock, maybe mob heads and other shit.

**Is your feature request related to a problem? Please describe.**
Nope.

**Additional context**
Make it customisable. I would prefer a tracer to point to the block highlighted in red.

**Comment by tycrek** [comment]
Search already has an option for IllegalBedrock:

![](https://x.tycrek.com/‌‌‌​⁠‌⁠⁠‌⁠‍​)

> unusually large bedrock patches

Not much point since you can just [get this from the world seed](https://www.youtube.com/watch?v=vSRAwXMuPSQ)

> maybe mob heads

`*search blocks add skull` should work for this

**Comment by HermanGoring** [comment]
i see
