### ISSUE TITLE
[FEATURE] Optfine cape grabber

### ISSUE THREAD

**Issue by Lempity** [John200410/rusherhack-issues#642]
**What feature would you like to be added.**
Optfine cape grabber (no way this is happening)

**Is your feature request related to a problem? Please describe.**
you would Middle click a player and it would grab there optfine cape and open it in https://www.needcoolshoes.com/banner

**Additional context**

**Comment by jumboman32** [comment]
this would be much more complicated to set up than to just go on namemc

**Comment by John200410** [comment]
Not worthwhile to add.
