### ISSUE TITLE
[FEATURE] Remove VisiblePredicate and force it on

### ISSUE THREAD

**Issue by tycrek** [John200410/rusherhack-issues#644]
**What feature would you like to be added.**

I can't think of any reason to not use it and it makes it much easier to configure things. Personally I think it's best to just remove it completely and force enable it for everyone.

**Comment by ProfKambing** [comment]
whats visiblepredicate

**Comment by tycrek** [comment]
> 
> 
> whats visiblepredicate

Hides settings in a module in ClickGUI when they aren't relevant to the current mode.

**Comment by John200410** [comment]
Instead of removing it, I will just set it to enabled by default.

**Comment by John200410** [comment]
Actually, it is already enabled by default since v1.2
