### ISSUE TITLE
[FEATURE] "AntiRegear"

### ISSUE THREAD

**Issue by Lempity** [John200410/rusherhack-issues#645]
**What feature would you like to be added.**
Not owned to fucker for shulkers so I dont have to turn it off when I regear. or separate module like "AntiRegear"

**Is your feature request related to a problem? Please describe.**
Breaks others shulkers so they cant regear.

**Additional context**

**Comment by jennifer-uwu** [comment]
selective nuker ♿

**Comment by jumboman32** [comment]
Fucker custom blocks?

**Comment by John200410** [comment]
You can just use Fucker with Shulkers enabled.
