### ISSUE TITLE
[FEATURE] RIGHT CLICK GAP

### ISSUE THREAD

**Issue by ProfKambing** [John200410/rusherhack-issues#649]
Offhand right click gap when u have a sword in mainhand

**Comment by tycrek** [comment]
Did you mean "AutoEat should work with gaps in offhand"? Because that's a bug I've had

**Comment by jumboman32** [comment]
He wants offhand to switch to a golden apple while you are holding a sword with packeteat so you can just right click once to eat. (i think)

**Comment by ProfKambing** [comment]
no packeteat, i just want offhand improvement

**Comment by tycrek** [comment]
Like what? "improvement" isn't helpful, what *specifically* do you want improved?

**Comment by ProfKambing** [comment]
offhand gap when sword in mainhand, default item, no hotbar, right click gap, fall distance. like salhack, konas, and gamesense. those are the clients that have good offhand

**Comment by RemainingToast** [comment]
Whilst right clicking with a sword swap to a golden apple and swap back once right click is released

**Comment by ProfKambing** [comment]
^

**Comment by John200410** [comment]
Duplicate of #409
