### ISSUE TITLE
[BUG] Can't break blocks after restarting when using clientsidetime

### ISSUE THREAD

**Issue by Redifier** [John200410/rusherhack-issues#65]
**Describe the bug**
Whenever I start mc and clientsidetime is on I can't break blocks unless I disable and renable.

**To Reproduce**
Start mc turn on clientsidetime, restart mc, launch mc

**Other mods**
I don't use anything that could cause this

https://streamable.com/z2qd0k

**Comment by ignelias** [comment]
i'm on 2b now and it work fine

**Comment by Redifier** [comment]
> i'm on 2b now and it work fine

I mean when I restart and launch again

**Comment by John200410** [comment]
Does this happen on servers?

**Comment by Redifier** [comment]
> Does this happen on servers?

yes

**Comment by John200410** [comment]
Unable to reproduce this.
