### ISSUE TITLE
ANIMATED itemviewmodel [FEATURE]

### ISSUE THREAD

**Issue by y4ndex1** [John200410/rusherhack-issues#650]
A challange for you John. 

Make an animated viewmodel with some type of animations like spin, fov change and scale. Inspired by my brain and abyss (Ciruu codes very well so props to him) 

showcase : https://cdn.discordapp.com/attachments/831114092643221564/831662042729283644/Jdk1.8.0_281_2021.04.14_-_00.46.26.05.mp4

**Comment by jewbob** [comment]
i mean okay but who would use that?

**Comment by jumboman32** [comment]
bloat 👎 
this is probably the worst suggestion out of all 200 issues

**Comment by ShaderTheBlackKid** [comment]
So useless lmfao

**Comment by Mishi04** [comment]
useless and ugly lol
