### ISSUE TITLE
[FEATURE] Stacked minecart storage indicator

### ISSUE THREAD

**Issue by HarryPotter42MC** [John200410/rusherhack-issues#653]
**What feature would you like to be added.**
A detailed explanation of what this feature should be.
https://youtu.be/Ny0VruD8cVk heres what a popular 2b2t youtuber just posted and I think there would be a way to counter it. Make a module wich: Messages you when theres a customizable amount of customizable type of storage minecarts (as furnce, chets and hopper minecarts) minecarts in a costomizable area. It shows the coords inc hat and sends a loud sound to the player. Maybe even a message wich needs to be klicked away so you cna go afk and dont miss the message. 2.d Module: Stacked minecart ESP. Shows a big colored box (customizable lol) around the area where the stacked storage minecarts are. maybe even a tracers option
**Is your feature request related to a problem? Please describe.**
I dont wanna miss out on those hidden stashes
**Additional context**
https://youtu.be/Ny0VruD8cVk video how the technique works

**Comment by John200410** [comment]
You can just use the EntityList hud element to determine if minecarts are being stacked, or look at the shadow of the minecarts.
