### ISSUE TITLE
[FEATURE] Selfblock indicator

### ISSUE THREAD

**Issue by HarryPotter42MC** [John200410/rusherhack-issues#656]
**What feature would you like to be added.**
A detailed explanation of what this feature should be.
An indicator wich is being a text/ filled colour square
![2021-04-16_08 00 13](https://user-images.githubusercontent.com/82435253/114978910-48dc3a80-9e8a-11eb-9993-ca60489bf7ae.png)
![2021-04-16_08 00 01](https://user-images.githubusercontent.com/82435253/114978915-4aa5fe00-9e8a-11eb-874e-a62b22e00b04.png)

 on the screen ich is indicationg if you can do selfblock without getting bugged out and maybe even something that stops you from self blocking when its gonna bug you out
**Is your feature request related to a problem? Please describe.**
I sometimes die when trying to selfblock but getting bugged out on the block
**Additional context**
look in the picture I put in bwlow this

**Comment by ProfKambing** [comment]
what tf is ur hud

**Comment by HarryPotter42MC** [comment]
idk man

**Comment by Mishi04** [comment]
Nice hud 🤑

**Comment by jumboman32** [comment]
How do you expect to predict what the AC is going to do on a laggy server?

**Comment by HarryPotter42MC** [comment]
> How do you expect to predict what the AC is going to do on a laggy server?

thats literally something on every server with anticheat. 1 block gap above you = bug out. 2 full blocks or more are ok

**Comment by jumboman32** [comment]
> > How do you expect to predict what the AC is going to do on a laggy server?
> 
> 
> 
> thats literally something on every server with anticheat. 1 block gap above you = bug out. 2 full blocks or more are ok

Are you referencing burrow fail or knowing if a block is above your head 😂

**Comment by HarryPotter42MC** [comment]
> > > How do you expect to predict what the AC is going to do on a laggy server?
> > 
> > 
> > thats literally something on every server with anticheat. 1 block gap above you = bug out. 2 full blocks or more are ok
> 
> Are you referencing burrow fail or knowing if a block is above your head joy

yes thats how it works

**Comment by jumboman32** [comment]
> > > > How do you expect to predict what the AC is going to do on a laggy server?
> 
> > > 
> 
> > > 
> 
> > > thats literally something on every server with anticheat. 1 block gap above you = bug out. 2 full blocks or more are ok
> 
> > 
> 
> > Are you referencing burrow fail or knowing if a block is above your head joy
> 
> 
> 
> yes thats how it works

I asked a question with two choices and you answered "Yes".

**Comment by HarryPotter42MC** [comment]
> > > > > How do you expect to predict what the AC is going to do on a laggy server?
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > thats literally something on every server with anticheat. 1 block gap above you = bug out. 2 full blocks or more are ok
> > 
> > 
> > > 
> > 
> > 
> > > Are you referencing burrow fail or knowing if a block is above your head joy
> > 
> > 
> > yes thats how it works
> 
> I asked a question with two choices and you answered "Yes".

I used burrow SO MUCH I know when it fails and when it doesnt

**Comment by abt5** [comment]
cant you just look up its pretty easy

**Comment by HarryPotter42MC** [comment]
If im in a fight, I dont wanna look up cause in the time, someone would mine my hole or smth. pvp is quick and this would be very helpful to me and others

**Comment by John200410** [comment]
I'm not adding this. It takes less than a second to move your mouse upwards to check if there is a block above your head.

**Comment by bush-did-711** [comment]
rofl
