### ISSUE TITLE
[FEATURE] Console improvements: arrow-history and tab autocomplete

### ISSUE THREAD

**Issue by tycrek** [John200410/rusherhack-issues#66]
**What feature would you like to be added.**

Would be nice if console behaved like a standard unix terminal where you could use the arrow keys to cycle between commands (and also return to the current incomplete command/blank line).

Also tab autocomplete, and if it's not too much work, a small tooltip or popup showing potential completions (similar to how newer versions of Minecraft do commands).

**Comment by John200410** [comment]
I will probably be able to have the arrow key cycle in v1.2. However, with the autocomplete thing it would be possible to probably implement it with the current command system I would much rather rewrite the command system and possibly use brigadier.

**Comment by John200410** [comment]
Arrow history has been added in the next update. Re-opening another issue for the command completions though
