### ISSUE TITLE
[FEATURE] Sword only critical mode

### ISSUE THREAD

**Issue by ProfKambing** [John200410/rusherhack-issues#660]
i like this idea because i leave aura on all the time with weapon check and criticals made the ca buggy

**Comment by jumboman32** [comment]
Which critical settings are you using? I was not able to replicate with rusherhack crits + both rh and future ca.

**Comment by ProfKambing** [comment]
Im using wp2 ca

**Comment by John200410** [comment]
Criticals doesn't do anything when attacking crystals.
