### ISSUE TITLE
[FEATURE] Packetmine range

### ISSUE THREAD

**Issue by Qwer956** [John200410/rusherhack-issues#661]
**What feature would you like to be added.**
Range setting to packetmine. When you go out of range, it stops rotating towards the block.
**Is your feature request related to a problem? Please describe.**
When I click a block, then go away from the block, it still rotates toward the block and I can't place blocks, open echests, or packetfly normally

**Additional context**
no

**Comment by jumboman32** [comment]
Just toggle it off.

**Comment by jumboman32** [comment]
> Just toggle it off.

Had an anomaly, can verify that toggling does not always fix.

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
This has been added in the next update.
