### ISSUE TITLE
[BUG] Cant get back in server after old discord account terminated

### ISSUE THREAD

**Issue by Craivile** [John200410/rusherhack-issues#664]
**Describe the bug**
I have no way of getting back to the discord server after my old discord account was terminated.

**To Reproduce**

**Other mods**
List other forge mods you are using (if any):

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Mishi04** [comment]
dm John200410#0428

**Comment by Craivile** [comment]
> dm #428

what

**Comment by Craivile** [comment]
> dm #428

Dm what

**Comment by ProfKambing** [comment]
are you retard

**Comment by ProfKambing** [comment]
dm john

**Comment by Craivile** [comment]
> dm john

on here or discord
i emailed him about 2 months ago and he didnt reply

**Comment by ProfKambing** [comment]
https://discord.gg/DK7skcaCA5

**Comment by Craivile** [comment]
> https://discord.gg/DK7skcaCA5

thanks

**Comment by John200410** [comment]
> > dm john
> 
> on here or discord
> i emailed him about 2 months ago and he didnt reply

I reply to all emails unless they are in Spam. Only use this issue tracker for suggestions and bug reports.
