### ISSUE TITLE
[FEATURE] more notification themes

### ISSUE THREAD

**Issue by seqk** [John200410/rusherhack-issues#665]
**What feature would you like to be added.**
more type of notification themes like i have seen some clients have a look exactly like windows notifications 

**Additional context**
i sadly don't have any screenshots as i have no clue where i saw it

**Comment by HermanGoring** [comment]
Would be funny if there was a clippy notification theme. haha

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
Closing in favor of #682
