### ISSUE TITLE
[FEATURE] Fucker AutoDisable

### ISSUE THREAD

**Issue by jumboman32** [John200410/rusherhack-issues#667]
**What feature would you like to be**
A threshold for Fucker after it destroys a certain number of blocks it will disable.

**Additional context**
This would be helpful in PvP.

**Comment by HermanGoring** [comment]
I agree.

**Comment by John200410** [comment]
Can you provide a scenario in which this would be useful?

**Comment by jumboman32** [comment]
> Can you provide a scenario in which this would be useful?

If someone is regearing and you can't mine/explode their shulker, you could get rid of it

**Comment by jumboman32** [comment]
after testing it fucker works fine without it
