### ISSUE TITLE
[FEATURE] Command Suggestions

### ISSUE THREAD

**Issue by HarryPotter42MC** [John200410/rusherhack-issues#668]
**What feature would you like to be added.**
just like in konas or pyro
![grafik](https://user-images.githubusercontent.com/82435253/115351184-46dde880-a1b6-11eb-81f4-fadc1ec242dc.png)
![grafik](https://user-images.githubusercontent.com/82435253/115351221-50ffe700-a1b6-11eb-8378-8da39f0c6707.png)
under this: auto-complete with TAB
![grafik](https://user-images.githubusercontent.com/82435253/115351410-81e01c00-a1b6-11eb-8fb9-bcc1981556b0.png)

**Is your feature request related to a problem? Please describe.**
I hate when I dont know everything I can do with commands

**Additional context**

**Comment by ProfKambing** [comment]
Oh yeah this thing is in kami blue too

**Comment by Mishi04** [comment]
this thing is in wwe 😎

**Comment by John200410** [comment]
Thank you for the suggestions.

**Comment by Ozynt** [comment]
This has been added in the next update.

**Comment by TwoThreeTwo** [comment]
john is a sexy mf
