### ISSUE TITLE
[FEATURE] KillAura Modes

### ISSUE THREAD

**Issue by HermanGoring** [John200410/rusherhack-issues#669]
**What feature would you like to be added.**
Modes for KillAura and different modules for them

(Mode: 32k Mode)

32k Switch: Switches to 32k before attacking if present in hotbar
Throw Reverted: Throws reverted 32ks
(Note: Meant to be binded with Auto32k of another client)

(Mode: Rhythmic)

Will attack at choosen amount of tick delays

for example:

2 ticks, attack, 3 ticks, attack, 1 tick, attack, 3 ticks, attack.......

i find this funny haha. also may help when the tps is low?

(Mode: Health)

Attacks enemy at chosen amount of health, for example if I am on low health and I do not want to crystal, KA activates and attacks the opponent. Useful when you are on low health and you dont want to crystal, and you maybe have no totems

**Is your feature request related to a problem? Please describe.**
No. No problem at all.

**Additional context**
Not applicable.

**Comment by John200410** [comment]
I don't really think any of this would be useful.
