### ISSUE TITLE
[FEATURE] ObbyFarmer (EChestMiner)

### ISSUE THREAD

**Issue by HermanGoring** [John200410/rusherhack-issues#670]
**What feature would you like to be added.**
Places ender chests and breaks with a non-silk touch pickaxe. Preferably with an enchant priority mode (chooses a pickaxe with fortune in your hotbar) and spoof mode (aka not switching slots but still place echests and mine them)

**Is your feature request related to a problem? Please describe.**
Nope.

**Additional context**
Similar to SalHack's EnderChestFarmer, but improved :)

Useful for getting more obby for pvp/building quickly.

**Comment by Badinek** [comment]
duplicate of #498

**Comment by ShaderTheBlackKid** [comment]
> duplicate of #498

No, its a duplicate of 337

**Comment by ShaderTheBlackKid** [comment]
> **What feature would you like to be added.**
> Places ender chests and breaks with a non-silk touch pickaxe. Preferably with an enchant priority mode (chooses a pickaxe with fortune in your hotbar) and spoof mode (aka not switching slots but still place echests and mine them)
> 
> **Is your feature request related to a problem? Please describe.**
> Nope.
> 
> **Additional context**
> Similar to SalHack's EnderChestFarmer, but improved :)
> 
> Useful for getting more obby for pvp/building quickly.

Are you too blind to look if this has already been suggested? This is a duplicate of 337.

**Comment by Badinek** [comment]
> > duplicate of #498
> 
> No, its a duplicate of 337

except that one has 0 explanation lmfao

**Comment by HermanGoring** [comment]
Understandable. Closing issue.

> > **What feature would you like to be added.**
> > Places ender chests and breaks with a non-silk touch pickaxe. Preferably with an enchant priority mode (chooses a pickaxe with fortune in your hotbar) and spoof mode (aka not switching slots but still place echests and mine them)
> > **Is your feature request related to a problem? Please describe.**
> > Nope.
> > **Additional context**
> > Similar to SalHack's EnderChestFarmer, but improved :)
> > Useful for getting more obby for pvp/building quickly.
> 
> Are you too blind to look if this has already been suggested? This is a duplicate of 337.
