### ISSUE TITLE
[BUG] DiscordRichPresence doesnt work on mac

### ISSUE THREAD

**Issue by end41r** [John200410/rusherhack-issues#671]
**Describe the bug**
discord-rpc.jar doesnt work on mac at all

**Expected behavior**
DiscordRPC on mac
![Screenshot](https://user-images.githubusercontent.com/82461251/115428782-0b1d4000-a203-11eb-9d93-8f657afccc17.png)

**Comment by seqk** [comment]
rusherhack doesnt show up in there is just displays on your profile

**Comment by end41r** [comment]
> rusherhack doesnt show up in there is just displays on your profile

It doesnt too
![screenshot]()

**Comment by seqk** [comment]
oh i did not know

**Comment by end41r** [comment]
> oh i did not know

np

**Comment by end41r** [comment]
it works lol
