### ISSUE TITLE
[FEATURE] CockESP

### ISSUE THREAD

**Issue by gerald0mc** [John200410/rusherhack-issues#672]
**What feature would you like to be added.**
Just like in Xatz where it has a rendered cock on your mc player

**Comment by gerald0mc** [comment]
if you add you might get the sucky sucky fun time

**Comment by Mishi04** [comment]
bruh this is offensive xDDDD

**Comment by jumboman32** [comment]
a what?

**Comment by ProfKambing** [comment]
a cockesp

**Comment by RemainingToast** [comment]
If its gonna be accurate the size will be too small to see for most players

**Comment by L-Nadav** [comment]
Kek

**Comment by gerald0mc** [comment]
make it so you can adjust the size of everything

**Comment by YeahOMA** [comment]
this will be most based rusher module

**Comment by bstar16** [comment]
this will be a plus exclusive module

**Comment by DankDupe** [comment]
this is DankDupe approoved

**Comment by HarryPotter42MC** [comment]
please dont make this

**Comment by YeahOMA** [comment]
Make this or I will refund my rusher payment
