### ISSUE TITLE
[FEATURE] Hiding modules from FeatureList

### ISSUE THREAD

**Issue by end41r** [John200410/rusherhack-issues#673]
Adding
![Снимок экрана 2021-04-21 в 09 53 00](https://user-images.githubusercontent.com/82461251/115517368-5d07a980-a287-11eb-9304-89a6745431e0.png)
![Снимок экрана 2021-04-21 в 09 52 56](https://user-images.githubusercontent.com/82461251/115517381-60029a00-a287-11eb-8802-dedc2068c1aa.png)
"HIDE" Option to module (Like in pyro check screenshot nr. 1)

I use really lot of modules 
![Снимок экрана 2021-04-21 в 09 50 04](https://user-images.githubusercontent.com/82461251/115517570-904a3880-a287-11eb-893d-8206afe7530b.png)
 And I dont need them all, but there are modules, that i use in switch (speed, step, elytraflight etc.)
and i want to disable modules like ESP or whatever modules i ALWAYS use and dont turn on/off

**Comment by ProfKambing** [comment]
*drawn (module)

**Comment by end41r** [comment]
> *drawn (module)

rly? wtf didnt know

**Comment by ShaderTheBlackKid** [comment]
Smort
