### ISSUE TITLE
[FEATURE] ShulkerAura

### ISSUE THREAD

**Issue by ProfKambing** [John200410/rusherhack-issues#674]
cheapskate version of piston aura bet you can even code this

https://medal.tv/clips/49517246/d1337KGLkInM

**Comment by Mishi04** [comment]
bro wtf this is 10000iq

**Comment by Tux8068** [comment]
I'm the one that told everyone about that lmfao

**Comment by ShaderTheBlackKid** [comment]
But doesn't the shulker break when the crystal explodes?

**Comment by ProfKambing** [comment]
Did you start play minecraft yesterday?

**Comment by ShaderTheBlackKid** [comment]
So yeah it breaks.

**Comment by ProfKambing** [comment]
No?

**Comment by jumboman32** [comment]
Garbage bloat module. Just install Konas or Gamesense if you want this kind of shit.

**Comment by HarryPotter42MC** [comment]
I already suggested it and John said no

**Comment by HarryPotter42MC** [comment]
> I'm the one that told everyone about that lmfao

then youre late ;D
