### ISSUE TITLE
[FEATURE] Notofications support for Ubuntu 20.04

### ISSUE THREAD

**Issue by HarryPotter42MC** [John200410/rusherhack-issues#675]
**What feature would you like to be added.**
A fix/ workaround for notifications not working on Ubuntu 20.04 #LinuxLivesMatter

**Is your feature request related to a problem? Please describe.**
I hate it when I wanna use it but cant

**Additional context**
I think theres actually a way to use notifications on Ubuntu 20.04
![grafik](https://user-images.githubusercontent.com/82435253/115724064-e5b64080-a380-11eb-8aeb-92144d5ba3ad.png)

**Comment by seqk** [comment]
ubuntu 🤮

**Comment by HarryPotter42MC** [comment]
> ubuntu vomiting_face

and now? youve never used it, dont know it and say stuff abt it

**Comment by HarryPotter42MC** [comment]
> what? i have used it. it is garbage get a better distro

I can use whatever I want ok? why do you just have to say shit that doesnt matter for you

**Comment by Mishi04** [comment]
Ubuntu > Windows

**Comment by jumboman32** [comment]
Use something else or don't use notifications, this is like adding Windows 95 support because one person uses it.

**Comment by Mishi04** [comment]
i use dualboot Windows + Ubuntu 20.04 🤑

**Comment by seqk** [comment]
install gentoo

**Comment by HarryPotter42MC** [comment]
> Use something else or don't use notifications, this is like adding Windows 95 support because one person uses it.

theres actually a bunch of rusher users using Ubuntu. reminder: Ubuntu 20.04 is the 4th most used OS after Windows 10; Windows 7 and MAC OS

**Comment by system69-e** [comment]
people unironically use ubuntu lmao

**Comment by system69-e** [comment]
> > Use something else or don't use notifications, this is like adding Windows 95 support because one person uses it.
> 
> theres actually a bunch of rusher users using Ubuntu. reminder: Ubuntu 20.04 is the 4th most used OS after Windows 10; Windows 7 and MAC OS

yea like 2 people

**Comment by jumboman32** [comment]
This should just be closed unless these "bunch of rusher users using Ubuntu" appear.

**Comment by system69-e** [comment]
> This should just be closed unless these "bunch of rusher users using Ubuntu" appear.

this

**Comment by FluorideHistorian** [comment]
i use ubuntu just not with rusher yet

**Comment by Mishi04** [comment]
me too

**Comment by HarryPotter42MC** [comment]
let Tux live in peace. #PinguinLivesMatter

**Comment by HarryPotter42MC** [comment]
theres like 2 people who hate Ubuntu and dont wanna have that in rh but many rh Ubuntu users theyre just not as active here and dont see the issue

**Comment by L-Nadav** [comment]
I use Ubuntu quite a bit kek

**Comment by John200410** [comment]
There's nothing I can do about this.
