### ISSUE TITLE
[FEATURE] Stashfinder rewrite

### ISSUE THREAD

**Issue by HarryPotter42MC** [John200410/rusherhack-issues#676]
**What feature would you like to be added.**
A rewrite of basefinder orientated to stashes just like kami's one

**Is your feature request related to a problem? Please describe.**
I need to use kami only for it but I dont want to 

**Additional context**
Options:
-log to chat (with coords)
-add waypoint
-sound
-system notification

everything after trapped Chests is the same but just with other storage units (some are entities)
here to make it better to read if you dont wanna get confused asf
Chests
trapped Chests
Shulkers
Furnaces
Droppers
Dispensers
Hoppers
item frames
Chest minecarts
Hopper minecarts
Furnace minecarts

Storage Options:
- Chests yes/ no
  how many chests in an area
  how big area (to bypass scattered around stashes)
  how many doublechests in render distance
  notify if too many over a y level y level
   how high is this y level
- trapped Chests yes/ no
  how many trapped chests in an area
  how big area (to bypass scattered around stashes)
  how many trapped doublechests in render distance
  notify if too many over a y level y level
   how high is this y level
- Shulkers yes/ no
  how many shulkers in an area
  how big area (to bypass scattered around stashes)
  notify if too many over a y level y level
   how many to notify if over this y level
    how high is this y level
- furnaces yes/ no
  how many furnaces in an area
  how big area (to bypass scattered around stashes)
  notify if too many over a y level y level
   how many to notify if over this y level
    how high is this y level
- Droppers yes/ no
  how many droppers in an area
  how big area (to bypass scattered around stashes)
  notify if too many over a y level y level
   how many to notify if over this y level
    how high is this y level
- Dispensers yes/ no
  how many dispensers in an area
  how big area (to bypass scattered around stashes)
  notify if too many over a y level y level
   how many to notify if over this y level
    how high is this y level
- Hoppers yes/ no
  how many hoppers in an area
  how big area (to bypass scattered around stashes)
  notify if too many over a y level y level
   how many to notify if over this y level
    how high is this y level
- Item frames yes/ no
  how many Item frames in an area
  how big area (to bypass scattered around stashes)
  notify if too many over a y level y level
   how many to notify if over this y level
    how high is this y level
- Chest minecarts yes/ no
  how many chest minecarts in an area
  how big area (to bypass scattered around stashes)
  notify if too many over a y level y level
   how many to notify if over this y level
    how high is this y level
- Hopper minecarts yes/ no
  how many hopper minecarts in an area
  how big area (to bypass scattered around stashes)
  notify if too many over a y level y level
   how many to notify if over this y level
    how high is this y level
- Furnace minecarts yes/ no
  how many furnace minecarts in an area
  how big area (to bypass scattered around stashes)
  notify if too many over a y level y level
   how many to notify if over this y level
    how high is this y level

**Comment by HarryPotter42MC** [comment]
I love how noone commented on this cause the tetx is so long lmfao

**Comment by John200410** [comment]
Thank you for the suggestions.

**Comment by jumboman32** [comment]
Merged with #892
