### ISSUE TITLE
[FEATURE] NoRender RidingEntity

### ISSUE THREAD

**Issue by HarryPotter42MC** [John200410/rusherhack-issues#678]
**What feature would you like to be added.**
Something in NoRender:Entities just like RidingBoat but for every entity like horses, minecarts usw so you can see whats under you

**Is your feature request related to a problem? Please describe.**
I hate it when Im on a griefed highway and I dont wanna fall down but I cant see if theres blocks under me or not cause Im using a horse

**Additional context**
just hides the entity your riding in first person

**Comment by John200410** [comment]
I am gonna replace the RidingBoat setting with this. Thank you for the suggestion.

**Comment by John200410** [comment]
This has been done in the next update.
