### ISSUE TITLE
[BUG] MentionHighlight text mode resets formatting

### ISSUE THREAD

**Issue by hashalite** [John200410/rusherhack-issues#681]
**Describe the bug**
MentionHighlight text mode resets the color formatting of the message on some servers.

**To Reproduce**
Enable MentionHighlight text mode and join Constantiam

**Other mods**
none

**Expected behavior**
Only the username color is changed.

**Screenshots**
Constantiam - bug is present
![Constantiam - bug is present](https://user-images.githubusercontent.com/71229440/115984447-18288f00-a575-11eb-81e2-acb867f7927a.png)

Oldfag - works as intended
![Oldfag - works as intended](https://user-images.githubusercontent.com/71229440/115984465-31314000-a575-11eb-888f-df80abf3705f.png)

**Comment by John200410** [comment]
Thank you for reporting this.

**Comment by John200410** [comment]
This has been fixed in the next update:

![image](https://user-images.githubusercontent.com/43681932/150736122-a1ce8ca5-6cf5-48c4-ae10-9ac74f29e358.png)
