### ISSUE TITLE
[FEATURE] better notifications hud

### ISSUE THREAD

**Issue by SoggyBacco** [John200410/rusherhack-issues#682]
notif hud rewrite or more customization options.
the way it is right now can fill up ur screen sometimes

**Comment by jumboman32** [comment]
yeah a max number of pop up notifications that can appear at a time would be cool and if chat notifications could only show one at a time instead of sending multiple

**Comment by Mishi04** [comment]
and a setting for change the position of the notifs

**Comment by John200410** [comment]
Thank you for the suggestions. I will also add a theme option and make a Windows' styled theme

**Comment by jumboman32** [comment]
Merging.
