### ISSUE TITLE
Inverse color hud features/crosshair [FEATURE]

### ISSUE THREAD

**Issue by MIshaTheWarlord** [John200410/rusherhack-issues#687]
I would like an inverse color option to be added to certain hud elements (crosshair and module-list)
Just thought it might look cool, not sure how the text will look though tbh

**Comment by John200410** [comment]
I don't quite understand. Can you elaborate?

**Comment by MIshaTheWarlord** [comment]
So, lets say, for simplicity, that you are looking at a wall in front of you that is completely made of a red block and your crosshair is on that wall. Your crosshair would turn green, because its the opposite (complimentary) color of red.

**Comment by MIshaTheWarlord** [comment]
Other HUD elements could do the same thing, so if your module-list was on the "inverse" setting it would also turn the opposite color of whatever its in front of. I have no idea how any of this would work, just that it might look cool and would end up being a unique feature.
