### ISSUE TITLE
[BUG] Character acting weird after using FastBreak

### ISSUE THREAD

**Issue by OffeeX** [John200410/rusherhack-issues#688]
So, yesterday i used rh's FastBreak (config showed in video below) as instamine, and mined couples of enderchests with it, and today, after i came up to place where i was doing it, my character started acting weird:
- My head started rotating in random directions
- i can't eat food
- I moving weird and getting rubberbanded
- i sprinting when i don't press Left CTRL , and sprint module is toggled off
- i can't place blocks.
- and some other issues.
I was using Konas, but it's not Konas fault, cuz i tested rh without it, and i had same issue.
Looks like my player trying to break a block infinitely that doesn't exist anymore.
Go sprinting when i don't press Left CTRL
https://youtu.be/mNUbDt4S_kU
i can't fix this issue, even as hard as i try. Restarting game doesn't help

UPD: Seems HotbarReplentish causes that shit

**Comment by ProfKambing** [comment]
Youre desynced idiot

**Comment by Mishi04** [comment]
config issue :troll:

**Comment by OffeeX** [comment]
> Youre desynced idiot

yeah ofc desynced. it happens every time i join server, retard

**Comment by ProfKambing** [comment]
Whats ur active modules on konas

**Comment by John200410** [comment]
Some inventory-related modules like HotbarReplenish can cause this.
