### ISSUE TITLE
[FEATURE] NoForceRotate Silent mode

### ISSUE THREAD

**Issue by ProfKambing** [John200410/rusherhack-issues#689]
You still rotate on the server sidd but the rotation on the client side is silent. I think its in Future.

**Comment by Badinek** [comment]
uh im p sure this would desync

**Comment by ProfKambing** [comment]
How could a client sided module would desync

**Comment by jumboman32** [comment]
Maybe if it isn't synced with the server??

**Comment by John200410** [comment]
This would not be helpful.
