### ISSUE TITLE
[FEATURE] New HUD Formatting Option

### ISSUE THREAD

**Issue by Azurilex** [John200410/rusherhack-issues#69]
**What feature would you like to be added.**
Wasn't really sure what to call this feature, but I tried. Anyways, this would add an option under every single HUD element that's text based (TPS, Ping, FPS, Speed, Position, Memory, etc.). Let's say we enable this option for TPS, and our color chosen for TPS is purple. Here's what it would look like: (PURPLE)TPS: (WHITE)20.00. This would make it easier to at a glance, find the information you need without having to really read it. When it's all one color, it makes it harder to quickly read. Maybe don't even make it an option and just make this enabled by default. 

**Is your feature request related to a problem? Please describe.**
Nope

**Additional context**
Sorry about how awkwardly explained this was, I couldn't find the right wording to name this.

**Comment by gcurtiss** [comment]
issue number do be nice tho

**Comment by John200410** [comment]
There is already a color setting for most hud elements, I don't really want to add 2 more settings to those. I will probably just make this a toggle with 1 setting under the hud module alongside a global color picker for the hud elements instead of each one having an individual setting.

**Comment by tycrek** [comment]
> 
> 
> There is already a color setting for most hud elements, I don't really want to add 2 more settings to those. I will probably just make this a toggle with 1 setting under the hud module alongside a global color picker for the hud elements instead of each one having an individual setting.

Does this mean the label ("TPS", "Speed", etc) would use the locally set colour and the value is the global colour, or the other way around? Or if it's possible, have the ability to set either/both to the global value. Maybe "UseGlobal" with options `None/Label/Value/Both`

**Comment by Azurilex** [comment]
> 
> 
> > There is already a color setting for most hud elements, I don't really want to add 2 more settings to those. I will probably just make this a toggle with 1 setting under the hud module alongside a global color picker for the hud elements instead of each one having an individual setting.
> 
> Does this mean the label ("TPS", "Speed", etc) would use the locally set colour and the value is the global colour, or the other way around? Or if it's possible, have the ability to set either/both to the global value. Maybe "UseGlobal" with options `None/Label/Value/Both`

Ideally, I think it would be best to have the label just be flat out white. and only have the color modifier, whether it's global or not, apply to the actual values. If John does decide to make colors global, here's how I could personally see it:

HUD Settings on ClickGUI:
GlobalColor:
UseLabelColor:
LabelColor:

Settings under each individual HUD module that would make use of this setting:
UseGlobalColor:

**Comment by John200410** [comment]
This has been added in the next update: 
![image](https://user-images.githubusercontent.com/43681932/143665436-f0f8dde1-e2b0-417d-90fd-4d9ac48b5166.png)
