### ISSUE TITLE
[FEATURE] AutoCrystal outline option for render settings

### ISSUE THREAD

**Issue by droideka101** [John200410/rusherhack-issues#690]
**What feature would you like to be added.**
be able to turn off the lines on ca render

**Is your feature request related to a problem? Please describe.**
no lines looks better in my opinion 

**Additional context**
![2021-04-28_17 19 03](https://user-images.githubusercontent.com/83362540/116438182-1e08c380-a846-11eb-8fb5-448bda5e1738.png) 
phobos 1.9 ca render

**Comment by jumboman32** [comment]
What lines?

**Comment by droideka101** [comment]
> What lines?

thats a example of what i like (phobos 1.9)

**Comment by seqk** [comment]
do you mean the render block

**Comment by HarryPotter42MC** [comment]
> > What lines?
> 
> thats a example of what i like (phobos 1.9)

how tf am I suppost to know whats going on in phobos lmfao its a rat

**Comment by seqk** [comment]
what phobos isn't a rat lol

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
This has been added in the next update.
