### ISSUE TITLE
[FEATURE] glow mode for hole esp

### ISSUE THREAD

**Issue by droideka101** [John200410/rusherhack-issues#691]
**What feature would you like to be added.**
a glow or fade mode to hole esp 

**Is your feature request related to a problem? Please describe.**
looks nice 

**Additional context**
n/a

**Comment by John200410** [comment]
Can you provide screenshots?

**Comment by HarryPotter42MC** [comment]
I think hes talking about fade.

![grafik](https://user-images.githubusercontent.com/82435253/116809816-6a068180-ab40-11eb-987c-3ddcc845329d.png)
![grafik](https://user-images.githubusercontent.com/82435253/116809823-75f24380-ab40-11eb-95e4-113397862fee.png)
maybe implementing these options

**Comment by Mishi04** [comment]
![unknown-247.png](https://user-images.githubusercontent.com/69492405/116817148-691f2100-ab3b-11eb-8a83-2bac521eeb9c.png)

**Comment by jumboman32** [comment]
Merging.
