### ISSUE TITLE
[BUG] CA placement

### ISSUE THREAD

**Issue by phobologicalt** [John200410/rusherhack-issues#692]
**Describe the bug**
Placement for ca is wack af, it places on two sides when the enemy is in a hole when you faceplace and when they are on flat / exposed
**To Reproduce**
just use a real / fakeplayer and turn on CA, might be my config but i changed it alot and it still does it.

**Other mods**
List other forge mods you are using (if any):
Future 2.10
PineapleClient 1.8.1 (Wurst+2 skid)

**Expected behavior**
For rusher to only place in one spot when faceplacing, and not to have kinda wacky placements

**Comment by John200410** [comment]
This is config error. What are your settings?

**Comment by jumboman32** [comment]
@phobologicalt

**Comment by phobologicalt** [comment]
> @phobologicalt

yes? I messaged john on discord about this by the way
