### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by fredrikww** [John200410/rusherhack-issues#693]
**What feature would you like to be added.**
A detailed explanation of what this feature should be.

I would like if you added packet mode to nofall since it makes nofall better. 

**Is your feature request related to a problem? Please describe.**

It would make nofall much better beacuse how packet mode works. 

**Additional context**

**Comment by ProfKambing** [comment]
Bro are u retarded? Rh already has no fall packet mode

**Comment by Mishi04** [comment]
wtf XD
