### ISSUE TITLE
[question] Cant download installer

### ISSUE THREAD

**Issue by SCO69** [John200410/rusherhack-issues#696]
i have used rhack before but i lost the installer, it is not in my emails, how do i get it?

**Comment by jumboman32** [comment]
i would like to purchase rusherhack for $5

**Comment by Mishi04** [comment]
RusherHack.org/users

**Comment by 0x450** [comment]
go to https://rusherhack.org/users then sign in and download the installer

**Comment by tycrek** [comment]
[RusherHack TOS](https://rusherhack.org/tos.html)
