### ISSUE TITLE
[BUG] Mention highlight background doesn't show while Konas is installed

### ISSUE THREAD

**Issue by hashalite** [John200410/rusherhack-issues#697]
**Describe the bug**
Mention highlight backgrounds don't show while Konas is installed.

**To Reproduce**
1. Install Konas + Rusher
2. Enable Mentions > Highlight > Background
3. Join a server with a join message

Your username will not have a background.

**Comment by John200410** [comment]
Thank you for reporting this. Do you see any mixin errors in your log when you start your game? If so can you post them?

**Comment by hashalite** [comment]
This is what I could find: [https://pastebin.com/bArTsDzc](https://pastebin.com/bArTsDzc)
