### ISSUE TITLE
[FEATURE] Stand still in mid-air with Boost ElytraFly

### ISSUE THREAD

**Issue by Recrucity** [John200410/rusherhack-issues#698]
**What feature would you like to be added.**
Stand still in mid-air with boost elytrafly like in konas client

**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Additional context**
Konas client has a feature which lets you stand still in midair while Elytra Flying with boost mode. I can't find any footage of it nor do I own Konas myselef but it's in the konas changelog.

![image](https://user-images.githubusercontent.com/68477164/116715356-ebda9b80-a9d6-11eb-8950-a590aadf2589.png)

**Comment by ShaderTheBlackKid** [comment]
use timer to slow it down or antipacket

**Comment by HarryPotter42MC** [comment]
why tf do you want that

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
This has been added in the next update.
