### ISSUE TITLE
[FEATURE] AutoEat falldistance mode

### ISSUE THREAD

**Issue by HarryPotter42MC** [John200410/rusherhack-issues#699]
**What feature would you like to be added.**
A option in autoeat wich makes you autoeat when you fall a distance, you would pop or die from

**Is your feature request related to a problem? Please describe.**
I hate if when hause stops my elytra and I pop cause I fall to high

**Additional context**
idk man

**Comment by John200410** [comment]
I don't really think this would be that useful, and it's not very hard to manually eat in that scenario anyway.
