### ISSUE TITLE
Macro Improvements [FEATURE]

### ISSUE THREAD

**Issue by TheRedBlocker** [John200410/rusherhack-issues#70]
**What feature would you like to be added.**
Ability to make macros that do more than one action. It would also add the ability to cycle through enum settings. 
**Is your feature request related to a problem? Please describe.**
I want an offhand that I can toggle on and off and until this is implemented I have to use 2 separate keys
**Additional context**
N/A

**Comment by John200410** [comment]
Thank you for the suggestions

**Comment by John200410** [comment]
This has been added in the next update. Not specifying a specific option will now just increment the mode.
