### ISSUE TITLE
[FEATURE]Chat that slides in from the left

### ISSUE THREAD

**Issue by Lempity** [John200410/rusherhack-issues#701]
**What feature would you like to be added.**
add it so chat slides in from the left

**Is your feature request related to a problem? Please describe.**
add it to extrachat

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by ShaderTheBlackKid** [comment]
John make it si that chat is a HUD element and you can move it to wherever you want to

**Comment by John200410** [comment]
This has been added in the next update:

https://rusherhack.org/i/aym1a088b7.mp4
