### ISSUE TITLE
[FEATURE] Auto switch elytra/chestplate 

### ISSUE THREAD

**Issue by CapWithA-K** [John200410/rusherhack-issues#703]
**What feature would you like to be added?**
I think it would be a good idea to have an auto swap elytra/chestplate.
The way i would see it working is that if you are falling and wearing a chestplate it will auto switch to your elytra while falling. This could work vice versa were if you are walking on land with an elytra equipped it would switch to your chestplate.
Until 2b2t fixes the bug were wearing an elytra on land uses up durability (which has been around for 3 months now) this will really be a useful addition.
Thanks for reading, hopefully that made sense.

**Comment by jumboman32** [comment]
Add a macro to toggle the Elytra Priority setting in AutoArmor that is the same as your keybind for ElytraFly.

ex. `*macro add g autoarmor elytra_priority`
