### ISSUE TITLE
[FEATURE] AutoQueueMain

### ISSUE THREAD

**Issue by HermanGoring** [John200410/rusherhack-issues#710]
**What feature would you like to be added.**
Inputs /queue main at every constant set interval.

**Is your feature request related to a problem? Please describe.**
no

**Additional context**
Used for queueing on 2b2t.

**Comment by John200410** [comment]
All this is useful for is for re-connecting to the 2b2t queue if you get disconnected while queueing. In which case can be mitigated by using the Queue setting in AutoReconnect.

**Comment by ProfKambing** [comment]
Just use spammer lol
