### ISSUE TITLE
Discord Bot Support 

### ISSUE THREAD

**Issue by soham9229** [John200410/rusherhack-issues#713]
**What feature would you like to be added?**
I would like to have Discord Bot Support for RusherHack. 
1. The Bot will have a RPC showing your IGN, Health, Time Elapsed Playing (optional), Postion In Queue ( if in queue ).
2. You could control modules by giving commands to bot ( in DMs or in a seperate personal server ) ( simply what can be done in 2b chat, should be able to be done by giving commands to bot. 

If the user decides to create a personal discord server for bot and his interaction.

3. the bot will save your chat with someone on the server to a discord channel ( Here chat means whenever you /msg someone and someone /msg's you ) 
4. Bot will constantly send you  your Position in queue in a specific channel in the server. And it will give you pings when your pos is below a particular number ( this number can be defined by user ).
5. Also if someone has a RusherHack promo code, the user should be able to check the uses of the code through the bot. 
 

**Is your feature request related to a problem? Please describe.**
No

**Additional context**

Edit : 

Note: Bot will only run when you launch minecraft with RusherHack.

**Comment by jumboman32** [comment]
This would be an insanely large project when discord-minecraft bridges already exist. Making it specific to rusherhack would only limit its usefulness.
