### ISSUE TITLE
[FEATURE] Packet Cancel

### ISSUE THREAD

**Issue by Minilox2** [John200410/rusherhack-issues#715]
**What feature would you like to be added.** packet cancel. used for dupes etc
A detailed explanation of what this feature should be.

**Is your feature request related to a problem? Please describe.** no

**Additional context**

**Comment by ProfKambing** [comment]
already in rusherhack retard config issue brain issue

**Comment by ProfKambing** [comment]
also if ur dumb like -1000 iq you could you search bar which you press (ctrl+f)

**Comment by ShaderTheBlackKid** [comment]
How retarded are you? You open an issue for something that has been in the mod for multiple versions and your too lazy to ask or use the search bar to find it.

**Comment by jumboman32** [comment]
It is called AntiPacket and there is a window for it.
