### ISSUE TITLE
[FEATURE]  auto Search bar

### ISSUE THREAD

**Issue by CapWithA-K** [John200410/rusherhack-issues#719]
**What feature would you like to be added.**

When you have the gui open and you press any key, it will auto enable the search bar
(also make it so when the search bar is open it will disable inventory move)
thanks

**Comment by jumboman32** [comment]
ref: https://upload.jumboman32.club/‍‍‌⁠​‌​‍‍⁠​​

**Comment by John200410** [comment]
AutoFocus setting has been added in the next update.
