### ISSUE TITLE
[BUG] CityESP Rendering Issue

### ISSUE THREAD

**Issue by Azurilex** [John200410/rusherhack-issues#72]
**Describe the bug**
Basically, when CityESP is on it doesn't render all possible city'able blocks. This may not be a bug, but if you notice in the video I linked down further, if you walk away, Nametags breaks, and so does CityESP entirely. This happens with Future's nametags and Rhack's nametags. I'm not sure if the rendering bug is related to CityESP at all, but this is how i encountered it.

**To Reproduce**
Enable HoleESP with CityESP enabled. Turn on nametags. Walk back a bit until you see nametags & cityesp break. Then walk back, you can now see the rendering is broken.

**Other mods**
Future
Pyro (nothing enabled)
World Download
Baritone
Optifine

**Expected behavior**
I expected all city'able blocks to be rendered for ME and the fakeplayer. I also expected Nametags to stay rendered after I left the area.

**Screenshots**
https://www.youtube.com/watch?v=jksoBnGbTog

**Additional context**
N/A

**Comment by TheRedBlocker** [comment]
this affects other clients nametags too besides just rushers and futures

**Comment by John200410** [comment]
Thank you for reporting this

**Comment by John200410** [comment]
This has been fixed in v1.1.1
