### ISSUE TITLE
[FEATURE] Server Finder

### ISSUE THREAD

**Issue by ghost** [John200410/rusherhack-issues#720]
**What feature would you like to be added.**
Server Finder like in wurst

**Is your feature request related to a problem? Please describe.**

**Additional context**

**Comment by ProfKambing** [comment]
provide more info

**Comment by jumboman32** [comment]
I think this might encourage some cheating where it's not allowed

**Comment by sa6ta6ni6c** [comment]
> 
> 
> provide more info

![изображение](https://user-images.githubusercontent.com/69301944/117005302-bfcd5c00-acef-11eb-83c1-7ab9dc7b1077.png)

**Comment by jumboman32** [comment]
cracked minecraft type beat
