### ISSUE TITLE
[FEATURE] Fucker fire mode

### ISSUE THREAD

**Issue by HarryPotter42MC** [John200410/rusherhack-issues#725]
**What feature would you like to be added.**
A option that breaks fire just like the other blocks but with fire
![grafik](https://user-images.githubusercontent.com/82435253/117281382-e0b6be00-ae63-11eb-9d42-6f410b06274e.png)

**Is your feature request related to a problem? Please describe.**
I farmed blazerods and everywhere was fire so the blazerods burned

**Additional context**

**Comment by John200410** [comment]
This has been added in the next update.
