### ISSUE TITLE
[FEATURE]ModuleNotify That doesnt spam

### ISSUE THREAD

**Issue by tescomealdeal** [John200410/rusherhack-issues#726]
**What feature would you like to be added.**
A detailed explanation of what this feature should be.
a mode for module notifier that removes the last client message of somethign being toggled on/off, in pvp where i might be swiftly toggling speed or crystalaura it spams chat which is incredibly annoying

**Additional context**
http://scunthorpe.zone/e1d1dc05b689 ‍screenshot showcasing it

**Comment by John200410** [comment]
Filter setting has been added in the next update.
