### ISSUE TITLE
Auto log, radar or above view.

### ISSUE THREAD

**Issue by TeachingYou** [John200410/rusherhack-issues#727]
Auto log depending on how many totems are in your inventory, Radar that shows peoples name and what blocks are in the area kinda like pyros radar, above view, A birds eye view looking down on you and a customizable distance of hight and length.

No just feel like it would be a good addition.

Radar 
![Screenshot 2021-05-06 210623](https://user-images.githubusercontent.com/83795542/117383470-da016880-aeae-11eb-9560-8c593c5d6454.png)
Above view 
![Screenshot 2021-05-06 210834](https://user-images.githubusercontent.com/83795542/117383607-22b92180-aeaf-11eb-8300-66c9703f254a.png)

**Comment by jumboman32** [comment]
Duplicate and merging.
