### ISSUE TITLE
[FEATURE] "Stop" mode for autototem

### ISSUE THREAD

**Issue by ObeyJuanCannoli** [John200410/rusherhack-issues#728]
**What feature would you like to be added.**
A setting for autototem that stops the player when they pop so that they will get a new totem on servers like 2b that have the updated ncp that patches inventorymove and noslow. Similar to Future's "stop" setting.

**Is your feature request related to a problem? Please describe.**
Many players keep moving when they pop on 2b which would make the autototem fail.

**Additional context**
no

**Comment by ProfKambing** [comment]
i would love a backup item

**Comment by jumboman32** [comment]
Merging.
