### ISSUE TITLE
[FEATURE] offhand settings to make offhand better

### ISSUE THREAD

**Issue by ProfKambing** [John200410/rusherhack-issues#731]
fall distance - self explanatory
right click gap - check sword in mainhand, if true and holding right click, change offhand to gaps
crystalcheck - if theres an player and crystal nearby can cause health lower than totem health, change to totem
no hotbar - dont take item from hotbar

make a command so you can make custom offhand
[additional] button (activate only if this button was pressed)
example *offhand (mainhand) (offhand) (right-click [hold] )

maybe too complicated but its only a suggestion lol

**Comment by jumboman32** [comment]
merging.
