### ISSUE TITLE
[FEATURE] Addition to Better Chat

### ISSUE THREAD

**Issue by AiryXV** [John200410/rusherhack-issues#732]
**What feature would you like to be added.**
www.curseforge.com/minecraft/mc-mods/better-chat/ 

Something like that , It provides a smooth animation of message incoming and outgoing /

**Is your feature request related to a problem? Please describe.**
No its not

**Additional context**
Example : https://youtu.be/SOqtHIBWwS0

**Comment by ProfKambing** [comment]
just download it ffs

**Comment by AiryXV** [comment]
it takes a bit of resources

**Comment by ProfKambing** [comment]
huh, its the same when john adds it to rh

**Comment by jumboman32** [comment]
Duplicate of #701
