### ISSUE TITLE
[FEATURE] Spammer Suggestions

### ISSUE THREAD

**Issue by ghost** [John200410/rusherhack-issues#736]
**What feature would you like to be added.**
Add Random delay (MinDelay and MaxDelay) and Strict mode (adds random symbols to the message)

**Is your feature request related to a problem? Please describe.**
Regular anticheat catches spammer and doesn't allow it to work. Also spammer doesn't work with russian text.

**Additional context**
No additional context.

**Comment by HarryPotter42MC** [comment]
> **What feature would you like to be added.**
> Add Random delay (MinDelay and MaxDelay) and Strict mode (adds random symbols to the message)
> 
> **Is your feature request related to a problem? Please describe.**
> Regular anticheat catches spammer and doesn't allow it to work. Also spammer doesn't work with russian text.
> 
> **Additional context**
> No additional context.

Unicode doesnt work on 2b regardless of spammer.  Random number after the message dont affect antispam. It flags you if you use banned words or repeat words to much.

**Comment by nullemo** [comment]
> > **What feature would you like to be added.**
> > Add Random delay (MinDelay and MaxDelay) and Strict mode (adds random symbols to the message)
> > **Is your feature request related to a problem? Please describe.**
> > Regular anticheat catches spammer and doesn't allow it to work. Also spammer doesn't work with russian text.
> > **Additional context**
> > No additional context.
> 
> Unicode doesnt work on 2b regardless of spammer. Random number after the message dont affect antispam. It flags you if you use banned words or repeat words to much.

no, I use spammer where it allows unicode (russian text)

**Comment by John200410** [comment]
Spammer has had a RandomDelay setting for 2 years.

You can use it with ChatAppend Random setting to get random numbers at the end.
