### ISSUE TITLE
Damage taken option in notifications

### ISSUE THREAD

**Issue by jaamesk** [John200410/rusherhack-issues#740]
Just the title

**Comment by lol420m** [comment]
this is useless just look at your health bar

**Comment by jaamesk** [comment]
do you know what a notifiaction is?

**Comment by lol420m** [comment]
no i dont know what a notifiaction is

**Comment by ProfKambing** [comment]
you’re definitely a konas user sir

**Comment by jumboman32** [comment]
Please re-open the issue using the proper template.
