### ISSUE TITLE
[FEATURE] better hud colors

### ISSUE THREAD

**Issue by jennifer-uwu** [John200410/rusherhack-issues#747]
grey element name and white value, like what future has
![2021-05-03_20 56 19](https://user-images.githubusercontent.com/77944228/118283353-4676fb80-b49d-11eb-9935-888749a5cefe.png)
looks a lot better than a flat color or rgb in my opinion

**Comment by HarryPotter42MC** [comment]
upvote

**Comment by ProfKambing** [comment]
#69 already exist

**Comment by jumboman32** [comment]
Closing in favor of #69

**Comment by ProfKambing** [comment]
FUNNY NUMBER ISSUE
