### ISSUE TITLE
[BUG] Custom watermark does not apply immediately after launching, need to toggle

### ISSUE THREAD

**Issue by tycrek** [John200410/rusherhack-issues#75]
**Describe the bug**
Having a custom watermark set does not show the watermark at first after launching the game.

**To Reproduce**
You need to toggle the HUD module off and on to apply it.

**Other mods**

- Xaero's minimap/worldmap
- Sound Filters
- Rebind Narrator
- Neat
- Light Level Overlay Reloaded
- Chunk Animator
- Armor Chroma
- Apple Skin

**Expected behavior**
Show custom watermark right at the start

**Comment by John200410** [comment]
Thank you for reporting this.

**Comment by John200410** [comment]
This has been fixed in v1.1.2
