### ISSUE TITLE
[FEATURE]Burrow improvements

### ISSUE THREAD

**Issue by Qwer956** [John200410/rusherhack-issues#757]
**What feature would you like to be added.**
Make burrow work in 3 block high area and make rotate silent

**Is your feature request related to a problem? Please describe.**
Burrow doesn't work in 3 block high area and the rotate isn't silent

**Additional context**
no

**Comment by ProfKambing** [comment]
rotate is silent for me

**Comment by HarryPotter42MC** [comment]
same. I see the caracter doing it in F5 but my head doesnt get moved

**Comment by Qwer956** [comment]
Oh yea my head doesn't move if I use noforcerotate but still doesnt work in 3 block high

**Comment by ProfKambing** [comment]
john should add (fake jump) height/offset

**Comment by jumboman32** [comment]
Merging.
