### ISSUE TITLE
[FEATURE] Advanced Rainbow customization

### ISSUE THREAD

**Issue by nekounderscore** [John200410/rusherhack-issues#76]
**What feature would you like to be added.**
- That you can like let the rainbow cycle through 2 colors for example it will go through all purple stages to blue and back and to blue etc. Also can do like from purple to white and back. 
- That you can change the rainbow direction; Let it go sideways to the right or the left or upwards or downwards.

**Is your feature request related to a problem? Please describe.**
Nope not a problem

**Additional context**
I can provide examples via recording if needed if this is a little shady.
i am the neko#0001

**Comment by John200410** [comment]
Thanks for the suggestion. Could you comment with some examples? I think I know what you are asking for but I want to make sure

**Comment by jumboman32** [comment]
Closing in favor of #539
