### ISSUE TITLE
[FEATURE] Wireframe visual hack

### ISSUE THREAD

**Issue by MoreOrgasm** [John200410/rusherhack-issues#761]
Second suggestion i had, wireframe, as i used it a lot back when i was playing on impact

draws the outline of blocks that are facing airblocks and empties the middle of the block

I personally found it to makes detection of caves when you're inside a cave easier, player tunnels too, 
confuses my brain less, since no texture are reversed etc

Thanks !

**Comment by SoggyBacco** [comment]
aready a thing in chams
mode: wireframe

**Comment by MoreOrgasm** [comment]
That's not the same thing, that's for models so mobs and players for exemple, what i am suggesting is for blocks

**Comment by John200410** [comment]
Just use the CaveFinder module which was made for this purpose.

**Comment by MoreOrgasm** [comment]
You can't play with cavefinder on 24/7, since it removes blocks directly in your view, same way a xray would, this mod doesn't do that, they don't have the same purpose, wireframe doesn't remove anything

**Comment by ProfKambing** [comment]
so ur saying ur playing with wirefram 24/7

**Comment by MoreOrgasm** [comment]
I played with it for extended periods, hours, especially on highways where you spend a LOT of time, i can't do that with cavefinder

**Comment by FluorideHistorian** [comment]
config issue

**Comment by MoreOrgasm** [comment]
What do you mean

**Comment by ShaderTheBlackKid** [comment]
Just use a wireframe texture pack

**Comment by MoreOrgasm** [comment]
it's a feature of multiple free clients, i can't see why it shouldn't be added to be honest

**Comment by MoreOrgasm** [comment]
Here's the screenshot of a wireframe module

there's also a parameter to change the width of the lines

![2021-05-21_21 43 00](https://user-images.githubusercontent.com/84248880/119191525-0d332280-ba7f-11eb-9132-83a014955069.png)

**Comment by John200410** [comment]
Thank you for the suggestion. This has been added in the next update:
![image](https://user-images.githubusercontent.com/43681932/119218566-f60c2900-baae-11eb-9faa-dd94bca616b6.png)
