### ISSUE TITLE
[FEATURE] AntiDisconnect Window

### ISSUE THREAD

**Issue by ItzDawnfall** [John200410/rusherhack-issues#767]
**What feature would you like to be added.**
Have antidisconnect apply to closing the game itself to prevent closing the game by accident

**Comment by Bananapants37** [comment]
It’s pretty hard to hit cntrl + q or alt + f4 on accident

**Comment by HarryPotter42MC** [comment]
> It’s pretty hard to hit cntrl + q or alt + f4 on accident

doesnt matter. still a good thing

**Comment by Bananapants37** [comment]
How would that work tho cuz the computer is closing the application not mc

**Comment by ItzDawnfall** [comment]
> How would that work tho cuz the computer is closing the application not mc

Idk lol, I think impact or pyro has it

**Comment by ItzDawnfall** [comment]
> It’s pretty hard to hit cntrl + q or alt + f4 on accident

There's been times where I've accidentally pressed the close button

**Comment by HarryPotter42MC** [comment]
> > It’s pretty hard to hit cntrl + q or alt + f4 on accident
> 
> There's been times where I've accidentally pressed the close button

same

**Comment by Bananapants37** [comment]
First dawnfall they might from my experience they don’t but yea. Also for the rest there is a software that can lock those buttons maybe that can be an alternative rather than stopping the game from shutting down

**Comment by jumboman32** [comment]
The AntiSisconnect was so scuffed in pyro, There are much better programs that make it less difficult to close any windows. I suggest using those.

**Comment by John200410** [comment]
This has been added in the next update.
