### ISSUE TITLE
[FEATURE] Horse strengh command

### ISSUE THREAD

**Issue by HarryPotter42MC** [John200410/rusherhack-issues#768]
**What feature would you like to be added.**
Something where I can see how fast my horse is and how high it can jump **in numbers** to get a perfect horse. Maybe even Health

**Is your feature request related to a problem? Please describe.**
I hate it when I dont have a perfect horse :rage: 

**Additional context**
Speeds
 1 Horse's movement speed ranges from 0.1125–0.3375 in internal units, with an average of 0.225. For reference, the player's
 normal walking speed is 0.1.
 2 4.74 blocks/second to 14.23 blocks/second
Jump heights
 1 Horse's jump strength ranges from 0.4–1.0, with an average of 0.7.
 A jump strength of 0.5 is enough to clear 1 9⁄16 blocks, while 1.0 is enough to clear 5 1⁄2 blocks. 
Health
 1 Horse's hearts ranges from 15–30, with an average of 22.5  (♥ × 11.25.)
 
[https://minecraft.fandom.com/wiki/Horse]

**Comment by jennifer-uwu** [comment]
this but for nametags

**Comment by jumboman32** [comment]
Riding HUD. I talked about this a few times, but this is a decent idea.

**Comment by John200410** [comment]
This has been added in the next update as a setting in Nametags:

![image](https://user-images.githubusercontent.com/43681932/130164755-e0dfd15d-b4db-4b9c-8186-6808c235bc18.png)
