### ISSUE TITLE
[BUG] Gui scrolling is tied to framerate, and not delta time

### ISSUE THREAD

**Issue by Gav06** [John200410/rusherhack-issues#770]
**Describe the bug**
When you scroll up and down inside of the gui panels, it would normally scoll back to where the modules are showing, but the animation runs much slower if your framerate is lower

**To Reproduce**
Scroll up and down in the clickgui with a low framerate

**Other mods**
List other forge mods you are using (if any):
Other mods were used, but they should not affect it.

**Expected behavior**
I expected the scrolling to be independent of the framerate

**Screenshots**
If applicable, add screenshots to help explain your problem
I don't have a screenshot, but I have a [video](https://streamable.com/8adtf3) of it. 

**Additional context**
n/a

**Comment by TwoThreeTwo** [comment]
Can you host the video with GitHub? It's no longer viewable

**Comment by John200410** [comment]
This has been fixed in the next update.
