### ISSUE TITLE
[FEATURE] OnGround only condition for SelfBlock

### ISSUE THREAD

**Issue by end41r** [John200410/rusherhack-issues#777]
So, im very often playing on crystalpvp and sometimes, when im not yet in a hole and i click on selfblock bind it pushes me up from hole and i lose

Its related to a problem, selfblock doesnt have && player.OnGroung condition for selfblock onEnable()

**Comment by ProfKambing** [comment]
yes

**Comment by John200410** [comment]
This has been done in the next update.
