### ISSUE TITLE
[FEATURE] Stash Sorter

### ISSUE THREAD

**Issue by huddy987** [John200410/rusherhack-issues#78]
**What feature would you like to be added.**
A module which automatically sorts chests for you. Here's how it would work:
1. The user enables a "Pull Chests" mode inside the module. When a user right clicks a chest this will mark the chest as a chest that they want to pull unsorted items from.
2. The user enables a "Sort Chests" mode inside the module. When a user right clicks a chest with an item in their hand, that chest will be marked as a chest to put said item in.
3. The user enables the module. Using baritone, the user goes back and forth pulling items from the "pull chests" and putting them into the correct "sort chest"

**Comment by John200410** [comment]
Thank you for the suggestion

**Comment by jumboman32** [comment]
ref to #880
