### ISSUE TITLE
[FEATURE] egap finder

### ISSUE THREAD

**Issue by L-Nadav** [John200410/rusherhack-issues#784]
**What feature would you like to be added.**
A module that records egap coords, also should automatically place a waypoint to the next coordinate. Also a chunk pregenerator would be useful. 

**Is your feature request related to a problem? Please describe.**

**Additional context**

**Comment by jumboman32** [comment]
Not sure if he will add this when [this](https://pastebin.com/mPxTyWgt) exists.

**Comment by L-Nadav** [comment]
Yes I am aware that it exists, I was there when it was made xD, however I think that it would be a useful feature in rh and the automatic waypoint idea would be very useful + chunk pregenerator

**Comment by jennifer-uwu** [comment]
sounds like a lot of work for a feature almost no one would use

**Comment by L-Nadav** [comment]
What? Every single oldfag player would use this? Don't close this because *you* wouldn't use it.

**Comment by jumboman32** [comment]
It already exists, there is no incompatibility issue, and the current mod works as intended. It is useless.
