### ISSUE TITLE
[FEATURE] Smart Hole ESP + Glow Mode

### ISSUE THREAD

**Issue by 06d** [John200410/rusherhack-issues#788]
Shows whenever someone is in a web, in fast pace situations in crystal pvp you might not think about it and get caught in a web.
Web esp will prevent that p much

Like a smart HoleESP option Showing if a cobweb is in a hole

and glow mode for hole esp

**Comment by jumboman32** [comment]
Use search.

**Comment by 06d** [comment]
> Use search.

if someone has a shit pc and they're on cc they're pc will blow up pretty much. im talking like if the web is in a hole

**Comment by jumboman32** [comment]
oh so like a smarter hole esp. i think this would be nice, a burrow esp would be cool too

**Comment by 06d** [comment]
> oh so like a smarter hole esp. i think this would be nice, a burrow esp would be cool too

exactly

**Comment by John200410** [comment]
HoleESP already doesn't show holes with cobweb.

Glow setting has been added in the next update:
![image](https://user-images.githubusercontent.com/43681932/130369085-b71ba246-5bce-4315-b7c3-d48c9d15e842.png)
