### ISSUE TITLE
Mode Smart on OnGround Speed [FEATURE]

### ISSUE THREAD

**Issue by SilverEyes2b2t** [John200410/rusherhack-issues#790]
**What feature would you like to be added.**
A "smart" mode for the Speed setting "OnGround." This "smart" mode will turn off the module when you are not in a 1 x 2 tunnel. As on 2b2t, (and most other anarchy servers) "OnGround" only works in a 1 by 2 tunnel.

**Additional context**
Here is a video I uploaded showcasing this idea

https://youtu.be/ssx4aRq98gI

**Comment by MoreOrgasm** [comment]
That's a cool idea

would it turn back on when you re-enter a 1x2 tunnel ? that'd be nice

**Comment by SilverEyes2b2t** [comment]
> That's a cool idea
> 
> would it turn back on when you re-enter a 1x2 tunnel ? that'd be nice

yes

**Comment by John200410** [comment]
This has been added in the next update: https://www.youtube.com/watch?v=FEaY6bVCzyI
