### ISSUE TITLE
[FEATURE] Logout Bind

### ISSUE THREAD

**Issue by HermanGoring** [John200410/rusherhack-issues#791]
**What feature would you like to be added.**
A feature where you can bind a key to, and it disconnects manually for you

**Is your feature request related to a problem? Please describe.**
No.

**Additional context**
If AutoLog or AutoDisconnect fails, i can press a key to instantly log out when I am being crystalled on 2b2t at 0,0. AutoDisconnect failed like 2 times.

**Comment by jennifer-uwu** [comment]
how would auto log fail? that sounds like a config issue
