### ISSUE TITLE
[FEATURE] Entity Logger

### ISSUE THREAD

**Issue by ClassicalBlueTooth** [John200410/rusherhack-issues#793]
**What feature would you like to be added.**
An entity logger which allows you to select 1 or more entities and notifies you when one comes in view range. e.g. you need a donkey, you add it and enable it and as you fly when donkeys come into the render distance it notifies you.

**Is your feature request related to a problem? Please describe.**

**Additional context**

**Comment by jumboman32** [comment]
I think this is already a thing in base finder. A player logger would be nice though.

**Comment by ClassicalBlueTooth** [comment]
> I think this is already a thing in base finder. A player logger would be nice though.

Oh, it indeed is. Although limited to donkeys and llamas.

**Comment by John200410** [comment]
An Alert setting has now been added to Search Entities in the next update:
![image](https://user-images.githubusercontent.com/43681932/122653363-eca7c800-d111-11eb-82de-7543a08977f7.png)
