### ISSUE TITLE
[FEATURE] antiweb

### ISSUE THREAD

**Issue by jennifer-uwu** [John200410/rusherhack-issues#799]
https://streamable.com/v0a598

something like this to spam downward movement packets and cancel any rotations to prevent setbacks
this would help in crystal pvp since lots of people use webs on 2b now
this could be a setting in noslow to complement issue #798

**Comment by jumboman32** [comment]
"web noslow rubberbands you when you are falling through the web but works well once you are on the ground.
this would be helpful for crystal pvp servers like 2b2t where players use webs frequently"
merging bc similar

**Comment by jumboman32** [comment]
Merging.
