### ISSUE TITLE
Boatfly Lavastream Avoid[FEATURE]

### ISSUE THREAD

**Issue by TheRedBlocker** [John200410/rusherhack-issues#80]
**What feature would you like to be added.**
It would prevent you from flying into lava streams/lava pools/fire while boat flying in the nether. This would make it easier to fly so your boats do not break. 
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I'm boat flying in the nether and I fly into a lava stream and my boat breaks.

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by jumboman32** [comment]
Not relevant anymore.
