### ISSUE TITLE
[FEATURE] Surround Feature/Bug??

### ISSUE THREAD

**Issue by NutrientAphid** [John200410/rusherhack-issues#800]
Strict mode for surround

On servers that have strict anticheat, when surround is activated it starts to put blocks through the walls and it gets bugged.

**Comment by jennifer-uwu** [comment]
this is an issue with surround trying to place unnecessary blocks below your feet, when this is fixed that will no longer be an issue

**Comment by John200410** [comment]
This has been fixed in the next update.
