### ISSUE TITLE
Anti fall damage (or just damage in general) concept.

### ISSUE THREAD

**Issue by Chiwarn** [John200410/rusherhack-issues#803]
In almost all versions of Minecraft, falling from a deadly height (or any height) than logging out of the game 4 blocks or less before touching the ground, then logging back in results in no fall damage whatsoever. My idea is anti-fall damage will log you out about 3 blocks above the ground preventing fall damage. This can also go for more things. When logging in to a game you get a very short time of invincibility. ( I don't know if this goes for multiplayer ) it logs you out every time the invincibility wears off. it might be very tedious in 2b2t (which has a queue) but this feature can be a last resort kind of thing in case you have a lot on the line just cannot die.

**Comment by jumboman32** [comment]
This is a server feature not a minecraft feature, but I think a FakeKick module with this as a setting would be nice.
