### ISSUE TITLE
BaseFinder improvements

### ISSUE THREAD

**Issue by ignelias** [John200410/rusherhack-issues#81]
make minecart chests not be the same as chests on base finder so it doesn't log mineshafts 

make it so base finder has an option to not log dungeon chests by making it so if theres a mob spawner within 5 blocks of a chest it doesn't log it

make it so you can log nether portals with base finder

**Comment by John200410** [comment]
Thank you for the suggestions

**Comment by jumboman32** [comment]
Merged with #892
