### ISSUE TITLE
[FEATURE] Desktop notification for when BaseFinder Finds a base/stash

### ISSUE THREAD

**Issue by 2147483647ms** [John200410/rusherhack-issues#814]
Pretty much just does a windows notification on your desktop when BaseFinder finds a stash and makes a loud noise

**Comment by jennifer-uwu** [comment]
basefinder already has a notification setting

**Comment by jaamesk** [comment]
basefinders notification mode is only a rusherhack notification not a windows one

**Comment by jumboman32** [comment]
Merged with #892
