### ISSUE TITLE
Auto Iron golem

### ISSUE THREAD

**Issue by Chiwarn** [John200410/rusherhack-issues#815]
It's quite simple, it's auto-wither expect it's with iron golems in case you need to protect your base or something.

**Comment by jaamesk** [comment]
bloat

**Comment by Mishi04** [comment]
who the hell protects his base with iron golems??

**Comment by Chiwarn** [comment]
> who the hell protects his base with iron golems??

Or you could just spawn one mid-fight lol

**Comment by MIshaTheWarlord** [comment]
This shit's fuckin dumb

**Comment by end41r** [comment]
Useless shit...

**Comment by Bananapants37** [comment]
How tf would that be useful it ain’t that hard

**Comment by DqrkCap** [comment]
protecting base with iron golems?LOL

**Comment by MoreOrgasm** [comment]
i mean it would be pretty funny to be fair, pretty much useless but you could spam gollems at spawn just for the sake of it,

idk how much use you could get of them in pvp tho considering they get killed so easily

**Comment by end41r** [comment]
It could be an enhancement for AutoWither module, so you could choose what to build (wither -> golem -> snow golem)

**Comment by jennifer-uwu** [comment]
no
