### ISSUE TITLE
[FEATURE] Show queue position in RPC

### ISSUE THREAD

**Issue by tycrek** [John200410/rusherhack-issues#82]
**What feature would you like to be added.**
Show the queue position in Discord Rich Presence. Instead of it showing `(1 of 1)` like it currently does, it could do `([position] of [players in queue])`. Players in queue could either come from the lolritter API or just set it to the first position on join.

![rusherhacksuggestion](https://user-images.githubusercontent.com/29926144/97816895-f4cff780-1c55-11eb-8e80-93922876106d.png)

**Comment by 0popbob** [comment]
and name of the account

**Comment by John200410** [comment]
Thank you for the suggestions

**Comment by John200410** [comment]
This has been added in the next update:
![image](https://user-images.githubusercontent.com/43681932/114297803-ca922980-9a80-11eb-8868-78d6e1db1c94.png)
