### ISSUE TITLE
[FEATURE] Make Search & Xray NOT reload chunks

### ISSUE THREAD

**Issue by tycrek** [John200410/rusherhack-issues#827]
**What feature would you like to be added.**

It's really annoying and most other clients can toggle these without needing to reload every chunk

**Comment by ItzDawnfall** [comment]
I for one like it reloading chunks. It's quicker than doing f3+a

**Comment by tycrek** [comment]
I don't really see how. I dislike it because if I preload chunks for a screenshot, then toggle my render modules, it resets all my preloaded chunks and I have to reload them. 
Jun. 2, 2021, 1:01 a.m. by ***@***.***:

**Comment by jumboman32** [comment]
should just be an option then

**Comment by John200410** [comment]
This has been added in the next update:
https://www.youtube.com/watch?v=JB6lekzh5Q8
