### ISSUE TITLE
[BUG] Enabling/Disabling Packets Kicks From Server/Crashes Game

### ISSUE THREAD

**Issue by FuzzyRussian** [John200410/rusherhack-issues#831]
**Describe the bug**
If you enter the rusher menu by pressing " ` " and enable/disable the packets in rapid succession while on 2b2t I was kicked from the server. I then tried to recrate it and my game crashed. I was able to replicate this with "AntiPacket" enabled and disabled.

**To Reproduce**
Steps to reproduce the behavior: Go into the rusher menu and enable/disable the packets for AntiPacket quickly while in a server.

**Other mods**
Baritone api forge 1.2.14
kami blue highway tools fork v9.8
konas
OptiFine
World downloader
XaerosWorldMap 1.11.5

**Expected behavior**
I expected to just be able to enable/disable what packet I wanted to cancel.

**Screenshots**
NA

**Additional context**
NA

**Comment by John200410** [comment]
Can you please provide a crash log?
