### ISSUE TITLE
[FEATURE] raise armor hud while in water

### ISSUE THREAD

**Issue by jennifer-uwu** [John200410/rusherhack-issues#837]
setting for armor hud to raise a bit while in water to not overlap with bubbles
![2021-06-04_13 46 09](https://user-images.githubusercontent.com/77944228/120842926-6dc06600-c53b-11eb-8fcb-3bd00bd5e40c.png)

**Comment by John200410** [comment]
This has been added in the latest update:

https://rusherhack.org/i/4r86jdbhvj.mp4

**Comment by martin010919** [comment]
Pog
