### ISSUE TITLE
[BUG] HUD > IP > Port removes IP if user does not specify a port

### ISSUE THREAD

**Issue by tycrek** [John200410/rusherhack-issues#84]
**Describe the bug**
Title

**To Reproduce**
Turn off Port under IP HUD while logged onto a server that you didn't specify a port for (example: "2b2t.org")

**Expected behavior**
Hide the port if specified, otherwise do nothing. 

**Screenshots**
![unknown-18.png](https://user-images.githubusercontent.com/29926144/97819787-f99da700-1c67-11eb-9d6d-4373222af7de.png)
![unknown-17.png](https://user-images.githubusercontent.com/29926144/97819792-fd312e00-1c67-11eb-8297-fa5dcbca49ab.png)

**Additional context**
I think you're just using a string split. If so, maybe just check the number of colons in the string as it seems to be including the colon in "IP:"

**Comment by John200410** [comment]
Thank you for reporting this.

**Comment by John200410** [comment]
This has been fixed in v1.1.2
