### ISSUE TITLE
Weather Module

### ISSUE THREAD

**Issue by DiscordBotTester** [John200410/rusherhack-issues#840]
**What feature would you like to be added.**
Module for showing the weather in your area.

**Is your feature request related to a problem? Please describe.**
.

**Additional context**
This could be useful if you arent close to a window or if you cant tell what it is like outside.

**Comment by jumboman32** [comment]
weather api + converting address/zip code to id

also pls use the templates.

**Comment by DiscordBotTester** [comment]
> weather api + converting address/zip code to id
> 
> also pls use the templates.

forgot ab that, will edit it so it follows the template!

**Comment by jennifer-uwu** [comment]
average 2b2t playing basement dweller

**Comment by jennifer-uwu** [comment]
useless
