### ISSUE TITLE
[FEATURE] AntiCity module

### ISSUE THREAD

**Issue by SewerHatch** [John200410/rusherhack-issues#847]
A module that prevents your surround getting citied

**Comment by DqrkCap** [comment]
This really is usefull,there could be a mode in surround called anticity mode.For example in another payed client it has it.


![image](https://user-images.githubusercontent.com/81417233/120982472-6be7e400-c781-11eb-9b2a-17e42b4b98c1.png)

**Comment by abt5** [comment]
why did you censor konas its not like john will go crazy

**Comment by jennifer-uwu** [comment]
what does "getting citied" mean

**Comment by SoggyBacco** [comment]
> what does "getting citied" mean

get trapped and ur surround mined out

**Comment by jennifer-uwu** [comment]
placing an extra block to the sides wouldn't do anything to stop that
