### ISSUE TITLE
[FEATURE] Record/Play Module

### ISSUE THREAD

**Issue by MoreOrgasm** [John200410/rusherhack-issues#850]
**What feature would you like to be added.**
A Module that could record keyboard and mouse imput in minecraft to recreate movement etc
you'd activate it with a bind, do what you want, (ex: run around, place blocks, collect items, send chat messages, whatever)
then stop by pressing that bind again, and play it by pressing a second bind ?

i think it would need to have an option so the module registers starting coords, YAW, etc if you need it to,

maybe the module could have a window where you save multiple recordings and select the one you want to play, a bit like the profiles window

**Comment by jennifer-uwu** [comment]
what's the point of this?

**Comment by MoreOrgasm** [comment]
If you can't see the point with what i've written above i really can't help you dude, if you have more precise questions maybe i could help

**Comment by jennifer-uwu** [comment]
how would this be useful

**Comment by MoreOrgasm** [comment]
This is pretty much the same question dude

this is a recording module it's only useful if you have ideas on how to use it ? there's loads of automation that can be done with it, stuff where baritone would not help, i've been searching for a mod to do that but couldn't find any that fits, there's one guy that tried on liteloader but it's outdated and not precise because of the limitations of the macro/keybind mod

**Comment by jennifer-uwu** [comment]
ok but could you list a specific task that this would be used for? and there is other external software you can use for this purpose

**Comment by jumboman32** [comment]
razer, asus, and corsair have software that can do this and I imagine a lot more do too so try using those

**Comment by MoreOrgasm** [comment]
> 
> 
> ok but could you list a specific task that this would be used for? and there is other external software you can use for this purpose

at that rate i can use external software for a third of the hacks in any client

Automation ? recording specific planned routes for an afk session ? could be used to dupe with an ALT if you're alone for exemple

it really is as useful as you let it be
