### ISSUE TITLE
[FEATURE] Easy Switch 

### ISSUE THREAD

**Issue by fudge92** [John200410/rusherhack-issues#853]
**What feature would you like to be added.**
A Module that will help you switch between elytra and chestplate easily.
Like in Bedrock Edition if you have chestplate on, and elytra in your hotbar,  so if you right click on elytra it will switch places with chestplate and vice versa. 

**Is your feature request related to a problem? Please describe.**
Its very frustrating to open inventory and manually change elytra with chestplate and also a lot time consuming.

**Additional context**
A Video from bedrock edition, me changing Chestplate with Elytra in one click.

![EasySwitch-RH](https://user-images.githubusercontent.com/83440724/121059765-789b2500-c7df-11eb-8729-ae369ae4f450.gif)

**Comment by John200410** [comment]
Make a macro to toggle the ElytraPriority setting in AutoArmor.
