### ISSUE TITLE
[FEATURE] autocrystal keep rotation

### ISSUE THREAD

**Issue by jennifer-uwu** [John200410/rusherhack-issues#854]
keep rotation after breaking a crystal while there is a target present for a few ticks so that when you break the crystal you don't rotate back to where you were and have to rotate back to face the target for the next crystal. 

this is more important the further from the target you look and the lower the aimstep is.

**Comment by jumboman32** [comment]
inhibit?

**Comment by jennifer-uwu** [comment]
that stops you from attacking crystals more than once iirc

**Comment by John200410** [comment]
This has been done in the next update.
