### ISSUE TITLE
Chest Swap

### ISSUE THREAD

**Issue by Neon273** [John200410/rusherhack-issues#860]
Chest Swap that swaps chestplate for elytra when key bind is pressed
could be under AutoArmor module or just a new module

**Comment by ProfKambing** [comment]
mf u could use macro

**Comment by fudge92** [comment]
duplicate of #853

**Comment by fudge92** [comment]
check #853  it will be much better, insteas of a keybind

**Comment by jumboman32** [comment]
Closing in favor of #853, in the meantime use a macro with autoarmor elytrapriority.
