### ISSUE TITLE
AutoTNT

### ISSUE THREAD

**Issue by Droid-D3V** [John200410/rusherhack-issues#862]
AutoTNT is a module which will need TNT and one flint and steel
If someone is in a BedRock hole, it will automatic place an adjustable amount of TNT and it will light it, it will also trap them in the hole so it will detonate and this cannot get out in time!

Also, if you could rename Selfblock to "Burrow" it'd be greatly appreciated!

**Comment by FluorideHistorian** [comment]
burrow is a retarded name

**Comment by Droid-D3V** [comment]
true though, true

**Comment by jennifer-uwu** [comment]
useless
