### ISSUE TITLE
[FEATURE] "Vertical" waypoint

### ISSUE THREAD

**Issue by tycrek** [John200410/rusherhack-issues#87]
**What feature would you like to be added.**

Not the best name but basically have an option to put the distance/coordinates for a waypoint *under* the name rather than beside it.

Bad example:

```
Current:

   LagMachine (100, 54, -63)

New:

     LagMachine
   (100, 54, -63)

```

**Comment by John200410** [comment]
I understand, I actually really like this idea.

Will probably be in v1.1.2

**Comment by John200410** [comment]
This has been added to v1.1.2
![image](https://user-images.githubusercontent.com/43681932/97939001-e31f4a80-1d50-11eb-8718-751f3d17a153.png)
