### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by a-a3458** [John200410/rusherhack-issues#872]
**What feature would you like to be added.**
A detailed explanation of what this feature should be.
basically a account check for when you buy a bunch of nfa mc accounts like you put the info in a .tx file and on account check you hit open file you select the .txt file it what ever ones do work it adds them in the account manager 
**Is your feature request related to a problem? Please describe.**
no it's not a problem 
**Additional context**
i think this would make it so when you buy a bunch of nfa mc accounts it would make it much easier adding them.

**Comment by John200410** [comment]
No. I do not support the use of stolen Minecraft Accounts.
