### ISSUE TITLE
[BUG] holefiller placements

### ISSUE THREAD

**Issue by SoggyBacco** [John200410/rusherhack-issues#873]
sometimes if ur in a hole it wont fill an open hole thats within a block or 2 of u

**Comment by jumboman32** [comment]
Idk why i never made an issue for this but yeah its usually blocks diagonal to your hole.

**Comment by thebruhmoment** [comment]
pls john fix this shit already i dont want to download another client for holefill

**Comment by John200410** [comment]
Thank you for reporting this. This has been fixed in the next update.
