### ISSUE TITLE
[FEATURE] Slot-machine window

### ISSUE THREAD

**Issue by end41r** [John200410/rusherhack-issues#874]
**What feature would you like to be added.**
A slot machine without money limit where you can bet and all this stuff

**Is your feature request related to a problem? Please describe.**
I dont have this much money to play slots

**Comment by jumboman32** [comment]
This seems a bit extra.

**Comment by John200410** [comment]
I love this idea but I do not want to encourage underage gambling so I am not going to do this.

**Comment by end41r** [comment]
:((((

**Comment by ProfKambing** [comment]
but john ur 17
