### ISSUE TITLE
[FEATURE] Add ability to use baritone with ElytraFly module

### ISSUE THREAD

**Issue by aerospaces** [John200410/rusherhack-issues#877]
I think it would be very useful to have the ability to use baritone with the ElytraFly module. 

This could be used with all the different modes and could also have a settings to input coordinates that you want to reach. This would make nether highway travel very easy because you could afk ElytraFly without having much user input. Without inputing coordinates you want to reach it would just fly in a straight direction (including diagonal) using baritone to maintain a path and fly around obstacles. In the overworld this new feature would make for very easy afk traveling to specific destinations.

**Comment by John200410** [comment]
This is the rusherhack GitHub not Baritone.
