### ISSUE TITLE
[FEATURE] Edit HUD elements via console

### ISSUE THREAD

**Issue by tycrek** [John200410/rusherhack-issues#88]
**What feature would you like to be added.**

Basically the title. Might need a new command for this.

Example:

`*hudman position axis y` (value)
`*hudman position comma` (toggle, possibly also support `true/false`)

I picked `hudman` for "HUD Manager"

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
I have added a command to the Hud module to manage hud elements.

![image](https://user-images.githubusercontent.com/43681932/114285510-ae14d380-9a25-11eb-8357-50fcace68243.png)
