### ISSUE TITLE
[BUG]  double hole esp

### ISSUE THREAD

**Issue by droideka101** [John200410/rusherhack-issues#883]
**Describe the bug**
A clear and concise description of what the bug is. extra side on double holes

**To Reproduce**
Steps to reproduce the behavior: turn on hole esp with doubles

**Expected behavior**
A clear and concise description of what you expected to happen. not have the dark bit

**Screenshots**
![image](https://user-images.githubusercontent.com/83362540/123548177-9e22ab00-d75b-11eb-9a74-46d24ae80fa7.png)

**Comment by end41r** [comment]
But this is not a bug
This is supposed to be like this

**Comment by HarryPotter42MC** [comment]
maybe add an option to toggle this

**Comment by jumboman32** [comment]
This is not a bug, feel free to re-open the issue if you would like to suggest a different render mode for HoleESP.
