### ISSUE TITLE
Source remover with echests kick[BUG] 

### ISSUE THREAD

**Issue by FuzzyRussian** [John200410/rusherhack-issues#884]
**Describe the bug**
If source remover tries to use echests and opens the echest it will kick you from whatever server you are on

**To Reproduce**
Have source remover use echest
**Other mods**
NA

**Expected behavior**
You will be kicked from the server you are connected to

**Screenshots**
NA

**Additional context**
NA

**Comment by John200410** [comment]
Thank you for reporting this. I have fixed it in the next update.
