### ISSUE TITLE
[FEATURE] Chat movable in hud editor to prevent overlapping

### ISSUE THREAD

**Issue by HarryPotter42MC** [John200410/rusherhack-issues#885]
**What feature would you like to be added.**
This is coords without open chat
![grafik](https://user-images.githubusercontent.com/82435253/123609820-4f7b1c80-d800-11eb-84d0-3c082a3dcab9.png)
and this is with chat opened
![grafik](https://user-images.githubusercontent.com/82435253/123609880-5c980b80-d800-11eb-918c-242b6dd3b909.png)
to prevent this maybe make chat movable in hud editor

**Is your feature request related to a problem? Please describe.**
Im using the chat to tab out but then I cant read the X coord properly and it overlaps

**Additional context**
none

**Comment by jumboman32** [comment]
HUD Editor > Position > Axis > Y

Or use https://5zigreborn.eu/, but this would be way too much work when there's a simple fix.
