### ISSUE TITLE
[FEATURE] Tweakable Hit delay in Kill Aura

### ISSUE THREAD

**Issue by martin010919** [John200410/rusherhack-issues#886]
So, I was experimenting with aura, and if you turn off hit delay it clicks so fast, my big ping and the TPS of 2b, can't pickup the hits. But if you turn on hit delay, yes you get crit every time but you aren't fast.

So I request hit delay tweaker, so you can set to as fast, as the server can pick up the incoming punches.

Thx in advance

**Comment by jumboman32** [comment]
This exists.
![image](https://user-images.githubusercontent.com/68603817/123812607-376bd180-d8c2-11eb-89f2-c42556a56ffe.png)
