### ISSUE TITLE
[BUG] Bedspawn is bugged

### ISSUE THREAD

**Issue by martin010919** [John200410/rusherhack-issues#887]
**Describe the bug**
So after a nice grinding i get my first bed, and i slept like 5-8second in it, and i cheked the *bedspawn and it says 0 60 0, what is spawn. After this, i slept util it turned into day again, and kicked me out, cheked *bedspawn and 0 60 0 again, not my bed coords. I dont want to commit suicide just  to chek if it set, bc i dont want risk going back to spawn,

**To Reproduce**
sleep, use the command

**Other mods**
none

**Expected behavior**
it should write my real base coords

**Screenshots**.
i dont take any

**Additional context**
na

**Comment by end41r** [comment]
Try to speep again and try the command again

**Comment by end41r** [comment]
Best advice ever 🤟

**Comment by martin010919** [comment]
> Try to speep again and try the command again

i tried 3 times
2 timeswith short sleep 10second max
1 time until it kicked me out

still 0 60 0 as bedspawn

**Comment by end41r** [comment]
Definetly a bug, not a server issue, bed works 999%

**Comment by Witherinqq** [comment]
doesnt work for me either

**Comment by TwoThreeTwo** [comment]
(john removed this command entirely)

**Comment by GentlemanMC** [comment]
(bruh)
