### ISSUE TITLE
[FEATURE] More keystrokes options

### ISSUE THREAD

**Issue by abt5** [John200410/rusherhack-issues#890]
**What feature would you like to be added.**

- Ability to add other keys
- Option to move the keystrokes around, with snapping/clamping
- Option to remove background, change background width, and height
- Scale for the entire keystrokes

**Is your feature request related to a problem? Please describe.**
Would be cool to have more customization

**Additional context**
I just found out that keystrokes were in the client from the discord, and now I want a bit more options

**Comment by jennifer-uwu** [comment]
do you really need a hud to tell you what keys you are pressing?
i assume you'll want breathing reminders next

**Comment by abt5** [comment]
Bruh what they are just cool to have

**Comment by abt5** [comment]
You could say that to almost every hud element, server element, watermark, hunger, biome and more

**Comment by jennifer-uwu** [comment]
adding a bunch of settings and a system to add and render (without overlap and without weird stacking) is way more work than drawing a watermark string.

**Comment by ignelias** [comment]
just use sk1er keystrokes
