### ISSUE TITLE
[FEATURE] Autocast on autofish

### ISSUE THREAD

**Issue by ClassicalBlueTooth** [John200410/rusherhack-issues#900]
**What feature would you like to be added.**
Have Autofish automatically cast the fishing rod once its equipped.

**Is your feature request related to a problem? Please describe.**
When playing on a server that restarts frequently (Constantiam) it'll restart and autofish will stop until you manually throw the rod again. It makes overnight afk fishing impossible as once you reconnect your char wont yeet the rod.

**Additional context**

**Comment by John200410** [comment]
Duplicate of #425
