### ISSUE TITLE
Auto-place for tunnels

### ISSUE THREAD

**Issue by Kalculater** [John200410/rusherhack-issues#902]
When creating a base, a really tedious and difficult task is getting far enough off the main axis so that your future base can stay secure. Normally you have two options with this. The first is trying to use an elytra which are extremely unreliable and is very slow when dealing with hundreds of thousands of blocks, each chunk with it’s own hazards. The second option is tunneling off the axis and patching the blocks, however you will have to first go one way, go back, and then hope you have enough netherack to fully patch it up, which can take weeks. 

I think RH should add a new module (possibly under autotunnel or baritone) that automatically places blocks behind the player, speeding up the process of base location by a lot. This would conserve a lot of time and materials for builders and would also make RH even more appealing as a client.

**Comment by jennifer-uwu** [comment]
enable backfill in baritone

**Comment by Kalculater** [comment]
> enable backfill in baritone

I am not seeing a “backfill” in the baritone section. 
![BC427ADA-B6A2-453D-9462-7F1658EFEDE1](https://user-images.githubusercontent.com/86805907/124362031-399e9a80-dbf8-11eb-81b9-475ab54b9697.png)
