### ISSUE TITLE
[BUG] False DM Notification Flag

### ISSUE THREAD

**Issue by PixelMelt** [John200410/rusherhack-issues#903]
**Describe the bug**
Notifications trigger when a pm was received are triggering when someone says `user whispers: foo` in public chat.

**To Reproduce**
be online
have someone say `user whispers: foo` in public chat.

**Other mods**
List other forge mods you are using (if any):
baritone

**Expected behavior**
notification will only trigger when a pm is actually received.

**Screenshots**
![Screenshot_20210703_142318](https://user-images.githubusercontent.com/44953835/124363680-b76ba180-dc0a-11eb-9060-a404f12a4523.png)

**Additional context**
none

**Comment by John200410** [comment]
This has been fixed in the next update.
