### ISSUE TITLE
[BUG] AutoEat Kick in GUI

### ISSUE THREAD

**Issue by jumboman32** [John200410/rusherhack-issues#911]
**Describe the bug**
AutoEat attempts to eat too quickly in a GUI causing a kick on 2b2t.

**To Reproduce**
1. Turn on AutoEat
2. Aim your crosshair at a shulker box
3. Go below threshold

**Other mods**
List other forge mods you are using (if any):
N/A

**Comment by jumboman32** [comment]
Could've made a suggestion for an AutoEat NoInteract option, but this seemed better.

**Comment by John200410** [comment]
This has already been fixed
