### ISSUE TITLE
[BUG] Step not working on 9b9t

### ISSUE THREAD

**Issue by Radiocabea** [John200410/rusherhack-issues#918]
**Describe the bug**
Step doesn't work on 9b9t

**To Reproduce**
Activate Step with any setting

**Other mods**
List other forge mods you are using (if any):
none

**Expected behavior**
To move up 1 block without jumping

**Screenshots**
https://youtu.be/8ws6BsqRVlY

**Additional context**

**Comment by John200410** [comment]
Use NCP mode.

**Comment by Radiocabea** [comment]
Hello John, Just to let you know that NCP mode also doesn't work at all on 9b9t.
Thanks

**Comment by Radiocabea** [comment]
Hey, NCP mode also doesn't work on 9b9t, (i also show it on the video)

**Comment by John200410** [comment]
It seems like you may have another module conflicting with Step. Try with all other modules off.

**Comment by FluorideHistorian** [comment]
step was also behaving wrong on 9b for me

**Comment by Radiocabea** [comment]
Hey, I've tested with only the Step module on, and the problem persists:https://youtu.be/986H6Fx_JUs
I think it's the anticheat the server's owner is using, would be cool if you could work on a workaround of it!
What leads me to believe it's the anticheat is that the queue server doesn't have this problem, only on the main server.
Thanks

**Comment by FluorideHistorian** [comment]
the queue server doesnt have an anticheat
