### ISSUE TITLE
[FEATURE] Improve Step to be more like Future Step

### ISSUE THREAD

**Issue by tycrek** [John200410/rusherhack-issues#92]
**What feature would you like to be added.**

This is the one thing I was still using in Future. It's kind of hard to explain but just try out Future's step and you'll see it is a lot more smooth. Rhack step seems to not work with omnidirectional sprint.

**Comment by John200410** [comment]
Thank you for the suggestion

**Comment by John200410** [comment]
Will also be adding a Vanilla mode.

**Comment by ProfKambing** [comment]
future step :sus:

**Comment by John200410** [comment]
Step logic has been rewritten, and a Vanilla mode has been added.
