### ISSUE TITLE
[BUG] announcer doesn't announce walking

### ISSUE THREAD

**Issue by jennifer-uwu** [John200410/rusherhack-issues#923]
title

**Comment by ProfKambing** [comment]
😐

**Comment by martin010919** [comment]
Turn it off and don't use it announcer is bullcrap, it is instant /ignorehard for me

**Comment by John200410** [comment]
Unable to reproduce: 
![image](https://user-images.githubusercontent.com/43681932/124973530-a56a7400-dff9-11eb-8639-d10216c061a0.png)

What are your settings?

**Comment by jennifer-uwu** [comment]
![2021-07-08_14 49 46](https://user-images.githubusercontent.com/77944228/124975242-d350b800-dffb-11eb-8f3f-03402e5ebeae.png)
