### ISSUE TITLE
[BUG] ca smart break hangups

### ISSUE THREAD

**Issue by SoggyBacco** [John200410/rusherhack-issues#926]
smart break tends to hang up on moving targets and faceplace, at first i thought it was just a cfg issue but after some testing it doesnt happen with break all or own.

my guess is this has something to do with dmg calcs, maybe separate mindmg settings for place and break would fix this?

**Comment by FluorideHistorian** [comment]
can you record it happening

**Comment by FluorideHistorian** [comment]
just realized this should have been fixed
