### ISSUE TITLE
[FEATURE] Water speed vertical improvements

### ISSUE THREAD

**Issue by Phantom568** [John200410/rusherhack-issues#929]
What feature would you like to be added.
I would like a separate Y multipliers one for up and another for down

**Is your feature request related to a problem? Please describe.**
I always have an issue when configing water speed because going up the multiplier needs to be lower than the multiplier for going down.

**Additional context**
https://medal.tv/clips/57933014/d13373l9hCWL
Here is an example of what it should be 0:07 and at 0:12 you can see the difference in speeds.

**Comment by John200410** [comment]
These settings have been added in the next update:
![image](https://user-images.githubusercontent.com/43681932/128258337-f3772c0a-37b7-4527-9488-39ffcd9532e6.png)
