### ISSUE TITLE
[FEATURE] Exact value entering

### ISSUE THREAD

**Issue by mestupid** [John200410/rusherhack-issues#93]
**What feature would you like to be added.**
The ability to make the value of something precise, maybe like the way Pyro does it where you can type in whatever you want. This could still probably work with limits, so that you couldn't have boatfly go above 5, but I think it would still be useful for other modules.

**Is your feature request related to a problem? Please describe.**
I was trying to set up AutoTrap and the value I was going for was right between 0 and 0.23, the only two values I could assign using the slider.

**Additional context**
The text input box could be activated by middle-slicking on the slider.

**Comment by John200410** [comment]
You can do this with commands. Command syntax is as follows: *modulename settingname settingvalue

Example: *autotrap placedelay 0.2
