### ISSUE TITLE
[BUG] Aura PauseBaritone settingis not working properly

### ISSUE THREAD

**Issue by gargamelius** [John200410/rusherhack-issues#938]
**Describe the bug**
The Aura PauseBaritone setting is only working for commands like #goto or #path but if you use Baritone to mine or place blocks it wont be paused 

**Other mods**
Baritone

**Expected behavior**
Pasue Baritone if its mining something and an entity is nearby

**Screenshots**
https://youtu.be/OT05KgUAAis

**Comment by John200410** [comment]
This has been fixed in the next update.
