### ISSUE TITLE
Make the boat controls less slippery [FEATURE]

### ISSUE THREAD

**Issue by ManOnTheMoon28** [John200410/rusherhack-issues#94]
**Less slippery boat controls:**
When you use boats and turn left or right the boat kinda keeps moving even after you let go of the keybbind and keeps rotating in that direction. Its quite annoying when going in small spaces, maybe add an option to make the boat control more similar to pyro where it kinda feels like ur using a fly hack.

**Comment by John200410** [comment]
Thank you for the suggestion

**Comment by John200410** [comment]
This has been finished and will be in v1.1.3
