### ISSUE TITLE
[FEATURE] Normal Chams

### ISSUE THREAD

**Issue by bstar16** [John200410/rusherhack-issues#944]
Shows entitys/players through walls as is without using colours
![CE70ED4A-57A7-4BBD-9174-8814AC74F163](https://user-images.githubusercontent.com/76526844/125676543-515a212a-18d7-43c7-98e4-b691a0c52473.jpeg)

**Comment by SoggyBacco** [comment]
this is a mode already

**Comment by jumboman32** [comment]
Use mode normal.
