### ISSUE TITLE
[BUG] Unnecessary Obsidian Placements with Surround

### ISSUE THREAD

**Issue by FuzzyRussian** [John200410/rusherhack-issues#945]
**Describe the bug**
When using surround and there is no supporting block under a bedrock block right next to you surround will place obby.

**To Reproduce**
Stand next to a bedrock block with nothing under it and turn on surround

**Expected behavior**
Surround will place unnecessary obsidian if there is an airblock under an obby block next to you.

**Comment by jennifer-uwu** [comment]
#800 duplicate
