### ISSUE TITLE
[FEATURE] ghosthand

### ISSUE THREAD

**Issue by Badinek** [John200410/rusherhack-issues#946]
**What feature would you like to be added.**
A detailed explanation of what this feature should be.
ghosthand- makes you unable to interact with certain blocks (you can choose) you go thru then when clicking (u cant break them or place on them) but u can still walk on them. 

**Is your feature request related to a problem? Please describe.**

**Additional context**
mad_king_lambo might buy rusherhack if you add it since he uses it

**Comment by ProfKambing** [comment]
mad king lambo 😈 👨 💸

**Comment by Doogie13** [comment]
this would be amazing for citying people through bedrock without freecam

**Comment by Ozynt** [comment]
This was added in the v1.3 update.
