### ISSUE TITLE
[FEATURE] ChestSwap

### ISSUE THREAD

**Issue by 453452hw** [John200410/rusherhack-issues#947]
**What feature would you like to be added.**
Chestswap: When activated swaps your chestplate with your elytra or your elytra with your chestplate.

**Comment by abt5** [comment]
im pretty sure you can make a macro for that

**Comment by abt5** [comment]
as in rusherhacks macro command

**Comment by 453452hw** [comment]
if you know the macro. send me it but i dont know if thats possible with a macro

**Comment by abt5** [comment]
*macro add (key) autoarmor elytra_priority

**Comment by jumboman32** [comment]
Duplicate of #853.  (or use macro)
