### ISSUE TITLE
[BUG] smartbreak wont break faceplaced crystals

### ISSUE THREAD

**Issue by SoggyBacco** [John200410/rusherhack-issues#948]
crystals that do less than min placedmg r completely ignored by smart break, this causes ca to hang up on moving targets or when ur trying to faceplace

**To Reproduce**
turn on smart break and set mindmg to anything above 3

**Expected behavior**
at faceplace health smartbreak should ignore mindmg like place does

**Additional context**
a separate mindmg setting for break could fix this, otherwise u have to set mindmg to 2 which is the same as faceplace 36

**Comment by jennifer-uwu** [comment]
https://github.com/John200410/rusherhack-issues/issues/823
