### ISSUE TITLE
[BUG] Freecam not using player's health

### ISSUE THREAD

**Issue by bdat1234** [John200410/rusherhack-issues#95]
**Describe the bug**
When you have freecam on, the health stays at 20, but in reality, in some situations you would have less health without you knowing while in freecam

**To Reproduce**
Jump off a cliff and turn on free cam, you hear the damage but the health is still full

**Other mods**
Pyro, Wurst+2, Clientcommands, and Badlion+

**Expected behavior**
The health in freecam to sync with the actual health you have

**Comment by John200410** [comment]
Thank you for reporting this

**Comment by John200410** [comment]
This has been fixed in v1.1.2
