### ISSUE TITLE
[FEATURE] Working auto-ignore

### ISSUE THREAD

**Issue by martin010919** [John200410/rusherhack-issues#950]
**What feature would you like to be added.**

I know it is already out but I think there can be improvements. I suggest, it should recognise same messages and ignore them.

 Also make a "autoignore-players . txt" , where you can list up need to be ignored players.

Also it would be cool to add a "ignorephrase.txt" where you can list up phrases what like to be ignored, like 'discord', or 'cloudanarchy'. And it will automatically ignore them

**Is your feature request related to a problem? Please describe.**
Never working auto ignore

**Additional context**
Nope

**Comment by tycrek** [comment]
I like the phrase idea, specifically it would be nice to automatically mute any whispers containing Discord or other links from players that aren't Friends

**Comment by John200410** [comment]
AutoIgnore has been rewritten into an AntiSpam module with many new features.
