### ISSUE TITLE
[FEATURE] AutoArmor ElytraPriority settings

### ISSUE THREAD

**Issue by autoselfpop** [John200410/rusherhack-issues#953]
**What feature would you like to be added.**

An option for ElytraPriority in AutoArmor to be active only when ElytraFly is toggled.

**Is your feature request related to a problem? Please describe.**

No.

**Comment by jumboman32** [comment]
*macro add 'efly bind' autoarmor elytrapriority

**Comment by bstar16** [comment]
this doesn’t work well it just desyncs and you have to update inventory for it to appear

**Comment by jumboman32** [comment]
> this doesn’t work well it just desyncs and you have to update inventory for it to appear

Wait 3 seconds after toggling.
