### ISSUE TITLE
[FEATURE] Nuker priority Closest improvement

### ISSUE THREAD

**Issue by HarryPotter42MC** [John200410/rusherhack-issues#960]
**What feature would you like to be added.**
An option to make closest not cancel breaking a block in range when anotehr block gets the closest so it doesnt loose the focus

**Is your feature request related to a problem? Please describe.**
I wanna remove an obby pyramid and its annoying how I cant move without cancelling the block breaking when moving even a bit

**Comment by John200410** [comment]
This has been done in the next update.
