### ISSUE TITLE
[BUG] Nuker not breaking snowlayers in mode selective

### ISSUE THREAD

**Issue by HarryPotter42MC** [John200410/rusherhack-issues#962]
**Describe the bug**
When I tap a snow layer using nuker selective it doesnt berak the snow layers even thi ut does with other blocks

**To Reproduce**
![grafik](https://user-images.githubusercontent.com/82435253/126809092-bea8253a-c5fc-4747-95d6-d2923b90af10.png)
tap a snow layer

**Other mods**
lambda, future

**Expected behavior**
it should break the snow layers

**Screenshots**
none

**Additional context**
![grafik](https://user-images.githubusercontent.com/82435253/126809363-21434358-6302-49a4-a239-1c2a7b22370c.png)
config

**Comment by SewerHatch** [comment]
for me it does

**Comment by John200410** [comment]
Unable to reproduce.
