### ISSUE TITLE
[FEATURE] Paid cloaks

### ISSUE THREAD

**Issue by 06d** [John200410/rusherhack-issues#968]
Something like lunar, a creator can apply for a cloak and can make their own design

Im pretty sure normal users don't have a cape, so a paid cape could be the only way to get one without making 5 people to use your referral code

**Comment by jennifer-uwu** [comment]
john said he's not going to add custom capes because he doesn't know how to implement it on the webserver

**Comment by John200410** [comment]
We are planning on adding a cape selection so plus users can choose from a variety of capes and possibly upload custom ones.

**Comment by ProfKambing** [comment]
based
