### ISSUE TITLE
[FEATURE] Boatfly Waypoint lock

### ISSUE THREAD

**Issue by tycrek** [John200410/rusherhack-issues#97]
**What feature would you like to be added.**

1. Currently RotationLock doesn't work with Boatfly, I think it makes sense that it should work
2. More of a reminder because there isn't an issue for it: you mentioned WaypointLock on the discord where Boatfly would snap to a specific waypoint. This is probably easiest with commands I think.

**Comment by John200410** [comment]
I will probably be able to fix the rotationlock bug in v1.1.2. The waypoint thing will probably have to wait for v1.2

**Comment by John200410** [comment]
RotationLock bug has been fixed in v1.1.2. Waypoint locking will be added in v1.2

**Comment by John200410** [comment]
*yaw command now has ability to rotate towards a waypoint in the next update.
