### ISSUE TITLE
ElytraFly > AutoOpen

### ISSUE THREAD

**Issue by SewerHatch** [John200410/rusherhack-issues#974]
I suggest a feature that would automaticaly open your wings when you are in the air. It would be useful for afk flights because AutoArmor closes your wings when it switches broken elytra to a fresh one which results in you falling which stops the flight or might even pop/kill you.

**Comment by tycrek** [comment]
You mean like AutoRedeploy which already exists? Or does that not work with AutoArmor?

![autoredeploy](https://ass.rip/ij9jnmLPfW92/direct)

**Comment by SewerHatch** [comment]
i have it enabled but it dosent work in such situation

**Comment by John200410** [comment]
> i have it enabled but it dosent work in such situation

What ElytraFly mode do you use?
