### ISSUE TITLE
[FEATURE] *enable and *disable

### ISSUE THREAD

**Issue by tycrek** [John200410/rusherhack-issues#98]
**What feature would you like to be added.**

Would be very helpful for complex macros. You could do `*enable autocrystal` and it would turn on that module. Specific enable/disable would be much better than a toggle at times, because perhaps the module is already turned on, and your macro is a batch "enable", if that makes sense.

**Comment by John200410** [comment]
Thank you for the suggestion, however I think this will be better if it was a second argument for the toggle command.

Example: `*toggle autocrystal true` or `*toggle autocrystal false`.

Let me know what you think about this

**Comment by tycrek** [comment]
Yep that would work too! 

Nov. 4, 2020, 6:59 p.m. by notifications@github.com:

**Comment by John200410** [comment]
This has been finished and will appear in v1.1.2
