### ISSUE TITLE
How do you Change the search as it is only searching portals[FEATURE]

### ISSUE THREAD

**Issue by keyslost** [John200410/rusherhack-issues#989]
**What feature would you like to be added.**
A detailed explanation of what this feature should be.

**Is your feature request related to a problem? Please describe.**

**Additional context**

**Comment by HarryPotter42MC** [comment]
ask in #support on the discord and delete this issue

**Comment by John200410** [comment]
This is the suggestions/bug reports page. Not the support page.

**Comment by keyslost** [comment]
what is the discord

**Comment by martin010919** [comment]
@keyslost when you bought it you get an invite to the official discord, use the #support channel there

**Comment by HarryPotter42MC** [comment]
howd you even get the github link without being in the discord? youc an find the discord invite on https://rusherhack.org/users/ when you log in
