### ISSUE TITLE
Installer Suggestion

### ISSUE THREAD

**Issue by PFTpancake** [John200410/rusherhack-issues#991]
I think it would be nice to have a little thing that tells you what version RusherHack is on in the installer
![Screenshot 2021-08-03 193049](https://user-images.githubusercontent.com/70246391/128112452-2bbde0c4-9220-4f6d-8d8e-aa3891f46ca9.png)
   

Maybe there

**Comment by HarryPotter42MC** [comment]
1. this isnt a bug 2. use the template 3. the installer autoupdates and installs the newest version of rusherhack that's how installers work

**Comment by tycrek** [comment]
Closing for reasons described by @HarryPotter42MC
