### ISSUE TITLE
[BUG] Autowalk cancel walking bug

### ISSUE THREAD

**Issue by HarryPotter42MC** [John200410/rusherhack-issues#992]
**Describe the bug**
When I use autowalk normal, keep w pressed and disable autowalk it makes me stop moving even tho I have w held down

**To Reproduce**
uzse autowalk normal, press w, disable autowalk

**Other mods**
lambda, future

**Expected behavior**
it should go on walking

**Comment by jumboman32** [comment]
this is not a bug, autowalk ignores w key input because it is just holding it

**Comment by HarryPotter42MC** [comment]
but dont you think this shouldnt be like it?
