### ISSUE TITLE
[FEATURE] FPS Limiter when minimized

### ISSUE THREAD

**Issue by SynnKFPS** [John200410/rusherhack-issues#994]
**What feature would you like to be added.**
When you minimize minecraft, the animated background animation stops and the game limits the fps to 15, then when you back to the game, fps limiter goes to the normal value

**Is your feature request related to a problem? Please describe.**
Yes, my computer lags when i get minimize the game.

**Additional context**
N/A

**Comment by Badinek** [comment]
dude this is already a feature, Miscellaneous > LagReducer

**Comment by tycrek** [comment]
Closing as it's already a feature.
