### ISSUE TITLE
[FEATURE]Aspect Ratio Slider

### ISSUE THREAD

**Issue by 0xMench** [John200410/rusherhack-issues#996]
**What feature would you like to be added.**
A detailed explanation of what this feature should be.
A slider to change aspect ratio.

**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Additional context**
Just simple module to change aspect ratio quickly with slider :)

**Comment by HarryPotter42MC** [comment]
whats aspect ratio

**Comment by ProfKambing** [comment]
bro...

**Comment by 0xMench** [comment]
> whats aspect ratio

bruh

**Comment by John200410** [comment]
This does not seem useful nor do I think people will find it visually appealing
